// Generated by build-index.mjs — one entry per topic file, keyed by topic slug.
import type { TopicContent } from "../types";
import { agencyBusinessStructures } from "./business-law-agency-and-business-structures";
import { contracts } from "./business-law-contracts";
import { cCorporations } from "./c-corporation-taxation";
import { circular230 } from "./circular-230-and-practitioner-ethics";
import { debtorCreditorBankruptcy } from "./debtor-creditor-and-bankruptcy";
import { payrollBenefits } from "./employee-benefits-and-payroll-tax";
import { exemptOrganizations } from "./exempt-organizations-basics";
import { taxProceduresPenalties } from "./federal-tax-procedures-and-penalties";
import { filingStatusCreditsAmt } from "./filing-status-credits-and-amt";
import { adjustmentsDeductions } from "./individual-taxation-adjustments-and-deductions";
import { grossIncome } from "./individual-taxation-gross-income";
import { irsProcedures } from "./irs-procedures-and-appeals";
import { partnerships } from "./partnership-taxation";
import { basisCostRecovery } from "./property-transactions-basis-and-cost-recovery";
import { gainsLossesLikeKind } from "./property-transactions-gains-losses-and-like-kind-exchanges";
import { retirementPlans } from "./retirement-plans-and-tax-planning-basics";
import { sCorporations } from "./s-corporation-taxation";
import { trustsEstatesGift } from "./trusts-estates-and-gift-tax-basics";

export const regContent: Record<string, TopicContent> = {
  "business-law-agency-and-business-structures": agencyBusinessStructures,
  "business-law-contracts": contracts,
  "c-corporation-taxation": cCorporations,
  "circular-230-and-practitioner-ethics": circular230,
  "debtor-creditor-and-bankruptcy": debtorCreditorBankruptcy,
  "employee-benefits-and-payroll-tax": payrollBenefits,
  "exempt-organizations-basics": exemptOrganizations,
  "federal-tax-procedures-and-penalties": taxProceduresPenalties,
  "filing-status-credits-and-amt": filingStatusCreditsAmt,
  "individual-taxation-adjustments-and-deductions": adjustmentsDeductions,
  "individual-taxation-gross-income": grossIncome,
  "irs-procedures-and-appeals": irsProcedures,
  "partnership-taxation": partnerships,
  "property-transactions-basis-and-cost-recovery": basisCostRecovery,
  "property-transactions-gains-losses-and-like-kind-exchanges": gainsLossesLikeKind,
  "retirement-plans-and-tax-planning-basics": retirementPlans,
  "s-corporation-taxation": sCorporations,
  "trusts-estates-and-gift-tax-basics": trustsEstatesGift,
};
