// Generated by build-index.mjs — one entry per topic file, keyed by topic slug.
import type { TopicContent } from "../types";
import { accountingChanges } from "./accounting-changes-and-error-corrections";
import { balanceSheetIncomeStatement } from "./balance-sheet-and-income-statement-preparation";
import { businessCombinations } from "./business-combinations-and-consolidations";
import { cashReceivables } from "./cash-receivables-and-bad-debts";
import { conceptualFramework } from "./conceptual-framework-and-financial-statement-presentation";
import { currentLiabilitiesContingencies } from "./current-liabilities-contingencies-and-commitments";
import { equityEps } from "./equity-and-earnings-per-share";
import { governmentalAccounting } from "./governmental-accounting";
import { incomeTaxes } from "./income-taxes";
import { intangibleAssetsGoodwill } from "./intangible-assets-and-goodwill";
import { inventory } from "./inventory";
import { investments } from "./investments-debt-and-equity-securities";
import { leases } from "./leases";
import { longTermDebt } from "./long-term-debt";
import { notForProfit } from "./not-for-profit-accounting";
import { notesSubsequentEventsGoingConcern } from "./notes-subsequent-events-and-going-concern";
import { propertyPlantEquipment } from "./property-plant-and-equipment";
import { revenueRecognition } from "./revenue-recognition";
import { secSegmentsInterim } from "./sec-reporting-segments-and-interim-reporting";
import { statementOfCashFlows } from "./statement-of-cash-flows";

export const farContent: Record<string, TopicContent> = {
  "accounting-changes-and-error-corrections": accountingChanges,
  "balance-sheet-and-income-statement-preparation": balanceSheetIncomeStatement,
  "business-combinations-and-consolidations": businessCombinations,
  "cash-receivables-and-bad-debts": cashReceivables,
  "conceptual-framework-and-financial-statement-presentation": conceptualFramework,
  "current-liabilities-contingencies-and-commitments": currentLiabilitiesContingencies,
  "equity-and-earnings-per-share": equityEps,
  "governmental-accounting": governmentalAccounting,
  "income-taxes": incomeTaxes,
  "intangible-assets-and-goodwill": intangibleAssetsGoodwill,
  "inventory": inventory,
  "investments-debt-and-equity-securities": investments,
  "leases": leases,
  "long-term-debt": longTermDebt,
  "not-for-profit-accounting": notForProfit,
  "notes-subsequent-events-and-going-concern": notesSubsequentEventsGoingConcern,
  "property-plant-and-equipment": propertyPlantEquipment,
  "revenue-recognition": revenueRecognition,
  "sec-reporting-segments-and-interim-reporting": secSegmentsInterim,
  "statement-of-cash-flows": statementOfCashFlows,
};
