// Generated by build-index.mjs — one entry per topic file, keyed by topic slug.
import type { TopicContent } from "../types";
import { businessProcessAutomation } from "./business-process-automation";
import { dataManagementGovernance } from "./data-management-and-governance";
import { emergingTechnology } from "./emerging-technology-considerations";
import { incidentResponse } from "./incident-response";
import { informationSystemsFundamentals } from "./information-systems-fundamentals";
import { itAuditAdvisory } from "./it-audit-and-advisory";
import { itGeneralControls } from "./it-general-controls";
import { privacyFrameworks } from "./privacy-frameworks";
import { securityFundamentals } from "./security-fundamentals";
import { socEngagements } from "./soc-engagements";
import { systemsDevelopmentChange } from "./systems-development-life-cycle";
import { thirdPartyRisk } from "./third-party-and-vendor-risk";

export const iscContent: Record<string, TopicContent> = {
  "business-process-automation": businessProcessAutomation,
  "data-management-and-governance": dataManagementGovernance,
  "emerging-technology-considerations": emergingTechnology,
  "incident-response": incidentResponse,
  "information-systems-fundamentals": informationSystemsFundamentals,
  "it-audit-and-advisory": itAuditAdvisory,
  "it-general-controls": itGeneralControls,
  "privacy-frameworks": privacyFrameworks,
  "security-fundamentals": securityFundamentals,
  "soc-engagements": socEngagements,
  "systems-development-life-cycle": systemsDevelopmentChange,
  "third-party-and-vendor-risk": thirdPartyRisk,
};
