// Generated by build-index.mjs — one entry per topic file, keyed by topic slug.
import type { TopicContent } from "../types";
import { businessCombinationsAdvanced } from "./business-combinations-advanced";
import { dataAnalytics } from "./data-analytics-for-accounting";
import { derivativesHedging } from "./derivatives-and-hedge-accounting";
import { employeeBenefitPlans } from "./employee-benefit-plan-accounting";
import { forecastingValuation } from "./financial-forecasting-and-projections";
import { financialStatementAnalysis } from "./financial-statement-analysis";
import { foreignCurrency } from "./foreign-currency-translation";
import { governmentWideAcfr } from "./government-wide-financial-statements";
import { governmentalFunds } from "./governmental-fund-accounting";
import { lessorAccounting } from "./lease-accounting-lessor";
import { publicCompanyReporting } from "./public-company-reporting-topics";
import { revenueSpecificArrangements } from "./revenue-for-specific-industries";
import { stockCompensation } from "./stock-compensation";

export const barContent: Record<string, TopicContent> = {
  "business-combinations-advanced": businessCombinationsAdvanced,
  "data-analytics-for-accounting": dataAnalytics,
  "derivatives-and-hedge-accounting": derivativesHedging,
  "employee-benefit-plan-accounting": employeeBenefitPlans,
  "financial-forecasting-and-projections": forecastingValuation,
  "financial-statement-analysis": financialStatementAnalysis,
  "foreign-currency-translation": foreignCurrency,
  "government-wide-financial-statements": governmentWideAcfr,
  "governmental-fund-accounting": governmentalFunds,
  "lease-accounting-lessor": lessorAccounting,
  "public-company-reporting-topics": publicCompanyReporting,
  "revenue-for-specific-industries": revenueSpecificArrangements,
  "stock-compensation": stockCompensation,
};
