// Generated by build-index.mjs — one entry per topic file, keyed by topic slug.
import type { TopicContent } from "../types";
import { cCorporationCompliance } from "./c-corporation-tax-compliance";
import { entityChoice } from "./entity-choice-and-structuring";
import { distributionsLiquidations } from "./entity-distributions-and-liquidations";
import { estateGiftPlanning } from "./estate-and-gift-tax-planning";
import { individualTaxPlanning } from "./individual-tax-planning-strategies";
import { multiJurisdictional } from "./multi-jurisdictional-and-international-basics";
import { partnershipPlanning } from "./partnership-planning";
import { personalFinancialPlanning } from "./personal-financial-planning";
import { propertyPlanning } from "./property-transactions-advanced-planning";
import { retirementPlanningStrategies } from "./retirement-planning-strategies";
import { sCorporationPlanning } from "./s-corporation-planning";
import { taxResearch } from "./tax-research-and-documentation";

export const tcpContent: Record<string, TopicContent> = {
  "c-corporation-tax-compliance": cCorporationCompliance,
  "entity-choice-and-structuring": entityChoice,
  "entity-distributions-and-liquidations": distributionsLiquidations,
  "estate-and-gift-tax-planning": estateGiftPlanning,
  "individual-tax-planning-strategies": individualTaxPlanning,
  "multi-jurisdictional-and-international-basics": multiJurisdictional,
  "partnership-planning": partnershipPlanning,
  "personal-financial-planning": personalFinancialPlanning,
  "property-transactions-advanced-planning": propertyPlanning,
  "retirement-planning-strategies": retirementPlanningStrategies,
  "s-corporation-planning": sCorporationPlanning,
  "tax-research-and-documentation": taxResearch,
};
