// Generated by build-index.mjs — one entry per topic file, keyed by topic slug.
import type { TopicContent } from "../types";
import { analyticalProcedures } from "./analytical-procedures";
import { assessingRisk } from "./assessing-risk-of-material-misstatement";
import { attestationSoc } from "./attestation-and-soc-engagements";
import { planningMateriality } from "./audit-planning-and-materiality";
import { auditReports } from "./audit-reports";
import { auditSampling } from "./audit-sampling";
import { auditingEstimates } from "./auditing-accounting-estimates";
import { acceptanceQualityManagement } from "./engagement-acceptance-and-quality-management";
import { evidenceProcedures } from "./evidence-types-and-procedures";
import { fraudRisk } from "./fraud-risk";
import { groupAuditsOthersWork } from "./group-audits-and-using-others-work";
import { itControlsInAudit } from "./it-controls-in-audit";
import { ethicsIndependence } from "./professional-ethics-and-independence";
import { relatedPartiesGoingConcern } from "./related-parties-and-going-concern";
import { respondingToRisks } from "./responding-to-assessed-risks";
import { reviewsCompilationsAup } from "./reviews-compilations-and-aup";
import { understandingInternalControl } from "./understanding-the-entity-and-internal-control";
import { completingAudit } from "./written-representations-and-completing-the-audit";

export const audContent: Record<string, TopicContent> = {
  "analytical-procedures": analyticalProcedures,
  "assessing-risk-of-material-misstatement": assessingRisk,
  "attestation-and-soc-engagements": attestationSoc,
  "audit-planning-and-materiality": planningMateriality,
  "audit-reports": auditReports,
  "audit-sampling": auditSampling,
  "auditing-accounting-estimates": auditingEstimates,
  "engagement-acceptance-and-quality-management": acceptanceQualityManagement,
  "evidence-types-and-procedures": evidenceProcedures,
  "fraud-risk": fraudRisk,
  "group-audits-and-using-others-work": groupAuditsOthersWork,
  "it-controls-in-audit": itControlsInAudit,
  "professional-ethics-and-independence": ethicsIndependence,
  "related-parties-and-going-concern": relatedPartiesGoingConcern,
  "responding-to-assessed-risks": respondingToRisks,
  "reviews-compilations-and-aup": reviewsCompilationsAup,
  "understanding-the-entity-and-internal-control": understandingInternalControl,
  "written-representations-and-completing-the-audit": completingAudit,
};
