import type { SubjectSeed } from "./types";
import { audContent } from "./content/aud";

export const aud: SubjectSeed = {
  slug: "aud",
  name: "Auditing and Attestation",
  shortName: "AUD",
  type: "CORE",
  description:
    "Auditing and Attestation (AUD) tests the audit process end to end: Ethics, Professional Responsibilities and General Principles (15–25%), Assessing Risk and Developing a Planned Response (25–35%), Performing Further Procedures and Obtaining Evidence (30–40%), and Forming Conclusions and Reporting (10–20%). About half the score comes from task-based simulations, so knowing how procedures fit together matters as much as definitions.",
  difficulty: "HARD",
  estimatedHours: 110,
  blueprintUrl: "https://www.aicpa-cima.com/resources/download/aud-cpa-exam-blueprint",
  order: 2,
  topics: [
    {
      slug: "professional-ethics-and-independence",
      title: "Professional Ethics & Independence",
      shortDescription: "The American Institute of Certified Public Accountants (AICPA) Code of Professional Conduct, the conceptual framework, independence rules, and issuer requirements.",
      blueprintArea: "Area I: Ethics, Professional Responsibilities & General Principles",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 1,
      studyMaterialHtml: audContent["professional-ethics-and-independence"].study,
      revisionNoteHtml: audContent["professional-ethics-and-independence"].revision,
      mcqs: [
        {
          question: "An audit senior on the engagement team owns 10 shares of the audit client's common stock, worth approximately $300. What is the effect on independence?",
          options: [
            { label: "A", text: "Independence is not impaired because the amount is immaterial", isCorrect: false, rationale: "Materiality is only relevant for indirect financial interests. A direct interest impairs independence regardless of amount." },
            { label: "B", text: "Independence is impaired because a covered member holds a direct financial interest", isCorrect: true, rationale: "Correct — any direct financial interest in an attest client held by a covered member impairs independence, regardless of how small." },
            { label: "C", text: "Independence is impaired only if the senior is the engagement partner", isCorrect: false, rationale: "The engagement team as a whole are covered members, not just the partner." },
            { label: "D", text: "Independence is preserved if the shares are disclosed in the audit report", isCorrect: false, rationale: "Disclosure does not cure an independence impairment for an audit engagement." },
          ],
          explanation: "A direct financial interest in an attest client held by a covered member impairs independence regardless of materiality. Only indirect financial interests (such as an interest through a diversified mutual fund) are evaluated against a materiality threshold.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["ethics", "independence"],
        },
        {
          question: "For which of the following engagements is the CPA firm NOT required to be independent?",
          options: [
            { label: "A", text: "An audit of financial statements", isCorrect: false, rationale: "Audits are attest engagements requiring independence." },
            { label: "B", text: "A review of interim financial statements", isCorrect: false, rationale: "Reviews are attest engagements requiring independence." },
            { label: "C", text: "A compilation of financial statements", isCorrect: true, rationale: "Correct — independence is not required for a compilation, but if the accountant is not independent, that fact must be disclosed in the compilation report." },
            { label: "D", text: "An examination of prospective financial information", isCorrect: false, rationale: "Examinations are attest engagements requiring independence." },
          ],
          explanation: "Independence is required for attest engagements — audits, reviews, and examinations. A compilation is a non-attest SSARS service where independence is not required, though a lack of independence must be disclosed in the accountant's compilation report.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["ethics", "independence", "SSARS"],
        },
      ],
    },
    {
      slug: "engagement-acceptance-and-quality-management",
      title: "Engagement Acceptance & Quality Management",
      shortDescription: "Client acceptance, predecessor communications, engagement letters, and quality management under the Statements on Quality Management Standards (SQMS).",
      blueprintArea: "Area I: Ethics, Professional Responsibilities & General Principles",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 2,
      studyMaterialHtml: audContent["engagement-acceptance-and-quality-management"].study,
      revisionNoteHtml: audContent["engagement-acceptance-and-quality-management"].revision,
      mcqs: [
        {
          question: "Before accepting a new audit engagement, who is responsible for initiating communication with the predecessor auditor, and what permission is required?",
          options: [
            { label: "A", text: "The predecessor initiates it; no permission is needed", isCorrect: false, rationale: "The successor, not the predecessor, must initiate the communication." },
            { label: "B", text: "The successor initiates it, after obtaining the prospective client's permission", isCorrect: true, rationale: "Correct — the successor auditor must attempt communication with the predecessor before accepting, and must first obtain the client's permission because of confidentiality obligations." },
            { label: "C", text: "The successor initiates it; no permission is needed because of the public interest", isCorrect: false, rationale: "Client confidentiality still applies — permission is required before the predecessor may respond." },
            { label: "D", text: "Either party may initiate it after the engagement is accepted", isCorrect: false, rationale: "The communication must occur before acceptance, and the successor must initiate it." },
          ],
          explanation: "The successor auditor is required to initiate communication with the predecessor auditor before accepting an audit engagement. Because the predecessor owes the former client a duty of confidentiality, the successor must first obtain the prospective client's permission for the predecessor to respond.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["acceptance", "predecessor auditor"],
        },
      ],
    },
    {
      slug: "audit-planning-and-materiality",
      title: "Audit Planning & Materiality",
      shortDescription: "Setting overall materiality, performance materiality, and the clearly trivial threshold, plus developing the audit strategy.",
      blueprintArea: "Area II: Assessing Risk and Developing a Planned Response",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 3,
      studyMaterialHtml: audContent["audit-planning-and-materiality"].study,
      revisionNoteHtml: audContent["audit-planning-and-materiality"].revision,
      mcqs: [
        {
          question: "Why does an auditor set performance materiality at an amount lower than overall materiality?",
          options: [
            { label: "A", text: "To comply with the SEC's requirement for public company audits", isCorrect: false, rationale: "Performance materiality is a GAAS/ISA concept applied in all audits, not an SEC-specific requirement." },
            { label: "B", text: "To reduce the probability that undetected and uncorrected misstatements aggregate to exceed overall materiality", isCorrect: true, rationale: "Correct — performance materiality creates a buffer so that individually immaterial misstatements do not add up to a material amount in total." },
            { label: "C", text: "Because performance materiality applies only to income statement accounts", isCorrect: false, rationale: "Performance materiality applies across the financial statements, not just to the income statement." },
            { label: "D", text: "To establish the threshold below which misstatements are clearly trivial", isCorrect: false, rationale: "That describes the clearly trivial threshold, which is a separate and much lower amount." },
          ],
          explanation: "Performance materiality is set below overall materiality to provide a margin for undetected misstatements and for individually immaterial misstatements that could, in aggregate, exceed overall materiality.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["materiality", "planning"],
        },
      ],
    },
    {
      slug: "understanding-the-entity-and-internal-control",
      title: "Understanding the Entity & Internal Control",
      shortDescription: "The five Committee of Sponsoring Organizations of the Treadway Commission (COSO) components, controls to evaluate, and communicating deficiencies.",
      blueprintArea: "Area II: Assessing Risk and Developing a Planned Response",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 60,
      order: 4,
      studyMaterialHtml: audContent["understanding-the-entity-and-internal-control"].study,
      revisionNoteHtml: audContent["understanding-the-entity-and-internal-control"].revision,
      mcqs: [
        {
          question: "In a financial statement audit of a nonissuer, which of the following is required in every audit?",
          options: [
            { label: "A", text: "Testing the operating effectiveness of internal controls", isCorrect: false, rationale: "Testing operating effectiveness is only required when the auditor intends to rely on controls or when substantive procedures alone cannot provide sufficient evidence." },
            { label: "B", text: "Obtaining an understanding of internal control relevant to the audit", isCorrect: true, rationale: "Correct — the auditor must obtain an understanding of internal control relevant to the audit in every engagement, in order to assess risk and design further procedures." },
            { label: "C", text: "Issuing an opinion on the effectiveness of internal control", isCorrect: false, rationale: "That is a separate integrated audit engagement, generally required for larger issuers, not for every nonissuer audit." },
            { label: "D", text: "Communicating all control deficiencies to those charged with governance", isCorrect: false, rationale: "Only significant deficiencies and material weaknesses must be communicated in writing; lesser deficiencies need not be." },
          ],
          explanation: "Obtaining an understanding of internal control relevant to the audit — evaluating design and determining implementation — is mandatory in every audit. Testing operating effectiveness is optional and depends on whether the auditor plans to rely on controls.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["internal control", "COSO"],
        },
        {
          question: "An auditor identifies a control deficiency that creates a reasonable possibility that a material misstatement of the financial statements would not be prevented or detected on a timely basis. How should this be classified and communicated?",
          options: [
            { label: "A", text: "A significant deficiency, communicated orally to management", isCorrect: false, rationale: "The definition given matches a material weakness, and communication must be in writing." },
            { label: "B", text: "A material weakness, communicated in writing to those charged with governance and management", isCorrect: true, rationale: "Correct — a reasonable possibility of a material misstatement not being prevented or detected defines a material weakness, which must be communicated in writing." },
            { label: "C", text: "A control deficiency requiring no communication", isCorrect: false, rationale: "This severity level requires written communication; it cannot be ignored." },
            { label: "D", text: "A material weakness that must be reported in the auditor's opinion on the financial statements", isCorrect: false, rationale: "In a nonissuer financial statement audit, material weaknesses are communicated to governance, not reported in the opinion on the financial statements themselves." },
          ],
          explanation: "A material weakness is a deficiency, or combination of deficiencies, such that there is a reasonable possibility that a material misstatement will not be prevented or detected on a timely basis. Both material weaknesses and significant deficiencies must be communicated in writing to those charged with governance.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["internal control", "deficiencies"],
        },
      ],
    },
    {
      slug: "assessing-risk-of-material-misstatement",
      title: "Assessing Risk of Material Misstatement",
      shortDescription: "Combining inherent and control risk to plan the nature, timing, and extent of audit procedures.",
      blueprintArea: "Area II: Assessing Risk and Developing a Planned Response",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 70,
      order: 5,
      studyMaterialHtml: audContent["assessing-risk-of-material-misstatement"].study,
      revisionNoteHtml: audContent["assessing-risk-of-material-misstatement"].revision,
      mcqs: [
        {
          question: "A client operates with weak segregation of duties over its cash disbursement process. All else equal, how should the auditor respond?",
          options: [
            { label: "A", text: "Increase acceptable detection risk and perform fewer substantive procedures", isCorrect: false, rationale: "This is backwards — weaker controls mean higher control risk, which requires a lower, not higher, acceptable detection risk." },
            { label: "B", text: "Decrease acceptable detection risk and perform more extensive substantive procedures", isCorrect: true, rationale: "Correct — weak segregation of duties increases control risk. To keep overall audit risk at an acceptable level, the auditor must lower acceptable detection risk, which means more extensive, more reliable, and more year-end-focused procedures." },
            { label: "C", text: "Rely entirely on the client's internal controls without further testing", isCorrect: false, rationale: "Weak controls mean the auditor should rely less on controls, not more, and should increase substantive testing instead." },
            { label: "D", text: "Take no action, since detection risk is unrelated to control risk", isCorrect: false, rationale: "Detection risk is directly related to control and inherent risk through the audit risk model." },
          ],
          explanation: "Under the audit risk model (AR = IR × CR × DR), when control risk increases, the auditor must reduce acceptable detection risk to keep overall audit risk at an acceptably low level. This is achieved through more extensive, more reliable, and more period-end-focused substantive procedures.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["risk assessment", "audit risk model"],
        },
        {
          question: "An auditor notes that goods shipped on December 29 were recorded as sales in the following fiscal year. Which assertion is most directly at risk?",
          options: [
            { label: "A", text: "Existence", isCorrect: false, rationale: "Existence relates to whether recorded transactions actually occurred, not to which period they were recorded in." },
            { label: "B", text: "Cutoff", isCorrect: true, rationale: "Correct — cutoff addresses whether transactions are recorded in the correct accounting period. Recording a December shipment in the wrong year is a cutoff issue." },
            { label: "C", text: "Rights and obligations", isCorrect: false, rationale: "Rights and obligations relates to whether the entity holds the rights to assets or is obligated for liabilities, not timing of recording." },
            { label: "D", text: "Presentation and disclosure", isCorrect: false, rationale: "This assertion relates to whether items are properly classified, described, and disclosed, not to which period a transaction is recorded in." },
          ],
          explanation: "Cutoff is the assertion that addresses whether transactions and events have been recorded in the correct accounting period. Shipping goods in December but recording the related sale in the next fiscal year is a textbook cutoff error.",
          difficulty: "EASY",
          questionType: "APPLICATION",
          tags: ["assertions"],
        },
      ],
    },
    {
      slug: "fraud-risk",
      title: "Fraud Risk",
      shortDescription: "The fraud triangle, required fraud procedures, and the auditor's responsibility for detecting fraud.",
      blueprintArea: "Area II: Assessing Risk and Developing a Planned Response",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 6,
      studyMaterialHtml: audContent["fraud-risk"].study,
      revisionNoteHtml: audContent["fraud-risk"].revision,
      mcqs: [
        {
          question: "Which fraud-related presumption can NEVER be rebutted by the auditor?",
          options: [
            { label: "A", text: "That revenue recognition is a fraud risk", isCorrect: false, rationale: "This presumption can be rebutted, but the auditor must document the reasons for the conclusion." },
            { label: "B", text: "That management override of controls is a risk in every audit", isCorrect: true, rationale: "Correct — because management is uniquely able to override controls, the auditor must always address this risk and cannot rebut the presumption." },
            { label: "C", text: "That the entity's control environment is ineffective", isCorrect: false, rationale: "There is no such presumption; the control environment is assessed based on evidence." },
            { label: "D", text: "That employee misappropriation of assets has occurred", isCorrect: false, rationale: "No such presumption exists — the auditor assesses risk, not an assumption that fraud has occurred." },
          ],
          explanation: "Because of management's unique ability to override controls that otherwise appear to be operating effectively, the risk of management override is presumed to exist in every audit and this presumption cannot be rebutted. Specific required procedures include testing journal entries, reviewing estimates for bias, and evaluating significant unusual transactions.",
          difficulty: "MEDIUM",
          questionType: "EXCEPTION",
          tags: ["fraud", "management override"],
        },
      ],
    },
    {
      slug: "responding-to-assessed-risks",
      title: "Responding to Assessed Risks",
      shortDescription: "Designing further audit procedures: nature, timing, and extent, and choosing between controls reliance and substantive testing.",
      blueprintArea: "Area III: Performing Further Procedures and Obtaining Evidence",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 7,
      studyMaterialHtml: audContent["responding-to-assessed-risks"].study,
      revisionNoteHtml: audContent["responding-to-assessed-risks"].revision,
      mcqs: [
        {
          question: "An auditor assesses control risk as very low for the revenue cycle after successfully testing controls. Which statement is correct regarding substantive procedures for revenue?",
          options: [
            { label: "A", text: "Substantive procedures for revenue may be omitted entirely", isCorrect: false, rationale: "Substantive procedures can never be eliminated for a material class of transactions, no matter how effective controls are." },
            { label: "B", text: "Substantive procedures may be reduced but must still be performed for the material class of transactions", isCorrect: true, rationale: "Correct — effective controls allow reduced substantive testing, but the auditor must still perform some substantive procedures for each material class of transactions, balance, and disclosure." },
            { label: "C", text: "Only analytical procedures are permitted once controls are tested", isCorrect: false, rationale: "The auditor may choose tests of details, substantive analytics, or both — there is no such restriction." },
            { label: "D", text: "Control testing must be repeated at year-end before any reduction is allowed", isCorrect: false, rationale: "Interim control testing with appropriate roll-forward procedures is acceptable; retesting entirely at year-end is not required." },
          ],
          explanation: "Substantive procedures must be performed for each material class of transactions, account balance, and disclosure regardless of the assessed level of control risk. Effective controls justify reducing the extent of substantive testing but never eliminating it.",
          difficulty: "MEDIUM",
          questionType: "EXAM_TRAP",
          tags: ["substantive procedures", "controls reliance"],
        },
      ],
    },
    {
      slug: "audit-sampling",
      title: "Audit Sampling",
      shortDescription: "Statistical and nonstatistical sampling, sampling risk, and how sample size responds to risk and tolerable misstatement.",
      blueprintArea: "Area III: Performing Further Procedures and Obtaining Evidence",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 8,
      studyMaterialHtml: audContent["audit-sampling"].study,
      revisionNoteHtml: audContent["audit-sampling"].revision,
      mcqs: [
        {
          question: "In a test of controls, the tolerable deviation rate is 5% and the computed upper deviation rate based on the sample is 6.2%. What should the auditor conclude?",
          options: [
            { label: "A", text: "The control can be relied on as planned, since the sample deviation rate is likely below 5%", isCorrect: false, rationale: "The comparison is between the computed upper deviation rate and the tolerable rate, not the sample rate alone." },
            { label: "B", text: "The control cannot be relied on at the planned level, and control risk should be increased", isCorrect: true, rationale: "Correct — when the computed upper deviation rate exceeds the tolerable rate, the sample does not support the planned reliance, so the auditor increases assessed control risk and expands substantive procedures." },
            { label: "C", text: "The auditor must issue a qualified opinion", isCorrect: false, rationale: "A control deviation finding affects the audit approach, not directly the opinion on the financial statements." },
            { label: "D", text: "The sample size was too large and should be reduced", isCorrect: false, rationale: "The result indicates the control is not operating effectively enough to rely on; it says nothing about the sample being too large." },
          ],
          explanation: "The auditor compares the computed upper deviation rate (which incorporates sampling risk) to the tolerable deviation rate. When the upper deviation rate exceeds tolerable, the planned reliance on the control is not supported — the auditor raises assessed control risk and increases substantive testing.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["sampling", "tests of controls"],
        },
        {
          question: "Which sampling risk is most concerning because it leads the auditor to an incorrect conclusion about the financial statements?",
          options: [
            { label: "A", text: "The risk of assessing control risk too high", isCorrect: false, rationale: "This is an efficiency risk — the auditor does more work than necessary but does not reach a wrong conclusion." },
            { label: "B", text: "The risk of incorrect rejection", isCorrect: false, rationale: "This is also an efficiency risk — it leads to unnecessary additional procedures, not an audit failure." },
            { label: "C", text: "The risk of incorrect acceptance", isCorrect: true, rationale: "Correct — incorrect acceptance means concluding a materially misstated balance is fairly stated, which is an audit effectiveness failure." },
            { label: "D", text: "Nonsampling risk", isCorrect: false, rationale: "Nonsampling risk (e.g., applying the wrong procedure) is a real concern but is not one of the two sampling risks being contrasted here." },
          ],
          explanation: "The risk of incorrect acceptance (and its controls-testing counterpart, the risk of assessing control risk too low) relates to audit effectiveness: the auditor wrongly concludes that a materially misstated balance is acceptable. Efficiency risks only cause unnecessary work.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["sampling", "sampling risk"],
        },
      ],
    },
    {
      slug: "evidence-types-and-procedures",
      title: "Evidence: Types & Procedures",
      shortDescription: "The hierarchy of audit evidence reliability and the eight types of audit procedures.",
      blueprintArea: "Area III: Performing Further Procedures and Obtaining Evidence",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 9,
      studyMaterialHtml: audContent["evidence-types-and-procedures"].study,
      revisionNoteHtml: audContent["evidence-types-and-procedures"].revision,
      mcqs: [
        {
          question: "An auditor selects recorded sales transactions from the sales journal and examines the related shipping documents and customer orders. This procedure primarily tests which assertion?",
          options: [
            { label: "A", text: "Completeness", isCorrect: false, rationale: "Completeness is tested by tracing from source documents forward into the accounting records, the opposite direction." },
            { label: "B", text: "Occurrence (existence)", isCorrect: true, rationale: "Correct — starting with recorded amounts and vouching back to supporting documents tests whether recorded sales actually occurred." },
            { label: "C", text: "Rights and obligations", isCorrect: false, rationale: "This procedure addresses whether the transaction happened, not who holds legal rights." },
            { label: "D", text: "Presentation and disclosure", isCorrect: false, rationale: "The procedure addresses transaction validity, not classification or note disclosure." },
          ],
          explanation: "Vouching — selecting items already recorded in the accounting records and examining the supporting documentation — tests occurrence/existence. Tracing in the opposite direction (from shipping documents to the sales journal) would test completeness.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["evidence", "vouching", "assertions"],
        },
        {
          question: "Which condition would make the use of negative accounts receivable confirmations INAPPROPRIATE?",
          options: [
            { label: "A", text: "A large number of small, homogeneous account balances", isCorrect: false, rationale: "This condition supports the use of negative confirmations." },
            { label: "B", text: "A low assessed risk of material misstatement", isCorrect: false, rationale: "Low risk is one of the conditions supporting negative confirmations." },
            { label: "C", text: "A high expected rate of exceptions and reason to believe recipients will ignore the requests", isCorrect: true, rationale: "Correct — negative confirmations are inappropriate when the auditor expects significant exceptions or believes recipients will not review the requests, because silence would be wrongly interpreted as agreement." },
            { label: "D", text: "Effective internal control over receivables", isCorrect: false, rationale: "Effective controls support the use of negative confirmations." },
          ],
          explanation: "Negative confirmations are only appropriate when risk of material misstatement is low, controls are effective, the population consists of many small homogeneous balances, and the auditor has no reason to believe recipients will disregard the request. A high expected exception rate makes them inappropriate.",
          difficulty: "MEDIUM",
          questionType: "EXCEPTION",
          tags: ["evidence", "confirmations"],
        },
      ],
    },
    {
      slug: "analytical-procedures",
      title: "Analytical Procedures",
      shortDescription: "Using analytical procedures in planning, as substantive tests, and in the final review stage.",
      blueprintArea: "Area III: Performing Further Procedures and Obtaining Evidence",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 45,
      order: 10,
      studyMaterialHtml: audContent["analytical-procedures"].study,
      revisionNoteHtml: audContent["analytical-procedures"].revision,
      mcqs: [
        {
          question: "At which stages of the audit are analytical procedures REQUIRED?",
          options: [
            { label: "A", text: "Planning and substantive testing", isCorrect: false, rationale: "Substantive analytical procedures are optional — the auditor may choose tests of details instead." },
            { label: "B", text: "Planning and final review", isCorrect: true, rationale: "Correct — analytical procedures are required during risk assessment (planning) and again near the end of the audit as an overall review." },
            { label: "C", text: "Substantive testing and final review", isCorrect: false, rationale: "Planning analytics are required; substantive analytics are not." },
            { label: "D", text: "All three stages", isCorrect: false, rationale: "Substantive analytical procedures remain optional." },
          ],
          explanation: "Analytical procedures are required in the risk assessment (planning) stage to identify unusual relationships, and again in the final review stage to form an overall conclusion about whether the financial statements are consistent with the auditor's understanding. Their use as substantive procedures is optional.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["analytical procedures"],
        },
      ],
    },
    {
      slug: "auditing-accounting-estimates",
      title: "Auditing Accounting Estimates",
      shortDescription: "Evaluating management's estimates, identifying management bias, and auditing fair value measurements.",
      blueprintArea: "Area III: Performing Further Procedures and Obtaining Evidence",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 55,
      order: 11,
      studyMaterialHtml: audContent["auditing-accounting-estimates"].study,
      revisionNoteHtml: audContent["auditing-accounting-estimates"].revision,
      mcqs: [
        {
          question: "During the audit, the auditor notes that each of management's significant estimates falls within a reasonable range, but every one lands at the end of the range that maximizes reported income. How should the auditor evaluate this?",
          options: [
            { label: "A", text: "Accept the estimates, since each is individually within a reasonable range", isCorrect: false, rationale: "Individual reasonableness does not resolve the pattern — the aggregate direction is itself audit evidence." },
            { label: "B", text: "Treat the pattern as a possible indicator of management bias and evaluate its effect on the financial statements as a whole", isCorrect: true, rationale: "Correct — a consistent one-directional pattern suggests management bias, which must be evaluated for its aggregate effect and considered as a fraud risk indicator." },
            { label: "C", text: "Issue an adverse opinion immediately", isCorrect: false, rationale: "The auditor must first evaluate the aggregate effect; an adverse opinion requires a material and pervasive misstatement." },
            { label: "D", text: "Require management to select the midpoint of each range", isCorrect: false, rationale: "The auditor does not dictate management's estimates; the auditor evaluates whether they are reasonable and free of bias." },
          ],
          explanation: "Even when individual estimates fall within acceptable ranges, a systematic pattern of estimates favoring one direction indicates possible management bias. The auditor must evaluate the aggregate effect on the financial statements and consider whether the pattern signals a fraud risk.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["estimates", "management bias"],
        },
      ],
    },
    {
      slug: "related-parties-and-going-concern",
      title: "Related Parties & Going Concern",
      shortDescription: "Identifying related-party transactions and evaluating substantial doubt about going concern.",
      blueprintArea: "Area III: Performing Further Procedures and Obtaining Evidence",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 12,
      studyMaterialHtml: audContent["related-parties-and-going-concern"].study,
      revisionNoteHtml: audContent["related-parties-and-going-concern"].revision,
      mcqs: [
        {
          question: "An auditor concludes that substantial doubt about a nonissuer's ability to continue as a going concern exists, and management has adequately disclosed the situation in the notes. What is the appropriate reporting?",
          options: [
            { label: "A", text: "A qualified opinion with a basis-for-qualification paragraph", isCorrect: false, rationale: "Adequate disclosure means there is no GAAP departure, so the opinion is not qualified." },
            { label: "B", text: "An unmodified opinion with a separate going-concern section", isCorrect: true, rationale: "Correct — when disclosure is adequate, the opinion remains unmodified and the auditor adds a separate section describing the substantial doubt." },
            { label: "C", text: "An adverse opinion", isCorrect: false, rationale: "An adverse opinion applies to material and pervasive GAAP departures, which does not apply where disclosure is adequate." },
            { label: "D", text: "A disclaimer of opinion", isCorrect: false, rationale: "A disclaimer applies to pervasive scope limitations, not to a properly disclosed going-concern uncertainty." },
          ],
          explanation: "When substantial doubt exists and management's disclosure is adequate, the auditor issues an unmodified opinion and includes a separate section headed 'Substantial Doubt About the Entity's Ability to Continue as a Going Concern.' Inadequate disclosure, by contrast, is a GAAP departure leading to a qualified or adverse opinion.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["going concern", "audit reports"],
        },
      ],
    },
    {
      slug: "it-controls-in-audit",
      title: "Information Technology (IT) Controls in the Audit",
      shortDescription: "General and application controls, auditing around vs. through the computer, and using data analytics.",
      blueprintArea: "Area III: Performing Further Procedures and Obtaining Evidence",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 13,
      studyMaterialHtml: audContent["it-controls-in-audit"].study,
      revisionNoteHtml: audContent["it-controls-in-audit"].revision,
      mcqs: [
        {
          question: "An auditor finds that a company's automated three-way match control is well designed, but application programmers have unrestricted access to modify programs in the production environment. What is the effect on the auditor's ability to rely on the automated control?",
          options: [
            { label: "A", text: "The control can still be relied on because its design is effective", isCorrect: false, rationale: "Design alone is not enough — weak general controls undermine reliance on the automated control's continued operation." },
            { label: "B", text: "The control cannot be relied on, because weak IT general controls undermine automated application controls", isCorrect: true, rationale: "Correct — without effective change management and access controls, the auditor cannot conclude the automated control operated consistently throughout the period." },
            { label: "C", text: "The auditor should test the control at year-end only", isCorrect: false, rationale: "Timing does not solve the problem — the integrity of the program throughout the period is in question." },
            { label: "D", text: "Reliance is permitted if management represents that no unauthorized changes were made", isCorrect: false, rationale: "A management representation is not sufficient evidence to overcome a general control deficiency." },
          ],
          explanation: "Automated application controls depend on the IT general controls that protect the programs and data. When change management and access controls are deficient, the auditor cannot conclude that the automated control operated consistently, and must shift to substantive testing.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["IT controls", "ITGC"],
        },
      ],
    },
    {
      slug: "group-audits-and-using-others-work",
      title: "Group Audits & Using Others' Work",
      shortDescription: "Component auditors, using internal audit's work, and using the work of a specialist.",
      blueprintArea: "Area III: Performing Further Procedures and Obtaining Evidence",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 14,
      studyMaterialHtml: audContent["group-audits-and-using-others-work"].study,
      revisionNoteHtml: audContent["group-audits-and-using-others-work"].revision,
      mcqs: [
        {
          question: "A group auditor decides to make reference to a component auditor who audited a significant subsidiary. What is the effect on the auditor's report?",
          options: [
            { label: "A", text: "The opinion must be qualified because of a scope limitation", isCorrect: false, rationale: "Making reference is a division of responsibility, not a scope limitation, and does not cause a qualification." },
            { label: "B", text: "The report indicates the division of responsibility, and the opinion remains unmodified", isCorrect: true, rationale: "Correct — the group auditor discloses that part of the audit was performed by another auditor and the magnitude involved, while still expressing an unmodified opinion." },
            { label: "C", text: "The component auditor must also sign the group auditor's report", isCorrect: false, rationale: "The component auditor does not sign the group report." },
            { label: "D", text: "A disclaimer of opinion is required for the component's portion", isCorrect: false, rationale: "No disclaimer is involved when reference is properly made." },
          ],
          explanation: "When the group auditor decides not to assume responsibility for a component auditor's work, the report makes reference to the component auditor and indicates the division of responsibility, including the magnitude of the portion audited by the other auditor. This does not modify the opinion.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["group audits"],
        },
      ],
    },
    {
      slug: "written-representations-and-completing-the-audit",
      title: "Written Representations & Completing the Audit",
      shortDescription: "Management representation letters, subsequent events procedures, and wrapping up the engagement.",
      blueprintArea: "Area IV: Forming Conclusions and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 15,
      studyMaterialHtml: audContent["written-representations-and-completing-the-audit"].study,
      revisionNoteHtml: audContent["written-representations-and-completing-the-audit"].revision,
      mcqs: [
        {
          question: "Management refuses to sign the written representation letter at the conclusion of the audit. What is the appropriate response?",
          options: [
            { label: "A", text: "Issue a qualified opinion", isCorrect: false, rationale: "A refusal to provide required representations is a pervasive scope limitation — a qualified opinion is not sufficient." },
            { label: "B", text: "Disclaim an opinion or withdraw from the engagement", isCorrect: true, rationale: "Correct — refusal to provide written representations is a scope limitation sufficiently pervasive that the auditor must disclaim an opinion or withdraw." },
            { label: "C", text: "Issue an unmodified opinion and document the refusal in the workpapers", isCorrect: false, rationale: "An unmodified opinion is not permitted when required representations are withheld." },
            { label: "D", text: "Issue an adverse opinion", isCorrect: false, rationale: "An adverse opinion applies to material and pervasive misstatements, not to scope limitations." },
          ],
          explanation: "Written representations are a required part of audit evidence. Management's refusal to provide them constitutes a scope limitation so significant that the auditor must disclaim an opinion or withdraw from the engagement.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["representations", "scope limitation"],
        },
      ],
    },
    {
      slug: "audit-reports",
      title: "Audit Reports",
      shortDescription: "Choosing between unmodified, qualified, adverse, and disclaimer opinions, and adding emphasis-of-matter paragraphs.",
      blueprintArea: "Area IV: Forming Conclusions and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 16,
      studyMaterialHtml: audContent["audit-reports"].study,
      revisionNoteHtml: audContent["audit-reports"].revision,
      mcqs: [
        {
          question: "An auditor is unable to observe the physical inventory count or satisfy themselves through alternative procedures, and inventory represents 60% of total assets. What opinion is appropriate?",
          options: [
            { label: "A", text: "Qualified opinion", isCorrect: false, rationale: "At 60% of total assets, the inability to obtain evidence is pervasive, which goes beyond a qualification." },
            { label: "B", text: "Disclaimer of opinion", isCorrect: true, rationale: "Correct — this is a scope limitation (inability to obtain sufficient appropriate evidence) that is both material and pervasive, requiring a disclaimer." },
            { label: "C", text: "Adverse opinion", isCorrect: false, rationale: "An adverse opinion applies when the statements are materially and pervasively misstated, not when evidence is unavailable." },
            { label: "D", text: "Unmodified opinion with an emphasis-of-matter paragraph", isCorrect: false, rationale: "An emphasis-of-matter paragraph cannot cure a significant scope limitation." },
          ],
          explanation: "Inability to obtain sufficient appropriate audit evidence is a scope limitation. When the possible effects are both material and pervasive — as with inventory representing 60% of total assets — the auditor must disclaim an opinion rather than qualify it.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["audit reports", "scope limitation"],
        },
        {
          question: "A company changed from FIFO to weighted-average inventory costing. The change is justified, properly accounted for, and adequately disclosed. How should the auditor report?",
          options: [
            { label: "A", text: "Qualified opinion due to a lack of consistency", isCorrect: false, rationale: "A justified, properly applied and disclosed accounting change is not a GAAP departure and does not qualify the opinion." },
            { label: "B", text: "Unmodified opinion with an emphasis-of-matter paragraph describing the change", isCorrect: true, rationale: "Correct — a justified change in accounting principle is a matter appropriately presented in the financial statements, warranting an emphasis-of-matter paragraph without modifying the opinion." },
            { label: "C", text: "Unmodified opinion with an other-matter paragraph", isCorrect: false, rationale: "Other-matter paragraphs address matters NOT presented in the financial statements; this change is disclosed in them." },
            { label: "D", text: "Adverse opinion", isCorrect: false, rationale: "There is no GAAP departure here at all." },
          ],
          explanation: "A justified and properly disclosed change in accounting principle is highlighted with an emphasis-of-matter paragraph, because it refers to a matter that IS presented or disclosed in the financial statements. The opinion itself remains unmodified.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["audit reports", "emphasis of matter"],
        },
      ],
    },
    {
      slug: "reviews-compilations-and-aup",
      title: "Reviews, Compilations & Agreed-Upon Procedures",
      shortDescription: "Statements on Standards for Accounting and Review Services (SSARS) engagements — preparation, compilation, and review — plus agreed-upon procedures.",
      blueprintArea: "Area IV: Forming Conclusions and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 17,
      studyMaterialHtml: audContent["reviews-compilations-and-aup"].study,
      revisionNoteHtml: audContent["reviews-compilations-and-aup"].revision,
      mcqs: [
        {
          question: "Which procedures form the primary basis of a review of financial statements under SSARS?",
          options: [
            { label: "A", text: "Tests of controls and substantive tests of details", isCorrect: false, rationale: "These are audit procedures; a review does not include testing controls or detailed substantive testing." },
            { label: "B", text: "Inquiry and analytical procedures", isCorrect: true, rationale: "Correct — a review consists primarily of inquiries of management and analytical procedures, which provide limited assurance." },
            { label: "C", text: "Confirmation of receivables and observation of inventory", isCorrect: false, rationale: "These are audit procedures not performed in a review engagement." },
            { label: "D", text: "Obtaining an understanding of internal control and assessing control risk", isCorrect: false, rationale: "Understanding internal control is an audit requirement, not a review procedure." },
          ],
          explanation: "A SSARS review is built on inquiry and analytical procedures. It provides limited (negative) assurance and specifically excludes audit procedures such as testing controls, confirming balances, or observing inventory.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["SSARS", "review"],
        },
        {
          question: "In an agreed-upon procedures engagement, what does the practitioner's report contain?",
          options: [
            { label: "A", text: "An opinion on whether the subject matter is fairly stated", isCorrect: false, rationale: "An opinion is expressed in an examination engagement, not in agreed-upon procedures." },
            { label: "B", text: "Limited assurance in the form of negative assurance", isCorrect: false, rationale: "Negative assurance is provided in a review, not in agreed-upon procedures." },
            { label: "C", text: "A description of the procedures performed and the findings, with no assurance expressed", isCorrect: true, rationale: "Correct — an AUP report presents procedures and findings; users draw their own conclusions, and the practitioner expresses no opinion or conclusion." },
            { label: "D", text: "A recommendation on the course of action the specified parties should take", isCorrect: false, rationale: "The practitioner reports findings, not recommendations on what users should decide." },
          ],
          explanation: "In an agreed-upon procedures engagement the practitioner performs specific procedures agreed with the engaging party and reports the findings without expressing an opinion or conclusion. Users evaluate the findings and draw their own conclusions.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["attestation", "AUP"],
        },
      ],
    },
    {
      slug: "attestation-and-soc-engagements",
      title: "Attestation & System and Organization Controls (SOC) Engagements",
      shortDescription: "Attestation engagements — examination, review, and agreed-upon procedures (AUP) — and System and Organization Controls (SOC) 1, 2, and 3 reports.",
      blueprintArea: "Area IV: Forming Conclusions and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 18,
      studyMaterialHtml: audContent["attestation-and-soc-engagements"].study,
      revisionNoteHtml: audContent["attestation-and-soc-engagements"].revision,
      mcqs: [
        {
          question: "A user auditor wants to rely on controls at a service organization for the entire audit period. Which report provides appropriate evidence?",
          options: [
            { label: "A", text: "A SOC 1 Type 1 report", isCorrect: false, rationale: "A Type 1 report addresses design at a point in time only, providing no evidence of operating effectiveness over a period." },
            { label: "B", text: "A SOC 1 Type 2 report", isCorrect: true, rationale: "Correct — a Type 2 report covers both the suitability of design and the operating effectiveness of controls throughout a specified period, which is what reliance requires." },
            { label: "C", text: "A SOC 3 report", isCorrect: false, rationale: "SOC 3 is a general-use summary report on Trust Services Criteria, not designed to give a user auditor detailed ICFR evidence." },
            { label: "D", text: "A SOC 2 Type 1 report", isCorrect: false, rationale: "SOC 2 addresses Trust Services Criteria rather than ICFR, and a Type 1 covers only a point in time." },
          ],
          explanation: "To rely on a service organization's controls for the audit period, the user auditor needs a SOC 1 Type 2 report: SOC 1 because it addresses controls relevant to internal control over financial reporting, and Type 2 because it covers operating effectiveness throughout a period rather than design at a single date.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["SOC", "service organizations"],
        },
        {
          question: "Which Trust Services Criterion must be included in every SOC 2 engagement?",
          options: [
            { label: "A", text: "Privacy", isCorrect: false, rationale: "Privacy is included only when relevant to the engagement scope." },
            { label: "B", text: "Security", isCorrect: true, rationale: "Correct — the security criteria (also called the common criteria) are mandatory in every SOC 2 engagement; the other four are optional depending on scope." },
            { label: "C", text: "Availability", isCorrect: false, rationale: "Availability is optional and included only if relevant." },
            { label: "D", text: "Processing integrity", isCorrect: false, rationale: "Processing integrity is optional and included only if relevant." },
          ],
          explanation: "The five Trust Services Criteria are security, availability, processing integrity, confidentiality, and privacy. Security — known as the common criteria — must be included in every SOC 2 engagement; the remaining four are included based on the scope agreed with the service organization.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["SOC", "trust services criteria"],
        },
      ],
    },
  ],
};
