import type { SubjectSeed } from "./types";
import { barContent } from "./content/bar";

export const bar: SubjectSeed = {
  slug: "bar",
  name: "Business Analysis and Reporting",
  shortName: "BAR",
  type: "DISCIPLINE",
  description:
    "Business Analysis and Reporting (BAR) covers Business Analysis (40–50%) — ratios, forecasting, valuation, and data analytics — Technical Accounting and Reporting (35–45%), and State and Local Governments under Governmental Accounting Standards Board (GASB) standards (10–20%). It suits candidates heading toward financial reporting, valuation, or advisory work.",
  difficulty: "HARD",
  estimatedHours: 90,
  blueprintUrl: "https://www.aicpa-cima.com/resources/download/bar-cpa-exam-blueprint",
  order: 4,
  topics: [
    {
      slug: "financial-statement-analysis",
      title: "Financial Statement Analysis",
      shortDescription: "Ratio analysis, common-size statements, and evaluating liquidity, solvency, and profitability.",
      blueprintArea: "Area I: Business Analysis",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 65,
      order: 1,
      studyMaterialHtml: barContent["financial-statement-analysis"].study,
      revisionNoteHtml: barContent["financial-statement-analysis"].revision,
      mcqs: [
        {
          question: "A company with a current ratio of 0.8 uses cash to pay off an accounts payable balance. What is the effect on the current ratio?",
          options: [
            { label: "A", text: "The current ratio increases", isCorrect: false, rationale: "That is the effect when the ratio is already above 1.0." },
            { label: "B", text: "The current ratio decreases", isCorrect: true, rationale: "Correct — when the current ratio is below 1.0, subtracting an equal amount from both current assets and current liabilities lowers the ratio further." },
            { label: "C", text: "The current ratio is unchanged", isCorrect: false, rationale: "Equal reductions to numerator and denominator change a ratio unless it equals exactly 1.0." },
            { label: "D", text: "The effect cannot be determined", isCorrect: false, rationale: "The direction is determinable from whether the starting ratio is above or below 1.0." },
          ],
          explanation: "Subtracting the same amount from both the numerator and denominator moves a ratio toward 1.0. Since the current ratio started at 0.8 (below 1.0), paying off a current liability moves it further down, away from where the company wants it.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["ratios", "liquidity"],
        },
        {
          question: "Under the DuPont framework, a company's ROE increased from 12% to 18%, driven entirely by an increase in the equity multiplier while margin and asset turnover were flat. What does this indicate?",
          options: [
            { label: "A", text: "Improved operating efficiency", isCorrect: false, rationale: "Operating efficiency would show up in asset turnover, which was unchanged." },
            { label: "B", text: "Increased financial leverage, and therefore increased financial risk", isCorrect: true, rationale: "Correct — a higher equity multiplier means more debt relative to equity; the ROE improvement reflects added leverage rather than better operations." },
            { label: "C", text: "Improved pricing power", isCorrect: false, rationale: "Pricing power would appear in net profit margin, which was flat." },
            { label: "D", text: "A reduction in the company's cost of capital", isCorrect: false, rationale: "More leverage typically increases financial risk and does not by itself imply a lower cost of capital." },
          ],
          explanation: "DuPont decomposes ROE into net profit margin, asset turnover, and financial leverage (equity multiplier). When ROE rises solely because of the equity multiplier, the company has simply taken on more debt — its underlying operating performance is unchanged and its financial risk has increased.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["DuPont", "ROE"],
        },
      ],
    },
    {
      slug: "business-combinations-advanced",
      title: "Business Combinations (Advanced)",
      shortDescription: "Step acquisitions, changes in ownership interest, intercompany eliminations, and consolidation mechanics.",
      blueprintArea: "Area II: Technical Accounting and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 75,
      order: 2,
      studyMaterialHtml: barContent["business-combinations-advanced"].study,
      revisionNoteHtml: barContent["business-combinations-advanced"].revision,
      mcqs: [
        {
          question: "A parent owning 80% of a subsidiary purchases an additional 10% from noncontrolling shareholders for an amount exceeding the carrying value of the interest acquired. How is the excess recorded?",
          options: [
            { label: "A", text: "As additional goodwill", isCorrect: false, rationale: "Goodwill is recognized only in a business combination that establishes control, not in subsequent purchases from NCI." },
            { label: "B", text: "As a reduction of additional paid-in capital (an equity transaction)", isCorrect: true, rationale: "Correct — transactions with noncontrolling shareholders that do not change control are accounted for in equity, with no gain, loss, or goodwill recognized." },
            { label: "C", text: "As a loss in the consolidated income statement", isCorrect: false, rationale: "No gain or loss is recognized when control is retained." },
            { label: "D", text: "As an increase in the investment account with no equity effect", isCorrect: false, rationale: "The investment account is eliminated in consolidation; the excess is an equity adjustment." },
          ],
          explanation: "Once a parent controls a subsidiary, changes in ownership percentage that do not result in a loss of control are equity transactions. Any difference between the consideration paid and the carrying amount of the noncontrolling interest acquired adjusts additional paid-in capital — no goodwill, gain, or loss arises.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["consolidation", "NCI"],
        },
      ],
    },
    {
      slug: "derivatives-and-hedge-accounting",
      title: "Derivatives & Hedge Accounting",
      shortDescription: "Derivative characteristics, fair value hedges, cash flow hedges, and where gains and losses are reported.",
      blueprintArea: "Area II: Technical Accounting and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 3,
      studyMaterialHtml: barContent["derivatives-and-hedge-accounting"].study,
      revisionNoteHtml: barContent["derivatives-and-hedge-accounting"].revision,
      mcqs: [
        {
          question: "A company with variable-rate debt enters into an interest rate swap to pay fixed and receive variable, properly designated and documented as a hedge. Where are changes in the swap's fair value reported?",
          options: [
            { label: "A", text: "Earnings, as a fair value hedge", isCorrect: false, rationale: "This hedges variability in future interest cash flows, not the fair value of a recognized item." },
            { label: "B", text: "Other comprehensive income, as a cash flow hedge, reclassified to earnings as interest is recognized", isCorrect: true, rationale: "Correct — hedging the variability of cash flows on variable-rate debt is a cash flow hedge, so fair value changes go to OCI and are reclassified when the hedged interest affects earnings." },
            { label: "C", text: "Directly to retained earnings", isCorrect: false, rationale: "Derivative gains and losses never bypass income or OCI to go straight to retained earnings." },
            { label: "D", text: "Not recognized until the swap settles", isCorrect: false, rationale: "Derivatives are recognized at fair value each reporting period, not deferred until settlement." },
          ],
          explanation: "A pay-fixed/receive-variable swap on variable-rate debt converts variable cash flows to fixed — that is a cash flow hedge. Changes in the derivative's fair value are recorded in other comprehensive income and reclassified into earnings in the periods the hedged interest payments affect earnings.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["derivatives", "cash flow hedge"],
        },
      ],
    },
    {
      slug: "foreign-currency-translation",
      title: "Foreign Currency Translation",
      shortDescription: "Functional currency determination, translation vs. remeasurement, and where the resulting adjustment goes.",
      blueprintArea: "Area II: Technical Accounting and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 60,
      order: 4,
      studyMaterialHtml: barContent["foreign-currency-translation"].study,
      revisionNoteHtml: barContent["foreign-currency-translation"].revision,
      mcqs: [
        {
          question: "A foreign subsidiary maintains its books in its local currency, which is also determined to be its functional currency. How is the resulting adjustment from converting to the parent's reporting currency treated?",
          options: [
            { label: "A", text: "As a remeasurement gain or loss in net income", isCorrect: false, rationale: "Remeasurement applies when the functional currency differs from the recording currency; here they are the same." },
            { label: "B", text: "As a cumulative translation adjustment in other comprehensive income", isCorrect: true, rationale: "Correct — when the local currency is the functional currency, the current rate method is used and the resulting translation adjustment goes to OCI." },
            { label: "C", text: "As an adjustment to retained earnings", isCorrect: false, rationale: "Translation adjustments accumulate in OCI, not directly in retained earnings." },
            { label: "D", text: "It is not recognized until the subsidiary is sold", isCorrect: false, rationale: "The adjustment is recognized in OCI each period; it is reclassified to earnings only upon disposal of the foreign operation." },
          ],
          explanation: "When the functional currency is the local currency, financial statements are translated using the current rate method and the resulting adjustment is reported in other comprehensive income as a cumulative translation adjustment. Remeasurement gains and losses, by contrast, flow through net income.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["foreign currency", "translation"],
        },
      ],
    },
    {
      slug: "employee-benefit-plan-accounting",
      title: "Employee Benefit Plan Accounting",
      shortDescription: "Defined benefit pension accounting, funded status, and the components of net periodic pension cost.",
      blueprintArea: "Area II: Technical Accounting and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 5,
      studyMaterialHtml: barContent["employee-benefit-plan-accounting"].study,
      revisionNoteHtml: barContent["employee-benefit-plan-accounting"].revision,
      mcqs: [
        {
          question: "A defined benefit plan has plan assets with a fair value of $8,000,000 and a projected benefit obligation of $9,500,000. How is this reported on the balance sheet?",
          options: [
            { label: "A", text: "A $1,500,000 noncurrent liability", isCorrect: true, rationale: "Correct — funded status is plan assets minus PBO: $8,000,000 − $9,500,000 = $(1,500,000), an underfunded position reported as a liability." },
            { label: "B", text: "A $1,500,000 noncurrent asset", isCorrect: false, rationale: "An asset arises only when plan assets exceed the PBO (overfunded)." },
            { label: "C", text: "$8,000,000 asset and $9,500,000 liability reported separately (gross)", isCorrect: false, rationale: "The funded status is reported net, not gross." },
            { label: "D", text: "No balance sheet recognition; disclosure only", isCorrect: false, rationale: "Full funded status must be recognized on the balance sheet." },
          ],
          explanation: "Employers must recognize the full funded status of a defined benefit plan on the balance sheet, measured as the fair value of plan assets minus the projected benefit obligation. Here the plan is underfunded by $1,500,000, producing a liability.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["pensions", "funded status"],
        },
      ],
    },
    {
      slug: "stock-compensation",
      title: "Stock Compensation",
      shortDescription: "Share-based payment accounting, grant-date fair value, and the effect of forfeitures and modifications.",
      blueprintArea: "Area II: Technical Accounting and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 6,
      studyMaterialHtml: barContent["stock-compensation"].study,
      revisionNoteHtml: barContent["stock-compensation"].revision,
      mcqs: [
        {
          question: "A company grants options that vest only if the share price reaches $50 within three years. The employees complete the service period, but the share price never reaches $50. How is compensation expense treated?",
          options: [
            { label: "A", text: "All previously recognized expense is reversed", isCorrect: false, rationale: "Reversal applies to performance conditions, not market conditions." },
            { label: "B", text: "The expense is retained, because a market condition is reflected in the grant-date fair value", isCorrect: true, rationale: "Correct — a market condition's probability is built into the grant-date fair value, so as long as the requisite service is rendered, the expense is not reversed even if the target is never achieved." },
            { label: "C", text: "Expense is recognized only when the share price target is achieved", isCorrect: false, rationale: "Expense is recognized over the service period regardless, since the condition is priced into fair value." },
            { label: "D", text: "The award is reclassified as a liability", isCorrect: false, rationale: "Failure to meet a market condition does not change the classification of the award." },
          ],
          explanation: "Market conditions (such as a share price target) are incorporated into the grant-date fair value measurement. Consequently, if employees render the required service, compensation cost is not reversed even when the market condition is never satisfied. Performance conditions behave differently — expense is reversed if achievement becomes improbable.",
          difficulty: "HARD",
          questionType: "EXCEPTION",
          tags: ["stock compensation", "market condition"],
        },
      ],
    },
    {
      slug: "revenue-for-specific-industries",
      title: "Revenue for Specific Arrangements",
      shortDescription: "Long-term and loss contracts, licenses, repurchase agreements, material rights, principal versus agent, and contract modifications.",
      blueprintArea: "Area II: Technical Accounting and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 60,
      order: 7,
      studyMaterialHtml: barContent["revenue-for-specific-industries"].study,
      revisionNoteHtml: barContent["revenue-for-specific-industries"].revision,
      mcqs: [
        {
          question: "A contractor's fixed-price contract of $5,000,000 now has total estimated costs of $5,600,000. Costs incurred to date are $2,800,000. How should the expected loss be recognized?",
          options: [
            { label: "A", text: "Recognize half the loss now and half in future periods, proportional to progress", isCorrect: false, rationale: "Anticipated contract losses are not allocated over time." },
            { label: "B", text: "Recognize the entire $600,000 expected loss immediately", isCorrect: true, rationale: "Correct — when a loss on the total contract becomes probable and estimable, the full expected loss is recognized in the period it becomes evident." },
            { label: "C", text: "Recognize the loss only when the contract is completed", isCorrect: false, rationale: "Deferring an expected loss to completion is not permitted." },
            { label: "D", text: "Do not recognize a loss because costs may still decrease", isCorrect: false, rationale: "Once a loss is expected on the overall contract, it must be recognized." },
          ],
          explanation: "When total estimated costs exceed the contract price, the entire anticipated loss ($5,600,000 − $5,000,000 = $600,000) is recognized immediately in the period the loss becomes evident, regardless of the stage of completion.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["revenue", "long-term contracts"],
        },
      ],
    },
    {
      slug: "lease-accounting-lessor",
      title: "Lease Accounting — Lessor Perspective",
      shortDescription: "Sales-type, direct financing, and operating lease classification and accounting for lessors.",
      blueprintArea: "Area II: Technical Accounting and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 60,
      order: 8,
      studyMaterialHtml: barContent["lease-accounting-lessor"].study,
      revisionNoteHtml: barContent["lease-accounting-lessor"].revision,
      mcqs: [
        {
          question: "What is the primary accounting difference between a sales-type lease and a direct financing lease for a lessor?",
          options: [
            { label: "A", text: "Only a sales-type lease results in derecognition of the leased asset", isCorrect: false, rationale: "Both classifications derecognize the asset and replace it with a net investment in the lease." },
            { label: "B", text: "Selling profit is recognized immediately in a sales-type lease but deferred over the term in a direct financing lease", isCorrect: true, rationale: "Correct — this is the defining distinction between the two lessor finance-lease classifications." },
            { label: "C", text: "Only a direct financing lease produces interest income", isCorrect: false, rationale: "Both produce interest income on the net investment over the lease term." },
            { label: "D", text: "A direct financing lease keeps the asset on the lessor's balance sheet", isCorrect: false, rationale: "That describes an operating lease; direct financing leases derecognize the asset." },
          ],
          explanation: "Both sales-type and direct financing leases remove the underlying asset and record a net investment in the lease, earning interest income over the term. The difference is the treatment of selling profit: recognized immediately in a sales-type lease, and deferred and recognized over the lease term in a direct financing lease.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["leases", "lessor"],
        },
      ],
    },
    {
      slug: "financial-forecasting-and-projections",
      title: "Financial Forecasting, Budgeting & Valuation",
      shortDescription: "Building forecasts, budget variance analysis, cost-volume-profit, and business valuation approaches.",
      blueprintArea: "Area I: Business Analysis",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 9,
      studyMaterialHtml: barContent["financial-forecasting-and-projections"].study,
      revisionNoteHtml: barContent["financial-forecasting-and-projections"].revision,
      mcqs: [
        {
          question: "A product sells for $80 with variable costs of $50 per unit. Fixed costs are $360,000. How many units must be sold to earn a target operating profit of $90,000?",
          options: [
            { label: "A", text: "12,000 units", isCorrect: false, rationale: "This is the breakeven volume ($360,000 ÷ $30), which ignores the target profit." },
            { label: "B", text: "15,000 units", isCorrect: true, rationale: "Correct — contribution margin per unit is $80 − $50 = $30. ($360,000 + $90,000) ÷ $30 = 15,000 units." },
            { label: "C", text: "5,625 units", isCorrect: false, rationale: "This incorrectly divides by the selling price rather than the contribution margin." },
            { label: "D", text: "18,000 units", isCorrect: false, rationale: "This overstates the requirement; the correct calculation yields 15,000 units." },
          ],
          explanation: "Contribution margin per unit is $80 − $50 = $30. Units needed for a target profit equal (fixed costs + target profit) ÷ contribution margin per unit = ($360,000 + $90,000) ÷ $30 = 15,000 units.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["CVP", "breakeven"],
        },
      ],
    },
    {
      slug: "data-analytics-for-accounting",
      title: "Data Analytics for Accounting",
      shortDescription: "Types of analytics, data visualization, and using analytics to support financial reporting decisions.",
      blueprintArea: "Area I: Business Analysis",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 45,
      order: 10,
      studyMaterialHtml: barContent["data-analytics-for-accounting"].study,
      revisionNoteHtml: barContent["data-analytics-for-accounting"].revision,
      mcqs: [
        {
          question: "An analyst builds a model that recommends the optimal inventory reorder quantity for each SKU based on demand forecasts and carrying costs. What type of analytics is this?",
          options: [
            { label: "A", text: "Descriptive analytics", isCorrect: false, rationale: "Descriptive analytics summarizes what already happened." },
            { label: "B", text: "Diagnostic analytics", isCorrect: false, rationale: "Diagnostic analytics explains why something happened." },
            { label: "C", text: "Prescriptive analytics", isCorrect: true, rationale: "Correct — recommending a specific course of action (the optimal reorder quantity) is prescriptive analytics." },
            { label: "D", text: "Predictive analytics", isCorrect: false, rationale: "Predictive analytics forecasts what is likely to happen; here the model goes further and recommends what to do about it." },
          ],
          explanation: "Prescriptive analytics goes beyond forecasting to recommend a specific action. Predicting demand would be predictive; using that prediction plus cost data to recommend the optimal order quantity is prescriptive.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["data analytics"],
        },
      ],
    },
    {
      slug: "governmental-fund-accounting",
      title: "Governmental Fund Accounting",
      shortDescription: "Fund types, modified accrual basis, and the measurement focus of governmental funds.",
      blueprintArea: "Area III: State and Local Governments",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 70,
      order: 11,
      studyMaterialHtml: barContent["governmental-fund-accounting"].study,
      revisionNoteHtml: barContent["governmental-fund-accounting"].revision,
      mcqs: [
        {
          question: "A city's General Fund purchases a fire truck for $400,000 cash. How is this recorded in the General Fund?",
          options: [
            { label: "A", text: "As a capital asset, depreciated over its useful life", isCorrect: false, rationale: "Governmental funds use the current financial resources measurement focus and do not report capital assets or depreciation." },
            { label: "B", text: "As an expenditure of $400,000", isCorrect: true, rationale: "Correct — under modified accrual with a current financial resources focus, the entire cost is recorded as a capital outlay expenditure in the year of purchase." },
            { label: "C", text: "As an other financing use", isCorrect: false, rationale: "Other financing uses cover items like transfers out and debt issuance-related items, not the direct purchase of an asset." },
            { label: "D", text: "As a prepaid asset amortized over the truck's life", isCorrect: false, rationale: "No such treatment exists for capital purchases in governmental funds." },
          ],
          explanation: "Governmental funds use the current financial resources measurement focus and modified accrual basis. Capital assets are not reported in the fund; the purchase is recorded entirely as an expenditure. The truck would, however, appear as a capital asset in the government-wide statements, which use full accrual.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["governmental", "modified accrual"],
        },
      ],
    },
    {
      slug: "government-wide-financial-statements",
      title: "Government-Wide Statements & the Annual Comprehensive Financial Report",
      shortDescription: "The statement of activities, reconciling fund statements to government-wide statements, component units, and the Annual Comprehensive Financial Report (ACFR).",
      blueprintArea: "Area III: State and Local Governments",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 12,
      studyMaterialHtml: barContent["government-wide-financial-statements"].study,
      revisionNoteHtml: barContent["government-wide-financial-statements"].revision,
      mcqs: [
        {
          question: "In reconciling total governmental fund balances to net position of governmental activities, which adjustment is required?",
          options: [
            { label: "A", text: "Subtract capital assets, because they are not financial resources", isCorrect: false, rationale: "Capital assets must be added, since the funds expensed them but government-wide statements capitalize them." },
            { label: "B", text: "Add capital assets net of accumulated depreciation and subtract long-term liabilities", isCorrect: true, rationale: "Correct — governmental funds report neither capital assets nor long-term debt, so both must be brought in to reach full accrual net position." },
            { label: "C", text: "Add long-term liabilities such as bonds payable", isCorrect: false, rationale: "Long-term liabilities reduce net position and must be subtracted, not added." },
            { label: "D", text: "No reconciliation is required because both use the same basis of accounting", isCorrect: false, rationale: "The two use different bases — modified accrual versus full accrual — which is exactly why a reconciliation is required." },
          ],
          explanation: "Governmental funds use modified accrual and the current financial resources focus, so they exclude capital assets and long-term liabilities. Converting to government-wide net position requires adding capital assets (net of depreciation) and subtracting long-term liabilities, among other adjustments.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["governmental", "reconciliation", "GASB 34"],
        },
        {
          question: "Which fund type is EXCLUDED from the government-wide financial statements?",
          options: [
            { label: "A", text: "Enterprise funds", isCorrect: false, rationale: "Enterprise funds are reported within business-type activities." },
            { label: "B", text: "Fiduciary funds", isCorrect: true, rationale: "Correct — fiduciary resources are held for others and are not available to support the government's own programs, so they are excluded from the government-wide statements." },
            { label: "C", text: "Internal service funds", isCorrect: false, rationale: "Internal service funds are generally consolidated into governmental activities." },
            { label: "D", text: "Special revenue funds", isCorrect: false, rationale: "Special revenue funds are governmental funds reported within governmental activities." },
          ],
          explanation: "Fiduciary funds — pension trust, investment trust, private-purpose trust, and custodial funds — hold resources for the benefit of parties outside the government. Because those resources cannot be used to support the government's own programs, they are excluded from the government-wide statements while still being presented in the fund financial statements.",
          difficulty: "MEDIUM",
          questionType: "EXCEPTION",
          tags: ["governmental", "fund types"],
        },
      ],
    },
    {
      slug: "public-company-reporting-topics",
      title: "Public Company Reporting Topics",
      shortDescription: "Diluted earnings per share with multiple securities, Securities and Exchange Commission (SEC) disclosures, internal control certifications, and recent disclosure standards.",
      blueprintArea: "Area II: Technical Accounting and Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 13,
      studyMaterialHtml: barContent["public-company-reporting-topics"].study,
      revisionNoteHtml: barContent["public-company-reporting-topics"].revision,
      mcqs: [
        {
          question: "A company has combined segment assets of $80,000,000. One segment has revenue of 6% of combined revenue, a loss equal to 4% of the relevant profit/loss benchmark, and assets of $9,000,000. Is the segment reportable?",
          options: [
            { label: "A", text: "No, because it fails both the revenue and profit tests", isCorrect: false, rationale: "The tests are applied independently — meeting any single one makes the segment reportable." },
            { label: "B", text: "Yes, because its assets are 11.25% of combined assets, exceeding the 10% threshold", isCorrect: true, rationale: "Correct — $9,000,000 ÷ $80,000,000 = 11.25%. Meeting the asset test alone makes the segment reportable regardless of the revenue and profit results." },
            { label: "C", text: "No, because a segment must meet at least two of the three tests", isCorrect: false, rationale: "Only one of the three quantitative thresholds needs to be satisfied." },
            { label: "D", text: "Only if the 75% test would otherwise not be met", isCorrect: false, rationale: "The 75% test adds segments when needed; it does not override a segment that already qualifies." },
          ],
          explanation: "A segment is reportable if it meets any one of the three 10% thresholds (revenue, absolute profit or loss, or assets). With assets of $9,000,000 against combined assets of $80,000,000 — 11.25% — the asset test alone makes this segment reportable.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["segment reporting"],
        },
      ],
    },
  ],
};
