export type FaqSeed = { category: string; question: string; answer: string; order: number };

export const faqs: FaqSeed[] = [
  // Basics
  { category: "Basics", order: 1, question: "What is the US CPA?", answer: "The Certified Public Accountant (CPA) is a license issued by individual US state boards of accountancy, held by accounting professionals who have passed the Uniform CPA Examination and met a state's education, examination, and experience requirements. It's the credential that authorizes someone to sign audit reports and practice public accounting in the US." },
  { category: "Basics", order: 2, question: "How many exam sections are there?", answer: "Four: three mandatory Core sections (FAR, AUD, REG) that every candidate takes, plus one Discipline section chosen from BAR, ISC, or TCP. All combinations lead to the same CPA license." },
  { category: "Basics", order: 3, question: "Is the CPA Exam difficult?", answer: "Yes — pass rates for individual sections have historically ranged roughly in the 40s-60s percent range and vary by section and testing window. It's a demanding, application-heavy exam, especially FAR and REG, which is why structured study across several months is standard rather than the exception." },
  { category: "Basics", order: 4, question: "What is the Discipline section, exactly?", answer: "Starting with CPA Evolution, candidates choose one Discipline — BAR (Business Analysis and Reporting), ISC (Information Systems and Controls), or TCP (Tax Compliance and Planning) — based on their career interests. Unlike the Core sections, all candidates don't take the same Discipline, but all Disciplines lead to an identical CPA license." },
  { category: "Basics", order: 5, question: "Which Discipline should I choose?", answer: "There's no universally 'easiest' choice — pick based on career direction. BAR suits candidates headed toward financial reporting, valuation, or advisory. ISC fits IT audit, risk, and controls interests. TCP is for candidates focused on tax planning and compliance. Many candidates choose based on which Core section (FAR, ISC content, or REG) they found most natural, since each Discipline extends one of those." },

  // Eligibility
  { category: "Eligibility", order: 1, question: "Can Indians take the CPA Exam?", answer: "Yes. Indian candidates are eligible provided they meet a US state board's education requirements (typically verified through a credential evaluation) and are approved by that board — nationality or residency in the US is not required." },
  { category: "Eligibility", order: 2, question: "Can CA students pursue CPA?", answer: "Yes, and many do. Indian CA qualification often satisfies a significant portion of a US state board's education requirements once evaluated, though this varies by state and by how your specific CA/degree combination is assessed." },
  { category: "Eligibility", order: 3, question: "Can B.Com students pursue CPA?", answer: "Often yes, but a standalone 3-year B.Com is frequently evaluated at fewer than 120 US semester hours, which is below the minimum most state boards accept even under the newer 120-credit licensure pathway. An M.Com, CA/CMA-level coursework, or additional credits can close the gap — only a formal credential evaluation tells you where you actually stand." },
  { category: "Eligibility", order: 7, question: "What is the 120-credit CPA licensure pathway?", answer: "Historically, licensure required 150 semester hours of education plus about one year of experience. Many states have now added an alternative: a bachelor's degree with 120 semester hours plus two years of supervised experience. As of mid-2026, roughly two dozen jurisdictions had this pathway in force (New York's takes effect in November 2026), and more have enacted laws starting later. Rules differ in the details, so confirm your chosen board's current requirements before relying on it." },
  { category: "Eligibility", order: 4, question: "What is credential evaluation?", answer: "It's the process where a NACES-member evaluation agency reviews your Indian academic transcripts and converts them into US semester-hour equivalents, so a state board can determine if you meet its education requirement." },
  { category: "Eligibility", order: 5, question: "What is NIES?", answer: "NASBA International Evaluation Services — an evaluation service NASBA offers specifically to help international candidates, including many in India, find a state board whose requirements they're likely to meet." },
  { category: "Eligibility", order: 6, question: "Do I need work experience before taking the exam?", answer: "No — most state boards let you sit for the exam before completing your experience requirement. Experience requirements typically apply to licensure (getting the CPA license), not to exam eligibility." },

  // Application
  { category: "Application", order: 1, question: "What is NASBA?", answer: "The National Association of State Boards of Accountancy — it coordinates application processing, international administration, and candidate services across the 50+ US jurisdictions that license CPAs." },
  { category: "Application", order: 2, question: "What is AICPA?", answer: "The American Institute of CPAs — the national professional body that develops the Uniform CPA Examination content (the Blueprints) in partnership with NASBA and the state boards, and sets professional standards for CPAs." },
  { category: "Application", order: 3, question: "What is Prometric?", answer: "Prometric is the test-delivery company that administers the CPA Exam at physical testing centers, including several cities in India." },
  { category: "Application", order: 4, question: "What is an NTS?", answer: "Notice to Schedule — the document issued once your state board approves your exam application. You need a valid NTS for each section before you can book a Prometric appointment." },
  { category: "Application", order: 5, question: "How long is an NTS valid?", answer: "NTS validity periods vary by state board, but are commonly around 6 months per section — check your specific state board's current policy, since expired NTS periods generally require reapplying and paying fees again." },

  // State Selection
  { category: "State Selection", order: 1, question: "Do I need to live in the state I apply through?", answer: "No. Most Indian candidates choose a state board based on which one's education/experience requirements they can meet — not on residency or where they plan to work." },
  { category: "State Selection", order: 2, question: "Which states are popular with Indian candidates?", answer: "This changes as state rules evolve, so treat any specific list as a starting point to verify, not a fixed answer — some state boards have historically had more accommodating credit-hour or experience rules for international candidates. Confirm current requirements directly with NASBA/NIES or the specific board." },
  { category: "State Selection", order: 3, question: "Can I change my state board after starting the process?", answer: "It's possible but adds friction and cost — you may need to reapply and, depending on timing, some exam credit transfer rules (like the NASBA Advisory Evaluation) can help. It's better to pick carefully upfront using a proper credential evaluation." },

  // Fees
  { category: "Fees", order: 1, question: "How much does US CPA cost for an Indian candidate?", answer: "It includes an application/registration fee, a per-section exam fee, an international administration fee (if testing outside the US), and a one-time credential evaluation fee. These figures change and vary by state, so use our Fee Estimator (/fees) for current, sourced figures rather than a fixed number here." },
  { category: "Fees", order: 2, question: "Is there an extra cost for testing in India?", answer: "Yes — testing internationally (including in India) carries an additional international administration fee per section, on top of the standard exam fee, paid separately to NASBA." },
  { category: "Fees", order: 3, question: "Are CPA Exam fees refundable?", answer: "Generally not once an NTS is issued or an exam is scheduled, though policies vary by state board and circumstance (e.g., Prometric rescheduling rules differ from state-board application refund rules). Always check the specific policy before paying." },

  // Exam
  { category: "Exam", order: 1, question: "How many sections are mandatory?", answer: "Three Core sections — FAR, AUD, and REG — are mandatory for every candidate, plus exactly one Discipline section chosen from BAR, ISC, or TCP." },
  { category: "Exam", order: 2, question: "Is the CPA Exam purely multiple choice?", answer: "No. Each section combines multiple-choice questions (MCQs) with task-based simulations (TBS) across five testlets, and TBS questions typically make up roughly half the scored content in most sections." },
  { category: "Exam", order: 3, question: "How long is each section?", answer: "Each of the four sections is 4 hours long, for a total exam commitment of 16 hours across all four sections." },
  { category: "Exam", order: 4, question: "How long do I have to pass all four sections?", answer: "Most state boards now give you a rolling 30-month window (up from the older 18-month rule), usually measured from the date the score for your first passed section is released. If the window closes before you pass all four, your earliest credit expires and that section must be retaken. A few boards measure it differently, so check yours." },
  { category: "Exam", order: 6, question: "What score do I need to pass?", answer: "A scaled score of 75 on a 0-99 scale, in every section. It's a scaled score rather than a percentage, so 75 does not mean 75% of questions correct, and MCQs and task-based simulations are weighted together to produce it." },
  { category: "Exam", order: 7, question: "When can I take each section?", answer: "The Core sections (FAR, AUD, REG) are offered year-round under continuous testing. The Discipline sections (BAR, ISC, TCP) are only offered in the first month of each quarter: January, April, July, and October. Plan your Discipline attempt around those windows, since a missed window means a three-month wait." },
  { category: "Exam", order: 5, question: "Can I retake a section I failed?", answer: "Yes, though retake availability depends on the testing windows for that section (Core sections are offered year-round; Discipline sections only in January, April, July, and October) and your state board's reapplication rules." },

  // India
  { category: "India", order: 1, question: "Where can I take the CPA Exam in India?", answer: "NASBA has arranged for Prometric testing centers in several Indian cities, including Ahmedabad, Bengaluru, Kolkata, Chennai, Hyderabad, Mumbai, New Delhi, and Trivandrum — availability can change, so confirm current locations when scheduling." },
  { category: "India", order: 2, question: "Do I need to travel to the US to take the exam?", answer: "No — once you're eligible through a US state board and hold a valid NTS, you can book your Prometric appointment at an Indian testing center and take the exam without traveling to the US." },
  { category: "India", order: 3, question: "Is CPA useful after CA in India?", answer: "It can be, particularly if your work touches US GAAP, SEC reporting, US tax, or Big 4/MNC engagement teams serving US clients. It's a complementary credential rather than a strict upgrade to CA — see our full CPA for Indian Students guide for a deeper breakdown." },

  // Preparation
  { category: "Preparation", order: 1, question: "How long does it take to prepare for the CPA Exam?", answer: "Total study time across all four sections commonly falls in the 300-450+ hour range, spread over roughly 6-18 months depending on whether you're studying full-time or working alongside a job." },
  { category: "Preparation", order: 2, question: "Which section should I take first?", answer: "There's no single right order, but many candidates start with AUD or FAR to build foundational knowledge early, and take their chosen Discipline after (or alongside) the related Core section — e.g., TCP after REG, BAR after FAR." },
  { category: "Preparation", order: 3, question: "How can I study for CPA while working full-time?", answer: "Consistent daily blocks (even 60-90 minutes) beat occasional long weekend sessions. Most working candidates plan for 3-4 months of focused study per section, prioritizing topic-by-topic mastery with revision notes and MCQ practice rather than re-reading full study material repeatedly." },

  // Career
  { category: "Career", order: 1, question: "What can I do with a US CPA in India?", answer: "Common paths include Big 4 and mid-tier audit/US tax practices with India-based teams serving US clients, US GAAP-focused controllership roles at MNCs and GCCs (Global Capability Centres), and advisory roles that specifically require US accounting expertise." },
  { category: "Career", order: 2, question: "Does CPA guarantee a job?", answer: "No — no credential guarantees employment. The CPA can open doors to specific roles and demonstrate a verified level of US accounting expertise, but outcomes depend on your experience, the market, and how you position the credential." },

  // Licensing
  { category: "Licensing", order: 1, question: "Is passing the exam the same as being licensed?", answer: "No — passing all four sections is a major milestone, but most states also require verified work experience (typically one year under the 150-credit pathway, or two years under the newer 120-credit pathway, usually supervised by a licensed CPA) and, in many states, a separate ethics exam before issuing the actual CPA license." },
  { category: "Licensing", order: 2, question: "Can I use the CPA license while working in India?", answer: "A US CPA license authorizes you to practice as a CPA under that state's rules — using the credential/title in India is generally about demonstrating your qualification rather than practicing under Indian regulatory authority, which is governed separately by Indian law and ICAI rules for statutory work in India." },

  // CA / Indian Students
  { category: "CA / Indian Students", order: 1, question: "CPA vs CA: what actually differs?", answer: "CA is India's domestic credential, built around Ind AS, Indian tax, and Indian company law, and is required for Indian statutory audit work. CPA is the US credential, built around US GAAP, SEC reporting, and US federal tax. They test different bodies of knowledge for different regulatory jurisdictions." },
  { category: "CA / Indian Students", order: 2, question: "CPA vs ACCA: which is better?", answer: "Neither is universally 'better' — ACCA is UK/global-oriented and widely recognized across the Middle East and UK-linked markets; CPA is specifically US-oriented. The right choice depends on which markets and employers you're targeting." },
  { category: "CA / Indian Students", order: 3, question: "Is CPA worth it for a working professional?", answer: "It depends on whether your career path benefits specifically from US GAAP/US tax expertise — for professionals in GCCs, Big 4 US-facing teams, or MNC finance functions, it often is; for purely domestic Indian practice, Indian CA remains the more directly relevant credential." },
];
