import type { SubjectSeed } from "./types";
import { farContent } from "./content/far";

export const far: SubjectSeed = {
  slug: "far",
  name: "Financial Accounting and Reporting",
  shortName: "FAR",
  type: "CORE",
  description:
    "Financial Accounting and Reporting (FAR) tests your ability to prepare and analyze financial statements under US Generally Accepted Accounting Principles (GAAP), plus not-for-profit and governmental reporting. The 2026 blueprint splits it into Financial Reporting (30–40%), Select Balance Sheet Accounts (30–40%), and Select Transactions (25–35%). It's the broadest Core section and usually needs the most study time.",
  difficulty: "HARD",
  estimatedHours: 140,
  blueprintUrl: "https://www.aicpa-cima.com/resources/download/far-cpa-exam-blueprint",
  order: 1,
  topics: [
    {
      slug: "conceptual-framework-and-financial-statement-presentation",
      title: "Conceptual Framework & Financial Statement Presentation",
      shortDescription: "The Financial Accounting Standards Board (FASB) conceptual framework, qualitative characteristics, elements, measurement, and the required financial statements.",
      blueprintArea: "Area I: Financial Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "EASY",
      estimatedMinutes: 45,
      order: 1,
      studyMaterialHtml: farContent["conceptual-framework-and-financial-statement-presentation"].study,
      revisionNoteHtml: farContent["conceptual-framework-and-financial-statement-presentation"].revision,
      mcqs: [
        {
          question: "Under the FASB conceptual framework, which of the following is one of the two fundamental qualitative characteristics of useful financial information?",
          options: [
            { label: "A", text: "Comparability", isCorrect: false, rationale: "Comparability is an enhancing characteristic, not a fundamental one." },
            { label: "B", text: "Faithful representation", isCorrect: true, rationale: "Correct — relevance and faithful representation are the two fundamental qualitative characteristics." },
            { label: "C", text: "Timeliness", isCorrect: false, rationale: "Timeliness is an enhancing characteristic." },
            { label: "D", text: "Verifiability", isCorrect: false, rationale: "Verifiability is an enhancing characteristic." },
          ],
          explanation: "The conceptual framework identifies relevance and faithful representation as the two fundamental qualitative characteristics. Comparability, verifiability, timeliness, and understandability enhance the usefulness of information that is already relevant and faithfully represented.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["conceptual framework"],
        },
        {
          question: "A logistics company sells one of its used delivery trucks for more than its carrying value. How should this transaction be classified in the income statement?",
          options: [
            { label: "A", text: "As revenue, since the truck was used to generate revenue", isCorrect: false, rationale: "Revenue arises from an entity's ongoing major or central operations — selling delivery trucks isn't the logistics company's business." },
            { label: "B", text: "As a gain, since it results from a peripheral or incidental transaction", isCorrect: true, rationale: "Correct — disposing of equipment not held for resale is peripheral to a logistics company's core operations, so any excess of proceeds over carrying value is a gain." },
            { label: "C", text: "Directly to other comprehensive income", isCorrect: false, rationale: "This is a realized transaction affecting net income, not an OCI item." },
            { label: "D", text: "As a reduction of operating expenses", isCorrect: false, rationale: "Gains are reported separately from operating expenses, typically within other income/(expense)." },
          ],
          explanation: "Gains arise from peripheral or incidental transactions, while revenue arises from an entity's ongoing major operations. Selling a used truck is incidental to a logistics company's core business of moving goods, so the excess of proceeds over carrying value is a gain, not revenue.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["conceptual framework", "exam trap"],
        },
      ],
    },
    {
      slug: "balance-sheet-and-income-statement-preparation",
      title: "Balance Sheet & Income Statement Preparation",
      shortDescription: "Classified balance sheet structure, multi-step income statement, and discontinued operations presentation.",
      blueprintArea: "Area I: Financial Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 60,
      order: 2,
      studyMaterialHtml: farContent["balance-sheet-and-income-statement-preparation"].study,
      revisionNoteHtml: farContent["balance-sheet-and-income-statement-preparation"].revision,
    },
    {
      slug: "statement-of-cash-flows",
      title: "Statement of Cash Flows",
      shortDescription: "Direct vs indirect method, and classifying activities as operating, investing, or financing.",
      blueprintArea: "Area I: Financial Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 75,
      order: 3,
      studyMaterialHtml: farContent["statement-of-cash-flows"].study,
      revisionNoteHtml: farContent["statement-of-cash-flows"].revision,
    },
    {
      slug: "notes-subsequent-events-and-going-concern",
      title: "Notes, Subsequent Events & Going Concern",
      shortDescription: "Recognized vs non-recognized subsequent events and management's going-concern evaluation.",
      blueprintArea: "Area I: Financial Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 45,
      order: 4,
      studyMaterialHtml: farContent["notes-subsequent-events-and-going-concern"].study,
      revisionNoteHtml: farContent["notes-subsequent-events-and-going-concern"].revision,
    },
    {
      slug: "revenue-recognition",
      title: "Revenue Recognition",
      shortDescription: "The five-step model for revenue from contracts with customers: contracts, performance obligations, transaction price, allocation, and timing.",
      blueprintArea: "Area III: Select Transactions",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 90,
      order: 5,
      studyMaterialHtml: farContent["revenue-recognition"].study,
      revisionNoteHtml: farContent["revenue-recognition"].revision,
      mcqs: [
        {
          question: "Under ASC 606, revenue from a performance obligation should be recognized over time if which of the following is true?",
          options: [
            { label: "A", text: "The customer pays in installments over the contract term", isCorrect: false, rationale: "Payment terms alone don't determine timing of revenue recognition." },
            { label: "B", text: "The entity's performance creates an asset with no alternative use to the entity and the entity has an enforceable right to payment for performance completed to date", isCorrect: true, rationale: "Correct — this is one of the three over-time recognition criteria under ASC 606." },
            { label: "C", text: "Legal title to the goods has transferred to the customer", isCorrect: false, rationale: "Transfer of legal title is an indicator of point-in-time control transfer, not an over-time criterion." },
            { label: "D", text: "The contract is non-cancellable", isCorrect: false, rationale: "Cancellability affects whether a contract exists, not the timing of recognition once it does." },
          ],
          explanation: "ASC 606 recognizes revenue over time when: the customer simultaneously receives and consumes benefits as the entity performs; the entity's performance creates or enhances a customer-controlled asset; or the asset created has no alternative use to the entity and the entity has an enforceable right to payment for performance completed to date.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["revenue recognition"],
        },
        {
          question: "A company sells a machine for $100,000 with a 5% volume rebate that historically about 60% of customers claim. How should the company initially estimate the transaction price for a sale where the rebate is expected to be claimed?",
          options: [
            { label: "A", text: "$100,000, recognizing the rebate only when paid", isCorrect: false, rationale: "Variable consideration must be estimated at contract inception, not recognized only when paid — that would misstate revenue in the period of sale." },
            { label: "B", text: "$95,000, net of the full expected rebate, subject to the constraint on variable consideration", isCorrect: true, rationale: "Correct — expected variable consideration (the rebate) reduces the transaction price to the extent it's probable a significant revenue reversal won't occur." },
            { label: "C", text: "$100,000, with the rebate recorded as a marketing expense when paid", isCorrect: false, rationale: "Rebates to customers reduce the transaction price under ASC 606; they are not marketing expenses." },
            { label: "D", text: "$97,500, averaging the rebate probability into the price", isCorrect: false, rationale: "The rebate is estimated using the expected value or most likely amount method — simple probability-weighted averaging without following the standard's estimation methods is not correct here." },
          ],
          explanation: "Variable consideration such as rebates must be estimated and included in the transaction price (reducing it) at contract inception, to the extent it is probable that a significant reversal of cumulative revenue will not occur. This is part of Step 3 of the ASC 606 model.",
          difficulty: "HARD",
          questionType: "CALCULATION",
          tags: ["revenue recognition", "variable consideration"],
        },
        {
          question: "Which of the following costs should be capitalized as a contract cost under ASC 606, assuming the amortization period exceeds one year?",
          options: [
            { label: "A", text: "General administrative costs of the sales department", isCorrect: false, rationale: "These are not incremental to obtaining a specific contract, so they're expensed as incurred." },
            { label: "B", text: "A sales commission paid only if the specific contract is won", isCorrect: true, rationale: "Correct — this is an incremental cost of obtaining a contract and should be capitalized if the entity expects to recover it and the amortization period exceeds one year." },
            { label: "C", text: "Cost of goods sold for the product delivered under the contract", isCorrect: false, rationale: "COGS is expensed when the related revenue is recognized; it is not a contract acquisition cost." },
            { label: "D", text: "Bid preparation costs that would have been incurred regardless of whether the contract was won", isCorrect: false, rationale: "Only costs incremental to winning the specific contract qualify — costs incurred regardless of outcome are expensed." },
          ],
          explanation: "Incremental costs of obtaining a contract — costs that would not have been incurred if the contract had not been obtained, such as a commission paid only on a won deal — are capitalized (if recoverable) and amortized over the period of benefit, unless that period is one year or less.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["revenue recognition", "contract costs"],
        },
      ],
    },
    {
      slug: "cash-receivables-and-bad-debts",
      title: "Cash, Receivables & Bad Debts",
      shortDescription: "Cash equivalents, bank reconciliations, the current expected credit loss (CECL) model, and transfers of receivables.",
      blueprintArea: "Area II: Select Balance Sheet Accounts",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 60,
      order: 6,
      studyMaterialHtml: farContent["cash-receivables-and-bad-debts"].study,
      revisionNoteHtml: farContent["cash-receivables-and-bad-debts"].revision,
    },
    {
      slug: "inventory",
      title: "Inventory",
      shortDescription: "Cost flow assumptions, lower of cost and net realizable value, and the periodic vs perpetual systems.",
      blueprintArea: "Area II: Select Balance Sheet Accounts",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 70,
      order: 7,
      studyMaterialHtml: farContent["inventory"].study,
      revisionNoteHtml: farContent["inventory"].revision,
      mcqs: [
        {
          question: "A company uses LIFO for both tax and financial reporting. During a period of rising prices, which of the following is true relative to FIFO?",
          options: [
            { label: "A", text: "LIFO results in higher net income and higher ending inventory", isCorrect: false, rationale: "This describes FIFO's effect in rising prices, not LIFO's." },
            { label: "B", text: "LIFO results in higher cost of goods sold and lower ending inventory", isCorrect: true, rationale: "Correct — under LIFO, the most recently purchased (higher-cost) items are expensed first, increasing COGS and leaving older, lower-cost items in ending inventory." },
            { label: "C", text: "LIFO and FIFO always produce identical net income", isCorrect: false, rationale: "They only produce identical results when unit costs are unchanged during the period." },
            { label: "D", text: "LIFO is prohibited under US GAAP", isCorrect: false, rationale: "LIFO is permitted under US GAAP (though not under IFRS)." },
          ],
          explanation: "In a period of rising prices, LIFO matches the most recent (higher) costs against revenue, producing higher COGS, lower net income, and a lower ending inventory balance compared to FIFO.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["inventory", "LIFO", "FIFO"],
        },
        {
          question: "Inventory has a cost of $80 per unit. Selling price is $100, disposal costs are $15, and normal profit margin is $10. Replacement cost is $70. Under the lower-of-cost-or-market rule (LIFO/retail inventory), what is the inventory's reported value per unit?",
          options: [
            { label: "A", text: "$70", isCorrect: false, rationale: "Replacement cost of $70 is below the floor of $75, so $70 cannot be used as 'market' — the floor applies instead." },
            { label: "B", text: "$75", isCorrect: true, rationale: "Correct — NRV (ceiling) = $100 − $15 = $85; floor = $85 − $10 = $75. Replacement cost ($70) is below the floor, so market is capped at the floor of $75. Lower of cost ($80) and market ($75) = $75." },
            { label: "C", text: "$80", isCorrect: false, rationale: "Cost is $80, but market ($75) is lower, so the item should be written down to $75, not left at cost." },
            { label: "D", text: "$85", isCorrect: false, rationale: "$85 is the NRV ceiling, not the final 'market' figure — market is bounded between the floor and ceiling using replacement cost, which here is below the floor." },
          ],
          explanation: "Under the LCM rule: ceiling = NRV = selling price − disposal costs = $100 − $15 = $85. Floor = NRV − normal profit = $85 − $10 = $75. Since replacement cost ($70) is below the floor, market is set at the floor, $75. Lower of cost ($80) and market ($75) is $75.",
          difficulty: "HARD",
          questionType: "CALCULATION",
          tags: ["inventory", "LCM"],
        },
      ],
    },
    {
      slug: "property-plant-and-equipment",
      title: "Property, Plant & Equipment",
      shortDescription: "Capitalization, depreciation methods, subsequent expenditures, and asset impairment.",
      blueprintArea: "Area II: Select Balance Sheet Accounts",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 75,
      order: 8,
      studyMaterialHtml: farContent["property-plant-and-equipment"].study,
      revisionNoteHtml: farContent["property-plant-and-equipment"].revision,
      mcqs: [
        {
          question: "Under US GAAP, a long-lived asset held for use is tested for impairment. The carrying value is $500,000, undiscounted future net cash flows are $520,000, and fair value is $460,000. What impairment loss, if any, should be recognized?",
          options: [
            { label: "A", text: "$40,000", isCorrect: false, rationale: "This is carrying value minus fair value, but the recoverability test comes first — no impairment is triggered here." },
            { label: "B", text: "$0 — the asset is not impaired", isCorrect: true, rationale: "Correct — the recoverability test compares carrying value ($500,000) to undiscounted cash flows ($520,000). Since undiscounted cash flows exceed carrying value, the asset passes the recoverability test and no impairment is recognized, regardless of the fair value figure." },
            { label: "C", text: "$60,000", isCorrect: false, rationale: "This is undiscounted cash flows minus fair value, which is not how impairment is measured." },
            { label: "D", text: "$20,000", isCorrect: false, rationale: "This is undiscounted cash flows minus carrying value; since it's positive, it confirms no impairment, but $20,000 itself is not an impairment loss figure." },
          ],
          explanation: "US GAAP uses a two-step held-for-use impairment model. Step 1 (recoverability test) compares carrying value to undiscounted future net cash flows; the asset is impaired only if carrying value exceeds that undiscounted figure. Here, $500,000 < $520,000, so the asset passes the recoverability test and no impairment loss is recognized — fair value is irrelevant unless Step 1 indicates impairment.",
          difficulty: "HARD",
          questionType: "CALCULATION",
          tags: ["PP&E", "impairment"],
        },
        {
          question: "A company purchases equipment for $110,000 with an estimated salvage value of $10,000 and a 5-year useful life. Using double-declining-balance depreciation, what is depreciation expense in Year 2?",
          options: [
            { label: "A", text: "$44,000", isCorrect: false, rationale: "This is Year 1 depreciation ($110,000 × 40%), not Year 2." },
            { label: "B", text: "$26,400", isCorrect: true, rationale: "Correct — DDB rate = 2/5 = 40%. Year 1: $110,000 × 40% = $44,000, book value = $66,000. Year 2: $66,000 × 40% = $26,400." },
            { label: "C", text: "$20,000", isCorrect: false, rationale: "This would be straight-line depreciation ($100,000 ÷ 5), not double-declining-balance." },
            { label: "D", text: "$22,000", isCorrect: false, rationale: "This does not correctly apply the 40% DDB rate to the Year 2 beginning book value of $66,000." },
          ],
          explanation: "Double-declining-balance ignores salvage value in the calculation (until the final year, when depreciation is capped so book value doesn't go below salvage). The rate is 2 ÷ useful life = 40%. Year 1 depreciation = $110,000 × 40% = $44,000, leaving book value of $66,000. Year 2 depreciation = $66,000 × 40% = $26,400.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["PP&E", "depreciation"],
        },
      ],
    },
    {
      slug: "intangible-assets-and-goodwill",
      title: "Intangible Assets & Goodwill",
      shortDescription: "Finite and indefinite-lived intangibles, research and development (R&D) and software costs, goodwill impairment, and crypto assets.",
      blueprintArea: "Area II: Select Balance Sheet Accounts",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 60,
      order: 9,
      studyMaterialHtml: farContent["intangible-assets-and-goodwill"].study,
      revisionNoteHtml: farContent["intangible-assets-and-goodwill"].revision,
    },
    {
      slug: "investments-debt-and-equity-securities",
      title: "Investments (Debt & Equity Securities)",
      shortDescription: "Held-to-maturity (HTM), trading, and available-for-sale (AFS) debt securities, equity securities, and the equity method.",
      blueprintArea: "Area II: Select Balance Sheet Accounts",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 75,
      order: 10,
      studyMaterialHtml: farContent["investments-debt-and-equity-securities"].study,
      revisionNoteHtml: farContent["investments-debt-and-equity-securities"].revision,
    },
    {
      slug: "leases",
      title: "Leases",
      shortDescription: "Lease classification, lessee finance and operating leases, right-of-use assets, lease liabilities, and sale-leasebacks.",
      blueprintArea: "Area II: Select Balance Sheet Accounts",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 90,
      order: 11,
      studyMaterialHtml: farContent["leases"].study,
      revisionNoteHtml: farContent["leases"].revision,
      mcqs: [
        {
          question: "A lessee enters into a 4-year lease for equipment with a 10-year remaining economic life. There is no purchase option and ownership does not transfer. The present value of lease payments is 55% of the equipment's fair value. How should the lessee classify this lease?",
          options: [
            { label: "A", text: "Finance lease, because the lease term exceeds 12 months", isCorrect: false, rationale: "Lease term alone (as long as it's over 12 months) does not make a lease a finance lease — it must meet one of the five specific finance-lease criteria." },
            { label: "B", text: "Operating lease, because none of the five finance-lease criteria are met", isCorrect: true, rationale: "Correct — no ownership transfer, no purchase option, the 4-year term is not a major part of the 10-year remaining life, and the PV (55%) is not substantially all of fair value. With none of the five criteria met, it's an operating lease." },
            { label: "C", text: "Finance lease, because the present value exceeds 50% of fair value", isCorrect: false, rationale: "The PV criterion requires the PV to equal or exceed substantially all (generally around 90%) of fair value — 55% does not meet this threshold." },
            { label: "D", text: "The lessee has a choice between finance and operating classification", isCorrect: false, rationale: "Classification is determined by the five criteria, not elected freely by the lessee." },
          ],
          explanation: "A lease is classified as a finance lease if it meets any of the five ASC 842 criteria: ownership transfer, a purchase option reasonably certain to be exercised, lease term is a major part of remaining economic life, PV of payments is substantially all of fair value, or the asset is so specialized it has no alternative use. None apply here (4 of 10 years is not 'major part,' and 55% is not 'substantially all'), so it is an operating lease — though both a ROU asset and lease liability are still recognized.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["leases", "classification"],
        },
        {
          question: "Under ASC 842, how does a lessee's accounting for an operating lease differ from a finance lease in subsequent periods?",
          options: [
            { label: "A", text: "Only finance leases result in a right-of-use asset and lease liability on the balance sheet", isCorrect: false, rationale: "Both finance and operating leases result in a ROU asset and lease liability at commencement under ASC 842." },
            { label: "B", text: "Operating leases recognize a single straight-line lease expense, while finance leases separately recognize interest expense and amortization, typically front-loading total expense", isCorrect: true, rationale: "Correct — this is the key remaining distinction between the two lease types post-ASC 842." },
            { label: "C", text: "Operating leases are never recognized on the balance sheet", isCorrect: false, rationale: "This described the pre-ASC 842 rules; under ASC 842, operating leases are on the balance sheet too, with narrow short-term lease exceptions." },
            { label: "D", text: "Finance leases recognize no interest expense", isCorrect: false, rationale: "Finance leases specifically do recognize separate interest expense using the effective interest method on the lease liability." },
          ],
          explanation: "Since ASC 842 put both finance and operating leases on the balance sheet, the remaining difference is the income statement pattern: finance leases separately recognize interest expense (declining over time) and straight-line ROU amortization, producing a front-loaded total expense, while operating leases recognize one combined, straight-line lease expense.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["leases"],
        },
      ],
    },
    {
      slug: "current-liabilities-contingencies-and-commitments",
      title: "Current Liabilities, Contingencies & Commitments",
      shortDescription: "Accrued liabilities, loss contingency recognition thresholds, and warranty accounting.",
      blueprintArea: "Area II: Select Balance Sheet Accounts",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 60,
      order: 12,
      studyMaterialHtml: farContent["current-liabilities-contingencies-and-commitments"].study,
      revisionNoteHtml: farContent["current-liabilities-contingencies-and-commitments"].revision,
    },
    {
      slug: "long-term-debt",
      title: "Long-Term Debt (Bonds & Notes)",
      shortDescription: "Bond issuance at premium/discount, effective-interest amortization, and troubled debt restructuring.",
      blueprintArea: "Area II: Select Balance Sheet Accounts",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 75,
      order: 13,
      studyMaterialHtml: farContent["long-term-debt"].study,
      revisionNoteHtml: farContent["long-term-debt"].revision,
    },
    {
      slug: "equity-and-earnings-per-share",
      title: "Equity & Earnings Per Share",
      shortDescription: "Stock issuances, treasury stock, dividends and splits, share-based pay basics, and basic and diluted earnings per share (EPS).",
      blueprintArea: "Area II: Select Balance Sheet Accounts",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 80,
      order: 14,
      studyMaterialHtml: farContent["equity-and-earnings-per-share"].study,
      revisionNoteHtml: farContent["equity-and-earnings-per-share"].revision,
      mcqs: [
        {
          question: "A company has net income of $600,000 and paid $50,000 in dividends on cumulative preferred stock during the year, none of which were declared. What amount should be used as the numerator for basic EPS?",
          options: [
            { label: "A", text: "$600,000", isCorrect: false, rationale: "This ignores the required subtraction of the cumulative preferred dividend, whether or not it was declared." },
            { label: "B", text: "$550,000", isCorrect: true, rationale: "Correct — cumulative preferred dividends reduce the EPS numerator whether or not they are declared, since they accumulate as a claim on earnings." },
            { label: "C", text: "$650,000", isCorrect: false, rationale: "Preferred dividends are subtracted from net income for EPS purposes, not added." },
            { label: "D", text: "$600,000, because the dividend was never declared", isCorrect: false, rationale: "For cumulative preferred stock specifically, the dividend is subtracted for EPS purposes even if not declared — this is different from noncumulative preferred." },
          ],
          explanation: "For basic EPS, dividends on cumulative preferred stock are subtracted from net income whether or not they were declared during the period, because the right to those dividends accumulates. $600,000 − $50,000 = $550,000.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["EPS"],
        },
        {
          question: "A company has 10,000 stock options outstanding with an exercise price of $30. The average market price of the stock during the year was $25. How should these options be treated in the diluted EPS calculation?",
          options: [
            { label: "A", text: "Included, using the treasury stock method", isCorrect: false, rationale: "Since the exercise price ($30) exceeds the average market price ($25), the options are out of the money and anti-dilutive, so they should be excluded entirely." },
            { label: "B", text: "Excluded, because they are anti-dilutive", isCorrect: true, rationale: "Correct — when the exercise price exceeds the average market price, applying the treasury stock method would increase EPS (be anti-dilutive), so the options are excluded from diluted EPS." },
            { label: "C", text: "Included, using the if-converted method", isCorrect: false, rationale: "The if-converted method applies to convertible securities like bonds or preferred stock, not stock options." },
            { label: "D", text: "Included at their full face value in the denominator", isCorrect: false, rationale: "Options are never added to the denominator at full face value — only the net incremental shares under the treasury stock method, and only if dilutive." },
          ],
          explanation: "Options are anti-dilutive when their exercise price exceeds the average market price of the stock, because assumed exercise and repurchase under the treasury stock method would reduce (not increase) the share count relative to actual exercise — meaning EPS would rise, not fall. Anti-dilutive securities are excluded from the diluted EPS calculation entirely.",
          difficulty: "HARD",
          questionType: "EXCEPTION",
          tags: ["EPS", "dilution", "exam trap"],
        },
      ],
    },
    {
      slug: "income-taxes",
      title: "Income Taxes (Deferred Tax Accounting)",
      shortDescription: "Temporary differences, deferred tax assets/liabilities, and the valuation allowance.",
      blueprintArea: "Area III: Select Transactions",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 90,
      order: 15,
      studyMaterialHtml: farContent["income-taxes"].study,
      revisionNoteHtml: farContent["income-taxes"].revision,
      mcqs: [
        {
          question: "A company recognizes a warranty expense of $40,000 for book purposes in the current year, but the deduction is not allowed for tax purposes until the warranty claims are actually paid in future years. What is the tax effect of this temporary difference?",
          options: [
            { label: "A", text: "A deferred tax liability, since book expense exceeds tax deduction now", isCorrect: false, rationale: "This describes a situation that creates a deferred tax asset, not a liability — the company will get a tax deduction later that it doesn't get now." },
            { label: "B", text: "A deferred tax asset, since the tax deduction will be available in a future period", isCorrect: true, rationale: "Correct — the company recognizes the expense for books now but won't get the tax deduction until later, meaning it will pay more tax now and less tax later, creating a future tax benefit (a deferred tax asset)." },
            { label: "C", text: "A permanent difference with no deferred tax effect", isCorrect: false, rationale: "This difference will reverse when the warranty is paid and the tax deduction is taken, so it is temporary, not permanent." },
            { label: "D", text: "No tax effect, since only cash-basis differences are relevant for tax", isCorrect: false, rationale: "Book-tax differences in timing of expense recognition are exactly what deferred tax accounting addresses." },
          ],
          explanation: "When a book expense (like an estimated warranty expense) is recognized before it is deductible for tax purposes, the company pays more tax currently than book income would suggest, and expects a tax benefit in future periods when the expense becomes deductible. This creates a deferred tax asset.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["deferred taxes"],
        },
        {
          question: "A company has a $300,000 deferred tax asset related to a net operating loss carryforward. Based on a recent history of losses, management concludes it is more likely than not that only $100,000 of this asset will be realized. What should the company record?",
          options: [
            { label: "A", text: "No adjustment, since deferred tax assets are always recorded at full value", isCorrect: false, rationale: "Deferred tax assets must be reduced by a valuation allowance when realization is not more likely than not." },
            { label: "B", text: "A valuation allowance of $200,000, resulting in a net deferred tax asset of $100,000", isCorrect: true, rationale: "Correct — the valuation allowance reduces the gross deferred tax asset ($300,000) down to the amount expected to be realized ($100,000), a reduction of $200,000." },
            { label: "C", text: "A deferred tax liability of $200,000", isCorrect: false, rationale: "A valuation allowance reduces a deferred tax asset — it does not create a separate deferred tax liability." },
            { label: "D", text: "Write off the entire $300,000 deferred tax asset", isCorrect: false, rationale: "Only the portion not expected to be realized ($200,000) is offset by the valuation allowance; $100,000 remains as a net deferred tax asset." },
          ],
          explanation: "A valuation allowance is recorded against a deferred tax asset when it is more likely than not (a greater than 50% probability) that some or all of the asset will not be realized. Here, $300,000 − $100,000 realizable = $200,000 valuation allowance, leaving a net DTA of $100,000.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["deferred taxes", "valuation allowance"],
        },
        {
          question: "Which of the following is a permanent difference for income tax purposes, rather than a temporary difference?",
          options: [
            { label: "A", text: "Depreciation calculated using different methods for book and tax purposes", isCorrect: false, rationale: "This reverses over the asset's life (total depreciation is the same either way), making it a temporary difference." },
            { label: "B", text: "Interest income earned on municipal bonds, which is tax-exempt", isCorrect: true, rationale: "Correct — tax-exempt municipal bond interest is included in book income but never taxed, so it never reverses — a permanent difference." },
            { label: "C", text: "A warranty expense accrued for books but deductible for tax only when paid", isCorrect: false, rationale: "This difference reverses once the warranty is paid and the deduction is taken, making it temporary." },
            { label: "D", text: "Unearned rental income, taxable when received but recognized for books over the rental period", isCorrect: false, rationale: "This reverses as the rental period elapses and the revenue is earned for book purposes, making it temporary." },
          ],
          explanation: "Permanent differences never reverse — items like tax-exempt municipal bond interest, life insurance proceeds on key employees, and non-deductible fines/penalties are included in book income but permanently excluded from (or added to) taxable income, so they never create a deferred tax asset or liability.",
          difficulty: "EASY",
          questionType: "EXCEPTION",
          tags: ["deferred taxes", "permanent differences"],
        },
      ],
    },
    {
      slug: "accounting-changes-and-error-corrections",
      title: "Accounting Changes & Error Corrections",
      shortDescription: "Change in principle, estimate, and entity, plus prior-period error correction.",
      blueprintArea: "Area III: Select Transactions",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 16,
      studyMaterialHtml: farContent["accounting-changes-and-error-corrections"].study,
      revisionNoteHtml: farContent["accounting-changes-and-error-corrections"].revision,
    },
    {
      slug: "business-combinations-and-consolidations",
      title: "Business Combinations & Consolidations",
      shortDescription: "Acquisition method basics, goodwill calculation, and noncontrolling interest.",
      blueprintArea: "Area III: Select Transactions",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 90,
      order: 17,
      studyMaterialHtml: farContent["business-combinations-and-consolidations"].study,
      revisionNoteHtml: farContent["business-combinations-and-consolidations"].revision,
      mcqs: [
        {
          question: "Acquirer purchases 100% of Target for $1,200,000 cash. Target's identifiable assets have a fair value of $1,600,000 and liabilities assumed have a fair value of $500,000. What should Acquirer recognize?",
          options: [
            { label: "A", text: "Goodwill of $100,000", isCorrect: true, rationale: "Correct — net identifiable assets are $1,600,000 − $500,000 = $1,100,000. Consideration paid ($1,200,000) exceeds net identifiable assets ($1,100,000) by $100,000, which is recognized as goodwill." },
            { label: "B", text: "A bargain purchase gain of $100,000", isCorrect: false, rationale: "A bargain purchase gain arises only when net identifiable assets exceed consideration paid. Here consideration ($1,200,000) exceeds net identifiable assets ($1,100,000), so this is goodwill, not a bargain purchase." },
            { label: "C", text: "Goodwill of $500,000", isCorrect: false, rationale: "This appears to compare consideration to liabilities alone, not to net identifiable assets (assets minus liabilities)." },
            { label: "D", text: "No goodwill or gain, since assets equal liabilities plus consideration", isCorrect: false, rationale: "Assets ($1,600,000) do not equal liabilities plus consideration ($500,000 + $1,200,000 = $1,700,000) — there is a measurable $100,000 difference that must be recognized as goodwill." },
          ],
          explanation: "Net identifiable assets acquired = $1,600,000 (assets) − $500,000 (liabilities) = $1,100,000. Consideration paid = $1,200,000, which exceeds net identifiable assets of $1,100,000 by $100,000. Since consideration exceeds net assets acquired, this $100,000 excess is recognized as goodwill, not a bargain purchase gain (a bargain purchase would require net assets to exceed consideration).",
          difficulty: "HARD",
          questionType: "CALCULATION",
          tags: ["business combinations", "goodwill"],
        },
        {
          question: "In a business combination, how should the acquirer treat legal and advisory fees directly related to completing the acquisition?",
          options: [
            { label: "A", text: "Capitalize them as part of the fair value of consideration transferred", isCorrect: false, rationale: "Acquisition-related costs are explicitly excluded from consideration transferred under the acquisition method." },
            { label: "B", text: "Expense them as incurred", isCorrect: true, rationale: "Correct — acquisition-related costs such as legal and advisory fees are expensed in the periods incurred, separate from the business combination accounting itself." },
            { label: "C", text: "Include them in the calculation of goodwill", isCorrect: false, rationale: "These costs are not part of the fair value measurement used to calculate goodwill." },
            { label: "D", text: "Capitalize and amortize them over the expected life of the acquired business", isCorrect: false, rationale: "There is no such amortization treatment for acquisition-related transaction costs under US GAAP." },
          ],
          explanation: "Under ASC 805, acquisition-related costs (legal, accounting, valuation, advisory fees) are expensed as incurred and are not included in the consideration transferred or in the measurement of goodwill.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["business combinations"],
        },
      ],
    },
    {
      slug: "not-for-profit-accounting",
      title: "Not-for-Profit Accounting",
      shortDescription: "Net asset classification and contribution recognition for nonprofit entities.",
      blueprintArea: "Area I: Financial Reporting",
      blueprintStatus: "PROVISIONAL",
      difficulty: "MEDIUM",
      estimatedMinutes: 60,
      order: 18,
      studyMaterialHtml: farContent["not-for-profit-accounting"].study,
      revisionNoteHtml: farContent["not-for-profit-accounting"].revision,
    },
    {
      slug: "governmental-accounting",
      title: "Governmental Accounting",
      shortDescription: "Fund accounting basics and the modified accrual basis used by governmental funds.",
      blueprintArea: "Area I: Financial Reporting",
      blueprintStatus: "PROVISIONAL",
      difficulty: "HARD",
      estimatedMinutes: 75,
      order: 19,
      studyMaterialHtml: farContent["governmental-accounting"].study,
      revisionNoteHtml: farContent["governmental-accounting"].revision,
    },
    {
      slug: "sec-reporting-segments-and-interim-reporting",
      title: "Public Company Reporting, Segments & Interim Reporting",
      shortDescription: "Securities and Exchange Commission (SEC) forms and deadlines, reportable segment tests, and the integral view of interim reporting.",
      blueprintArea: "Area I: Financial Reporting",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 20,
      studyMaterialHtml: farContent["sec-reporting-segments-and-interim-reporting"].study,
      revisionNoteHtml: farContent["sec-reporting-segments-and-interim-reporting"].revision,
    },
  ],
};
