import type { SubjectSeed } from "./types";
import { iscContent } from "./content/isc";

export const isc: SubjectSeed = {
  slug: "isc",
  name: "Information Systems and Controls",
  shortName: "ISC",
  type: "DISCIPLINE",
  description:
    "Information Systems and Controls (ISC) sits where auditing meets information technology (IT): Information Systems and Data Management (35–45%), Security, Confidentiality and Privacy (35–45%), and System and Organization Controls (SOC) engagements (15–25%). It fits candidates interested in IT audit, risk, and controls, and rewards process thinking over calculation.",
  difficulty: "MEDIUM",
  estimatedHours: 80,
  blueprintUrl: "https://www.aicpa-cima.com/resources/download/isc-cpa-exam-blueprint",
  order: 5,
  topics: [
    {
      slug: "it-general-controls",
      title: "Information Technology General Controls (ITGCs)",
      shortDescription: "The four domains of information technology general controls (ITGCs) and how they support reliance on automated controls.",
      blueprintArea: "Area I: Information Systems and Data Management",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 1,
      studyMaterialHtml: iscContent["it-general-controls"].study,
      revisionNoteHtml: iscContent["it-general-controls"].revision,
      mcqs: [
        {
          question: "A developer at a company has standing write access to the production database. Which ITGC category does this deficiency primarily relate to, and why does it matter?",
          options: [
            { label: "A", text: "IT operations — it may disrupt job scheduling", isCorrect: false, rationale: "The core issue is inappropriate access and the ability to bypass change controls, not operational scheduling." },
            { label: "B", text: "Access to programs and data — it breaks segregation of duties and allows unauthorized changes to financial data", isCorrect: true, rationale: "Correct — developers should not have production access; this combines development and operations duties and permits undetected data or code changes." },
            { label: "C", text: "Program development — it affects how new systems are designed", isCorrect: false, rationale: "The deficiency is about access to the live environment, not the design methodology for new systems." },
            { label: "D", text: "It is not a deficiency if the developer is trusted and experienced", isCorrect: false, rationale: "Controls are designed independent of individual trustworthiness; the structural conflict remains." },
          ],
          explanation: "Standing developer access to production is fundamentally an access control deficiency that also breaks IT segregation of duties. It allows a single individual to both write code and alter live financial data, bypassing change management approvals — which undermines reliance on every automated control in that system.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["ITGC", "access controls"],
        },
      ],
    },
    {
      slug: "information-systems-fundamentals",
      title: "Information Systems Fundamentals",
      shortDescription: "Enterprise resource planning (ERP) and other systems, processing methods, cloud service models, networks, and business continuity.",
      blueprintArea: "Area I: Information Systems and Data Management",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 2,
      studyMaterialHtml: iscContent["information-systems-fundamentals"].study,
      revisionNoteHtml: iscContent["information-systems-fundamentals"].revision,
      mcqs: [
        {
          question: "A company migrates its accounting system to a SaaS provider. Which responsibility remains with the company?",
          options: [
            { label: "A", text: "Patching the underlying operating system", isCorrect: false, rationale: "In SaaS the provider manages the infrastructure and operating system." },
            { label: "B", text: "Provisioning and reviewing user access rights within the application", isCorrect: true, rationale: "Correct — under the shared responsibility model, the customer always retains responsibility for its data and for granting, reviewing, and revoking user access." },
            { label: "C", text: "Maintaining the physical data center", isCorrect: false, rationale: "Physical infrastructure is the provider's responsibility in all cloud models." },
            { label: "D", text: "Managing the application server middleware", isCorrect: false, rationale: "Middleware is managed by the provider in a SaaS arrangement." },
          ],
          explanation: "Cloud computing operates on a shared responsibility model. As you move from IaaS to PaaS to SaaS, the provider assumes more of the technology stack — but the customer always remains responsible for its own data, the configuration of user access, and oversight of the vendor.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["cloud", "shared responsibility"],
        },
      ],
    },
    {
      slug: "data-management-and-governance",
      title: "Data Management & Governance",
      shortDescription: "The data life cycle, data quality dimensions, and governance roles and frameworks.",
      blueprintArea: "Area I: Information Systems and Data Management",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 3,
      studyMaterialHtml: iscContent["data-management-and-governance"].study,
      revisionNoteHtml: iscContent["data-management-and-governance"].revision,
      mcqs: [
        {
          question: "Who is normally accountable for approving which users may access a particular set of financial data?",
          options: [
            { label: "A", text: "The data custodian in the IT department", isCorrect: false, rationale: "The custodian implements and safeguards access technically but should not decide who is entitled to it." },
            { label: "B", text: "The business data owner", isCorrect: true, rationale: "Correct — the data owner is the accountable business leader who approves access rights and data classification." },
            { label: "C", text: "The data user requesting access", isCorrect: false, rationale: "Self-approval would defeat the purpose of access controls." },
            { label: "D", text: "The external auditor", isCorrect: false, rationale: "Auditors evaluate controls; they do not administer access rights." },
          ],
          explanation: "Data governance separates accountability from custody. The business data owner decides who should have access and how data is classified; the IT data custodian implements and protects that access. Letting IT make access decisions is a governance weakness.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["data governance"],
        },
      ],
    },
    {
      slug: "security-fundamentals",
      title: "Information Security Fundamentals",
      shortDescription: "Confidentiality, integrity, and availability (CIA), threats, access management, encryption, network defenses, and cybersecurity frameworks.",
      blueprintArea: "Area II: Security, Confidentiality and Privacy",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 60,
      order: 4,
      studyMaterialHtml: iscContent["security-fundamentals"].study,
      revisionNoteHtml: iscContent["security-fundamentals"].revision,
      mcqs: [
        {
          question: "To send a confidential message that only the intended recipient can read, which key should the sender use to encrypt it?",
          options: [
            { label: "A", text: "The sender's private key", isCorrect: false, rationale: "Encrypting with the sender's private key creates a digital signature — anyone with the public key could decrypt it, so it provides authenticity, not confidentiality." },
            { label: "B", text: "The recipient's public key", isCorrect: true, rationale: "Correct — only the recipient holds the matching private key, so only they can decrypt the message." },
            { label: "C", text: "The recipient's private key", isCorrect: false, rationale: "The sender does not have access to the recipient's private key." },
            { label: "D", text: "The sender's public key", isCorrect: false, rationale: "The sender's own public key would require the sender's private key to decrypt, which the recipient does not have." },
          ],
          explanation: "In public key cryptography, confidentiality is achieved by encrypting with the recipient's public key, since only the recipient's private key can decrypt it. Signing with the sender's private key achieves authenticity and non-repudiation instead.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["encryption", "PKI"],
        },
        {
          question: "A system requires users to enter a password and then answer a personal security question. Does this constitute multi-factor authentication?",
          options: [
            { label: "A", text: "Yes, because two separate credentials are required", isCorrect: false, rationale: "MFA requires factors from different categories, not merely two credentials." },
            { label: "B", text: "No, because both are 'something you know'", isCorrect: true, rationale: "Correct — a password and a security question are both knowledge factors, so this is single-factor authentication applied twice." },
            { label: "C", text: "Yes, because security questions are a possession factor", isCorrect: false, rationale: "A security question tests knowledge, not possession." },
            { label: "D", text: "Only if the security question changes each login", isCorrect: false, rationale: "Rotating knowledge-based questions does not convert them into a different authentication factor." },
          ],
          explanation: "Multi-factor authentication requires credentials from at least two different categories: something you know, something you have, or something you are. A password and a security question are both knowledge factors, so combining them does not achieve MFA.",
          difficulty: "EASY",
          questionType: "EXAM_TRAP",
          tags: ["authentication", "MFA"],
        },
      ],
    },
    {
      slug: "privacy-frameworks",
      title: "Privacy & Regulatory Frameworks",
      shortDescription: "Privacy principles, major privacy and data protection laws, and techniques such as anonymization and tokenization.",
      blueprintArea: "Area II: Security, Confidentiality and Privacy",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 5,
      studyMaterialHtml: iscContent["privacy-frameworks"].study,
      revisionNoteHtml: iscContent["privacy-frameworks"].revision,
      mcqs: [
        {
          question: "Which framework is specifically designed for the governance and management of enterprise IT?",
          options: [
            { label: "A", text: "COSO Internal Control — Integrated Framework", isCorrect: false, rationale: "COSO addresses internal control broadly across an organization, not IT governance specifically." },
            { label: "B", text: "COBIT", isCorrect: true, rationale: "Correct — COBIT is the framework focused on the governance and management of enterprise information and technology." },
            { label: "C", text: "ISO 9001", isCorrect: false, rationale: "ISO 9001 addresses quality management systems, not IT governance." },
            { label: "D", text: "PCI DSS", isCorrect: false, rationale: "PCI DSS is a contractual security standard for payment card data, not a governance framework." },
          ],
          explanation: "COBIT provides a framework for the governance and management of enterprise IT, linking IT objectives to business goals. COSO addresses internal control generally, NIST CSF addresses cybersecurity risk, and ISO 27001 provides a certifiable information security management system.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["frameworks", "COBIT"],
        },
      ],
    },
    {
      slug: "incident-response",
      title: "Incident Response & Monitoring",
      shortDescription: "The incident response life cycle, logging and monitoring, and breach notification obligations.",
      blueprintArea: "Area II: Security, Confidentiality and Privacy",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 6,
      studyMaterialHtml: iscContent["incident-response"].study,
      revisionNoteHtml: iscContent["incident-response"].revision,
      mcqs: [
        {
          question: "A company can tolerate losing at most 15 minutes of transaction data in a disaster. Which metric does this define, and what does it drive?",
          options: [
            { label: "A", text: "Recovery time objective — it drives how fast systems must be restored", isCorrect: false, rationale: "RTO concerns downtime duration, not the amount of data loss." },
            { label: "B", text: "Recovery point objective — it drives backup and replication frequency", isCorrect: true, rationale: "Correct — RPO defines the maximum tolerable data loss, which determines how frequently data must be backed up or replicated." },
            { label: "C", text: "Mean time between failures — it drives hardware selection", isCorrect: false, rationale: "MTBF is a reliability measure, not a recovery objective." },
            { label: "D", text: "Maximum tolerable downtime — it drives site selection", isCorrect: false, rationale: "That relates to how long the business can be down, which is the RTO concept, not data loss." },
          ],
          explanation: "The recovery point objective specifies the maximum acceptable amount of data loss measured in time. A 15-minute RPO requires backups or replication at least every 15 minutes. The recovery time objective, by contrast, defines how quickly systems must be restored to operation.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["BCP", "RPO", "RTO"],
        },
      ],
    },
    {
      slug: "business-process-automation",
      title: "Business Processes & Automation",
      shortDescription: "Key transaction cycles, robotic process automation, and controls over automated processes.",
      blueprintArea: "Area I: Information Systems and Data Management",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 7,
      studyMaterialHtml: iscContent["business-process-automation"].study,
      revisionNoteHtml: iscContent["business-process-automation"].revision,
      mcqs: [
        {
          question: "Which segregation of duties weakness most directly enables a fictitious vendor fraud?",
          options: [
            { label: "A", text: "The same person prepares and reviews bank reconciliations", isCorrect: false, rationale: "This is a real weakness but relates more to concealing cash misappropriation than to creating fictitious vendors." },
            { label: "B", text: "The same person can add vendors to the master file and approve payments", isCorrect: true, rationale: "Correct — combining vendor creation with payment authority allows an individual to set up a fake vendor and pay it without independent challenge." },
            { label: "C", text: "The receiving department also counts physical inventory", isCorrect: false, rationale: "This affects inventory accuracy, not vendor payment fraud." },
            { label: "D", text: "The IT department maintains the general ledger software", isCorrect: false, rationale: "Application maintenance is normal for IT; the issue would be production data access, not vendor fraud specifically." },
          ],
          explanation: "Creating a fictitious vendor and then authorizing payments to it requires control over both the vendor master file and the payment process. Segregating vendor master file maintenance from payment approval and disbursement is the key preventive control.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["business processes", "segregation of duties"],
        },
      ],
    },
    {
      slug: "systems-development-life-cycle",
      title: "Systems Development & Change Management",
      shortDescription: "System development life cycle (SDLC) phases, conversion methods, agile and DevOps, and change management controls.",
      blueprintArea: "Area I: Information Systems and Data Management",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 8,
      studyMaterialHtml: iscContent["systems-development-life-cycle"].study,
      revisionNoteHtml: iscContent["systems-development-life-cycle"].revision,
      mcqs: [
        {
          question: "Which system conversion approach carries the highest risk?",
          options: [
            { label: "A", text: "Parallel conversion", isCorrect: false, rationale: "Running both systems simultaneously provides a fallback and is the lowest-risk approach." },
            { label: "B", text: "Direct cutover", isCorrect: true, rationale: "Correct — switching entirely to the new system at once provides no fallback if the new system fails, making it the highest-risk approach." },
            { label: "C", text: "Pilot conversion", isCorrect: false, rationale: "Piloting limits exposure to a single location or unit, containing risk." },
            { label: "D", text: "Phased conversion", isCorrect: false, rationale: "Phasing spreads risk across stages rather than concentrating it." },
          ],
          explanation: "Direct cutover (\"big bang\") replaces the old system entirely at a single point in time. It is the cheapest and fastest approach but offers no fallback if problems emerge. Parallel conversion, which runs both systems simultaneously, is the lowest risk but the most expensive.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["SDLC", "conversion"],
        },
      ],
    },
    {
      slug: "third-party-and-vendor-risk",
      title: "Third-Party & Vendor Risk",
      shortDescription: "Evaluating service providers, contractual protections, and ongoing vendor monitoring.",
      blueprintArea: "Area III: SOC Engagements",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 45,
      order: 9,
      studyMaterialHtml: iscContent["third-party-and-vendor-risk"].study,
      revisionNoteHtml: iscContent["third-party-and-vendor-risk"].revision,
      mcqs: [
        {
          question: "A service organization's SOC 1 report uses the carve-out method for a subservice organization. What does this mean for the user entity?",
          options: [
            { label: "A", text: "The subservice organization's controls are included and tested in the report", isCorrect: false, rationale: "That describes the inclusive method, not carve-out." },
            { label: "B", text: "The subservice organization's controls are excluded, so the user entity needs separate assurance over them", isCorrect: true, rationale: "Correct — under the carve-out method the subservice organization's controls are described but not tested, leaving a gap the user entity must address separately." },
            { label: "C", text: "The user entity may disregard the subservice organization entirely", isCorrect: false, rationale: "The user entity still depends on those controls and must consider the residual risk." },
            { label: "D", text: "The service auditor has issued a modified opinion", isCorrect: false, rationale: "Carve-out is a scoping method, not an indication of a modified opinion." },
          ],
          explanation: "Under the carve-out method, the service organization's description includes the subservice organization's services but excludes its controls from the description and from the service auditor's testing. The user entity must obtain separate assurance over those controls or accept the resulting residual risk.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["vendor risk", "SOC", "carve-out"],
        },
      ],
    },
    {
      slug: "soc-engagements",
      title: "System and Organization Controls (SOC) Engagements",
      shortDescription: "System and Organization Controls (SOC) 1, 2, and 3 reports, Type 1 versus Type 2, the Trust Services Criteria, and modified opinions.",
      blueprintArea: "Area III: SOC Engagements",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 10,
      studyMaterialHtml: iscContent["soc-engagements"].study,
      revisionNoteHtml: iscContent["soc-engagements"].revision,
      mcqs: [
        {
          question: "A prospective customer asks a SaaS provider for a report on its security controls that the provider can publish openly on its website. Which report is appropriate?",
          options: [
            { label: "A", text: "SOC 1 Type 2", isCorrect: false, rationale: "SOC 1 addresses financial reporting controls and is restricted-use." },
            { label: "B", text: "SOC 2 Type 2", isCorrect: false, rationale: "SOC 2 addresses the right subject matter but is a restricted-use report, not for open publication." },
            { label: "C", text: "SOC 3", isCorrect: true, rationale: "Correct — SOC 3 covers the same Trust Services Criteria as SOC 2 but in summarized form and is a general-use report suitable for public distribution." },
            { label: "D", text: "SOC 1 Type 1", isCorrect: false, rationale: "Wrong subject matter and restricted use." },
          ],
          explanation: "SOC 2 reports address the Trust Services Criteria but are restricted-use documents shared under NDA with specific parties. SOC 3 covers the same criteria in summary form and is designed for general use, making it appropriate for public posting.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["SOC", "SOC 3"],
        },
        {
          question: "Which Trust Services Criterion must be included in every SOC 2 engagement?",
          options: [
            { label: "A", text: "Privacy", isCorrect: false, rationale: "Privacy is included only when relevant to the engagement scope." },
            { label: "B", text: "Security", isCorrect: true, rationale: "Correct — the security criteria (the common criteria) are mandatory in every SOC 2; the other four are optional based on scope." },
            { label: "C", text: "Availability", isCorrect: false, rationale: "Availability is optional and included only if relevant." },
            { label: "D", text: "Processing integrity", isCorrect: false, rationale: "Processing integrity is optional and included only if relevant." },
          ],
          explanation: "The five Trust Services Criteria are security, availability, processing integrity, confidentiality, and privacy. Security — the common criteria — must be included in every SOC 2 engagement; the remaining four are added based on the scope agreed with the service organization.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["SOC", "trust services criteria"],
        },
      ],
    },
    {
      slug: "it-audit-and-advisory",
      title: "Information Technology (IT) Audit & Advisory Services",
      shortDescription: "Types of information technology (IT) engagements, auditing through and with the computer, validating system reports, and independence limits.",
      blueprintArea: "Area III: SOC Engagements",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 11,
      studyMaterialHtml: iscContent["it-audit-and-advisory"].study,
      revisionNoteHtml: iscContent["it-audit-and-advisory"].revision,
      mcqs: [
        {
          question: "An auditor plans to rely on an exception report generated by the client's ERP system. What must the auditor do before using it as audit evidence?",
          options: [
            { label: "A", text: "Nothing further, because the report comes directly from the system", isCorrect: false, rationale: "System-generated does not mean reliable — the report parameters or underlying data may be wrong." },
            { label: "B", text: "Test the completeness and accuracy of the report, including its logic and parameters", isCorrect: true, rationale: "Correct — information produced by the entity must be validated for completeness and accuracy before the auditor can rely on it." },
            { label: "C", text: "Obtain a management representation that the report is accurate", isCorrect: false, rationale: "A representation is not a substitute for testing the report itself." },
            { label: "D", text: "Use the report only if ITGCs were found to be ineffective", isCorrect: false, rationale: "This reverses the logic — effective ITGCs support, rather than preclude, reliance on system reports." },
          ],
          explanation: "Information produced by the entity — including system-generated reports used in controls or audit procedures — must be tested for completeness and accuracy. This typically involves validating the report's logic and parameters and agreeing key data back to the source system.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["IT audit", "IPE"],
        },
      ],
    },
    {
      slug: "emerging-technology-considerations",
      title: "Emerging Technology Considerations",
      shortDescription: "Artificial intelligence (AI), blockchain and crypto assets, and the Internet of Things (IoT) — the risks they create and the controls that follow.",
      blueprintArea: "Area I: Information Systems and Data Management",
      blueprintStatus: "PROVISIONAL",
      difficulty: "MEDIUM",
      estimatedMinutes: 45,
      order: 12,
      studyMaterialHtml: iscContent["emerging-technology-considerations"].study,
      revisionNoteHtml: iscContent["emerging-technology-considerations"].revision,
      mcqs: [
        {
          question: "What does recording a transaction on a blockchain reliably demonstrate?",
          options: [
            { label: "A", text: "That the transaction was properly authorized by management", isCorrect: false, rationale: "Blockchain does not validate whether the underlying transaction had proper business authorization." },
            { label: "B", text: "That the recorded transaction has not been altered since it was written", isCorrect: true, rationale: "Correct — the immutable, append-only structure provides strong assurance over the integrity of what was recorded." },
            { label: "C", text: "That the goods or services underlying the transaction actually exist", isCorrect: false, rationale: "Blockchain records data; it cannot verify physical existence in the real world." },
            { label: "D", text: "That the transaction is recorded at the correct fair value", isCorrect: false, rationale: "Valuation still requires traditional audit evidence and judgment." },
          ],
          explanation: "A blockchain provides strong assurance that data written to the ledger has not been subsequently altered. It does not address whether the transaction was authorized, correctly valued, or whether the underlying goods exist — those assertions still require conventional audit evidence.",
          difficulty: "MEDIUM",
          questionType: "EXAM_TRAP",
          tags: ["blockchain", "emerging technology"],
        },
      ],
    },
  ],
};
