import type { SubjectSeed } from "./types";
import { regContent } from "./content/reg";

export const reg: SubjectSeed = {
  slug: "reg",
  name: "Taxation and Regulation",
  shortName: "REG",
  type: "CORE",
  description:
    "Taxation and Regulation (REG) covers Ethics, Professional Responsibilities and Federal Tax Procedures (10–20%), Business Law (15–25%), Federal Taxation of Property Transactions (5–15%), Individuals (22–32%), and Entities (23–33%). Tax law changes from the One Big Beautiful Bill Act (OBBBA) have been testable since July 1, 2026. It rewards applying rules to numbers, not just reciting them.",
  difficulty: "HARD",
  estimatedHours: 130,
  blueprintUrl: "https://www.aicpa-cima.com/resources/download/reg-cpa-exam-blueprint",
  order: 3,
  topics: [
    {
      slug: "circular-230-and-practitioner-ethics",
      title: "Circular 230 & Practitioner Ethics",
      shortDescription: "Internal Revenue Service (IRS) rules for practitioners under Circular 230, professional tax standards, fees, and conflicts of interest.",
      blueprintArea: "Area I: Ethics, Professional Responsibilities & Federal Tax Procedures",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 1,
      studyMaterialHtml: regContent["circular-230-and-practitioner-ethics"].study,
      revisionNoteHtml: regContent["circular-230-and-practitioner-ethics"].revision,
      mcqs: [
        {
          question: "A CPA discovers that a client's previously filed return contains a material error. Under Circular 230, what must the CPA do?",
          options: [
            { label: "A", text: "Notify the IRS of the error immediately", isCorrect: false, rationale: "The practitioner may not disclose the error to the IRS without the client's consent — doing so would breach confidentiality." },
            { label: "B", text: "Advise the client of the error and the consequences of not correcting it", isCorrect: true, rationale: "Correct — Circular 230 requires the practitioner to promptly inform the client of the error or omission and the consequences under the Code and regulations." },
            { label: "C", text: "File an amended return on the client's behalf without discussing it", isCorrect: false, rationale: "The practitioner cannot unilaterally file an amended return; the decision belongs to the client." },
            { label: "D", text: "Immediately withdraw from the engagement", isCorrect: false, rationale: "Withdrawal may be considered if the client refuses to act, but the immediate required step is notifying the client." },
          ],
          explanation: "Circular 230 requires a practitioner who discovers a client's error or omission to advise the client promptly of the error and the consequences. The practitioner cannot notify the IRS without client consent, and cannot correct the return unilaterally.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["Circular 230", "ethics"],
        },
        {
          question: "Which contingent fee arrangement is PERMITTED under Circular 230?",
          options: [
            { label: "A", text: "A fee based on a percentage of the refund shown on an original tax return", isCorrect: false, rationale: "Contingent fees for preparing original returns are prohibited." },
            { label: "B", text: "A fee contingent on the outcome of an IRS examination of an already-filed return", isCorrect: true, rationale: "Correct — contingent fees are permitted for services in connection with an IRS examination or challenge to an original return, among other specified circumstances." },
            { label: "C", text: "A fee based on the tax savings achieved on a first-time return filing", isCorrect: false, rationale: "This is a contingent fee tied to an original return, which is prohibited." },
            { label: "D", text: "An unconscionable fee if disclosed to the client in writing", isCorrect: false, rationale: "Unconscionable fees are prohibited regardless of disclosure or consent." },
          ],
          explanation: "Circular 230 generally prohibits contingent fees for preparing original returns, but permits them for services rendered in connection with an IRS examination or challenge, a claim for refund filed within 120 days of a written notice of examination, a claim for credit or refund of interest and penalties, and judicial proceedings.",
          difficulty: "MEDIUM",
          questionType: "EXCEPTION",
          tags: ["Circular 230", "fees"],
        },
      ],
    },
    {
      slug: "irs-procedures-and-appeals",
      title: "Internal Revenue Service (IRS) Procedures & Appeals",
      shortDescription: "Audits, the appeals process, statutes of limitation, and where tax disputes get litigated.",
      blueprintArea: "Area I: Ethics, Professional Responsibilities & Federal Tax Procedures",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 2,
      studyMaterialHtml: regContent["irs-procedures-and-appeals"].study,
      revisionNoteHtml: regContent["irs-procedures-and-appeals"].revision,
      mcqs: [
        {
          question: "A taxpayer wishes to dispute a proposed deficiency without first paying the disputed amount. Which court must the taxpayer use?",
          options: [
            { label: "A", text: "U.S. District Court", isCorrect: false, rationale: "The District Court requires the taxpayer to pay the tax first and then sue for a refund." },
            { label: "B", text: "U.S. Tax Court", isCorrect: true, rationale: "Correct — the Tax Court is the only forum in which a taxpayer can litigate a deficiency before paying it." },
            { label: "C", text: "U.S. Court of Federal Claims", isCorrect: false, rationale: "This court also requires full payment before filing a refund suit." },
            { label: "D", text: "U.S. Court of Appeals", isCorrect: false, rationale: "The Court of Appeals hears appeals; it is not a trial-level forum for initiating a tax dispute." },
          ],
          explanation: "The U.S. Tax Court is the only trial forum where a taxpayer may litigate a deficiency without prepaying the tax. Both the U.S. District Court and the U.S. Court of Federal Claims require payment first, followed by a suit for refund — and only the District Court offers a jury trial.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["IRS procedures", "litigation"],
        },
        {
          question: "A taxpayer filed a return omitting gross income equal to 30% of the gross income reported. How long does the IRS have to assess additional tax?",
          options: [
            { label: "A", text: "Three years from the later of the due date or filing date", isCorrect: false, rationale: "The three-year period applies to the general rule, not where more than 25% of gross income is omitted." },
            { label: "B", text: "Six years from the later of the due date or filing date", isCorrect: true, rationale: "Correct — an omission of more than 25% of gross income extends the assessment statute of limitations to six years." },
            { label: "C", text: "The statute is unlimited", isCorrect: false, rationale: "An unlimited period applies to fraudulent returns or where no return was filed, not to a simple substantial omission." },
            { label: "D", text: "Two years from the date the tax was paid", isCorrect: false, rationale: "This relates to the taxpayer's refund claim window, not the IRS assessment period." },
          ],
          explanation: "The general assessment statute of limitations is three years, but it extends to six years when the taxpayer omits gross income exceeding 25% of the gross income stated on the return. Fraud or failure to file leaves the statute open indefinitely.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["statute of limitations"],
        },
      ],
    },
    {
      slug: "business-law-contracts",
      title: "Business Law: Contracts",
      shortDescription: "Formation, the statute of frauds, Uniform Commercial Code (UCC) versus common law, performance, breach, and remedies.",
      blueprintArea: "Area II: Business Law",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 60,
      order: 3,
      studyMaterialHtml: regContent["business-law-contracts"].study,
      revisionNoteHtml: regContent["business-law-contracts"].revision,
      mcqs: [
        {
          question: "On June 1, a merchant seller mails an offer to sell goods. On June 3, the seller mails a revocation. On June 4, the buyer mails an acceptance. On June 5, the buyer receives the revocation. Is there a contract?",
          options: [
            { label: "A", text: "No, because the revocation was mailed before the acceptance", isCorrect: false, rationale: "Revocations are effective on receipt, not dispatch, so the June 3 mailing did not terminate the offer before acceptance." },
            { label: "B", text: "Yes, because the acceptance was effective when mailed on June 4, before the revocation was received", isCorrect: true, rationale: "Correct — under the mailbox rule, acceptance is effective on dispatch while revocation is effective only on receipt, so a contract formed on June 4." },
            { label: "C", text: "No, because the buyer received the revocation before performance began", isCorrect: false, rationale: "The contract was already formed when the acceptance was dispatched; later receipt of the revocation is irrelevant." },
            { label: "D", text: "Yes, but only if the buyer is also a merchant", isCorrect: false, rationale: "The mailbox rule applies regardless of merchant status." },
          ],
          explanation: "Under the mailbox rule, an acceptance is effective when dispatched, while revocations, rejections, and counteroffers are effective only when received. Because the acceptance was mailed on June 4 and the revocation was not received until June 5, a binding contract was formed.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["contracts", "mailbox rule"],
        },
        {
          question: "A buyer and seller of goods orally agree to increase the contract price from $10,000 to $11,000 because of a supplier cost increase. No new consideration is exchanged. Under the UCC, is the modification enforceable?",
          options: [
            { label: "A", text: "No, because a contract modification always requires new consideration", isCorrect: false, rationale: "That is the common law rule; the UCC eliminates the consideration requirement for modifications." },
            { label: "B", text: "Yes, if the modification was made in good faith — although a written record is needed since the contract price exceeds $500", isCorrect: true, rationale: "Correct — UCC §2-209 allows modification without new consideration if made in good faith, but the modified contract must satisfy the Statute of Frauds for goods of $500 or more." },
            { label: "C", text: "No, because oral modifications of written contracts are never enforceable", isCorrect: false, rationale: "Oral modifications can be enforceable unless the Statute of Frauds or a no-oral-modification clause applies." },
            { label: "D", text: "Yes, and no writing is required regardless of amount", isCorrect: false, rationale: "The modified contract must still satisfy the Statute of Frauds, which applies to goods of $500 or more." },
          ],
          explanation: "Under UCC §2-209 a modification of a contract for the sale of goods needs no new consideration, provided it is sought in good faith. However, the contract as modified must still satisfy the Statute of Frauds — meaning a written record is required where the price is $500 or more.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["contracts", "UCC"],
        },
      ],
    },
    {
      slug: "business-law-agency-and-business-structures",
      title: "Business Law: Agency & Business Structures",
      shortDescription: "Agency authority and liability, plus the legal features of partnerships, limited liability companies (LLCs), and corporations.",
      blueprintArea: "Area II: Business Law",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 4,
      studyMaterialHtml: regContent["business-law-agency-and-business-structures"].study,
      revisionNoteHtml: regContent["business-law-agency-and-business-structures"].revision,
      mcqs: [
        {
          question: "A principal fires an agent but does not notify a long-standing supplier who had regularly dealt with that agent. The former agent places an order with the supplier in the principal's name. Who is liable to the supplier?",
          options: [
            { label: "A", text: "No one, because the agent's actual authority terminated upon firing", isCorrect: false, rationale: "Termination of actual authority does not automatically end apparent authority as to third parties who lack notice." },
            { label: "B", text: "The principal, because apparent authority continued until the supplier received notice", isCorrect: true, rationale: "Correct — apparent authority persists with respect to third parties who previously dealt with the agent until they receive appropriate notice of termination." },
            { label: "C", text: "The supplier, for failing to verify the agent's status", isCorrect: false, rationale: "The third party is entitled to rely on the appearance of authority the principal created." },
            { label: "D", text: "Only the former agent, in all circumstances", isCorrect: false, rationale: "The principal is bound where apparent authority existed; the agent may then be liable to the principal." },
          ],
          explanation: "Apparent authority arises from the principal's manifestations to third parties. When actual authority is terminated, the principal must give actual notice to third parties who previously dealt with the agent; otherwise apparent authority persists and the principal remains bound.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["agency", "apparent authority"],
        },
      ],
    },
    {
      slug: "debtor-creditor-and-bankruptcy",
      title: "Debtor-Creditor & Bankruptcy",
      shortDescription: "Secured transactions, perfection and priority, suretyship, and the bankruptcy claim hierarchy.",
      blueprintArea: "Area II: Business Law",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 60,
      order: 5,
      studyMaterialHtml: regContent["debtor-creditor-and-bankruptcy"].study,
      revisionNoteHtml: regContent["debtor-creditor-and-bankruptcy"].revision,
      mcqs: [
        {
          question: "A creditor takes a purchase money security interest in equipment and files a financing statement 15 days after the debtor receives possession. An earlier creditor had already perfected a security interest covering all of the debtor's equipment. Who has priority in the new equipment?",
          options: [
            { label: "A", text: "The earlier perfected creditor, because it filed first", isCorrect: false, rationale: "A properly perfected PMSI in non-inventory collateral takes priority over an earlier-filed general security interest." },
            { label: "B", text: "The PMSI creditor, because it perfected within 20 days of the debtor receiving possession", isCorrect: true, rationale: "Correct — a PMSI in non-inventory collateral has priority over a conflicting earlier-perfected interest if it is perfected within 20 days after the debtor takes possession." },
            { label: "C", text: "The two creditors share pro rata", isCorrect: false, rationale: "UCC priority rules produce a ranking, not pro rata sharing." },
            { label: "D", text: "Neither, because the PMSI attached after the general security interest", isCorrect: false, rationale: "Timing of attachment does not defeat the PMSI superpriority rule." },
          ],
          explanation: "A purchase money security interest in non-inventory collateral such as equipment obtains priority over a conflicting earlier-perfected security interest if it is perfected before or within 20 days after the debtor receives possession of the collateral. (For inventory, the PMSI must be perfected before delivery and prior notice given to existing secured parties.)",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["secured transactions", "PMSI"],
        },
      ],
    },
    {
      slug: "federal-tax-procedures-and-penalties",
      title: "Federal Tax Procedures & Penalties",
      shortDescription: "Filing requirements, estimated tax safe harbors, and preparer penalties under the Internal Revenue Code.",
      blueprintArea: "Area I: Ethics, Professional Responsibilities & Federal Tax Procedures",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 6,
      studyMaterialHtml: regContent["federal-tax-procedures-and-penalties"].study,
      revisionNoteHtml: regContent["federal-tax-procedures-and-penalties"].revision,
      mcqs: [
        {
          question: "A taxpayer's prior-year AGI was $250,000 with a tax liability of $50,000. To avoid an underpayment penalty for the current year using the prior-year safe harbor, how much must the taxpayer pay in through withholding and estimates?",
          options: [
            { label: "A", text: "$45,000 (90% of prior-year tax)", isCorrect: false, rationale: "The 90% test applies to the current year's tax, not the prior year's." },
            { label: "B", text: "$50,000 (100% of prior-year tax)", isCorrect: false, rationale: "The 100% figure applies only when prior-year AGI is $150,000 or less." },
            { label: "C", text: "$55,000 (110% of prior-year tax)", isCorrect: true, rationale: "Correct — because prior-year AGI exceeded $150,000, the prior-year safe harbor is 110% of the prior year's tax: 110% × $50,000 = $55,000." },
            { label: "D", text: "The full current-year liability, whatever it turns out to be", isCorrect: false, rationale: "The safe harbors exist precisely so the taxpayer need not predict the current-year liability exactly." },
          ],
          explanation: "Individuals avoid the estimated tax underpayment penalty by paying the lesser of 90% of the current year's tax or 100% of the prior year's tax. When prior-year AGI exceeds $150,000, the prior-year percentage rises to 110% — here, 110% × $50,000 = $55,000.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["estimated tax", "penalties"],
        },
      ],
    },
    {
      slug: "property-transactions-basis-and-cost-recovery",
      title: "Property Transactions: Basis & Cost Recovery",
      shortDescription: "Basis rules, Modified Accelerated Cost Recovery System (MACRS) depreciation, Section 179, and permanent 100% bonus depreciation.",
      blueprintArea: "Area III: Federal Taxation of Property Transactions",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 70,
      order: 7,
      studyMaterialHtml: regContent["property-transactions-basis-and-cost-recovery"].study,
      revisionNoteHtml: regContent["property-transactions-basis-and-cost-recovery"].revision,
      mcqs: [
        {
          question: "Under the One Big Beautiful Bill Act, which statement about bonus depreciation is correct for qualifying property acquired after January 19, 2025?",
          options: [
            { label: "A", text: "Bonus depreciation is limited to 40% and phases down annually", isCorrect: false, rationale: "The 40% rate applied in 2025 before OBBBA restored the full rate; the phase-down was eliminated." },
            { label: "B", text: "Bonus depreciation is 100%, has no annual dollar cap, and may create a net operating loss", isCorrect: true, rationale: "Correct — OBBBA permanently restored 100% bonus depreciation, which unlike Section 179 has no dollar limitation and is not restricted to taxable business income." },
            { label: "C", text: "Bonus depreciation is capped at $2.5 million per year", isCorrect: false, rationale: "The $2.5 million cap applies to Section 179 expensing, not bonus depreciation." },
            { label: "D", text: "Bonus depreciation cannot exceed taxable income from the business", isCorrect: false, rationale: "That limitation applies to Section 179; bonus depreciation can generate a loss." },
          ],
          explanation: "The One Big Beautiful Bill Act permanently restored 100% bonus depreciation for qualifying property acquired after January 19, 2025. Unlike Section 179 — which is capped at $2.5 million, phases out above $4 million of additions, and is limited to taxable business income — bonus depreciation has no dollar cap and can create or increase a net operating loss.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["OBBBA", "depreciation", "bonus depreciation"],
        },
        {
          question: "A donor gives property with an adjusted basis of $10,000 and a fair market value of $6,000 at the date of gift. The donee later sells it for $8,000. What is the donee's recognized gain or loss?",
          options: [
            { label: "A", text: "$2,000 loss", isCorrect: false, rationale: "For loss purposes the basis is the $6,000 FMV, and $8,000 exceeds that — so there is no loss." },
            { label: "B", text: "$2,000 gain", isCorrect: false, rationale: "For gain purposes the basis is the $10,000 carryover basis, and $8,000 is below that — so there is no gain." },
            { label: "C", text: "No gain or loss", isCorrect: true, rationale: "Correct — when the sale price falls between the FMV at the date of gift ($6,000) and the donor's carryover basis ($10,000), neither a gain nor a loss is recognized." },
            { label: "D", text: "$4,000 loss", isCorrect: false, rationale: "This incorrectly uses the donor's basis for a loss calculation, which the double-basis rule prohibits." },
          ],
          explanation: "Under the double-basis rule for gifted property that has declined in value, the donee uses the donor's carryover basis to compute gain and the lower FMV at the date of gift to compute loss. When the sales price falls between those two amounts, no gain or loss is recognized.",
          difficulty: "HARD",
          questionType: "CALCULATION",
          tags: ["basis", "gifts"],
        },
      ],
    },
    {
      slug: "property-transactions-gains-losses-and-like-kind-exchanges",
      title: "Property Transactions: Gains, Losses & Like-Kind Exchanges",
      shortDescription: "Capital vs. ordinary treatment, Section 1231, depreciation recapture, and Section 1031 exchanges.",
      blueprintArea: "Area III: Federal Taxation of Property Transactions",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 70,
      order: 8,
      studyMaterialHtml: regContent["property-transactions-gains-losses-and-like-kind-exchanges"].study,
      revisionNoteHtml: regContent["property-transactions-gains-losses-and-like-kind-exchanges"].revision,
      mcqs: [
        {
          question: "A business sells equipment for $55,000. Original cost was $50,000 and accumulated depreciation was $30,000. How is the gain characterized?",
          options: [
            { label: "A", text: "$35,000 of Section 1231 gain", isCorrect: false, rationale: "Section 1245 recapture applies first to the depreciation taken, converting part of the gain to ordinary income." },
            { label: "B", text: "$30,000 ordinary income under Section 1245 and $5,000 Section 1231 gain", isCorrect: true, rationale: "Correct — total gain is $35,000 ($55,000 − $20,000 adjusted basis). Section 1245 recaptures the $30,000 of depreciation as ordinary income, and the $5,000 exceeding original cost is Section 1231 gain." },
            { label: "C", text: "$35,000 of ordinary income", isCorrect: false, rationale: "Recapture is limited to depreciation taken ($30,000); gain above original cost is Section 1231." },
            { label: "D", text: "$5,000 ordinary income and $30,000 long-term capital gain", isCorrect: false, rationale: "This reverses the treatment — depreciation recapture is the ordinary portion." },
          ],
          explanation: "Adjusted basis is $50,000 − $30,000 = $20,000, so the gain is $35,000. Section 1245 recaptures depreciation previously taken ($30,000) as ordinary income. Only the portion of gain exceeding the original cost ($55,000 − $50,000 = $5,000) receives Section 1231 treatment.",
          difficulty: "HARD",
          questionType: "CALCULATION",
          tags: ["1231", "1245", "recapture"],
        },
        {
          question: "In a Section 1031 exchange, a taxpayer's realized gain is $80,000 and the taxpayer receives $30,000 of cash boot. How much gain is recognized?",
          options: [
            { label: "A", text: "$0", isCorrect: false, rationale: "Receipt of boot triggers recognition up to the amount of boot received." },
            { label: "B", text: "$30,000", isCorrect: true, rationale: "Correct — gain is recognized to the extent of the lesser of realized gain ($80,000) or boot received ($30,000)." },
            { label: "C", text: "$80,000", isCorrect: false, rationale: "The full realized gain is only recognized if boot equals or exceeds it." },
            { label: "D", text: "$50,000", isCorrect: false, rationale: "This subtracts boot from realized gain, which is the deferred amount, not the recognized amount." },
          ],
          explanation: "In a like-kind exchange, gain is recognized to the extent of the lesser of realized gain or boot received. Here that is $30,000; the remaining $50,000 of gain is deferred and reduces the basis of the replacement property.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["1031", "like-kind exchange", "boot"],
        },
      ],
    },
    {
      slug: "individual-taxation-gross-income",
      title: "Individual Taxation: Gross Income",
      shortDescription: "What counts as gross income, common exclusions, the kiddie tax, and passive activity loss limits.",
      blueprintArea: "Area IV: Federal Taxation of Individuals",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 65,
      order: 9,
      studyMaterialHtml: regContent["individual-taxation-gross-income"].study,
      revisionNoteHtml: regContent["individual-taxation-gross-income"].revision,
      mcqs: [
        {
          question: "Under the One Big Beautiful Bill Act, how is qualified tip income treated for an eligible employee in tax year 2026?",
          options: [
            { label: "A", text: "It is entirely excluded from gross income and exempt from payroll taxes", isCorrect: false, rationale: "The provision is a deduction, not an exclusion — the income remains in gross income and remains subject to payroll taxes." },
            { label: "B", text: "It is included in gross income, but the taxpayer may deduct up to $25,000 of qualified tips subject to income phase-outs", isCorrect: true, rationale: "Correct — OBBBA created a deduction of up to $25,000 for qualified tips for tax years 2025 through 2028, phasing out above $150,000 of income ($300,000 for joint filers)." },
            { label: "C", text: "It is taxed at a preferential capital gains rate", isCorrect: false, rationale: "Tips are ordinary compensation income; no preferential rate applies." },
            { label: "D", text: "It is excluded only for taxpayers with income above $150,000", isCorrect: false, rationale: "The relationship is reversed — the benefit phases out above that income level." },
          ],
          explanation: "The One Big Beautiful Bill Act provides a deduction — not an exclusion — of up to $25,000 for qualified tips for tax years 2025 through 2028. The tips remain includible in gross income and subject to payroll taxes, and the deduction phases out for taxpayers with income above $150,000 ($300,000 married filing jointly).",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["OBBBA", "gross income", "tips"],
        },
        {
          question: "Which of the following items is included in a taxpayer's federal gross income?",
          options: [
            { label: "A", text: "Interest earned on a municipal bond", isCorrect: false, rationale: "Municipal bond interest is specifically excluded from federal gross income." },
            { label: "B", text: "A $10,000 gift received from a parent", isCorrect: false, rationale: "Gifts received are excluded from the recipient's gross income." },
            { label: "C", text: "Gambling winnings from a casino", isCorrect: true, rationale: "Correct — gambling winnings are fully includible in gross income; losses are deductible only as an itemized deduction and only up to winnings." },
            { label: "D", text: "Life insurance proceeds received upon the death of a spouse", isCorrect: false, rationale: "Life insurance death benefits are generally excluded from the beneficiary's gross income." },
          ],
          explanation: "Gambling winnings are taxable in full and included in gross income. Municipal bond interest, gifts received, and life insurance death benefits are all specifically excluded under the Internal Revenue Code.",
          difficulty: "EASY",
          questionType: "CONCEPTUAL",
          tags: ["gross income", "exclusions"],
        },
      ],
    },
    {
      slug: "individual-taxation-adjustments-and-deductions",
      title: "Individual Taxation: Adjustments & Deductions",
      shortDescription: "Adjustments, the 2026 standard deduction, itemized deductions including the state and local tax (SALT) cap, the new tips, overtime, and senior deductions, and the qualified business income deduction.",
      blueprintArea: "Area IV: Federal Taxation of Individuals",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 10,
      studyMaterialHtml: regContent["individual-taxation-adjustments-and-deductions"].study,
      revisionNoteHtml: regContent["individual-taxation-adjustments-and-deductions"].revision,
      mcqs: [
        {
          question: "Under the One Big Beautiful Bill Act, what is the state and local tax (SALT) deduction cap, and is it permanent?",
          options: [
            { label: "A", text: "$10,000, made permanent", isCorrect: false, rationale: "$10,000 was the pre-OBBBA cap; OBBBA raised it, though the increase is temporary." },
            { label: "B", text: "$40,000, but scheduled to revert to $10,000 in 2030", isCorrect: true, rationale: "Correct — OBBBA temporarily increased the SALT cap to $40,000, with the cap scheduled to return to $10,000 beginning in 2030." },
            { label: "C", text: "Unlimited, restoring pre-2018 law", isCorrect: false, rationale: "The SALT deduction remains capped; it was not fully restored." },
            { label: "D", text: "$40,000, made permanent with no sunset", isCorrect: false, rationale: "Unlike some other OBBBA provisions, the SALT increase includes a scheduled reversion." },
          ],
          explanation: "OBBBA increased the SALT deduction cap from $10,000 to $40,000, but unlike the permanent QBI and estate tax changes, this increase is temporary — the cap is scheduled to revert to $10,000 beginning in 2030.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["OBBBA", "SALT", "itemized deductions"],
        },
        {
          question: "A taxpayer has AGI of $100,000 and incurs $12,000 of unreimbursed qualified medical expenses. What amount is deductible as an itemized deduction?",
          options: [
            { label: "A", text: "$12,000", isCorrect: false, rationale: "Medical expenses are deductible only to the extent they exceed the AGI floor." },
            { label: "B", text: "$4,500", isCorrect: true, rationale: "Correct — the floor is 7.5% × $100,000 = $7,500, so the deductible amount is $12,000 − $7,500 = $4,500." },
            { label: "C", text: "$7,500", isCorrect: false, rationale: "$7,500 is the non-deductible floor, not the deductible amount." },
            { label: "D", text: "$0", isCorrect: false, rationale: "The expenses exceed the floor, so a portion is deductible." },
          ],
          explanation: "Qualified medical expenses are deductible only to the extent they exceed 7.5% of AGI. With AGI of $100,000, the floor is $7,500, leaving $4,500 of the $12,000 in expenses deductible as an itemized deduction.",
          difficulty: "EASY",
          questionType: "CALCULATION",
          tags: ["itemized deductions", "medical"],
        },
      ],
    },
    {
      slug: "filing-status-credits-and-amt",
      title: "Filing Status, Credits & Alternative Minimum Tax",
      shortDescription: "Choosing the right filing status, refundable vs. nonrefundable credits, and the alternative minimum tax.",
      blueprintArea: "Area IV: Federal Taxation of Individuals",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 11,
      studyMaterialHtml: regContent["filing-status-credits-and-amt"].study,
      revisionNoteHtml: regContent["filing-status-credits-and-amt"].revision,
      mcqs: [
        {
          question: "An unmarried taxpayer pays more than half the cost of maintaining a separate household that is the principal residence of the taxpayer's dependent mother. The mother does not live with the taxpayer. What filing status may the taxpayer use?",
          options: [
            { label: "A", text: "Single, because the dependent does not live with the taxpayer", isCorrect: false, rationale: "The dependent-parent exception permits head of household even though the parent lives elsewhere." },
            { label: "B", text: "Head of household", isCorrect: true, rationale: "Correct — a taxpayer who pays more than half the cost of maintaining the principal home of a dependent parent qualifies for head of household even though the parent does not live with the taxpayer." },
            { label: "C", text: "Qualifying surviving spouse", isCorrect: false, rationale: "That status requires a deceased spouse and a dependent child." },
            { label: "D", text: "Married filing separately", isCorrect: false, rationale: "The taxpayer is unmarried." },
          ],
          explanation: "Head of household normally requires the qualifying person to live with the taxpayer for more than half the year, but a dependent parent is a specific exception: the taxpayer qualifies by paying more than half the cost of maintaining the parent's principal residence, even if that home is separate.",
          difficulty: "MEDIUM",
          questionType: "EXCEPTION",
          tags: ["filing status", "head of household"],
        },
      ],
    },
    {
      slug: "retirement-plans-and-tax-planning-basics",
      title: "Retirement Plans & Tax Planning Basics",
      shortDescription: "Traditional and Roth individual retirement accounts (IRAs), employer plans, 2026 limits, early withdrawals, and required distributions.",
      blueprintArea: "Area IV: Federal Taxation of Individuals",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 12,
      studyMaterialHtml: regContent["retirement-plans-and-tax-planning-basics"].study,
      revisionNoteHtml: regContent["retirement-plans-and-tax-planning-basics"].revision,
      mcqs: [
        {
          question: "A 45-year-old taxpayer takes a distribution from a Roth IRA opened three years ago, withdrawing an amount that exceeds total contributions. How is the excess (earnings) portion treated?",
          options: [
            { label: "A", text: "Tax-free, because Roth distributions are always tax-free", isCorrect: false, rationale: "Roth earnings are tax-free only if the distribution is qualified, which requires both the 5-year period and a qualifying event." },
            { label: "B", text: "Taxable as ordinary income and subject to the 10% early distribution penalty", isCorrect: true, rationale: "Correct — the 5-year holding period is not met and the taxpayer is under 59½, so the earnings portion is a nonqualified distribution: taxable and generally subject to the 10% additional tax." },
            { label: "C", text: "Taxable but exempt from the 10% penalty", isCorrect: false, rationale: "No exception applies on these facts, so the penalty also applies." },
            { label: "D", text: "Treated as a return of capital and excluded from income", isCorrect: false, rationale: "Contributions come out first tax-free, but the question specifies amounts exceeding contributions — the earnings portion." },
          ],
          explanation: "A qualified Roth distribution requires the account to have been held 5 years AND the owner to be at least 59½ (or meet death, disability, or first-time homebuyer conditions). Here neither test is satisfied, so the earnings portion is taxable and subject to the 10% early distribution penalty. Contributions themselves always come out tax- and penalty-free first.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["retirement", "Roth IRA"],
        },
      ],
    },
    {
      slug: "c-corporation-taxation",
      title: "C Corporation Taxation",
      shortDescription: "Corporate taxable income, book-tax differences, the dividends-received deduction, and distributions.",
      blueprintArea: "Area V: Federal Taxation of Entities",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 70,
      order: 13,
      studyMaterialHtml: regContent["c-corporation-taxation"].study,
      revisionNoteHtml: regContent["c-corporation-taxation"].revision,
      mcqs: [
        {
          question: "A corporation owns 30% of the stock of another domestic corporation and receives a $100,000 dividend. Ignoring the taxable income limitation, what is the dividends-received deduction?",
          options: [
            { label: "A", text: "$50,000", isCorrect: false, rationale: "The 50% rate applies to ownership of less than 20%." },
            { label: "B", text: "$65,000", isCorrect: true, rationale: "Correct — ownership of at least 20% but less than 80% qualifies for a 65% dividends-received deduction: 65% × $100,000 = $65,000." },
            { label: "C", text: "$100,000", isCorrect: false, rationale: "The 100% DRD requires ownership of 80% or more (affiliated group)." },
            { label: "D", text: "$0", isCorrect: false, rationale: "Domestic corporate dividends qualify for a DRD based on ownership percentage." },
          ],
          explanation: "The dividends-received deduction is tiered by ownership: less than 20% ownership gives a 50% deduction, 20% to less than 80% gives 65%, and 80% or more gives 100%. At 30% ownership, the DRD is 65% × $100,000 = $65,000.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["C corporation", "DRD"],
        },
        {
          question: "A corporation with no current or accumulated earnings and profits distributes $50,000 cash to a shareholder whose stock basis is $30,000. How is the distribution treated by the shareholder?",
          options: [
            { label: "A", text: "$50,000 dividend income", isCorrect: false, rationale: "Dividend treatment requires earnings and profits, and there are none here." },
            { label: "B", text: "$30,000 tax-free return of capital and $20,000 capital gain", isCorrect: true, rationale: "Correct — with no E&P, the distribution first reduces stock basis tax-free ($30,000), and the excess ($20,000) is treated as gain from the sale of stock." },
            { label: "C", text: "$50,000 tax-free return of capital", isCorrect: false, rationale: "Only amounts up to stock basis are tax-free; the excess is capital gain." },
            { label: "D", text: "$20,000 ordinary income", isCorrect: false, rationale: "Amounts exceeding basis are capital gain, not ordinary income." },
          ],
          explanation: "Corporate distributions follow a three-tier ordering: dividend income to the extent of current and accumulated E&P, then a tax-free return of capital reducing stock basis, then capital gain. With no E&P, $30,000 reduces basis to zero and the remaining $20,000 is capital gain.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["C corporation", "distributions", "E&P"],
        },
      ],
    },
    {
      slug: "s-corporation-taxation",
      title: "S Corporation Taxation",
      shortDescription: "Eligibility requirements, flow-through taxation, shareholder basis, and the accumulated adjustments account.",
      blueprintArea: "Area V: Federal Taxation of Entities",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 14,
      studyMaterialHtml: regContent["s-corporation-taxation"].study,
      revisionNoteHtml: regContent["s-corporation-taxation"].revision,
      mcqs: [
        {
          question: "Which of the following would immediately terminate a corporation's S election?",
          options: [
            { label: "A", text: "Issuing shares with different voting rights to existing shareholders", isCorrect: false, rationale: "Differences in voting rights alone do not create a second class of stock." },
            { label: "B", text: "Transferring shares to a nonresident alien individual", isCorrect: true, rationale: "Correct — nonresident aliens are ineligible S corporation shareholders, so such a transfer terminates the election immediately." },
            { label: "C", text: "Having 90 shareholders", isCorrect: false, rationale: "The limit is 100 shareholders, so 90 is permissible." },
            { label: "D", text: "Distributing appreciated property to a shareholder", isCorrect: false, rationale: "This has tax consequences but does not terminate the S election." },
          ],
          explanation: "S corporation shareholders must be individuals (who are U.S. citizens or residents), estates, or certain trusts. Transferring even one share to a nonresident alien violates the eligibility requirements and terminates the S election immediately.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["S corporation", "eligibility"],
        },
        {
          question: "How does an S corporation shareholder's stock basis differ from a partner's basis in a partnership with respect to entity-level debt?",
          options: [
            { label: "A", text: "Both include a proportionate share of entity liabilities", isCorrect: false, rationale: "Only partners include a share of entity liabilities in basis." },
            { label: "B", text: "An S corporation shareholder includes only direct loans made to the corporation, while a partner includes a share of partnership liabilities", isCorrect: true, rationale: "Correct — this is the fundamental basis distinction between the two pass-through forms, and it determines how much loss each owner can currently deduct." },
            { label: "C", text: "Neither includes any form of debt in basis", isCorrect: false, rationale: "Both include some debt — S shareholders through direct loans, partners through their share of liabilities." },
            { label: "D", text: "An S corporation shareholder includes a share of all corporate debt", isCorrect: false, rationale: "S shareholders do not get basis for general corporate borrowings, only for loans they personally make to the corporation." },
          ],
          explanation: "A partner's basis includes a share of partnership liabilities, which increases the losses the partner can deduct. An S corporation shareholder gets basis only from stock investment and direct loans made personally to the corporation — never from the corporation's third-party debt.",
          difficulty: "HARD",
          questionType: "CONCEPTUAL",
          tags: ["S corporation", "basis"],
        },
      ],
    },
    {
      slug: "partnership-taxation",
      title: "Partnership Taxation",
      shortDescription: "Formation, partner basis including liabilities, guaranteed payments, and distributions.",
      blueprintArea: "Area V: Federal Taxation of Entities",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 70,
      order: 15,
      studyMaterialHtml: regContent["partnership-taxation"].study,
      revisionNoteHtml: regContent["partnership-taxation"].revision,
      mcqs: [
        {
          question: "A partner has an outside basis of $20,000, which includes a $12,000 share of partnership liabilities. The partnership repays all of its debt. What is the tax consequence to the partner?",
          options: [
            { label: "A", text: "No consequence, because no cash was actually distributed", isCorrect: false, rationale: "A reduction in a partner's share of liabilities is treated as a deemed cash distribution." },
            { label: "B", text: "A deemed cash distribution of $12,000, reducing basis to $8,000 with no gain recognized", isCorrect: true, rationale: "Correct — the $12,000 decrease in liability share is a deemed distribution. Because it does not exceed the $20,000 basis, no gain is recognized and basis simply falls to $8,000." },
            { label: "C", text: "A $12,000 capital gain", isCorrect: false, rationale: "Gain arises only when a deemed distribution exceeds outside basis, which is not the case here." },
            { label: "D", text: "A $12,000 ordinary loss", isCorrect: false, rationale: "Debt repayment does not create a loss to the partner." },
          ],
          explanation: "A decrease in a partner's share of partnership liabilities is treated as a deemed cash distribution to that partner. It reduces outside basis and triggers gain only to the extent it exceeds basis. Here, $12,000 is less than the $20,000 basis, so basis simply falls to $8,000.",
          difficulty: "HARD",
          questionType: "CALCULATION",
          tags: ["partnership", "basis", "liabilities"],
        },
      ],
    },
    {
      slug: "trusts-estates-and-gift-tax-basics",
      title: "Trusts, Estates & Gift Tax Basics",
      shortDescription: "Fiduciary income tax, distributable net income, and the expanded estate and gift tax exemption.",
      blueprintArea: "Area V: Federal Taxation of Entities",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 60,
      order: 16,
      studyMaterialHtml: regContent["trusts-estates-and-gift-tax-basics"].study,
      revisionNoteHtml: regContent["trusts-estates-and-gift-tax-basics"].revision,
      mcqs: [
        {
          question: "Under the One Big Beautiful Bill Act, what is the lifetime estate and gift tax exemption per individual beginning in 2026, and is it scheduled to sunset?",
          options: [
            { label: "A", text: "$5 million, sunsetting in 2030", isCorrect: false, rationale: "This reflects pre-TCJA levels, not current law." },
            { label: "B", text: "$15 million, permanent with inflation indexing from 2027", isCorrect: true, rationale: "Correct — OBBBA set the exemption at $15 million per individual ($30 million per married couple) starting in 2026, made it permanent, and provided for inflation adjustment beginning in 2027." },
            { label: "C", text: "$15 million, sunsetting after 2028", isCorrect: false, rationale: "Unlike the TCJA provisions, the OBBBA exemption has no sunset." },
            { label: "D", text: "$30 million per individual", isCorrect: false, rationale: "$30 million is the combined amount for a married couple; the per-individual amount is $15 million." },
          ],
          explanation: "The One Big Beautiful Bill Act set the lifetime estate and gift tax exemption at $15 million per individual ($30 million for married couples) beginning in 2026. Unlike the Tax Cuts and Jobs Act version, this amount is permanent with no scheduled sunset, and is indexed for inflation starting in 2027.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["OBBBA", "estate tax", "gift tax"],
        },
        {
          question: "What is the primary function of distributable net income (DNI) in fiduciary income taxation?",
          options: [
            { label: "A", text: "It determines the trust's tax rate bracket", isCorrect: false, rationale: "Rate brackets are determined by taxable income, not by DNI's conduit function." },
            { label: "B", text: "It limits the entity's distribution deduction and the amount taxable to beneficiaries, and carries the character of income through", isCorrect: true, rationale: "Correct — DNI is the ceiling on both the fiduciary's deduction and the beneficiaries' inclusion, and it preserves the character of the underlying income items." },
            { label: "C", text: "It measures the trust's accumulated principal", isCorrect: false, rationale: "DNI relates to income, not corpus/principal." },
            { label: "D", text: "It determines whether the trust is simple or complex", isCorrect: false, rationale: "That classification depends on the trust's distribution requirements and powers, not on DNI." },
          ],
          explanation: "DNI serves as the conduit mechanism in fiduciary taxation: it caps the distribution deduction available to the trust or estate, caps the amount beneficiaries must include in income, and determines the character (e.g., tax-exempt, dividend, interest) of the income the beneficiaries report.",
          difficulty: "HARD",
          questionType: "CONCEPTUAL",
          tags: ["trusts", "DNI"],
        },
      ],
    },
    {
      slug: "employee-benefits-and-payroll-tax",
      title: "Employee Benefits & Payroll Tax",
      shortDescription: "Fringe benefit taxation, employer payroll obligations, and worker classification.",
      blueprintArea: "Area IV: Federal Taxation of Individuals",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 50,
      order: 17,
      studyMaterialHtml: regContent["employee-benefits-and-payroll-tax"].study,
      revisionNoteHtml: regContent["employee-benefits-and-payroll-tax"].revision,
      mcqs: [
        {
          question: "An employer provides each employee with a $50 gift card at year end and a $50 holiday ham. How are these treated for the employees?",
          options: [
            { label: "A", text: "Both are excludable de minimis fringe benefits", isCorrect: false, rationale: "Cash and cash equivalents such as gift cards can never qualify as de minimis." },
            { label: "B", text: "The gift card is taxable wages; the ham is an excludable de minimis fringe benefit", isCorrect: true, rationale: "Correct — cash equivalents like gift cards are always taxable compensation, while a low-value non-cash item such as a holiday ham qualifies as a de minimis fringe." },
            { label: "C", text: "Both are taxable wages", isCorrect: false, rationale: "The non-cash item of small value qualifies as de minimis and is excludable." },
            { label: "D", text: "The gift card is excludable because it is under $100", isCorrect: false, rationale: "There is no dollar threshold that makes a cash equivalent excludable." },
          ],
          explanation: "De minimis fringe benefits are small-value non-cash items where accounting for them would be impractical — a holiday ham qualifies. Cash and cash equivalents, including gift cards, are never de minimis and are always includible in the employee's wages.",
          difficulty: "EASY",
          questionType: "APPLICATION",
          tags: ["fringe benefits", "payroll"],
        },
      ],
    },
    {
      slug: "exempt-organizations-basics",
      title: "Exempt Organizations Basics",
      shortDescription: "501(c)(3) qualification, private foundations vs. public charities, and unrelated business income tax.",
      blueprintArea: "Area V: Federal Taxation of Entities",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 45,
      order: 18,
      studyMaterialHtml: regContent["exempt-organizations-basics"].study,
      revisionNoteHtml: regContent["exempt-organizations-basics"].revision,
      mcqs: [
        {
          question: "A tax-exempt museum operates a gift shop. Which activity would most likely generate unrelated business taxable income?",
          options: [
            { label: "A", text: "Selling reproductions of artwork displayed in the museum's collection", isCorrect: false, rationale: "This is substantially related to the museum's educational exempt purpose." },
            { label: "B", text: "Selling consumer electronics unrelated to the collection", isCorrect: true, rationale: "Correct — selling unrelated merchandise is a trade or business, regularly carried on, and not substantially related to the exempt purpose, so it generates UBTI." },
            { label: "C", text: "Selling donated used books once per year at a fundraising sale", isCorrect: false, rationale: "Sales of donated merchandise are specifically excluded from UBIT, and an annual sale is also not regularly carried on." },
            { label: "D", text: "Receiving dividend income from an endowment portfolio", isCorrect: false, rationale: "Dividends are passive investment income specifically excluded from UBIT." },
          ],
          explanation: "Unrelated business income requires a trade or business, regularly carried on, that is not substantially related to the exempt purpose. Selling art reproductions furthers the museum's educational purpose, but selling unrelated consumer electronics does not — that activity generates UBTI. Passive dividends and sales of donated goods are specifically excluded.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["exempt organizations", "UBIT"],
        },
      ],
    },
  ],
};
