import type { SubjectSeed } from "./types";
import { tcpContent } from "./content/tcp";

export const tcp: SubjectSeed = {
  slug: "tcp",
  name: "Tax Compliance and Planning",
  shortName: "TCP",
  type: "DISCIPLINE",
  description:
    "Tax Compliance and Planning (TCP) extends Taxation and Regulation (REG) into planning: individual tax and personal financial planning, entity compliance, entity planning, and property transactions — updated for the One Big Beautiful Bill Act (OBBBA). It's the natural choice for candidates heading into tax practice.",
  difficulty: "HARD",
  estimatedHours: 85,
  blueprintUrl: "https://www.aicpa-cima.com/resources/download/tcp-cpa-exam-blueprint",
  order: 6,
  topics: [
    {
      slug: "individual-tax-planning-strategies",
      title: "Individual Tax Planning Strategies",
      shortDescription: "Timing strategies, income shifting, bunching deductions, and managing the character of income.",
      blueprintArea: "Area I: Individual Tax Compliance & Personal Financial Planning",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 60,
      order: 1,
      studyMaterialHtml: tcpContent["individual-tax-planning-strategies"].study,
      revisionNoteHtml: tcpContent["individual-tax-planning-strategies"].revision,
      mcqs: [
        {
          question: "A taxpayer sells stock at a $10,000 loss on December 10 and repurchases the same stock on December 28 of the same year. What is the tax result?",
          options: [
            { label: "A", text: "The $10,000 loss is deductible in the current year", isCorrect: false, rationale: "The repurchase within 30 days triggers the wash sale rule, disallowing the loss." },
            { label: "B", text: "The loss is disallowed and added to the basis of the repurchased stock", isCorrect: true, rationale: "Correct — under the wash sale rule, buying substantially identical securities within 30 days before or after the sale disallows the loss, which is instead added to the basis of the replacement shares." },
            { label: "C", text: "The loss is permanently forfeited", isCorrect: false, rationale: "The loss is not lost forever — it is deferred through a basis increase in the replacement stock." },
            { label: "D", text: "Half the loss is deductible and half is deferred", isCorrect: false, rationale: "There is no such proportional split under the wash sale rule when the full position is repurchased." },
          ],
          explanation: "The wash sale rule disallows a loss when substantially identical securities are acquired within 30 days before or after the sale. The disallowed loss is not permanently lost — it increases the basis of the replacement shares, deferring the benefit until that position is finally sold outside a wash sale window.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["tax planning", "wash sale"],
        },
      ],
    },
    {
      slug: "personal-financial-planning",
      title: "Personal Financial Planning",
      shortDescription: "Education funding, insurance, and integrating tax planning with a client's broader financial goals.",
      blueprintArea: "Area I: Individual Tax Compliance & Personal Financial Planning",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 55,
      order: 2,
      studyMaterialHtml: tcpContent["personal-financial-planning"].study,
      revisionNoteHtml: tcpContent["personal-financial-planning"].revision,
      mcqs: [
        {
          question: "An employee receives disability benefits under a policy for which the employer paid all premiums and excluded them from the employee's taxable wages. How are the benefits taxed?",
          options: [
            { label: "A", text: "Entirely tax-free to the employee", isCorrect: false, rationale: "Benefits are tax-free only when the individual paid the premiums with after-tax dollars." },
            { label: "B", text: "Fully taxable to the employee as ordinary income", isCorrect: true, rationale: "Correct — because the premiums were paid with pre-tax employer dollars never included in the employee's income, the resulting benefits are fully taxable." },
            { label: "C", text: "Taxable only to the extent they exceed the premiums paid", isCorrect: false, rationale: "No such offset applies to disability benefits." },
            { label: "D", text: "Taxed at preferential capital gains rates", isCorrect: false, rationale: "Disability benefits are ordinary income when taxable." },
          ],
          explanation: "The taxability of disability benefits follows the premium dollars. When an employer pays premiums with pre-tax dollars that were never included in the employee's income, the benefits are fully taxable. When the individual pays premiums with after-tax dollars, the benefits are received tax-free.",
          difficulty: "MEDIUM",
          questionType: "APPLICATION",
          tags: ["personal financial planning", "disability insurance"],
        },
      ],
    },
    {
      slug: "retirement-planning-strategies",
      title: "Retirement Planning Strategies",
      shortDescription: "Roth conversions, required minimum distributions, and sequencing retirement withdrawals.",
      blueprintArea: "Area I: Individual Tax Compliance & Personal Financial Planning",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 60,
      order: 3,
      studyMaterialHtml: tcpContent["retirement-planning-strategies"].study,
      revisionNoteHtml: tcpContent["retirement-planning-strategies"].revision,
      mcqs: [
        {
          question: "A taxpayer has $90,000 in traditional IRAs, of which $9,000 represents nondeductible (after-tax) contributions. The taxpayer converts $10,000 to a Roth IRA. How much of the conversion is taxable?",
          options: [
            { label: "A", text: "$0, because the taxpayer designates the conversion as coming from nondeductible contributions", isCorrect: false, rationale: "The pro-rata rule prevents designating a conversion as coming solely from after-tax basis." },
            { label: "B", text: "$9,000", isCorrect: true, rationale: "Correct — the after-tax portion is 10% ($9,000 ÷ $90,000), so 10% of the $10,000 conversion ($1,000) is tax-free and the remaining $9,000 is taxable." },
            { label: "C", text: "$10,000", isCorrect: false, rationale: "A proportionate share of after-tax basis does come out tax-free, so the full amount is not taxable." },
            { label: "D", text: "$1,000", isCorrect: false, rationale: "This reverses the calculation — $1,000 is the tax-free portion, not the taxable portion." },
          ],
          explanation: "Under the pro-rata rule, all traditional IRAs are treated as one account. After-tax basis is $9,000 of $90,000, or 10%. Therefore 10% of the $10,000 conversion ($1,000) is tax-free and the remaining $9,000 is taxable ordinary income.",
          difficulty: "HARD",
          questionType: "CALCULATION",
          tags: ["retirement", "Roth conversion", "pro-rata rule"],
        },
      ],
    },
    {
      slug: "estate-and-gift-tax-planning",
      title: "Estate & Gift Tax Planning",
      shortDescription: "Lifetime gifting strategies, trusts, portability, and the permanent $15 million exemption.",
      blueprintArea: "Area I: Individual Tax Compliance & Personal Financial Planning",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 4,
      studyMaterialHtml: tcpContent["estate-and-gift-tax-planning"].study,
      revisionNoteHtml: tcpContent["estate-and-gift-tax-planning"].revision,
      mcqs: [
        {
          question: "A client's total estate is well below the $15 million exemption. The client asks whether to gift highly appreciated stock to children now or hold it until death. From a pure tax standpoint, which is generally better and why?",
          options: [
            { label: "A", text: "Gift now, to remove future appreciation from the estate", isCorrect: false, rationale: "Removing appreciation from the estate provides no benefit when the estate will not be taxable anyway, and it sacrifices the basis step-up." },
            { label: "B", text: "Hold until death, so the heirs receive a stepped-up basis and no estate tax is due regardless", isCorrect: true, rationale: "Correct — with the estate below the exemption, there is no estate tax to avoid, and holding preserves the step-up in basis that eliminates the built-in capital gain for the heirs." },
            { label: "C", text: "Gift now, because gifted property also receives a stepped-up basis", isCorrect: false, rationale: "Gifted property takes a carryover basis, not a stepped-up basis." },
            { label: "D", text: "It makes no difference, because basis is the same either way", isCorrect: false, rationale: "Basis treatment differs significantly between lifetime gifts and transfers at death." },
          ],
          explanation: "With the permanent $15 million exemption, most estates are not subject to estate tax, which shifts the planning focus to income tax basis. Lifetime gifts carry over the donor's basis, while property transferred at death receives a basis step-up to fair market value — eliminating the built-in gain for heirs.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["OBBBA", "estate planning", "basis"],
        },
      ],
    },
    {
      slug: "c-corporation-tax-compliance",
      title: "C Corporation Tax Compliance",
      shortDescription: "Form 1120, corporate taxable income, Schedules M-1, M-2, and M-3, net operating loss (NOL) rules, groups, and estimated taxes.",
      blueprintArea: "Area II: Entity Tax Compliance",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 5,
      studyMaterialHtml: tcpContent["c-corporation-tax-compliance"].study,
      revisionNoteHtml: tcpContent["c-corporation-tax-compliance"].revision,
      mcqs: [
        {
          question: "A corporation has taxable income before the NOL deduction of $600,000 and an NOL carryforward of $700,000 generated in 2022. What is the maximum NOL deduction?",
          options: [
            { label: "A", text: "$700,000, using the full carryforward", isCorrect: false, rationale: "Post-2017 NOLs are limited to 80% of taxable income computed before the NOL deduction." },
            { label: "B", text: "$480,000", isCorrect: true, rationale: "Correct — the deduction is limited to 80% × $600,000 = $480,000, leaving $120,000 of taxable income and $220,000 of NOL carried forward." },
            { label: "C", text: "$600,000, reducing taxable income to zero", isCorrect: false, rationale: "The 80% limitation prevents fully eliminating taxable income with a post-2017 NOL." },
            { label: "D", text: "$120,000", isCorrect: false, rationale: "This is the remaining taxable income after the limitation, not the deduction itself." },
          ],
          explanation: "Net operating losses arising in tax years after 2017 carry forward indefinitely but the deduction is limited to 80% of taxable income determined before the NOL deduction. Here, 80% × $600,000 = $480,000 is deductible, leaving $120,000 of taxable income and a $220,000 carryforward.",
          difficulty: "MEDIUM",
          questionType: "CALCULATION",
          tags: ["C corporation", "NOL"],
        },
      ],
    },
    {
      slug: "s-corporation-planning",
      title: "S Corporation Compliance & Planning",
      shortDescription: "Basis planning, distribution ordering, reasonable compensation, and built-in gains tax.",
      blueprintArea: "Area II: Entity Tax Compliance",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 6,
      studyMaterialHtml: tcpContent["s-corporation-planning"].study,
      revisionNoteHtml: tcpContent["s-corporation-planning"].revision,
      mcqs: [
        {
          question: "An S corporation shareholder wants to deduct a $50,000 loss but has only $20,000 of stock basis. Which action would create additional basis to absorb the loss?",
          options: [
            { label: "A", text: "Personally guaranteeing a $30,000 bank loan made to the corporation", isCorrect: false, rationale: "A guarantee creates no basis for an S corporation shareholder — only an actual economic outlay does." },
            { label: "B", text: "Lending $30,000 personally to the corporation", isCorrect: true, rationale: "Correct — a direct loan from the shareholder to the corporation creates debt basis, which can absorb losses after stock basis is exhausted." },
            { label: "C", text: "Having the corporation borrow $30,000 from a bank", isCorrect: false, rationale: "Unlike partnerships, corporate-level debt does not give S corporation shareholders basis." },
            { label: "D", text: "Increasing the shareholder's salary by $30,000", isCorrect: false, rationale: "Salary is a deduction to the corporation and income to the shareholder; it does not create stock or debt basis." },
          ],
          explanation: "S corporation shareholders obtain basis only through stock investment and direct loans they personally make to the corporation. Guaranteeing corporate debt or having the corporation borrow from a third party creates no shareholder basis — a key difference from partnership taxation.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["S corporation", "basis planning"],
        },
      ],
    },
    {
      slug: "partnership-planning",
      title: "Partnership Compliance & Planning",
      shortDescription: "Special allocations, distributions, Section 754 elections, and partnership interest transfers.",
      blueprintArea: "Area II: Entity Tax Compliance",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 65,
      order: 7,
      studyMaterialHtml: tcpContent["partnership-planning"].study,
      revisionNoteHtml: tcpContent["partnership-planning"].revision,
      mcqs: [
        {
          question: "A partner contributes land with a basis of $40,000 and a fair market value of $100,000. Three years later the partnership sells the land for $110,000. How is the gain allocated?",
          options: [
            { label: "A", text: "The entire $70,000 gain is shared according to the general profit-sharing ratio", isCorrect: false, rationale: "Section 704(c) requires the pre-contribution built-in gain to be allocated to the contributing partner." },
            { label: "B", text: "$60,000 of built-in gain is allocated to the contributing partner, and the remaining $10,000 is shared per the partnership agreement", isCorrect: true, rationale: "Correct — the $60,000 built-in gain at contribution ($100,000 − $40,000) must go to the contributing partner under §704(c); only the post-contribution appreciation of $10,000 is shared normally." },
            { label: "C", text: "The entire $70,000 gain is allocated to the contributing partner", isCorrect: false, rationale: "Only the pre-contribution built-in gain is specially allocated; post-contribution appreciation is shared." },
            { label: "D", text: "No gain is recognized because contributed property retains carryover basis", isCorrect: false, rationale: "Carryover basis means the gain is deferred until sale, not eliminated." },
          ],
          explanation: "Section 704(c) prevents shifting pre-contribution gain among partners. The $60,000 of built-in gain existing at the contribution date is allocated entirely to the contributing partner, while the $10,000 of appreciation occurring after contribution is allocated according to the partnership agreement.",
          difficulty: "HARD",
          questionType: "CALCULATION",
          tags: ["partnership", "704(c)"],
        },
      ],
    },
    {
      slug: "entity-choice-and-structuring",
      title: "Entity Choice & Structuring",
      shortDescription: "Selecting and changing entity type, and the tax consequences of conversions.",
      blueprintArea: "Area III: Entity Tax Planning",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 60,
      order: 8,
      studyMaterialHtml: tcpContent["entity-choice-and-structuring"].study,
      revisionNoteHtml: tcpContent["entity-choice-and-structuring"].revision,
      mcqs: [
        {
          question: "A C corporation with substantially appreciated assets wants to convert to an LLC taxed as a partnership. What is the primary tax consequence?",
          options: [
            { label: "A", text: "The conversion is tax-free under Section 351", isCorrect: false, rationale: "Section 351 applies to transfers into corporate solution, not out of it." },
            { label: "B", text: "The conversion is treated as a liquidation, triggering gain at both the corporate and shareholder levels", isCorrect: true, rationale: "Correct — converting from C corporation to a partnership form is treated as a deemed liquidation, producing corporate-level gain on the appreciated assets and shareholder-level gain on the deemed distribution." },
            { label: "C", text: "Only the shareholders recognize gain", isCorrect: false, rationale: "The corporation also recognizes gain as if it sold its assets at fair market value." },
            { label: "D", text: "Gain is deferred until the LLC later sells the assets", isCorrect: false, rationale: "There is no deferral mechanism for this type of conversion." },
          ],
          explanation: "Converting a C corporation into a partnership or LLC is treated as a liquidation of the corporation. The corporation recognizes gain as though it sold its assets at fair market value, and the shareholders recognize gain on the deemed distribution — often making this conversion prohibitively expensive.",
          difficulty: "HARD",
          questionType: "APPLICATION",
          tags: ["entity choice", "conversions"],
        },
      ],
    },
    {
      slug: "entity-distributions-and-liquidations",
      title: "Distributions, Redemptions & Liquidations",
      shortDescription: "Planning around corporate distributions, stock redemptions, and complete liquidations.",
      blueprintArea: "Area III: Entity Tax Planning",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 60,
      order: 9,
      studyMaterialHtml: tcpContent["entity-distributions-and-liquidations"].study,
      revisionNoteHtml: tcpContent["entity-distributions-and-liquidations"].revision,
      mcqs: [
        {
          question: "A shareholder owns 70% of a corporation's stock. Following a redemption, she owns 52%. Ignoring attribution, does the redemption qualify as substantially disproportionate?",
          options: [
            { label: "A", text: "Yes, because her ownership decreased significantly", isCorrect: false, rationale: "A significant decrease alone is not enough — both prongs of the mechanical test must be satisfied." },
            { label: "B", text: "No, because she still owns 50% or more of the voting power", isCorrect: true, rationale: "Correct — the substantially disproportionate test requires ownership below 80% of the prior percentage (below 56%) AND below 50% of total voting power. At 52% she fails the second prong." },
            { label: "C", text: "Yes, because 52% is less than 80% of 70%", isCorrect: false, rationale: "She does satisfy that prong (52% < 56%), but the 50% voting power requirement is not met." },
            { label: "D", text: "Yes, because any reduction in ownership qualifies", isCorrect: false, rationale: "The test is mechanical and both conditions must be satisfied." },
          ],
          explanation: "The substantially disproportionate redemption test under §302(b)(2) has two requirements: after the redemption, the shareholder must own less than 80% of their prior ownership percentage (here, less than 56%) AND less than 50% of total voting power. At 52%, she satisfies the first but fails the second, so the redemption would be treated as a dividend distribution.",
          difficulty: "HARD",
          questionType: "CALCULATION",
          tags: ["redemptions", "302"],
        },
      ],
    },
    {
      slug: "property-transactions-advanced-planning",
      title: "Property Transactions: Advanced Planning",
      shortDescription: "Installment sales, related-party rules, and structuring dispositions to manage timing and character.",
      blueprintArea: "Area IV: Property Transactions",
      blueprintStatus: "CONFIRMED",
      difficulty: "HARD",
      estimatedMinutes: 60,
      order: 10,
      studyMaterialHtml: tcpContent["property-transactions-advanced-planning"].study,
      revisionNoteHtml: tcpContent["property-transactions-advanced-planning"].revision,
      mcqs: [
        {
          question: "A taxpayer sells equipment with an adjusted basis of $60,000 (original cost $100,000, accumulated depreciation $40,000) for $120,000, receiving payments over four years. What is recognized in the year of sale beyond any installment gain on the first payment?",
          options: [
            { label: "A", text: "Nothing — all gain is spread over four years", isCorrect: false, rationale: "Depreciation recapture cannot be deferred under the installment method." },
            { label: "B", text: "$40,000 of ordinary income from Section 1245 depreciation recapture", isCorrect: true, rationale: "Correct — Section 1245 recapture of the $40,000 of depreciation taken is recognized entirely in the year of sale, regardless of how little cash is received." },
            { label: "C", text: "$60,000 of capital gain", isCorrect: false, rationale: "Total gain is $60,000, but $40,000 is recapture recognized immediately and the balance is spread." },
            { label: "D", text: "$120,000 of ordinary income", isCorrect: false, rationale: "Recapture is limited to depreciation previously taken, not the full sales price." },
          ],
          explanation: "Under the installment method, depreciation recapture under Section 1245 is recognized in full in the year of sale even if little or no cash is received. Here, $40,000 of recapture is ordinary income immediately, and only the remaining $20,000 of gain is spread across the installment payments.",
          difficulty: "HARD",
          questionType: "CALCULATION",
          tags: ["installment sale", "recapture"],
        },
      ],
    },
    {
      slug: "multi-jurisdictional-and-international-basics",
      title: "Multi-Jurisdictional & International Basics",
      shortDescription: "State nexus concepts, apportionment, and the fundamentals of US international taxation.",
      blueprintArea: "Area III: Entity Tax Planning",
      blueprintStatus: "PROVISIONAL",
      difficulty: "HARD",
      estimatedMinutes: 55,
      order: 11,
      studyMaterialHtml: tcpContent["multi-jurisdictional-and-international-basics"].study,
      revisionNoteHtml: tcpContent["multi-jurisdictional-and-international-basics"].revision,
      mcqs: [
        {
          question: "A company's only activity in a state is sending sales representatives to solicit orders for tangible goods, which are approved and shipped from outside the state. What protection does Public Law 86-272 provide?",
          options: [
            { label: "A", text: "Complete protection from all state taxes in that state", isCorrect: false, rationale: "P.L. 86-272 is narrow and does not shield all taxes." },
            { label: "B", text: "Protection from the state's net income tax only", isCorrect: true, rationale: "Correct — P.L. 86-272 prevents imposition of a net income tax when in-state activity is limited to soliciting orders for tangible personal property approved and shipped from outside the state." },
            { label: "C", text: "Protection from sales and use tax collection obligations", isCorrect: false, rationale: "Sales and use tax obligations are entirely outside the scope of P.L. 86-272." },
            { label: "D", text: "Protection from franchise and gross receipts taxes", isCorrect: false, rationale: "Only net income taxes are covered; franchise and gross receipts taxes are not." },
          ],
          explanation: "Public Law 86-272 offers narrow protection: it bars a state from imposing a net income tax where the taxpayer's only in-state activity is soliciting orders for tangible personal property that are approved and shipped from outside the state. It does not protect against sales and use tax, franchise taxes, or gross receipts taxes, and does not cover services or intangibles.",
          difficulty: "MEDIUM",
          questionType: "EXCEPTION",
          tags: ["state tax", "nexus", "P.L. 86-272"],
        },
      ],
    },
    {
      slug: "tax-research-and-documentation",
      title: "Tax Research & Documentation",
      shortDescription: "The hierarchy of tax authority, research methodology, and documenting a defensible position.",
      blueprintArea: "Area I: Individual Tax Compliance & Personal Financial Planning",
      blueprintStatus: "CONFIRMED",
      difficulty: "MEDIUM",
      estimatedMinutes: 45,
      order: 12,
      studyMaterialHtml: tcpContent["tax-research-and-documentation"].study,
      revisionNoteHtml: tcpContent["tax-research-and-documentation"].revision,
      mcqs: [
        {
          question: "A tax practitioner finds a Private Letter Ruling issued to another taxpayer that directly supports the client's intended position. How should the practitioner treat it?",
          options: [
            { label: "A", text: "Rely on it as binding precedent for the client", isCorrect: false, rationale: "A PLR may be relied upon only by the taxpayer who requested it." },
            { label: "B", text: "Treat it as an indication of IRS thinking, but not as authority the client can rely on", isCorrect: true, rationale: "Correct — PLRs are taxpayer-specific and cannot be cited as precedent, though they can indicate how the IRS views similar facts." },
            { label: "C", text: "Disregard it entirely, as it has no informational value", isCorrect: false, rationale: "PLRs do provide useful insight into the IRS's position, even without precedential force." },
            { label: "D", text: "Treat it as equivalent to a Revenue Ruling", isCorrect: false, rationale: "Revenue Rulings apply generally to all taxpayers with similar facts; PLRs do not." },
          ],
          explanation: "A Private Letter Ruling binds the IRS only with respect to the taxpayer who requested it and may not be cited as precedent by others. It remains useful as an indication of the IRS's interpretive position, but a Revenue Ruling — which applies generally — carries far greater weight.",
          difficulty: "MEDIUM",
          questionType: "CONCEPTUAL",
          tags: ["tax research", "authority"],
        },
      ],
    },
  ],
};
