// Regenerates <subject>/index.ts from the topic files in each subject folder.
// Run: node prisma/seed-data/content/build-index.mjs
import { readdirSync, readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = dirname(fileURLToPath(import.meta.url));
const subjects = ["far", "aud", "reg", "bar", "isc", "tcp"];
const present = [];
for (const subject of subjects) {
  const dir = join(root, subject);
  if (!existsSync(dir)) continue;
  const files = readdirSync(dir).filter((f) => f.endsWith(".ts") && f !== "index.ts").sort();
  const imports = [];
  const entries = [];
  for (const file of files) {
    const slug = file.replace(/\.ts$/, "");
    const src = readFileSync(join(dir, file), "utf8");
    const name = src.match(/export const (\w+): TopicContent/)?.[1];
    if (!name) throw new Error(`${subject}/${file}: no exported TopicContent`);
    imports.push(`import { ${name} } from "./${slug}";`);
    entries.push(`  "${slug}": ${name},`);
  }
  writeFileSync(
    join(dir, "index.ts"),
    `// Generated by build-index.mjs — one entry per topic file, keyed by topic slug.\nimport type { TopicContent } from "../types";\n${imports.join("\n")}\n\nexport const ${subject}Content: Record<string, TopicContent> = {\n${entries.join("\n")}\n};\n`,
  );
  present.push(subject);
}
writeFileSync(
  join(root, "index.ts"),
  `// Generated by build-index.mjs.\nimport type { TopicContent } from "./types";\n${present.map((s) => `import { ${s}Content } from "./${s}";`).join("\n")}\n\nexport const contentBySubject: Record<string, Record<string, TopicContent>> = {\n${present.map((s) => `  ${s}: ${s}Content,`).join("\n")}\n};\n\nexport type { TopicContent };\n`,
);
console.log("Indexed:", present.join(", "));
