// Generated by build-index.mjs.
import type { TopicContent } from "./types";
import { farContent } from "./far";
import { audContent } from "./aud";
import { regContent } from "./reg";
import { barContent } from "./bar";
import { iscContent } from "./isc";
import { tcpContent } from "./tcp";

export const contentBySubject: Record<string, Record<string, TopicContent>> = {
  far: farContent,
  aud: audContent,
  reg: regContent,
  bar: barContent,
  isc: iscContent,
  tcp: tcpContent,
};

export type { TopicContent };
