import type { McqBank } from "./types";

/** AUD question bank — third batch, bringing every AUD topic to at least 10 questions. */
export const audBankC: McqBank = {
  "professional-ethics-and-independence": [
    {
      question: "A covered member obtains a loan from a bank that is an audit client, under the bank's normal lending terms. Which type of loan is permitted without impairing independence?",
      options: [
        { label: "A", text: "An unsecured personal loan of $50,000", isCorrect: false, rationale: "Unsecured loans that are material to the covered member are not among the permitted loans." },
        { label: "B", text: "An automobile loan collateralized by the automobile", isCorrect: true, rationale: "Correct — auto loans and leases collateralized by the vehicle are permitted loans." },
        { label: "C", text: "A new home mortgage obtained after the bank became a client", isCorrect: false, rationale: "Mortgages are only grandfathered if obtained before the lender became a client (or before the person became a covered member)." },
        { label: "D", text: "A margin loan from the client's brokerage subsidiary to buy the bank's stock", isCorrect: false, rationale: "Buying the client's stock would itself be a direct financial interest." },
      ],
      explanation: "The AICPA Code permits certain loans from a financial institution client made under normal lending procedures: automobile loans and leases collateralized by the vehicle, loans fully collateralized by cash deposits at the institution, and credit card and overdraft balances of $10,000 or less in total. Other loans, such as mortgages, may be grandfathered only if obtained before independence rules applied.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["independence", "loans"],
    },
    {
      question: "The spouse of an audit engagement partner owns a small number of shares in the audit client, bought through a personal brokerage account. What is the effect on independence?",
      options: [
        { label: "A", text: "Independence is not impaired because the holding is immaterial", isCorrect: false, rationale: "Direct financial interests impair independence regardless of materiality." },
        { label: "B", text: "Independence is impaired, because a spouse's direct financial interest is treated as the covered member's own", isCorrect: true, rationale: "Correct — immediate family members are held to the same direct-interest prohibition." },
        { label: "C", text: "Independence is impaired only if the spouse works for the client", isCorrect: false, rationale: "Employment is a separate issue; the shareholding alone is enough here." },
        { label: "D", text: "Independence is not impaired because the spouse is not on the engagement team", isCorrect: false, rationale: "The partner is a covered member, and the spouse's interests are attributed to the partner." },
      ],
      explanation: "A covered member's immediate family (spouse, spousal equivalent, and dependents) are subject to the same independence rules as the covered member, with limited exceptions such as certain employee benefit plans. Any direct financial interest impairs independence, no matter how small.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["independence", "immediate family"],
    },
    {
      question: "Under the AICPA conceptual framework, which threat arises when a firm audits accounting records that it prepared for the client?",
      options: [
        { label: "A", text: "Advocacy threat", isCorrect: false, rationale: "Advocacy threats arise when the firm promotes the client's position." },
        { label: "B", text: "Familiarity threat", isCorrect: false, rationale: "Familiarity threats arise from long or close relationships." },
        { label: "C", text: "Self-review threat", isCorrect: true, rationale: "Correct — the firm would be evaluating its own work." },
        { label: "D", text: "Undue influence threat", isCorrect: false, rationale: "Undue influence arises from pressure by the client or others." },
      ],
      explanation: "A self-review threat exists when a member evaluates the results of a previous service performed by the member or firm and relies on that work in forming a judgment. Safeguards — such as the client designating a competent individual to oversee the service — may reduce it to an acceptable level.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["conceptual framework", "threats"],
    },
  ],

  "engagement-acceptance-and-quality-management": [
    {
      question: "Before an audit is completed, the client asks the auditor to change the engagement to a review. Which reason would most likely be considered reasonable justification for the change?",
      options: [
        { label: "A", text: "The auditor has been refused access to key personnel and records", isCorrect: false, rationale: "A scope restriction imposed by management is generally not a reasonable basis for downgrading." },
        { label: "B", text: "The client wants to avoid a modified opinion", isCorrect: false, rationale: "Avoiding an unfavorable report is not reasonable justification." },
        { label: "C", text: "A change in circumstances means the client no longer requires an audit", isCorrect: true, rationale: "Correct — a change in requirements or a misunderstanding about the service needed can justify the change." },
        { label: "D", text: "The client refuses to sign the representation letter", isCorrect: false, rationale: "Refusing representations in an audit also prevents a review, which requires them too." },
      ],
      explanation: "A change in circumstances affecting the need for the service, or a misunderstanding about the nature of the service originally requested, ordinarily justifies changing the engagement. A request driven by scope restrictions or information that would lead to a modified report generally does not.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["change in engagement"],
    },
    {
      question: "A successor auditor's inquiries of the predecessor auditor ordinarily include all of the following EXCEPT:",
      options: [
        { label: "A", text: "Information bearing on the integrity of management", isCorrect: false, rationale: "This is a required inquiry." },
        { label: "B", text: "Disagreements with management about accounting policies or auditing procedures", isCorrect: false, rationale: "This is a required inquiry." },
        { label: "C", text: "The predecessor's understanding of the reasons for the change in auditors", isCorrect: false, rationale: "This is a required inquiry." },
        { label: "D", text: "The amount of the predecessor's audit fee", isCorrect: true, rationale: "Correct — fees are not among the required inquiries." },
      ],
      explanation: "The successor's inquiries focus on matters that help decide whether to accept the engagement: management integrity, disagreements with management, communications with those charged with governance about fraud, noncompliance, and internal control matters, and the reasons for the change.",
      difficulty: "EASY",
      questionType: "EXCEPTION",
      tags: ["predecessor auditor", "acceptance"],
    },
    {
      question: "Which of the following is NOT one of the components of a firm's system of quality management under SQMS No. 1?",
      options: [
        { label: "A", text: "Governance and leadership", isCorrect: false, rationale: "This is a component." },
        { label: "B", text: "Monitoring and remediation process", isCorrect: false, rationale: "This is a component." },
        { label: "C", text: "Resources", isCorrect: false, rationale: "This is a component." },
        { label: "D", text: "Peer review", isCorrect: true, rationale: "Correct — peer review is an external oversight program, not a component of the firm's system." },
      ],
      explanation: "SQMS No. 1 has eight components: the firm's risk assessment process; governance and leadership; relevant ethical requirements; acceptance and continuance of client relationships and specific engagements; engagement performance; resources; information and communication; and the monitoring and remediation process. Peer review is a separate AICPA practice-monitoring program.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["SQMS No. 1", "quality management"],
    },
    {
      question: "Before allowing a successor auditor to review its audit documentation, the predecessor auditor may:",
      options: [
        { label: "A", text: "Refuse unless the successor pays a fee", isCorrect: false, rationale: "Access is not conditioned on a fee under the standards." },
        { label: "B", text: "Request consent from the client and an acknowledgment letter from the successor on how the documentation will be used", isCorrect: true, rationale: "Correct — client consent and a successor acknowledgment letter are customary." },
        { label: "C", text: "Provide the documentation only to the client", isCorrect: false, rationale: "The predecessor may give access directly to the successor with the client's consent." },
        { label: "D", text: "Require the successor to rely on its work without further testing", isCorrect: false, rationale: "The successor remains responsible for its own evidence and cannot simply rely on the predecessor." },
      ],
      explanation: "Reviewing the predecessor's documentation requires the client's consent. The predecessor commonly asks for a consent and acknowledgment letter from the client and a letter from the successor limiting the use of the documentation. The successor still must obtain its own sufficient appropriate evidence, including about opening balances.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["predecessor auditor", "audit documentation"],
    },
  ],

  "audit-planning-and-materiality": [
    {
      question: "Which benchmark is most commonly used to set overall materiality for a not-for-profit organization?",
      options: [
        { label: "A", text: "Pretax income from continuing operations", isCorrect: false, rationale: "NFPs are not profit-oriented, so income is usually not the most relevant measure." },
        { label: "B", text: "Total revenue or total expenses", isCorrect: true, rationale: "Correct — users of NFP statements focus on the scale of revenue and spending." },
        { label: "C", text: "Market capitalization", isCorrect: false, rationale: "NFPs have no market capitalization." },
        { label: "D", text: "Earnings per share", isCorrect: false, rationale: "NFPs don't report EPS." },
      ],
      explanation: "Materiality is based on the benchmark most relevant to financial statement users. For profit-oriented entities that is often pretax income from continuing operations; for not-for-profits, total revenue or total expenses (or net assets) are more common.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["materiality", "benchmarks"],
    },
    {
      question: "The auditor sets an amount below which misstatements are 'clearly trivial'. What is the purpose of this threshold?",
      options: [
        { label: "A", text: "Misstatements below it need not be accumulated", isCorrect: true, rationale: "Correct — the auditor accumulates all misstatements except those that are clearly trivial." },
        { label: "B", text: "Misstatements below it are automatically material", isCorrect: false, rationale: "Clearly trivial amounts are, by definition, inconsequential." },
        { label: "C", text: "It replaces performance materiality", isCorrect: false, rationale: "Performance materiality serves a different purpose — planning procedures." },
        { label: "D", text: "It is the amount above which the auditor must issue a qualified opinion", isCorrect: false, rationale: "Opinion modification depends on uncorrected misstatements relative to materiality, not this threshold." },
      ],
      explanation: "The auditor accumulates misstatements identified during the audit, other than those that are clearly trivial — amounts of a wholly different (smaller) order of magnitude than materiality. If there is any uncertainty about whether an item is clearly trivial, it is not.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["materiality", "clearly trivial"],
    },
    {
      question: "Which document describes the nature, timing, and extent of the risk assessment procedures and further audit procedures to be performed?",
      options: [
        { label: "A", text: "The engagement letter", isCorrect: false, rationale: "The engagement letter sets out terms of the engagement, not detailed procedures." },
        { label: "B", text: "The overall audit strategy", isCorrect: false, rationale: "The strategy sets scope, timing, and direction; the plan details the procedures." },
        { label: "C", text: "The audit plan", isCorrect: true, rationale: "Correct — the audit plan is more detailed than the strategy and specifies the procedures." },
        { label: "D", text: "The management representation letter", isCorrect: false, rationale: "Representations are obtained at the end of the audit." },
      ],
      explanation: "The overall audit strategy sets the scope, timing, and direction of the audit. The audit plan translates that strategy into specific procedures — the nature, timing, and extent of risk assessment procedures, further audit procedures, and other required procedures. Both are updated as the audit progresses.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["audit plan", "audit strategy"],
    },
    {
      question: "Late in the audit, actual year-end results turn out to be significantly lower than the preliminary figures used to set materiality. What should the auditor do?",
      options: [
        { label: "A", text: "Keep the original materiality, since planning is complete", isCorrect: false, rationale: "Materiality must be revised when new information would have led to a different amount." },
        { label: "B", text: "Revise materiality downward and consider whether the nature, timing, and extent of procedures remain appropriate", isCorrect: true, rationale: "Correct — a lower materiality may require more audit work." },
        { label: "C", text: "Increase materiality to reduce remaining work", isCorrect: false, rationale: "Lower results call for lower, not higher, materiality." },
        { label: "D", text: "Withdraw from the engagement", isCorrect: false, rationale: "Revising materiality is a normal part of the audit." },
      ],
      explanation: "The auditor revises materiality when information becomes available that would have caused a different amount to be set initially. If the revised materiality is lower, the auditor reconsiders performance materiality and whether further procedures need to be expanded.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["materiality", "revision"],
    },
  ],

  "understanding-the-entity-and-internal-control": [
    {
      question: "To evaluate the design of a control and determine whether it has been implemented, the auditor should:",
      options: [
        { label: "A", text: "Rely on inquiry of management alone", isCorrect: false, rationale: "Inquiry alone is not sufficient to evaluate design and implementation." },
        { label: "B", text: "Combine inquiry with procedures such as observation, inspection, or a walkthrough", isCorrect: true, rationale: "Correct — inquiry must be supplemented by other procedures." },
        { label: "C", text: "Perform tests of operating effectiveness in every case", isCorrect: false, rationale: "Operating effectiveness testing is only required when the auditor plans to rely on controls or when substantive procedures alone are insufficient." },
        { label: "D", text: "Perform substantive analytical procedures", isCorrect: false, rationale: "Substantive procedures test balances, not control design." },
      ],
      explanation: "Evaluating design and implementation is part of risk assessment. Inquiry must be combined with observation of the control, inspection of documents, or a walkthrough tracing a transaction through the system. This is different from testing operating effectiveness over the period.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["design and implementation", "walkthrough"],
    },
    {
      question: "A monthly bank reconciliation prepared by someone independent of cash handling is an example of which type of control?",
      options: [
        { label: "A", text: "Preventive control", isCorrect: false, rationale: "A reconciliation doesn't stop an error from occurring; it finds it afterward." },
        { label: "B", text: "Detective control", isCorrect: true, rationale: "Correct — reconciliations identify errors or irregularities after they have occurred." },
        { label: "C", text: "IT general control", isCorrect: false, rationale: "ITGCs relate to the IT environment, such as access and change management." },
        { label: "D", text: "Entity-level control environment", isCorrect: false, rationale: "The control environment is about tone at the top and governance, not specific reconciliations." },
      ],
      explanation: "Preventive controls stop misstatements from occurring (e.g., required approvals, segregation of duties). Detective controls find misstatements that have already occurred (e.g., reconciliations, reviews of exception reports). Effective systems use both.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["types of controls"],
    },
    {
      question: "At the end of an audit, the auditor identified no significant deficiencies or material weaknesses. With respect to written communication, the auditor should NOT:",
      options: [
        { label: "A", text: "Communicate other deficiencies to management orally", isCorrect: false, rationale: "Deficiencies that are not significant may be communicated orally to management." },
        { label: "B", text: "Issue a written communication stating that no significant deficiencies were identified", isCorrect: true, rationale: "Correct — such a statement could be misunderstood as assurance on internal control." },
        { label: "C", text: "Document the deficiencies identified", isCorrect: false, rationale: "Documentation is always required." },
        { label: "D", text: "Discuss internal control with those charged with governance", isCorrect: false, rationale: "Discussing internal control is permitted." },
      ],
      explanation: "Because a financial statement audit is not designed to find all control deficiencies, the auditor should not issue a written communication stating that no significant deficiencies were identified. Significant deficiencies and material weaknesses that are identified must be communicated in writing to management and those charged with governance.",
      difficulty: "HARD",
      questionType: "EXAM_TRAP",
      tags: ["communication of deficiencies"],
    },
  ],

  "assessing-risk-of-material-misstatement": [
    {
      question: "Under SAS No. 145, which of the following is NOT an inherent risk factor?",
      options: [
        { label: "A", text: "Complexity", isCorrect: false, rationale: "Complexity is an inherent risk factor." },
        { label: "B", text: "Subjectivity", isCorrect: false, rationale: "Subjectivity is an inherent risk factor." },
        { label: "C", text: "Susceptibility to misstatement due to management bias or fraud", isCorrect: false, rationale: "This is an inherent risk factor." },
        { label: "D", text: "The effectiveness of the entity's controls", isCorrect: true, rationale: "Correct — control effectiveness relates to control risk, not inherent risk." },
      ],
      explanation: "SAS No. 145 lists inherent risk factors — complexity, subjectivity, change, uncertainty, and susceptibility to misstatement due to management bias or other fraud risk factors — to help auditors place inherent risk on a spectrum. The effectiveness of controls affects control risk, which is assessed separately.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["SAS 145", "inherent risk factors"],
    },
    {
      question: "Under SAS No. 145, how must the auditor assess the risk of material misstatement at the relevant assertion level?",
      options: [
        { label: "A", text: "As a single combined assessment only", isCorrect: false, rationale: "SAS 145 requires separate assessments." },
        { label: "B", text: "By assessing inherent risk and control risk separately", isCorrect: true, rationale: "Correct — separate assessments are required." },
        { label: "C", text: "By assessing control risk only", isCorrect: false, rationale: "Inherent risk must also be assessed." },
        { label: "D", text: "By assessing detection risk first", isCorrect: false, rationale: "Detection risk is determined in response to the assessed RMM." },
      ],
      explanation: "SAS No. 145 requires separate assessments of inherent risk and control risk. If the auditor does not plan to test the operating effectiveness of controls, control risk is assessed at the maximum, so RMM equals the inherent risk assessment.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SAS 145", "risk assessment"],
    },
    {
      question: "The auditor responds to a significant risk with substantive procedures only, without relying on controls. Those procedures must include:",
      options: [
        { label: "A", text: "Substantive analytical procedures only", isCorrect: false, rationale: "Analytical procedures alone are not enough for a significant risk." },
        { label: "B", text: "Tests of details", isCorrect: true, rationale: "Correct — tests of details are required when the approach is substantive only." },
        { label: "C", text: "Inquiry of management only", isCorrect: false, rationale: "Inquiry alone never provides sufficient appropriate evidence." },
        { label: "D", text: "A test of controls", isCorrect: false, rationale: "The auditor has chosen not to rely on controls." },
      ],
      explanation: "For significant risks, the auditor performs substantive procedures specifically responsive to that risk. If the approach consists only of substantive procedures, they must include tests of details — substantive analytical procedures alone are insufficient.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["significant risks"],
    },
  ],

  "fraud-risk": [
    {
      question: "An employee steals customer payments and covers the theft by applying later collections from other customers to the earlier accounts. This scheme is:",
      options: [
        { label: "A", text: "Kiting, a form of fraudulent financial reporting", isCorrect: false, rationale: "Kiting involves transfers between bank accounts to inflate cash." },
        { label: "B", text: "Lapping, a form of misappropriation of assets", isCorrect: true, rationale: "Correct — lapping conceals stolen receipts by delaying credits to customer accounts." },
        { label: "C", text: "Channel stuffing, a form of fraudulent financial reporting", isCorrect: false, rationale: "Channel stuffing inflates sales by shipping excess goods to distributors." },
        { label: "D", text: "An error, not fraud", isCorrect: false, rationale: "Intentional theft and concealment is fraud." },
      ],
      explanation: "Lapping is a misappropriation scheme in which cash from one customer is stolen and later collections from other customers are used to cover it. Auditors can detect lapping by comparing deposit slip details with postings to individual customer accounts, and through confirmations.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["misappropriation", "lapping"],
    },
    {
      question: "In testing journal entries for evidence of management override, which characteristic makes an entry most worth selecting?",
      options: [
        { label: "A", text: "Routine entries posted automatically by the payroll system", isCorrect: false, rationale: "Automated routine entries are lower risk." },
        { label: "B", text: "Entries made at year-end by a senior executive who does not normally post entries, in round amounts to seldom-used accounts", isCorrect: true, rationale: "Correct — unusual preparers, timing, round amounts, and seldom-used accounts are classic fraud indicators." },
        { label: "C", text: "Entries reviewed and approved under normal procedures", isCorrect: false, rationale: "Normal, approved entries carry less override risk." },
        { label: "D", text: "Monthly depreciation entries generated by the fixed asset system", isCorrect: false, rationale: "System-generated recurring entries are low risk." },
      ],
      explanation: "Fraudulent entries are often made at the end of a period, by individuals who don't usually make entries, to unrelated, unusual, or seldom-used accounts, in round numbers, or with little or no explanation. The auditor uses such characteristics to select entries to test.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["journal entry testing", "management override"],
    },
    {
      question: "The auditor finds a $2,000 misstatement resulting from fraud committed by the CFO. The amount is well below materiality. What should the auditor do?",
      options: [
        { label: "A", text: "Ignore it because it is immaterial", isCorrect: false, rationale: "Fraud by senior management is qualitatively significant regardless of amount." },
        { label: "B", text: "Reevaluate the assessment of fraud risk and the reliability of management's representations and other evidence", isCorrect: true, rationale: "Correct — fraud involving senior management is unlikely to be an isolated occurrence." },
        { label: "C", text: "Report it directly to the SEC", isCorrect: false, rationale: "External reporting is not generally required and confidentiality rules apply." },
        { label: "D", text: "Adjust the financial statements and take no further action", isCorrect: false, rationale: "The auditor must consider the broader implications of senior-management fraud." },
      ],
      explanation: "When a misstatement may result from fraud, the auditor evaluates its implications even if it is immaterial. Fraud involving senior management is qualitatively significant: the auditor reevaluates RMM due to fraud, the reliability of evidence and representations, and communicates the matter to those charged with governance.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["fraud", "senior management"],
    },
    {
      question: "Management bonuses are tied to meeting aggressive earnings targets. In terms of the fraud triangle, this is an example of:",
      options: [
        { label: "A", text: "Opportunity", isCorrect: false, rationale: "Opportunity comes from weak controls or the ability to override them." },
        { label: "B", text: "Incentive or pressure", isCorrect: true, rationale: "Correct — compensation tied to targets creates pressure to manipulate results." },
        { label: "C", text: "Attitude or rationalization", isCorrect: false, rationale: "Rationalization is the mindset that justifies the fraud." },
        { label: "D", text: "Detection risk", isCorrect: false, rationale: "Detection risk is an audit risk concept, not part of the fraud triangle." },
      ],
      explanation: "The fraud triangle has three conditions: incentive/pressure (e.g., bonuses tied to earnings, debt covenants, market expectations), opportunity (e.g., weak controls, complex transactions), and attitude/rationalization (e.g., disregard for controls, a history of violations).",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["fraud triangle"],
    },
  ],

  "responding-to-assessed-risks": [
    {
      question: "An auditor plans to use evidence from prior audits about the operating effectiveness of controls that have not changed. How often must those controls be tested?",
      options: [
        { label: "A", text: "Every year, without exception", isCorrect: false, rationale: "Rotation is permitted for unchanged controls that don't address significant risks." },
        { label: "B", text: "At least once in every third audit, with some controls tested in each audit", isCorrect: true, rationale: "Correct — this is the rotation rule for unchanged controls." },
        { label: "C", text: "Only when the auditor changes", isCorrect: false, rationale: "Evidence ages; rotation limits reliance on older evidence." },
        { label: "D", text: "Once every five years", isCorrect: false, rationale: "The maximum interval is every third audit." },
      ],
      explanation: "If controls have not changed since last tested, the auditor may rely on prior-audit evidence, but must test each such control at least once every third audit and test some controls every year. Controls that mitigate significant risks must be tested in the current period.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["tests of controls", "rotation"],
    },
    {
      question: "Regardless of the assessed risks, which substantive procedure must be performed in every audit related to the financial statement closing process?",
      options: [
        { label: "A", text: "Confirming all bank accounts", isCorrect: false, rationale: "Confirmation decisions depend on risk; this is not the closing-process requirement." },
        { label: "B", text: "Agreeing the financial statements to the underlying accounting records and examining material journal entries and adjustments", isCorrect: true, rationale: "Correct — these procedures are required in every audit." },
        { label: "C", text: "Observing the inventory count", isCorrect: false, rationale: "Required only when inventory is material, and it is not a closing-process procedure." },
        { label: "D", text: "Testing controls over the closing process", isCorrect: false, rationale: "Tests of controls are not mandatory in every audit." },
      ],
      explanation: "The auditor's substantive procedures must include agreeing or reconciling the financial statements, including disclosures, with the underlying accounting records, and examining material journal entries and other adjustments made in preparing the financial statements.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["substantive procedures", "closing process"],
    },
    {
      question: "Which is an overall (financial statement level) response to an assessed risk of material misstatement due to fraud?",
      options: [
        { label: "A", text: "Increasing the sample size for one account", isCorrect: false, rationale: "That is an assertion-level response." },
        { label: "B", text: "Incorporating an element of unpredictability into the selection of audit procedures", isCorrect: true, rationale: "Correct — unpredictability is a required overall response to fraud risk." },
        { label: "C", text: "Reducing the use of professional skepticism", isCorrect: false, rationale: "Higher risk calls for more, not less, skepticism." },
        { label: "D", text: "Relying more heavily on management inquiries", isCorrect: false, rationale: "Higher fraud risk calls for more persuasive evidence than inquiry." },
      ],
      explanation: "Overall responses to fraud risk include assigning and supervising personnel appropriately, evaluating the entity's selection and application of accounting policies, and incorporating unpredictability into the nature, timing, and extent of procedures — for example, testing accounts or locations not normally tested.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["fraud responses", "unpredictability"],
    },
    {
      question: "When the assessed risk of material misstatement for an account is high, the auditor is most likely to perform substantive procedures:",
      options: [
        { label: "A", text: "At an interim date well before year-end", isCorrect: false, rationale: "Interim testing leaves a longer untested period, which is less suitable for high risk." },
        { label: "B", text: "At or near the period end", isCorrect: true, rationale: "Correct — testing near year-end reduces the risk of changes in the remaining period." },
        { label: "C", text: "Only if tests of controls were ineffective", isCorrect: false, rationale: "Substantive procedures are required for material items regardless." },
        { label: "D", text: "Using inquiry only", isCorrect: false, rationale: "Inquiry is never sufficient on its own." },
      ],
      explanation: "As the assessed RMM increases, the auditor obtains more persuasive evidence: more reliable procedures (nature), larger samples (extent), and testing at or near the period end (timing).",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["timing of procedures"],
    },
  ],

  "audit-sampling": [
    {
      question: "For attribute sampling in a test of controls over a large population, which factor has little effect on the required sample size?",
      options: [
        { label: "A", text: "Tolerable deviation rate", isCorrect: false, rationale: "A lower tolerable rate significantly increases sample size." },
        { label: "B", text: "Expected deviation rate", isCorrect: false, rationale: "A higher expected rate significantly increases sample size." },
        { label: "C", text: "Population size", isCorrect: true, rationale: "Correct — for large populations, population size has little effect." },
        { label: "D", text: "Acceptable risk of overreliance", isCorrect: false, rationale: "Lower acceptable risk significantly increases sample size." },
      ],
      explanation: "Sample size in attribute sampling is driven by the acceptable risk of overreliance, the tolerable deviation rate, and the expected deviation rate. Beyond a few thousand items, population size has little effect.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["attribute sampling", "sample size"],
    },
    {
      question: "An auditor samples items with a total book value of $100,000 and finds $2,000 of overstatements. The population's total book value is $1,000,000. Using the ratio approach, what is the projected misstatement?",
      options: [
        { label: "A", text: "$2,000", isCorrect: false, rationale: "This is the known misstatement in the sample only." },
        { label: "B", text: "$10,000", isCorrect: false, rationale: "This doesn't correctly scale the sample misstatement rate to the population." },
        { label: "C", text: "$20,000", isCorrect: true, rationale: "Correct — 2% misstatement rate × $1,000,000." },
        { label: "D", text: "$200,000", isCorrect: false, rationale: "This misplaces the decimal." },
      ],
      explanation: "The ratio approach projects the sample misstatement rate onto the population: $2,000 / $100,000 = 2%, and 2% × $1,000,000 = $20,000. The auditor then considers an allowance for sampling risk before comparing to tolerable misstatement.",
      difficulty: "EASY",
      questionType: "CALCULATION",
      tags: ["projected misstatement"],
    },
    {
      question: "In a PPS sample with a sampling interval of $10,000, an item with a recorded amount of $8,000 is found to have an audited amount of $6,000. What is the projected misstatement for this item?",
      options: [
        { label: "A", text: "$2,000", isCorrect: false, rationale: "This is the actual misstatement; items below the interval are projected using the tainting percentage." },
        { label: "B", text: "$2,500", isCorrect: true, rationale: "Correct — tainting of 25% ($2,000 / $8,000) × $10,000 interval." },
        { label: "C", text: "$10,000", isCorrect: false, rationale: "This assumes the whole interval is misstated." },
        { label: "D", text: "$8,000", isCorrect: false, rationale: "This is the recorded amount." },
      ],
      explanation: "For items smaller than the sampling interval, PPS projects misstatement using the tainting percentage: (recorded − audited) / recorded = 25%, multiplied by the interval: 25% × $10,000 = $2,500. For items equal to or larger than the interval, the actual misstatement is used without projection.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["PPS sampling", "tainting"],
    },
  ],

  "evidence-types-and-procedures": [
    {
      question: "An auditor selects shipping documents and traces them forward to recorded sales invoices in the sales journal. This procedure primarily tests which assertion?",
      options: [
        { label: "A", text: "Occurrence", isCorrect: false, rationale: "Occurrence is tested by vouching from the journal back to shipping documents." },
        { label: "B", text: "Completeness", isCorrect: true, rationale: "Correct — tracing from source documents to the records tests whether all shipments were recorded." },
        { label: "C", text: "Valuation", isCorrect: false, rationale: "This procedure does not test amounts or collectibility." },
        { label: "D", text: "Rights and obligations", isCorrect: false, rationale: "This procedure does not address ownership." },
      ],
      explanation: "Direction matters. Tracing from source documents forward to the accounting records tests completeness (were all transactions recorded?). Vouching from recorded entries back to supporting documents tests occurrence or existence (did recorded transactions really happen?).",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["tracing", "completeness"],
    },
    {
      question: "A cutoff bank statement is used primarily to:",
      options: [
        { label: "A", text: "Confirm the year-end bank balance with the bank", isCorrect: false, rationale: "The standard bank confirmation does that." },
        { label: "B", text: "Verify reconciling items on the year-end bank reconciliation, such as outstanding checks and deposits in transit", isCorrect: true, rationale: "Correct — the cutoff statement shows when those items actually cleared." },
        { label: "C", text: "Test the approval of cash disbursements", isCorrect: false, rationale: "Approval is tested by inspecting supporting documents." },
        { label: "D", text: "Detect unrecorded liabilities", isCorrect: false, rationale: "The search for unrecorded liabilities focuses on subsequent disbursements and unpaid invoices." },
      ],
      explanation: "A cutoff bank statement covers a short period after year-end and is sent directly to the auditor. It lets the auditor verify that outstanding checks and deposits in transit on the reconciliation clear in the following period, helping detect kiting and window dressing.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["cash", "cutoff bank statement"],
    },
    {
      question: "Management asks the auditor not to send a confirmation request to a particular customer. What should the auditor do?",
      options: [
        { label: "A", text: "Send the confirmation anyway without discussing it", isCorrect: false, rationale: "The auditor should first understand management's reasons." },
        { label: "B", text: "Inquire about management's reasons, seek evidence of their validity, and perform alternative procedures if the reasons are reasonable", isCorrect: true, rationale: "Correct — this is the required response." },
        { label: "C", text: "Automatically issue a qualified opinion", isCorrect: false, rationale: "A reasonable request, supported by alternative procedures, does not require modification." },
        { label: "D", text: "Withdraw from the engagement immediately", isCorrect: false, rationale: "Withdrawal is not the first step." },
      ],
      explanation: "If management refuses to allow a confirmation request, the auditor inquires about the reasons and evaluates their validity, considers the implications for the risk assessment (including fraud risk), and performs alternative procedures. If the refusal is unreasonable or alternative procedures are not possible, the auditor communicates with those charged with governance and considers the effect on the opinion.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["external confirmations"],
    },
  ],

  "analytical-procedures": [
    {
      question: "An auditor notes that the client's inventory turnover has declined significantly, while sales and industry conditions are stable. Which risk does this most likely indicate?",
      options: [
        { label: "A", text: "Understatement of inventory", isCorrect: false, rationale: "Declining turnover suggests inventory is growing relative to sales, pointing to overstatement." },
        { label: "B", text: "Overstatement of inventory, such as obsolete stock or fictitious items", isCorrect: true, rationale: "Correct — slower turnover can signal obsolete or overstated inventory." },
        { label: "C", text: "Understatement of sales", isCorrect: false, rationale: "Sales are stated to be stable." },
        { label: "D", text: "Overstatement of accounts payable", isCorrect: false, rationale: "Inventory turnover does not directly measure payables." },
      ],
      explanation: "Inventory turnover is cost of goods sold divided by average inventory. A decline without an operational explanation suggests inventory is accumulating — possibly obsolete, slow-moving, or overstated — and the auditor should focus on valuation and existence.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["ratio analysis", "inventory turnover"],
    },
    {
      question: "Average debt outstanding during the year was $2,000,000 at a 6% interest rate. Recorded interest expense is $150,000, and the auditor's threshold for investigating differences is $10,000. What should the auditor do?",
      options: [
        { label: "A", text: "Accept the recorded amount, since it is close to expectations", isCorrect: false, rationale: "The $30,000 difference exceeds the $10,000 threshold." },
        { label: "B", text: "Investigate the $30,000 difference between expected and recorded interest", isCorrect: true, rationale: "Correct — expected interest is $120,000, so the difference exceeds the threshold." },
        { label: "C", text: "Investigate a $20,000 difference", isCorrect: false, rationale: "The difference is $30,000." },
        { label: "D", text: "Propose an adjustment of $150,000", isCorrect: false, rationale: "The auditor first investigates the difference rather than assuming the entire amount is wrong." },
      ],
      explanation: "The auditor's expectation is $2,000,000 × 6% = $120,000. The $30,000 difference exceeds the threshold, so the auditor must investigate — for example, for unrecorded debt, rate changes, or misclassified charges — through inquiry corroborated by other evidence.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["substantive analytical procedures", "expectations"],
    },
    {
      question: "What is the purpose of analytical procedures performed near the end of the audit?",
      options: [
        { label: "A", text: "To obtain an understanding of the entity", isCorrect: false, rationale: "That is the purpose of risk assessment analytics." },
        { label: "B", text: "To help form an overall conclusion about whether the financial statements are consistent with the auditor's understanding of the entity", isCorrect: true, rationale: "Correct — final analytics assess overall reasonableness." },
        { label: "C", text: "To replace tests of details for material accounts", isCorrect: false, rationale: "Final analytics are not a substitute for substantive procedures." },
        { label: "D", text: "To test the operating effectiveness of controls", isCorrect: false, rationale: "Analytics do not test controls." },
      ],
      explanation: "Analytical procedures near the end of the audit help the auditor form an overall conclusion on whether the financial statements are consistent with its understanding of the entity. They may identify a previously unrecognized risk, which would require further procedures.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["final analytical procedures"],
    },
    {
      question: "An auditor estimates a hotel's room revenue by multiplying the number of rooms by the average occupancy rate, the average room rate, and the days in the year. This is an example of:",
      options: [
        { label: "A", text: "Trend analysis", isCorrect: false, rationale: "Trend analysis compares amounts over time." },
        { label: "B", text: "Ratio analysis", isCorrect: false, rationale: "Ratio analysis compares relationships between accounts." },
        { label: "C", text: "A reasonableness test", isCorrect: true, rationale: "Correct — it builds an expectation from operational and financial data." },
        { label: "D", text: "A test of controls", isCorrect: false, rationale: "This develops an expectation for a balance, not a test of controls." },
      ],
      explanation: "A reasonableness test develops an expectation using a model built from financial and nonfinancial data, such as occupancy and room rates. Because it uses independent operational data, it can produce a precise expectation.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["reasonableness test"],
    },
    {
      question: "When substantive analytical procedures are performed, the auditor's documentation must include all of the following EXCEPT:",
      options: [
        { label: "A", text: "The expectation and the factors considered in developing it", isCorrect: false, rationale: "This must be documented." },
        { label: "B", text: "The results of comparing the expectation to recorded amounts", isCorrect: false, rationale: "This must be documented." },
        { label: "C", text: "Additional procedures performed in response to significant unexpected differences", isCorrect: false, rationale: "This must be documented." },
        { label: "D", text: "A statement from management approving the auditor's expectation", isCorrect: true, rationale: "Correct — the expectation is developed by the auditor and needs no management approval." },
      ],
      explanation: "Documentation for substantive analytics includes the expectation and the factors considered in developing it (where not otherwise readily determinable), the results of the comparison, and any additional procedures performed and their results. Management does not approve the auditor's expectations.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["documentation", "analytical procedures"],
    },
  ],

  "auditing-accounting-estimates": [
    {
      question: "Testing management's estimate of inventory net realizable value by examining sales of the inventory after year-end, up to the report date, is most appropriate when:",
      options: [
        { label: "A", text: "The items are not expected to be sold for several years", isCorrect: false, rationale: "Subsequent events provide little evidence if the outcome won't occur before the report date." },
        { label: "B", text: "Sales of the items are expected to occur before the auditor's report date", isCorrect: true, rationale: "Correct — events up to the report date provide direct evidence about the estimate." },
        { label: "C", text: "Management has no process for developing the estimate", isCorrect: false, rationale: "That points to a control deficiency; it doesn't determine this approach." },
        { label: "D", text: "The estimate is immaterial", isCorrect: false, rationale: "Immaterial estimates may need little testing at all." },
      ],
      explanation: "SAS 143 allows three approaches, alone or combined: obtaining evidence from events occurring up to the report date, testing how management made the estimate, and developing the auditor's own point estimate or range. Subsequent events are most useful when they are expected to occur within that window.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["SAS 143", "subsequent events"],
    },
    {
      question: "Which condition is the strongest indicator of possible management bias in accounting estimates?",
      options: [
        { label: "A", text: "Estimates that were revised because new market data became available", isCorrect: false, rationale: "Changes driven by new information are appropriate." },
        { label: "B", text: "Changes in estimates or methods with no change in circumstances, in a direction that helps meet earnings targets", isCorrect: true, rationale: "Correct — unexplained changes that favor management's objectives indicate bias." },
        { label: "C", text: "Use of an external valuation specialist", isCorrect: false, rationale: "Using a specialist is not itself an indicator of bias." },
        { label: "D", text: "Estimates that differ from prior-year outcomes because of unexpected events", isCorrect: false, rationale: "Differences due to genuinely unforeseeable events do not indicate bias." },
      ],
      explanation: "Indicators of possible management bias include changes in estimates or methods where there is no change in circumstances, the selection of significant assumptions that produce a point estimate favorable to management's objectives, and consistently optimistic or pessimistic estimates.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["management bias"],
    },
    {
      question: "Fair value measurements based primarily on unobservable inputs (Level 3) generally have:",
      options: [
        { label: "A", text: "Lower estimation uncertainty than Level 1 measurements", isCorrect: false, rationale: "Level 1 uses quoted prices in active markets, the least uncertain inputs." },
        { label: "B", text: "Higher estimation uncertainty and greater susceptibility to management bias", isCorrect: true, rationale: "Correct — unobservable inputs require significant judgment." },
        { label: "C", text: "No need for audit procedures", isCorrect: false, rationale: "Level 3 measurements typically require more audit work." },
        { label: "D", text: "The same inherent risk as quoted prices", isCorrect: false, rationale: "Inherent risk is higher for judgmental measurements." },
      ],
      explanation: "The fair value hierarchy ranks inputs: Level 1 (quoted prices for identical assets in active markets), Level 2 (other observable inputs), and Level 3 (unobservable inputs). Level 3 measurements involve greater subjectivity and estimation uncertainty, which increases inherent risk.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["fair value", "estimation uncertainty"],
    },
    {
      question: "When the auditor develops a range to evaluate management's estimate, SAS No. 143 requires that the range:",
      options: [
        { label: "A", text: "Be as wide as possible to avoid proposing adjustments", isCorrect: false, rationale: "A wide range may fail to identify misstatements." },
        { label: "B", text: "Include only amounts supported by sufficient appropriate evidence that the auditor has evaluated as reasonable", isCorrect: true, rationale: "Correct — the range is narrowed until every outcome in it is reasonable." },
        { label: "C", text: "Be centered on management's point estimate", isCorrect: false, rationale: "The auditor develops the range independently." },
        { label: "D", text: "Equal materiality", isCorrect: false, rationale: "The range is based on evidence, not set to materiality." },
      ],
      explanation: "An auditor's range should include only amounts that are supported by sufficient appropriate evidence and that the auditor has evaluated as reasonable in the context of the applicable framework. Ranges wider than materiality may not be appropriate.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["SAS 143", "auditor's range"],
    },
    {
      question: "Management's estimate of a warranty liability is $500,000. The auditor, using sufficient appropriate evidence, develops a point estimate of $460,000. What misstatement should the auditor accumulate?",
      options: [
        { label: "A", text: "$0, because both amounts are estimates", isCorrect: false, rationale: "A difference from the auditor's point estimate is a misstatement." },
        { label: "B", text: "$40,000 overstatement", isCorrect: true, rationale: "Correct — the difference between management's estimate and the auditor's point estimate." },
        { label: "C", text: "$460,000", isCorrect: false, rationale: "This is the auditor's estimate, not the misstatement." },
        { label: "D", text: "$40,000 understatement", isCorrect: false, rationale: "Management's estimate is higher than the auditor's, so the liability is overstated." },
      ],
      explanation: "When the auditor develops a point estimate, the misstatement is the difference between that point estimate and management's estimate. Here the warranty liability is overstated by $40,000.",
      difficulty: "EASY",
      questionType: "CALCULATION",
      tags: ["point estimate", "misstatement"],
    },
  ],

  "related-parties-and-going-concern": [
    {
      question: "Under GAAS, over what period does the auditor evaluate whether there is substantial doubt about a nonissuer's ability to continue as a going concern (when the framework is US GAAP)?",
      options: [
        { label: "A", text: "Twelve months from the balance sheet date", isCorrect: false, rationale: "This was the older period; the current one runs from the issuance date." },
        { label: "B", text: "One year after the date the financial statements are issued or available to be issued", isCorrect: true, rationale: "Correct — this matches the period in ASC 205-40." },
        { label: "C", text: "Three years after the balance sheet date", isCorrect: false, rationale: "No framework uses this period." },
        { label: "D", text: "The remaining term of the entity's debt", isCorrect: false, rationale: "Debt terms are a factor to consider, not the evaluation period." },
      ],
      explanation: "For entities reporting under US GAAP, the going concern look-forward period is one year after the date the financial statements are issued (or available to be issued). The auditor's evaluation uses the same period as the framework.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["going concern"],
    },
    {
      question: "Which management plan is LEAST likely to mitigate substantial doubt about going concern?",
      options: [
        { label: "A", text: "Selling nonessential assets", isCorrect: false, rationale: "Asset sales can raise needed cash." },
        { label: "B", text: "Negotiating to restructure or extend debt payments", isCorrect: false, rationale: "Debt restructuring can relieve near-term obligations." },
        { label: "C", text: "Reducing or delaying discretionary expenditures", isCorrect: false, rationale: "Cutting spending preserves cash." },
        { label: "D", text: "Borrowing heavily to fund an expansion into a new market", isCorrect: true, rationale: "Correct — this increases obligations and risk rather than easing liquidity." },
      ],
      explanation: "Management's plans that may mitigate substantial doubt include disposing of assets, borrowing or restructuring debt, reducing or delaying expenditures, and increasing equity. The auditor evaluates whether each plan is probable of being effectively implemented and would mitigate the conditions. New debt-financed expansion usually worsens liquidity.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["going concern", "management's plans"],
    },
    {
      question: "Conditions raised substantial doubt about going concern, but the auditor concludes management's plans alleviate it, and the plans are adequately disclosed. How does this affect the auditor's report?",
      options: [
        { label: "A", text: "A separate 'Substantial Doubt About the Entity's Ability to Continue as a Going Concern' section is required", isCorrect: false, rationale: "That section is required only when substantial doubt remains." },
        { label: "B", text: "An unmodified opinion is issued with no required going concern section, although the auditor may include an emphasis-of-matter paragraph", isCorrect: true, rationale: "Correct — no going concern section is required when the doubt is alleviated." },
        { label: "C", text: "A qualified opinion is required", isCorrect: false, rationale: "There is no misstatement or scope limitation." },
        { label: "D", text: "A disclaimer of opinion is required", isCorrect: false, rationale: "A disclaimer is not required for going concern matters." },
      ],
      explanation: "If substantial doubt is alleviated by management's plans, the auditor ensures adequate disclosure but is not required to add a going concern section. The auditor may still emphasize the matter. If substantial doubt remains, a separate going concern section is required.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["going concern", "auditor's report"],
    },
    {
      question: "Management discloses that related party transactions were conducted on terms equivalent to arm's-length transactions but cannot support this. Management refuses to change the disclosure. The auditor should:",
      options: [
        { label: "A", text: "Issue an unmodified opinion with an emphasis-of-matter paragraph", isCorrect: false, rationale: "An unsupported assertion is a misstatement, which emphasis cannot fix." },
        { label: "B", text: "Issue a qualified or adverse opinion because of the unsupported representation", isCorrect: true, rationale: "Correct — an unsubstantiated disclosure is a departure from GAAP." },
        { label: "C", text: "Ignore it, since disclosures are management's responsibility", isCorrect: false, rationale: "The auditor's opinion covers disclosures." },
        { label: "D", text: "Disclaim an opinion", isCorrect: false, rationale: "This is a misstatement issue, not a scope limitation." },
      ],
      explanation: "An arm's-length representation may be made only if it can be substantiated. If management cannot support it and won't modify the disclosure, the statements contain a misstatement, leading to a qualified or adverse opinion depending on materiality and pervasiveness.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["related parties", "disclosure"],
    },
    {
      question: "Substantial doubt about going concern remains after considering management's plans, and management refuses to make the required disclosures. What opinion is appropriate?",
      options: [
        { label: "A", text: "Unmodified, with a going concern section", isCorrect: false, rationale: "That applies when disclosure is adequate." },
        { label: "B", text: "Qualified or adverse, because of inadequate disclosure", isCorrect: true, rationale: "Correct — missing going concern disclosure is a departure from the framework." },
        { label: "C", text: "Disclaimer, because of a scope limitation", isCorrect: false, rationale: "The problem is inadequate disclosure, not lack of evidence." },
        { label: "D", text: "Unmodified, with an other-matter paragraph", isCorrect: false, rationale: "Other-matter paragraphs don't address misstatements." },
      ],
      explanation: "When substantial doubt remains but disclosure is inadequate, the financial statements are materially misstated. The auditor expresses a qualified or adverse opinion, depending on how pervasive the effect is, and describes the substantial doubt in the basis for opinion section.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["going concern", "modified opinions"],
    },
  ],

  "it-controls-in-audit": [
    {
      question: "An application control that rejects a payroll input showing more than 80 hours worked in a week is an example of a:",
      options: [
        { label: "A", text: "Hash total", isCorrect: false, rationale: "A hash total sums a nonfinancial field to check batch completeness." },
        { label: "B", text: "Limit (reasonableness) check", isCorrect: true, rationale: "Correct — it rejects values outside a predetermined limit." },
        { label: "C", text: "Check digit", isCorrect: false, rationale: "A check digit validates identification numbers." },
        { label: "D", text: "Change management control", isCorrect: false, rationale: "Change management is an IT general control." },
      ],
      explanation: "Input edit checks include limit/reasonableness checks (values within set bounds), validity checks (values in an approved list), field checks (correct data type), and check digits. They are application controls that prevent errors from entering the system.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["application controls", "edit checks"],
    },
    {
      question: "Which is an IT general control over program changes?",
      options: [
        { label: "A", text: "A three-way match of purchase order, receiving report, and invoice", isCorrect: false, rationale: "This is an application control." },
        { label: "B", text: "Requiring program changes to be tested and approved by users before being moved into production", isCorrect: true, rationale: "Correct — change management is an IT general control." },
        { label: "C", text: "A credit limit check on customer orders", isCorrect: false, rationale: "This is an application control." },
        { label: "D", text: "Reconciling the sales subledger to the general ledger", isCorrect: false, rationale: "This is a manual detective control." },
      ],
      explanation: "IT general controls support the continued functioning of application controls across systems. Key areas are access to programs and data, program changes, program development, and computer operations. Without effective change management, the auditor cannot rely on automated controls operating consistently.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["ITGCs", "change management"],
    },
    {
      question: "An auditor tested an automated control last year. ITGCs over program changes are effective, and there is evidence the control has not changed. What does this allow?",
      options: [
        { label: "A", text: "The control need never be tested again", isCorrect: false, rationale: "Reliance on older evidence is limited and must be re-established periodically." },
        { label: "B", text: "The auditor may use a benchmarking strategy, relying on prior testing without fully retesting the control this year", isCorrect: true, rationale: "Correct — effective change controls support continued reliance on an unchanged automated control." },
        { label: "C", text: "Substantive procedures are no longer required", isCorrect: false, rationale: "Substantive procedures are required for material items regardless." },
        { label: "D", text: "The auditor must test the control on a large sample", isCorrect: false, rationale: "Automated controls operate consistently, so a large sample adds little." },
      ],
      explanation: "Automated controls perform consistently unless the program changes. When ITGCs — especially change management — are effective and the control hasn't changed, the auditor can benchmark: rely on prior testing and verify there have been no changes, rather than fully retesting.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["automated controls", "benchmarking"],
    },
    {
      question: "Which task would an auditor most likely perform with generalized audit software?",
      options: [
        { label: "A", text: "Observing the client's physical inventory count", isCorrect: false, rationale: "Observation is a physical procedure." },
        { label: "B", text: "Searching an entire vendor payment file for duplicate invoice numbers", isCorrect: true, rationale: "Correct — GAS can analyze entire populations quickly." },
        { label: "C", text: "Interviewing the accounts payable clerk", isCorrect: false, rationale: "Inquiry is not performed by software." },
        { label: "D", text: "Evaluating the tone at the top", isCorrect: false, rationale: "This requires judgment about the control environment." },
      ],
      explanation: "Generalized audit software and data analytics let the auditor work directly with client data: recalculating totals, selecting samples, identifying duplicates or gaps, aging balances, and comparing files. It enables testing of entire populations rather than samples.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["data analytics", "generalized audit software"],
    },
    {
      question: "A batch of vendor invoices is entered with a control total equal to the sum of the vendor account numbers. This total is known as a:",
      options: [
        { label: "A", text: "Record count", isCorrect: false, rationale: "A record count is the number of documents in the batch." },
        { label: "B", text: "Financial total", isCorrect: false, rationale: "A financial total sums a monetary field, such as invoice amounts." },
        { label: "C", text: "Hash total", isCorrect: true, rationale: "Correct — a sum of a field with no financial meaning, used to detect changes or losses in the batch." },
        { label: "D", text: "Limit check", isCorrect: false, rationale: "A limit check tests individual values against a threshold." },
      ],
      explanation: "Batch controls help ensure all transactions are processed completely and accurately. A hash total adds up a nonfinancial field, such as account numbers; if any record is lost, added, or altered, the recomputed total won't match.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["batch controls", "hash total"],
    },
  ],

  "group-audits-and-using-others-work": [
    {
      question: "In a group audit, who is responsible for the direction, supervision, and performance of the group audit engagement and for the auditor's report on the group financial statements?",
      options: [
        { label: "A", text: "Each component auditor for its component", isCorrect: false, rationale: "Component auditors report to the group engagement team." },
        { label: "B", text: "The group engagement partner", isCorrect: true, rationale: "Correct — overall responsibility rests with the group engagement partner." },
        { label: "C", text: "The group's audit committee", isCorrect: false, rationale: "Those charged with governance oversee reporting; they don't perform the audit." },
        { label: "D", text: "The client's internal audit function", isCorrect: false, rationale: "Internal audit may assist but carries no responsibility for the opinion." },
      ],
      explanation: "The group engagement partner is responsible for the group audit, including its direction, supervision, and performance, and for the auditor's report. That responsibility includes determining how component auditors' work will be used.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["group audits"],
    },
    {
      question: "Making reference to a component auditor in the group auditor's report is NOT appropriate when:",
      options: [
        { label: "A", text: "The component auditor performed an audit of the component's financial statements in accordance with GAAS", isCorrect: false, rationale: "This is a condition that permits reference." },
        { label: "B", text: "The component auditor issued an unmodified opinion", isCorrect: false, rationale: "Reference is permitted when the component report is unmodified." },
        { label: "C", text: "The component auditor performed only specified procedures rather than an audit of the component's financial statements", isCorrect: true, rationale: "Correct — reference requires that the component auditor issued a report on audited component financial statements." },
        { label: "D", text: "The component is significant to the group", isCorrect: false, rationale: "Significance alone does not prohibit reference." },
      ],
      explanation: "Reference is appropriate only when the component auditor has audited the component's financial statements under relevant standards and issued a report. If the component auditor performed only limited or specified procedures, the group auditor must assume responsibility for that work rather than refer to it.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["making reference", "component auditors"],
    },
    {
      question: "The group engagement team learns that a component auditor is not independent of the group. What follows?",
      options: [
        { label: "A", text: "The group auditor may make reference to the component auditor's report", isCorrect: false, rationale: "A non-independent auditor's work cannot be referred to." },
        { label: "B", text: "The group auditor may not use the component auditor's work and must obtain sufficient appropriate evidence about the component another way", isCorrect: true, rationale: "Correct — independence is a prerequisite for using a component auditor's work." },
        { label: "C", text: "The group auditor must disclaim an opinion", isCorrect: false, rationale: "The group auditor can perform the work itself or use another auditor." },
        { label: "D", text: "Nothing, as long as the component auditor is competent", isCorrect: false, rationale: "Competence doesn't cure a lack of independence." },
      ],
      explanation: "A component auditor must meet the independence requirements relevant to the group audit. If it does not, the group engagement team cannot use its work or make reference to its report, and must obtain evidence about the component's financial information itself or through another auditor.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["component auditors", "independence"],
    },
    {
      question: "The external auditor may NOT use internal auditors to provide direct assistance on which of the following?",
      options: [
        { label: "A", text: "Routine tests of details in a low-risk area", isCorrect: false, rationale: "Direct assistance on low-judgment, lower-risk work is permitted." },
        { label: "B", text: "Procedures involving significant judgments or high assessed risks of material misstatement", isCorrect: true, rationale: "Correct — these must be performed by the external auditor." },
        { label: "C", text: "Gathering documents for the external auditor", isCorrect: false, rationale: "Clerical assistance is acceptable." },
        { label: "D", text: "Performing tests of controls under the external auditor's direction and review", isCorrect: false, rationale: "This can be permitted in appropriate circumstances." },
      ],
      explanation: "Internal auditors providing direct assistance should not perform procedures that involve significant judgment, relate to higher assessed risks where judgment is more than limited, involve work in which they were previously involved, or involve decisions the external auditor must make. The external auditor directs, supervises, and reviews their work.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["internal audit", "direct assistance"],
    },
    {
      question: "When the auditor uses the work of a management's specialist (such as an actuary engaged by the client) as audit evidence, the auditor should evaluate the specialist's:",
      options: [
        { label: "A", text: "Competence, capabilities, and objectivity", isCorrect: true, rationale: "Correct — these are required evaluations when using a management's specialist's work." },
        { label: "B", text: "Independence of the client, which must be the same as the auditor's", isCorrect: false, rationale: "A management's specialist is engaged by the client and need not meet auditor independence rules; objectivity is evaluated instead." },
        { label: "C", text: "Fee arrangement only", isCorrect: false, rationale: "Fees may bear on objectivity but are not the only consideration." },
        { label: "D", text: "Nothing, because management is responsible for the specialist", isCorrect: false, rationale: "The auditor must evaluate evidence it relies on." },
      ],
      explanation: "When using information produced by a management's specialist, the auditor evaluates the specialist's competence, capabilities, and objectivity; obtains an understanding of the specialist's work; and evaluates the appropriateness of that work as audit evidence for the relevant assertion.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["specialists"],
    },
  ],

  "written-representations-and-completing-the-audit": [
    {
      question: "Who should sign the written representation letter that management provides to the auditor?",
      options: [
        { label: "A", text: "The audit engagement partner", isCorrect: false, rationale: "Representations come from management, not the auditor." },
        { label: "B", text: "Members of management with overall responsibility for financial and operating matters, such as the CEO and CFO", isCorrect: true, rationale: "Correct — those responsible for the financial statements and knowledgeable about them sign." },
        { label: "C", text: "The client's legal counsel", isCorrect: false, rationale: "Counsel responds to the legal letter, not the representation letter." },
        { label: "D", text: "A junior accountant who prepared the trial balance", isCorrect: false, rationale: "Representations must come from those with overall responsibility." },
      ],
      explanation: "Written representations are requested from management with appropriate responsibilities for the financial statements and knowledge of the matters concerned — normally the chief executive officer and chief financial officer. The letter is addressed to the auditor and dated as of the auditor's report date.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["representation letter"],
    },
    {
      question: "After the report has been released, the auditor becomes aware of a fact that existed at the report date and would have changed the report. Users are likely still relying on it. Management refuses to revise the financial statements. What should the auditor do?",
      options: [
        { label: "A", text: "Nothing, because the report has already been released", isCorrect: false, rationale: "The auditor has a responsibility for subsequently discovered facts that would have affected the report." },
        { label: "B", text: "Notify management and those charged with governance, and take action to seek to prevent future reliance on the report", isCorrect: true, rationale: "Correct — including notifying regulators or known users as appropriate, often after consulting legal counsel." },
        { label: "C", text: "Issue a new report without discussing it with management", isCorrect: false, rationale: "The auditor first discusses the matter with management." },
        { label: "D", text: "Record an adjustment in the next year's audit", isCorrect: false, rationale: "The problem concerns the already-issued statements." },
      ],
      explanation: "For facts discovered after the report release date that would have caused the report to change, the auditor discusses them with management. If management won't revise the statements, the auditor notifies those charged with governance and takes steps to prevent further reliance, such as notifying regulators or known users, usually with legal advice.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["subsequent discovery of facts"],
    },
    {
      question: "After the report release date, the auditor discovers that a planned procedure was omitted. The auditor believes the omission impairs its ability to support the opinion, and users are still relying on the report. The auditor should:",
      options: [
        { label: "A", text: "Withdraw the report immediately", isCorrect: false, rationale: "The first step is to try to perform the omitted procedure." },
        { label: "B", text: "Promptly perform the omitted procedure or alternative procedures", isCorrect: true, rationale: "Correct — this can provide a satisfactory basis for the opinion." },
        { label: "C", text: "Ignore the omission because the audit is complete", isCorrect: false, rationale: "An omission that impairs the basis for the opinion must be addressed." },
        { label: "D", text: "Disclose the omission in next year's report", isCorrect: false, rationale: "It must be addressed now, not deferred." },
      ],
      explanation: "When an omitted procedure is discovered after the report is released, the auditor assesses its importance. If it impairs the ability to support the opinion and users are relying on the report, the auditor promptly performs the omitted procedure or alternatives. If that reveals facts that would have changed the report, subsequent-discovery guidance applies.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["omitted procedures"],
    },
    {
      question: "The auditor's report should be dated no earlier than the date on which:",
      options: [
        { label: "A", text: "The fieldwork began", isCorrect: false, rationale: "The report date marks the end of evidence gathering, not the start." },
        { label: "B", text: "The auditor obtained sufficient appropriate evidence, including evidence that the statements were prepared and management asserted responsibility for them", isCorrect: true, rationale: "Correct — this is the earliest permissible report date." },
        { label: "C", text: "The financial statements are filed with a regulator", isCorrect: false, rationale: "Filing can occur after the report date." },
        { label: "D", text: "The client pays the audit fee", isCorrect: false, rationale: "Payment has no bearing on the report date." },
      ],
      explanation: "The report date is no earlier than when the auditor has sufficient appropriate evidence on which to base the opinion, including evidence that the audit documentation has been reviewed, all statements and disclosures have been prepared, and management has asserted responsibility for them. The representation letter is dated the same day.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["report date"],
    },
    {
      question: "A letter of audit inquiry sent to the client's external legal counsel is the auditor's primary means of:",
      options: [
        { label: "A", text: "Identifying all contracts the client has signed", isCorrect: false, rationale: "The legal letter focuses on litigation, claims, and assessments." },
        { label: "B", text: "Corroborating information provided by management about litigation, claims, and assessments", isCorrect: true, rationale: "Correct — the letter provides corroborating evidence from counsel." },
        { label: "C", text: "Obtaining a legal opinion on the fairness of the financial statements", isCorrect: false, rationale: "Lawyers don't opine on financial statement fairness." },
        { label: "D", text: "Replacing the need for inquiry of management", isCorrect: false, rationale: "The letter corroborates, not replaces, management's information." },
      ],
      explanation: "Management is the primary source of information about litigation, claims, and assessments. The auditor asks management to send a letter of inquiry to counsel, who responds directly to the auditor. A lawyer's refusal to respond is a scope limitation that may lead to a qualified opinion or disclaimer.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["legal letter", "litigation"],
    },
  ],

  "audit-reports": [
    {
      question: "The auditor concludes that other information in the client's annual report contains a material misstatement, and management refuses to correct it. The audited financial statements themselves are fairly presented. How is this reported under SAS No. 137?",
      options: [
        { label: "A", text: "The auditor issues an adverse opinion on the financial statements", isCorrect: false, rationale: "The financial statements are fairly presented, so the opinion is unaffected." },
        { label: "B", text: "The auditor's report includes an Other Information section describing the uncorrected material misstatement", isCorrect: true, rationale: "Correct — the opinion stays unmodified and the misstatement of the other information is described." },
        { label: "C", text: "The auditor ignores the matter because other information is not audited", isCorrect: false, rationale: "The auditor must read and consider other information." },
        { label: "D", text: "The auditor issues a qualified opinion", isCorrect: false, rationale: "A misstatement in other information does not qualify the opinion on the financial statements." },
      ],
      explanation: "The auditor reads other information in the annual report for material inconsistencies with the financial statements or the auditor's knowledge. If an uncorrected material misstatement of the other information remains, the auditor describes it in the Other Information section of the report and may consider withdrawing.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["other information", "SAS 137"],
    },
    {
      question: "Required supplementary information (RSI) prescribed by GASB is omitted by the client. The basic financial statements are fairly presented. What type of report should the auditor issue?",
      options: [
        { label: "A", text: "A qualified opinion because of the omission", isCorrect: false, rationale: "RSI is not part of the basic financial statements, so its omission doesn't affect the opinion." },
        { label: "B", text: "An unmodified opinion with a paragraph noting that the RSI was omitted", isCorrect: true, rationale: "Correct — the omission is reported in a separate section; the opinion is unaffected." },
        { label: "C", text: "An adverse opinion", isCorrect: false, rationale: "The basic statements are fairly presented." },
        { label: "D", text: "A disclaimer of opinion", isCorrect: false, rationale: "The auditor has sufficient evidence on the basic statements." },
      ],
      explanation: "RSI accompanies but is not part of the basic financial statements. When it is omitted, incomplete, or not presented in accordance with guidelines, the auditor's opinion remains unmodified and the auditor adds a section (an other-matter paragraph) describing the issue.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["required supplementary information"],
    },
    {
      question: "In an audit of a nonissuer, when are key audit matters (KAMs) communicated in the auditor's report?",
      options: [
        { label: "A", text: "In every audit report", isCorrect: false, rationale: "KAMs are not mandatory for nonissuers." },
        { label: "B", text: "Only when the auditor is engaged to communicate them or is required to by law or regulation", isCorrect: true, rationale: "Correct — AU-C 701 applies only when engaged or required." },
        { label: "C", text: "Only when the opinion is modified", isCorrect: false, rationale: "Modified opinions are addressed in the basis for opinion section, not as KAMs." },
        { label: "D", text: "Never — KAMs are a PCAOB concept", isCorrect: false, rationale: "PCAOB uses 'critical audit matters'; KAMs are the AICPA equivalent." },
      ],
      explanation: "For nonissuers, KAMs are communicated only when the auditor is engaged to do so or required by law or regulation. For issuers, PCAOB standards require critical audit matters (CAMs) in most audits.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["key audit matters"],
    },
  ],

  "reviews-compilations-and-aup": [
    {
      question: "A review report under SSARS expresses:",
      options: [
        { label: "A", text: "Reasonable assurance that the financial statements are fairly presented", isCorrect: false, rationale: "Reasonable assurance applies to audits." },
        { label: "B", text: "Limited assurance: the accountant is not aware of any material modifications that should be made", isCorrect: true, rationale: "Correct — a review provides limited assurance, expressed as a conclusion." },
        { label: "C", text: "No assurance of any kind", isCorrect: false, rationale: "Compilations and preparation engagements provide no assurance." },
        { label: "D", text: "An opinion on internal control", isCorrect: false, rationale: "Reviews do not address internal control effectiveness." },
      ],
      explanation: "A review under SSARS provides limited assurance, based primarily on analytical procedures and inquiries. The report states that, based on the review, the accountant is not aware of any material modifications that should be made for the statements to conform with the framework.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["review engagements"],
    },
    {
      question: "An accountant who is not independent of the client performs a compilation engagement. What must the compilation report include?",
      options: [
        { label: "A", text: "Nothing different — independence doesn't matter in compilations", isCorrect: false, rationale: "Lack of independence must be disclosed in the report." },
        { label: "B", text: "A statement that the accountant is not independent, with the reasons optionally described", isCorrect: true, rationale: "Correct — the lack of independence must be disclosed; describing reasons is optional." },
        { label: "C", text: "A disclaimer of opinion replacing the compilation report", isCorrect: false, rationale: "A compilation report is still issued." },
        { label: "D", text: "Nothing, because the accountant must decline the engagement", isCorrect: false, rationale: "Compilations may be performed without independence." },
      ],
      explanation: "Independence is not required for a compilation, but if the accountant is not independent, the report must include a final paragraph saying so. The accountant may describe the reasons, but if it does, all of them must be included.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["compilation", "independence"],
    },
    {
      question: "Which is required in a review engagement but NOT in a compilation engagement under SSARS?",
      options: [
        { label: "A", text: "An engagement letter", isCorrect: false, rationale: "Both engagements require a written engagement letter." },
        { label: "B", text: "A written management representation letter", isCorrect: true, rationale: "Correct — representations are required in a review but not in a compilation." },
        { label: "C", text: "Reading the financial statements for obvious material misstatements", isCorrect: false, rationale: "This is performed in both." },
        { label: "D", text: "Knowledge of the applicable financial reporting framework", isCorrect: false, rationale: "Both require this." },
      ],
      explanation: "Reviews require analytical procedures, inquiries, and a written representation letter. Compilations require an engagement letter and a read of the statements, but no inquiry, analytics, or representation letter because no assurance is given.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["review vs compilation"],
    },
    {
      question: "Under SSAE No. 19, who must acknowledge that the agreed-upon procedures are appropriate for the intended purpose of the engagement?",
      options: [
        { label: "A", text: "Every user of the report", isCorrect: false, rationale: "SSAE 19 removed the requirement for all users to agree to the procedures." },
        { label: "B", text: "The engaging party", isCorrect: true, rationale: "Correct — the engaging party acknowledges appropriateness before the report is issued." },
        { label: "C", text: "The practitioner alone", isCorrect: false, rationale: "The practitioner does not take responsibility for the appropriateness of procedures." },
        { label: "D", text: "The AICPA", isCorrect: false, rationale: "The AICPA has no engagement-level role." },
      ],
      explanation: "SSAE No. 19 made AUP engagements more flexible: the engaging party must acknowledge that the procedures are appropriate, procedures can be developed during the engagement, and the report may be general use unless the practitioner restricts it.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["agreed-upon procedures", "SSAE 19"],
    },
  ],

  "attestation-and-soc-engagements": [
    {
      question: "How does a review engagement under the attestation standards (SSAEs) differ from an examination?",
      options: [
        { label: "A", text: "A review provides reasonable assurance; an examination provides limited assurance", isCorrect: false, rationale: "It is the other way around." },
        { label: "B", text: "A review provides limited assurance, usually expressed as a conclusion; an examination provides reasonable assurance, expressed as an opinion", isCorrect: true, rationale: "Correct — the level of assurance and the form of the report differ." },
        { label: "C", text: "Neither provides any assurance", isCorrect: false, rationale: "Both are assurance engagements." },
        { label: "D", text: "Only examinations require independence", isCorrect: false, rationale: "Both examinations and reviews require independence." },
      ],
      explanation: "An examination provides reasonable assurance and results in an opinion. A review provides limited assurance, based mainly on inquiry and analytical procedures, and results in a conclusion about whether the practitioner is aware of material modifications needed. Both require independence.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["attestation", "examination vs review"],
    },
    {
      question: "Before accepting an attestation engagement, the practitioner must determine that the criteria to be used are:",
      options: [
        { label: "A", text: "Issued by the FASB", isCorrect: false, rationale: "Many attestation criteria come from other sources." },
        { label: "B", text: "Suitable and available to intended users", isCorrect: true, rationale: "Correct — both conditions must be met." },
        { label: "C", text: "Approved by the engaging party's lawyers", isCorrect: false, rationale: "Legal approval is not a precondition." },
        { label: "D", text: "Identical to GAAP", isCorrect: false, rationale: "Criteria depend on the subject matter." },
      ],
      explanation: "Criteria are the benchmarks used to measure or evaluate the subject matter. Suitable criteria are relevant, objective, measurable, and complete. They must also be available to intended users — publicly, in the report, or understood by them.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["attestation", "criteria"],
    },
    {
      question: "A service organization uses a subservice organization. Under the carve-out method, the SOC report:",
      options: [
        { label: "A", text: "Includes the subservice organization's controls in the scope of the report", isCorrect: false, rationale: "That describes the inclusive method." },
        { label: "B", text: "Excludes the subservice organization's controls from the scope, while describing the services it performs", isCorrect: true, rationale: "Correct — carved-out controls are not tested by the service auditor." },
        { label: "C", text: "Cannot be used by user auditors", isCorrect: false, rationale: "User auditors can use it but may need evidence about the subservice organization separately." },
        { label: "D", text: "Is a SOC 3 report", isCorrect: false, rationale: "The carve-out method can apply to SOC 1 or SOC 2 reports." },
      ],
      explanation: "Under the carve-out method, the service organization's description identifies the services performed by the subservice organization but excludes its controls from the scope of testing. Under the inclusive method, the subservice organization's controls are included. With a carve-out, user auditors may need to obtain evidence about the subservice organization separately.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SOC reports", "subservice organizations"],
    },
    {
      question: "Which SOC report is a general-use report designed for broad distribution, such as on a company's website?",
      options: [
        { label: "A", text: "SOC 1 Type 2", isCorrect: false, rationale: "SOC 1 reports are restricted to user entities and their auditors." },
        { label: "B", text: "SOC 2 Type 2", isCorrect: false, rationale: "SOC 2 reports are generally restricted to knowledgeable users." },
        { label: "C", text: "SOC 3", isCorrect: true, rationale: "Correct — SOC 3 reports are general use and omit the detailed description of tests and results." },
        { label: "D", text: "SOC 1 Type 1", isCorrect: false, rationale: "SOC 1 reports are restricted." },
      ],
      explanation: "SOC 3 reports address the same Trust Services Criteria as SOC 2 but are general-use reports without the detailed description of controls, tests, and results. They are often used for marketing purposes.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["SOC 3"],
    },
  ],
};
