import type { McqBank } from "./types";

/** AUD question bank — topics 10 through 18. */
export const audBankB: McqBank = {
  "analytical-procedures": [
    {
      question: "Analytical procedures are REQUIRED in which stages of the audit?",
      options: [
        { label: "A", text: "Planning and substantive testing", isCorrect: false, rationale: "Use as a substantive procedure is optional, not required." },
        { label: "B", text: "Planning and the final overall review", isCorrect: true, rationale: "Correct — analytical procedures are required as a risk assessment procedure and again near the end of the audit." },
        { label: "C", text: "Substantive testing and the final review", isCorrect: false, rationale: "Substantive use is optional; planning use is required." },
        { label: "D", text: "All three stages", isCorrect: false, rationale: "The substantive stage is the one where their use is at the auditor's discretion." },
      ],
      explanation: "Analytical procedures are required during planning, to identify unusual relationships and areas of higher risk, and near the end of the audit, to form an overall conclusion about whether the statements are consistent with the auditor's understanding. Using them as substantive procedures during fieldwork is optional.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["analytical procedures"],
    },
    {
      question: "Substantive analytical procedures are most effective and efficient when:",
      options: [
        { label: "A", text: "The account balance is subject to significant management judgment", isCorrect: false, rationale: "Judgmental accounts have less predictable relationships, weakening analytical evidence." },
        { label: "B", text: "The relationship being tested is plausible and predictable", isCorrect: true, rationale: "Correct — predictable relationships allow the auditor to develop a precise expectation, making deviations meaningful." },
        { label: "C", text: "The account is composed of many non-recurring transactions", isCorrect: false, rationale: "Non-recurring items break the stable relationships analytics depend on." },
        { label: "D", text: "Internal controls over the account are weak", isCorrect: false, rationale: "Weak controls undermine the reliability of the data used in the analysis." },
      ],
      explanation: "Substantive analytical procedures work best where relationships are plausible and predictable — interest expense against average debt, or payroll against headcount, for example. They are least effective for judgmental or non-routine accounts. The auditor must also assess the reliability of the underlying data before relying on the results.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["analytical procedures", "substantive"],
    },
    {
      question: "An auditor computes the gross margin percentage and finds it rose from 32% to 41% with no change in the business. The auditor should:",
      options: [
        { label: "A", text: "Accept the change as favorable operating performance", isCorrect: false, rationale: "Unexplained fluctuations require investigation, not acceptance." },
        { label: "B", text: "Investigate the fluctuation and corroborate management's explanation with other evidence", isCorrect: true, rationale: "Correct — significant unexpected differences must be investigated and explanations corroborated." },
        { label: "C", text: "Immediately conclude that fraud has occurred", isCorrect: false, rationale: "An unexpected fluctuation is a risk indicator, not proof of fraud." },
        { label: "D", text: "Reduce substantive testing because the analytic was performed", isCorrect: false, rationale: "An unexplained variance increases rather than decreases the required work." },
      ],
      explanation: "When analytical procedures identify fluctuations inconsistent with other information or that differ significantly from expected values, the auditor investigates by inquiring of management and obtaining corroborating audit evidence. Management's explanation alone is insufficient — a rising margin with no operational change could signal overstated inventory or understated cost of sales.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["analytical procedures", "investigation"],
    },
    {
      question: "Which factor most improves the precision of an auditor's expectation in a substantive analytical procedure?",
      options: [
        { label: "A", text: "Using annual rather than monthly data", isCorrect: false, rationale: "Aggregated annual data can mask offsetting misstatements; disaggregation improves precision." },
        { label: "B", text: "Disaggregating the data by month, product line, or location", isCorrect: true, rationale: "Correct — disaggregation reduces the chance that offsetting variances hide a misstatement." },
        { label: "C", text: "Relying on data prepared solely by client management without testing", isCorrect: false, rationale: "Untested data reduces the reliability of the entire procedure." },
        { label: "D", text: "Widening the threshold for investigating differences", isCorrect: false, rationale: "A wider threshold makes the procedure less sensitive to misstatement." },
      ],
      explanation: "Precision determines how much assurance an analytical procedure provides. Disaggregated data — by month, segment, or location — produces sharper expectations because offsetting fluctuations cannot conceal one another. Reliable, independently corroborated source data and a tight investigation threshold also increase precision.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["analytical procedures", "precision"],
    },
  ],

  "auditing-accounting-estimates": [
    {
      question: "When auditing an accounting estimate, the auditor may do all of the following EXCEPT:",
      options: [
        { label: "A", text: "Test how management made the estimate and the data on which it is based", isCorrect: false, rationale: "This is one of the standard approaches to auditing estimates." },
        { label: "B", text: "Develop an independent point estimate or range to evaluate management's estimate", isCorrect: false, rationale: "This is a recognized approach." },
        { label: "C", text: "Review subsequent events and transactions that provide evidence about the estimate", isCorrect: false, rationale: "This is a recognized approach." },
        { label: "D", text: "Determine the estimate on management's behalf and record it in the accounts", isCorrect: true, rationale: "Correct — making the estimate for the client is a management responsibility and would impair independence." },
      ],
      explanation: "The auditor may test management's process, develop an independent estimate for comparison, or review subsequent events bearing on the estimate. What the auditor cannot do is make the estimate itself — that is a management function, and assuming it would constitute management participation, impairing independence.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["estimates", "independence"],
    },
    {
      question: "In evaluating accounting estimates, the auditor should review prior period estimates against actual outcomes primarily to:",
      options: [
        { label: "A", text: "Identify and correct prior period errors", isCorrect: false, rationale: "A difference between estimate and outcome is not, by itself, an error." },
        { label: "B", text: "Assess the effectiveness of management's estimation process and identify possible management bias", isCorrect: true, rationale: "Correct — retrospective review evaluates the process and detects patterns of bias." },
        { label: "C", text: "Determine whether the prior year opinion should be withdrawn", isCorrect: false, rationale: "Differing outcomes do not indicate the prior opinion was wrong." },
        { label: "D", text: "Compute the current year materiality threshold", isCorrect: false, rationale: "Materiality is determined independently of estimate outcomes." },
      ],
      explanation: "A retrospective review of prior period estimates provides information about the reliability of management's estimation process and may reveal a pattern of bias — for example, estimates consistently at the favorable end of a reasonable range. The review is not intended to call into question prior period judgments made with the information then available.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["estimates", "management bias"],
    },
    {
      question: "Management's estimate of the allowance for credit losses is $400,000. The auditor develops a reasonable range of $340,000 to $390,000. The auditor should:",
      options: [
        { label: "A", text: "Accept management's estimate because it is conservative", isCorrect: false, rationale: "Conservatism does not justify an estimate outside the supportable range; neutrality is required." },
        { label: "B", text: "Treat the difference between $400,000 and the nearest point of the range as a likely misstatement", isCorrect: true, rationale: "Correct — when the estimate falls outside the auditor's supported range, the difference from the closest boundary is a misstatement." },
        { label: "C", text: "Require management to record exactly the midpoint of the range", isCorrect: false, rationale: "Any point within a reasonable range is acceptable; the auditor does not dictate a specific figure." },
        { label: "D", text: "Issue a disclaimer of opinion", isCorrect: false, rationale: "A single estimate difference does not warrant a disclaimer." },
      ],
      explanation: "When management's estimate lies outside the auditor's range of reasonable outcomes, the difference between it and the nearest boundary of that range is treated as a likely misstatement — here $10,000. If the estimate falls within the range, it is generally considered reasonable, though the auditor still watches for a pattern of bias across estimates.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["estimates", "misstatement"],
    },
    {
      question: "Estimation uncertainty in an accounting estimate refers to:",
      options: [
        { label: "A", text: "The auditor's uncertainty about whether management is honest", isCorrect: false, rationale: "This describes skepticism about integrity, not estimation uncertainty." },
        { label: "B", text: "The susceptibility of an estimate to an inherent lack of precision in its measurement", isCorrect: true, rationale: "Correct — estimation uncertainty is the inherent imprecision in measuring the estimate." },
        { label: "C", text: "The risk that controls over the estimate will fail", isCorrect: false, rationale: "That is control risk." },
        { label: "D", text: "The probability that the estimate will be audited", isCorrect: false, rationale: "This is not a meaningful audit concept." },
      ],
      explanation: "Estimation uncertainty is the susceptibility of an estimate and related disclosures to an inherent lack of precision in measurement. High estimation uncertainty — as with litigation reserves, fair values of illiquid assets, or long-term warranty obligations — often indicates a significant risk requiring specific audit responses and expanded disclosure.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["estimates", "estimation uncertainty"],
    },
  ],

  "related-parties-and-going-concern": [
    {
      question: "Substantial doubt about the entity's ability to continue as a going concern is NOT alleviated, and the financial statements adequately disclose the matter. The auditor should issue:",
      options: [
        { label: "A", text: "A qualified opinion", isCorrect: false, rationale: "Adequate disclosure means the statements are not materially misstated, so no qualification is warranted." },
        { label: "B", text: "An unmodified opinion with a separate going concern section", isCorrect: true, rationale: "Correct — adequate disclosure supports an unmodified opinion, with a separate section drawing attention to the matter." },
        { label: "C", text: "An adverse opinion", isCorrect: false, rationale: "An adverse opinion requires the statements to be materially misstated and pervasively so." },
        { label: "D", text: "A disclaimer of opinion", isCorrect: false, rationale: "A disclaimer results from an inability to obtain sufficient evidence, not from going concern doubt itself." },
      ],
      explanation: "When substantial doubt exists and disclosure is adequate, the opinion remains unmodified and the report includes a separate section headed 'Substantial Doubt About the Entity's Ability to Continue as a Going Concern.' If disclosure is inadequate, the statements are materially misstated and a qualified or adverse opinion follows.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["going concern", "audit reports"],
    },
    {
      question: "Which condition would most likely raise substantial doubt about an entity's ability to continue as a going concern?",
      options: [
        { label: "A", text: "A change in the entity's depreciation method", isCorrect: false, rationale: "An accounting method change has no bearing on the entity's viability." },
        { label: "B", text: "Recurring operating losses combined with default on loan covenants", isCorrect: true, rationale: "Correct — negative operating trends together with debt defaults are classic going concern indicators." },
        { label: "C", text: "A reduction in the dividend rate", isCorrect: false, rationale: "This may conserve cash and is not by itself a substantial doubt indicator." },
        { label: "D", text: "The retirement of a long-serving chief executive", isCorrect: false, rationale: "Management turnover alone does not raise substantial doubt." },
      ],
      explanation: "Going concern indicators include recurring operating losses, working capital deficiencies, negative operating cash flows, default on loans or similar agreements, denial of trade credit, and loss of a principal customer or franchise. The auditor evaluates them in the aggregate along with management's plans to mitigate them.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["going concern", "indicators"],
    },
    {
      question: "Because related party transactions may not be conducted at arm's length, the auditor should:",
      options: [
        { label: "A", text: "Assume all related party transactions are fraudulent", isCorrect: false, rationale: "Professional skepticism does not extend to presuming fraud without evidence." },
        { label: "B", text: "Evaluate whether the transactions have been properly identified, accounted for, and disclosed", isCorrect: true, rationale: "Correct — the audit objective is proper identification, accounting, and disclosure of related party relationships and transactions." },
        { label: "C", text: "Require management to obtain a fairness opinion for each transaction", isCorrect: false, rationale: "Auditing standards do not impose this requirement." },
        { label: "D", text: "Report all related party transactions to the SEC", isCorrect: false, rationale: "The auditor does not report directly to regulators in these circumstances." },
      ],
      explanation: "The auditor obtains an understanding of related party relationships and transactions sufficient to identify fraud risk factors, conclude whether the statements achieve fair presentation, and evaluate the adequacy of disclosure. Note that unless the auditor is engaged to do so, the auditor does not opine on whether transactions were at arm's length — a representation management cannot ordinarily support either.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["related parties"],
    },
    {
      question: "Which procedure would most likely help the auditor identify previously undisclosed related parties?",
      options: [
        { label: "A", text: "Recalculating depreciation expense", isCorrect: false, rationale: "This procedure is unrelated to identifying related parties." },
        { label: "B", text: "Reviewing significant unusual transactions and inspecting bank confirmations for guarantees", isCorrect: true, rationale: "Correct — unusual transactions and unexpected guarantees frequently reveal undisclosed relationships." },
        { label: "C", text: "Observing the physical inventory count", isCorrect: false, rationale: "Inventory observation addresses existence and condition." },
        { label: "D", text: "Confirming accounts payable balances", isCorrect: false, rationale: "Payable confirmations address recorded balances, not relationships." },
      ],
      explanation: "Procedures to identify undisclosed related parties include reviewing significant unusual transactions outside the normal course of business, inspecting bank confirmations for guarantees, reviewing board minutes and conflict-of-interest statements, examining large or unusual period-end transactions, and reviewing prior year working papers and regulatory filings.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["related parties", "procedures"],
    },
  ],

  "it-controls-in-audit": [
    {
      question: "Which is an example of an IT general control rather than an application control?",
      options: [
        { label: "A", text: "A validity check rejecting an invalid customer number", isCorrect: false, rationale: "Input validation is an application control operating on individual transactions." },
        { label: "B", text: "Logical access controls restricting who can modify production programs", isCorrect: true, rationale: "Correct — access to programs and data is a classic IT general control supporting the whole environment." },
        { label: "C", text: "A batch total reconciling the number of invoices processed", isCorrect: false, rationale: "Batch totals are processing application controls." },
        { label: "D", text: "A limit check flagging orders above a credit ceiling", isCorrect: false, rationale: "Limit checks are application-level input controls." },
      ],
      explanation: "IT general controls operate across the environment and support the effective functioning of application controls: access to programs and data, program change management, program development, and computer operations. Application controls — input validation, batch totals, limit checks, reasonableness tests — apply to individual transaction processing. Weak ITGCs undermine reliance on all application controls.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["IT controls", "ITGC"],
    },
    {
      question: "In a highly automated environment where transactions are initiated and processed only electronically, the auditor:",
      options: [
        { label: "A", text: "May rely exclusively on substantive procedures", isCorrect: false, rationale: "Where no paper audit trail exists, substantive procedures alone may not provide sufficient evidence." },
        { label: "B", text: "May find that substantive procedures alone cannot provide sufficient appropriate evidence, requiring tests of controls", isCorrect: true, rationale: "Correct — the absence of a traditional audit trail can make testing controls mandatory rather than optional." },
        { label: "C", text: "Must issue a disclaimer of opinion", isCorrect: false, rationale: "Automation does not preclude an audit opinion." },
        { label: "D", text: "Should ignore IT controls and focus on year-end balances", isCorrect: false, rationale: "This would leave the auditor without sufficient evidence about how balances arose." },
      ],
      explanation: "Testing controls is usually the auditor's choice, but it becomes required when substantive procedures alone cannot provide sufficient appropriate evidence at the assertion level. Highly automated processing with no paper documentation is the standard example — the evidence about transaction integrity exists only in the controls themselves.",
      difficulty: "HARD",
      questionType: "EXAM_TRAP",
      tags: ["IT controls", "automated environment"],
    },
    {
      question: "Segregation of duties in an IT environment is best achieved by separating:",
      options: [
        { label: "A", text: "Data entry from data verification", isCorrect: false, rationale: "Useful, but not the primary IT segregation concern." },
        { label: "B", text: "Systems development, computer operations, and data control functions", isCorrect: true, rationale: "Correct — separating these three functions prevents an individual from both writing and running programs affecting live data." },
        { label: "C", text: "Hardware maintenance from software licensing", isCorrect: false, rationale: "These administrative functions are not core control concerns." },
        { label: "D", text: "Help desk support from user training", isCorrect: false, rationale: "Neither function creates an incompatible duties risk." },
      ],
      explanation: "In IT, the critical incompatible functions are systems development or programming, computer operations, and data control or librarian duties. A programmer with operations access could write and then run unauthorized code against live data. This mirrors the general principle of separating authorization, recordkeeping, and custody.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["IT controls", "segregation of duties"],
    },
    {
      question: "The test data approach to auditing a computerized application involves:",
      options: [
        { label: "A", text: "Processing the client's actual data through the auditor's own software", isCorrect: false, rationale: "This describes parallel simulation." },
        { label: "B", text: "Processing the auditor's fictitious transactions through the client's system to see whether controls detect exceptions", isCorrect: true, rationale: "Correct — test data probes whether the application's programmed controls respond correctly." },
        { label: "C", text: "Embedding an audit module in the client's system to capture transactions continuously", isCorrect: false, rationale: "This describes an embedded audit module or integrated test facility approach." },
        { label: "D", text: "Comparing the client's source code against an authorized version", isCorrect: false, rationale: "This describes code comparison." },
      ],
      explanation: "Test data uses auditor-prepared transactions, including deliberately invalid ones, run through the client's application to verify that programmed controls reject or flag exceptions as intended. The auditor must ensure the test data does not contaminate live records and that the program tested is the one actually used in production.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["IT controls", "CAATs"],
    },
  ],

  "group-audits-and-using-others-work": [
    {
      question: "The group engagement partner decides to make reference to a component auditor in the auditor's report. The effect is that:",
      options: [
        { label: "A", text: "The opinion must be qualified", isCorrect: false, rationale: "Reference to a component auditor is not a qualification and does not modify the opinion." },
        { label: "B", text: "Responsibility for the audit is divided, and the report indicates the magnitude of the portion audited by others", isCorrect: true, rationale: "Correct — reference divides responsibility while the opinion remains unmodified." },
        { label: "C", text: "The group auditor assumes full responsibility for the component auditor's work", isCorrect: false, rationale: "Assuming responsibility is the alternative approach, in which no reference is made." },
        { label: "D", text: "A disclaimer of opinion must be issued on the group statements", isCorrect: false, rationale: "Referencing another auditor does not prevent an opinion." },
      ],
      explanation: "The group auditor either assumes responsibility for the component auditor's work — making no reference in the report — or makes reference, dividing responsibility. Making reference requires that the component auditor's report is not restricted, that the component auditor is independent and competent, and the report discloses the magnitude of the portion audited by the other firm. Either way the opinion can be unmodified.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["group audits", "component auditor"],
    },
    {
      question: "When evaluating whether to use the work of the client's internal audit function, the external auditor considers all of the following EXCEPT:",
      options: [
        { label: "A", text: "The objectivity of the internal audit function", isCorrect: false, rationale: "Objectivity, particularly the reporting line, is a key consideration." },
        { label: "B", text: "The competence of the internal auditors", isCorrect: false, rationale: "Competence is a key consideration." },
        { label: "C", text: "Whether the function applies a systematic and disciplined approach", isCorrect: false, rationale: "This is one of the three evaluation criteria." },
        { label: "D", text: "Whether using the work will reduce the audit fee", isCorrect: true, rationale: "Correct — fee considerations are irrelevant to whether internal audit work may be used." },
      ],
      explanation: "The external auditor evaluates the internal audit function's objectivity, competence, and whether it applies a systematic and disciplined approach including quality control. Cost savings play no part in the judgment, and the external auditor's sole responsibility for the opinion is never reduced by using others' work.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["internal audit", "using others' work"],
    },
    {
      question: "Regardless of how much the external auditor uses the work of internal auditors, the external auditor must:",
      options: [
        { label: "A", text: "Share responsibility for the opinion with the internal audit function", isCorrect: false, rationale: "Responsibility for the opinion is never shared with internal auditors." },
        { label: "B", text: "Make all significant judgments personally and remain solely responsible for the opinion", isCorrect: true, rationale: "Correct — significant judgments and the opinion itself cannot be delegated." },
        { label: "C", text: "Reperform all work done by internal auditors", isCorrect: false, rationale: "Complete reperformance would defeat the purpose; selective reperformance is used to evaluate the work." },
        { label: "D", text: "Refuse to use internal audit work on any significant account", isCorrect: false, rationale: "Internal audit work may be used in significant areas with appropriate evaluation, though more judgment means less reliance." },
      ],
      explanation: "The external auditor may use internal audit work as evidence and may obtain direct assistance from internal auditors under supervision, but sole responsibility for the audit opinion remains with the external auditor. As the amount of judgment and the assessed risk increase, the external auditor must perform more of the work personally.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["internal audit", "responsibility"],
    },
    {
      question: "When using the work of an auditor's specialist, such as an actuary or appraiser, the auditor should:",
      options: [
        { label: "A", text: "Refer to the specialist in the auditor's report to share responsibility", isCorrect: false, rationale: "Reference to a specialist in an unmodified report is not permitted, as it may be misread as a division of responsibility." },
        { label: "B", text: "Evaluate the specialist's competence, capabilities, and objectivity, and the appropriateness of their work as audit evidence", isCorrect: true, rationale: "Correct — the auditor evaluates both the specialist and the relevance and reasonableness of their findings." },
        { label: "C", text: "Accept the specialist's conclusions without further evaluation", isCorrect: false, rationale: "The auditor must evaluate the work, including the assumptions and methods used." },
        { label: "D", text: "Perform the specialist's calculations independently in every case", isCorrect: false, rationale: "Independent recomputation is not required where the specialist's work is properly evaluated." },
      ],
      explanation: "The auditor evaluates the specialist's competence, capabilities, and objectivity; obtains an understanding of the specialist's field; agrees on the nature and scope of the work; and evaluates the appropriateness of the findings, including the assumptions and methods used. Reference to the specialist is made in an unmodified opinion only when the reference is relevant to understanding a modification.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["specialists", "using others' work"],
    },
  ],

  "written-representations-and-completing-the-audit": [
    {
      question: "The management representation letter should be dated:",
      options: [
        { label: "A", text: "As of the balance sheet date", isCorrect: false, rationale: "The letter must cover the period through the report date, not just to year-end." },
        { label: "B", text: "As of the date of the auditor's report", isCorrect: true, rationale: "Correct — the representation letter carries the same date as the auditor's report." },
        { label: "C", text: "As of the date fieldwork began", isCorrect: false, rationale: "Representations must cover the entire audit through completion." },
        { label: "D", text: "As of the date the financial statements are issued to shareholders", isCorrect: false, rationale: "Issuance may occur later; the report date governs." },
      ],
      explanation: "The written representation letter is dated as of the date of the auditor's report and covers all periods referred to in the report. Because the auditor cannot date the report before obtaining sufficient appropriate evidence, and representations are part of that evidence, the two dates coincide.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["representations", "completing the audit"],
    },
    {
      question: "Management refuses to provide a written representation letter. The auditor should:",
      options: [
        { label: "A", text: "Issue a qualified opinion and note the refusal", isCorrect: false, rationale: "The refusal is severe enough that a qualified opinion is generally insufficient." },
        { label: "B", text: "Disclaim an opinion or withdraw from the engagement", isCorrect: true, rationale: "Correct — refusal to provide required representations is a scope limitation sufficiently pervasive to require a disclaimer or withdrawal." },
        { label: "C", text: "Issue an unmodified opinion with an emphasis-of-matter paragraph", isCorrect: false, rationale: "An emphasis paragraph does not address a fundamental evidence limitation." },
        { label: "D", text: "Obtain oral representations and proceed normally", isCorrect: false, rationale: "Oral representations do not satisfy the requirement for written representations." },
      ],
      explanation: "Written representations are required audit evidence. Management's refusal to provide them is a scope limitation so significant that the auditor disclaims an opinion or withdraws, and it also calls into question the reliability of all other management representations relied upon during the audit.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["representations", "scope limitation"],
    },
    {
      question: "A material subsequent event requiring adjustment is discovered after the original report date but before issuance, and the auditor extends procedures only for that event. The auditor should:",
      options: [
        { label: "A", text: "Use the original report date without change", isCorrect: false, rationale: "This would misrepresent when procedures on the new event were completed." },
        { label: "B", text: "Dual date the report, or date it as of the later date and extend all procedures to that date", isCorrect: true, rationale: "Correct — dual dating limits the auditor's responsibility for other events to the original date." },
        { label: "C", text: "Withdraw the report entirely", isCorrect: false, rationale: "Withdrawal is unnecessary when the event is properly reflected." },
        { label: "D", text: "Refuse to consider events occurring after the original report date", isCorrect: false, rationale: "The auditor must consider events up to the report date and respond to facts learned before issuance." },
      ],
      explanation: "Dual dating — for example, 'February 15, 20X6, except as to Note 12, which is as of March 3, 20X6' — limits the auditor's responsibility for subsequent events to the original report date, apart from the specific matter. Alternatively, the auditor may date the report as of the later date, which extends responsibility for all subsequent events to that date.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["subsequent events", "dual dating"],
    },
    {
      question: "During the completion phase, the auditor accumulates uncorrected misstatements primarily to:",
      options: [
        { label: "A", text: "Bill the client for additional audit time", isCorrect: false, rationale: "Billing is unrelated to the evaluation of misstatements." },
        { label: "B", text: "Evaluate whether their aggregate effect is material to the financial statements as a whole", isCorrect: true, rationale: "Correct — individually immaterial misstatements may be material in aggregate." },
        { label: "C", text: "Prepare the client's adjusting journal entries", isCorrect: false, rationale: "Recording adjustments is management's responsibility." },
        { label: "D", text: "Determine the following year's audit fee", isCorrect: false, rationale: "This is not a purpose of the evaluation." },
      ],
      explanation: "The auditor accumulates identified misstatements other than those that are clearly trivial, requests management to correct them, and evaluates whether uncorrected misstatements are material individually or in the aggregate. The evaluation considers both quantitative size and qualitative factors, such as whether a small misstatement turns a loss into a profit or masks a trend.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["completing the audit", "misstatements"],
    },
  ],

  "audit-reports": [
    {
      question: "The financial statements contain a material misstatement that is NOT pervasive. The auditor should issue:",
      options: [
        { label: "A", text: "An unmodified opinion with an emphasis-of-matter paragraph", isCorrect: false, rationale: "An emphasis paragraph cannot substitute for a modified opinion when statements are misstated." },
        { label: "B", text: "A qualified opinion", isCorrect: true, rationale: "Correct — material but not pervasive misstatement leads to a qualified 'except for' opinion." },
        { label: "C", text: "An adverse opinion", isCorrect: false, rationale: "An adverse opinion requires the misstatement to be both material and pervasive." },
        { label: "D", text: "A disclaimer of opinion", isCorrect: false, rationale: "A disclaimer results from an inability to obtain evidence, not from a known misstatement." },
      ],
      explanation: "Two questions determine the opinion: is the problem a misstatement or a scope limitation, and is it pervasive? Material misstatement not pervasive gives a qualified opinion; material and pervasive gives adverse. Scope limitation material but not pervasive gives qualified; material and pervasive gives a disclaimer.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["audit reports", "opinion types"],
    },
    {
      question: "In the auditor's report for a nonissuer, which section immediately follows the Opinion section?",
      options: [
        { label: "A", text: "Responsibilities of Management for the Financial Statements", isCorrect: false, rationale: "This section comes later, after the Basis for Opinion." },
        { label: "B", text: "Basis for Opinion", isCorrect: true, rationale: "Correct — the Basis for Opinion section directly follows the Opinion section." },
        { label: "C", text: "Auditor's Responsibilities for the Audit of the Financial Statements", isCorrect: false, rationale: "This is the final major section of the report." },
        { label: "D", text: "Key Audit Matters", isCorrect: false, rationale: "KAMs are presented only when the auditor is engaged to report them, and come after the basis section." },
      ],
      explanation: "The nonissuer report begins with the opinion for prominence: Opinion, then Basis for Opinion (including the independence statement), then any going concern or KAM sections, then Responsibilities of Management, then Auditor's Responsibilities. Leading with the opinion was a deliberate change to put the conclusion first.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["audit reports", "report structure"],
    },
    {
      question: "An emphasis-of-matter paragraph is used to:",
      options: [
        { label: "A", text: "Modify the auditor's opinion on the financial statements", isCorrect: false, rationale: "An emphasis paragraph never modifies the opinion." },
        { label: "B", text: "Draw users' attention to a matter appropriately presented or disclosed that is fundamental to their understanding", isCorrect: true, rationale: "Correct — it highlights properly disclosed information without changing the opinion." },
        { label: "C", text: "Communicate a matter not disclosed in the financial statements that is relevant to users' understanding of the audit", isCorrect: false, rationale: "That describes an other-matter paragraph." },
        { label: "D", text: "Disclose a material weakness in internal control", isCorrect: false, rationale: "Control deficiencies are communicated to those charged with governance, not in the opinion." },
      ],
      explanation: "An emphasis-of-matter paragraph highlights something already properly presented or disclosed in the statements — a major catastrophe, unusually important subsequent event, or significant related party transactions. An other-matter paragraph addresses something not disclosed in the statements but relevant to users' understanding of the audit, such as a prior period audited by another auditor.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["audit reports", "emphasis of matter"],
    },
    {
      question: "The client refuses to allow the auditor to observe the physical inventory count, and the auditor cannot verify inventory by alternative procedures. Inventory is 45% of total assets. The auditor should issue:",
      options: [
        { label: "A", text: "A qualified opinion", isCorrect: false, rationale: "At 45% of total assets the limitation is pervasive, exceeding what a qualification can convey." },
        { label: "B", text: "A disclaimer of opinion", isCorrect: true, rationale: "Correct — a scope limitation that is both material and pervasive requires a disclaimer." },
        { label: "C", text: "An adverse opinion", isCorrect: false, rationale: "An adverse opinion applies to known material and pervasive misstatement, not to missing evidence." },
        { label: "D", text: "An unmodified opinion with an other-matter paragraph", isCorrect: false, rationale: "An unmodified opinion cannot be issued without sufficient appropriate evidence." },
      ],
      explanation: "Inability to obtain sufficient appropriate evidence is a scope limitation. At 45% of total assets the effect is pervasive, so the auditor disclaims an opinion. A client-imposed limitation of this significance also raises questions about management integrity and may warrant withdrawal.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["audit reports", "scope limitation"],
    },
    {
      question: "Critical audit matters (CAMs) are reported in the audit reports of:",
      options: [
        { label: "A", text: "All nonissuers", isCorrect: false, rationale: "Nonissuer reports include key audit matters only when the auditor is engaged to report them." },
        { label: "B", text: "Issuers, under PCAOB standards", isCorrect: true, rationale: "Correct — CAMs are a PCAOB requirement applicable to issuer audits." },
        { label: "C", text: "All entities receiving an unmodified opinion", isCorrect: false, rationale: "The opinion type does not determine CAM reporting." },
        { label: "D", text: "Governmental entities only", isCorrect: false, rationale: "CAMs are not a governmental audit requirement." },
      ],
      explanation: "Critical audit matters arise under PCAOB standards for issuer audits: matters communicated to the audit committee that relate to material accounts or disclosures and involved especially challenging, subjective, or complex auditor judgment. Under AICPA standards for nonissuers, the analogous key audit matters are reported only when the auditor is engaged to do so.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["audit reports", "CAMs"],
    },
  ],

  "reviews-compilations-and-aup": [
    {
      question: "A review engagement under SSARS provides:",
      options: [
        { label: "A", text: "Reasonable assurance, the same as an audit", isCorrect: false, rationale: "Only an audit provides reasonable assurance." },
        { label: "B", text: "Limited assurance, expressed as negative assurance", isCorrect: true, rationale: "Correct — a review provides limited assurance, stated as the accountant not being aware of needed material modifications." },
        { label: "C", text: "Absolute assurance", isCorrect: false, rationale: "No engagement provides absolute assurance." },
        { label: "D", text: "No assurance", isCorrect: false, rationale: "A compilation provides no assurance; a review provides limited assurance." },
      ],
      explanation: "A review consists primarily of inquiry and analytical procedures, providing limited assurance expressed negatively: the accountant is not aware of any material modifications that should be made. An audit provides reasonable assurance with a positive opinion; a compilation provides no assurance at all.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["SSARS", "review"],
    },
    {
      question: "An accountant who is not independent may still perform which engagement?",
      options: [
        { label: "A", text: "An audit, if the lack of independence is disclosed", isCorrect: false, rationale: "Independence is mandatory for an audit and cannot be cured by disclosure." },
        { label: "B", text: "A compilation, provided the lack of independence is disclosed in the report", isCorrect: true, rationale: "Correct — a compilation is the one engagement permitted without independence, subject to disclosure." },
        { label: "C", text: "A review, if the lack of independence is disclosed", isCorrect: false, rationale: "A review is an attest engagement requiring independence." },
        { label: "D", text: "An examination of prospective financial information", isCorrect: false, rationale: "Examinations are attest engagements requiring independence." },
      ],
      explanation: "Independence is required for all attest engagements — audits, reviews, and examinations. A compilation is the exception: because it provides no assurance, the accountant may perform it while not independent, provided the report discloses the lack of independence. Disclosing the reason is optional, but if one reason is given, all must be.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["SSARS", "compilation", "independence"],
    },
    {
      question: "Which procedures are the primary basis for a review engagement?",
      options: [
        { label: "A", text: "Tests of controls and substantive tests of details", isCorrect: false, rationale: "These are audit procedures and are not performed in a review." },
        { label: "B", text: "Inquiry and analytical procedures", isCorrect: true, rationale: "Correct — a review consists principally of inquiries of management and analytical procedures." },
        { label: "C", text: "Confirmation and physical observation", isCorrect: false, rationale: "These are audit evidence-gathering procedures beyond a review's scope." },
        { label: "D", text: "Reperformance of the client's reconciliations", isCorrect: false, rationale: "Reperformance is an audit procedure." },
      ],
      explanation: "A review is built on inquiry and analytical procedures. The accountant does not obtain an understanding of internal control, assess fraud risk, test controls, confirm balances, or observe inventory. If the accountant becomes aware that information is incorrect or incomplete, however, additional procedures are performed.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SSARS", "review procedures"],
    },
    {
      question: "In a SSARS preparation engagement, the accountant:",
      options: [
        { label: "A", text: "Issues a report providing limited assurance on the statements", isCorrect: false, rationale: "No report is issued at all in a preparation engagement." },
        { label: "B", text: "Issues no report, but includes a legend on each page stating that no assurance is provided", isCorrect: true, rationale: "Correct — the legend substitutes for a report, making clear that no assurance accompanies the statements." },
        { label: "C", text: "Must be independent of the client", isCorrect: false, rationale: "A preparation engagement is a nonattest service, so independence is not required." },
        { label: "D", text: "Must perform inquiry and analytical procedures", isCorrect: false, rationale: "Those procedures characterize a review; a preparation engagement requires neither." },
      ],
      explanation: "A preparation engagement is a nonattest service in which the accountant prepares financial statements without providing any assurance. No report is issued; instead each page carries a legend stating that no assurance is provided. If the accountant cannot include such a legend, a disclaimer or a compilation report must be issued instead.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["SSARS", "preparation engagement"],
    },
  ],

  "attestation-and-soc-engagements": [
    {
      question: "A SOC 1 report addresses:",
      options: [
        { label: "A", text: "Controls at a service organization relevant to user entities' internal control over financial reporting", isCorrect: true, rationale: "Correct — SOC 1 is scoped to controls affecting user entities' financial reporting." },
        { label: "B", text: "Controls relating to security, availability, processing integrity, confidentiality, and privacy", isCorrect: false, rationale: "Those trust services criteria are the subject of SOC 2 and SOC 3 reports." },
        { label: "C", text: "The service organization's compliance with tax regulations", isCorrect: false, rationale: "Tax compliance is not the subject of a SOC report." },
        { label: "D", text: "The financial statements of the service organization", isCorrect: false, rationale: "A SOC report covers controls, not the service organization's own financial statements." },
      ],
      explanation: "SOC 1 reports on controls at a service organization relevant to user entities' internal control over financial reporting, and are used by user auditors. SOC 2 reports address the trust services criteria — security, availability, processing integrity, confidentiality, and privacy — and are restricted use. SOC 3 covers the same criteria but is a general use summary report.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SOC engagements", "SOC 1"],
    },
    {
      question: "The key difference between a Type 1 and a Type 2 SOC report is that a Type 2 report:",
      options: [
        { label: "A", text: "Covers a broader range of trust services criteria", isCorrect: false, rationale: "The criteria covered depend on the SOC type and scope, not on Type 1 versus Type 2." },
        { label: "B", text: "Includes an opinion on the operating effectiveness of controls over a period of time", isCorrect: true, rationale: "Correct — Type 2 tests operating effectiveness across a period, while Type 1 addresses design at a point in time." },
        { label: "C", text: "Is available for general distribution", isCorrect: false, rationale: "Distribution restrictions depend on the report type, not on Type 1 versus Type 2." },
        { label: "D", text: "Is prepared by management rather than by an independent practitioner", isCorrect: false, rationale: "Both types are issued by an independent service auditor." },
      ],
      explanation: "A Type 1 report addresses the fairness of management's description of the system and the suitability of the design of controls as of a specified date. A Type 2 report covers the same ground plus the operating effectiveness of those controls throughout a specified period. Only a Type 2 report gives a user auditor evidence to rely on the controls.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SOC engagements", "Type 1 vs Type 2"],
    },
    {
      question: "In an examination engagement under the attestation standards, the practitioner:",
      options: [
        { label: "A", text: "Provides limited assurance expressed negatively", isCorrect: false, rationale: "That describes a review engagement under the attestation standards." },
        { label: "B", text: "Obtains reasonable assurance and expresses an opinion on the subject matter", isCorrect: true, rationale: "Correct — an examination is the attestation equivalent of an audit, providing reasonable assurance." },
        { label: "C", text: "Reports findings without any assurance", isCorrect: false, rationale: "That describes an agreed-upon procedures engagement." },
        { label: "D", text: "Compiles the subject matter from management's records", isCorrect: false, rationale: "Compilation is a SSARS service, not an attestation examination." },
      ],
      explanation: "The attestation standards provide three levels of service: examination (reasonable assurance, positive opinion), review (limited assurance, negative assurance), and agreed-upon procedures (findings only, no assurance). They apply to subject matter other than historical financial statements, such as prospective information or compliance assertions.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["attestation", "examination"],
    },
    {
      question: "A user auditor obtains a SOC 1 Type 2 report on a service organization. The user auditor should:",
      options: [
        { label: "A", text: "Accept the report as sufficient evidence without further consideration", isCorrect: false, rationale: "The user auditor must evaluate the report's relevance, period covered, and any identified exceptions." },
        { label: "B", text: "Evaluate whether the report covers a suitable period, whether complementary user entity controls are implemented, and the effect of any exceptions noted", isCorrect: true, rationale: "Correct — the user auditor must assess the report's relevance and completeness for its own audit purposes." },
        { label: "C", text: "Contact the service auditor to obtain their working papers as a matter of course", isCorrect: false, rationale: "Access to the service auditor's workpapers is not a routine step." },
        { label: "D", text: "Disclaim an opinion because part of the processing occurs outside the entity", isCorrect: false, rationale: "Outsourced processing does not preclude an opinion." },
      ],
      explanation: "The user auditor evaluates whether the SOC report's period aligns with the audit period, whether the described controls are relevant to the user entity's assertions, whether complementary user entity controls assumed by the service organization are actually in place, and how any exceptions in the service auditor's testing affect the audit approach.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["SOC engagements", "user auditor"],
    },
  ],
};
