import type { McqBank } from "./types";

/** AUD question bank — topics 1 through 9. */
export const audBankA: McqBank = {
  "professional-ethics-and-independence": [
    {
      question: "Under the AICPA Code of Professional Conduct, independence is required for which type of engagement?",
      options: [
        { label: "A", text: "A tax return preparation engagement", isCorrect: false, rationale: "Tax preparation is a nonattest service; objectivity and integrity are required, but not independence." },
        { label: "B", text: "An audit of financial statements", isCorrect: true, rationale: "Correct — independence is required for all attest engagements, including audits, reviews, and examinations." },
        { label: "C", text: "A consulting engagement on inventory systems", isCorrect: false, rationale: "Consulting is a nonattest service that does not require independence." },
        { label: "D", text: "A compilation where the lack of independence is disclosed", isCorrect: false, rationale: "A compilation may be performed without independence provided the lack of independence is disclosed in the report." },
      ],
      explanation: "Independence is required for attest engagements — audits, reviews, examinations, and agreed-upon procedures. It is not required for nonattest services such as tax preparation and consulting, though integrity and objectivity always apply. A compilation is unique: it may be performed while not independent, as long as the accountant discloses that fact.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["ethics", "independence"],
    },
    {
      question: "Which situation most clearly impairs a covered member's independence with respect to an audit client?",
      options: [
        { label: "A", text: "Owning shares in a mutual fund that holds an immaterial amount of the client's stock", isCorrect: false, rationale: "An indirect financial interest impairs independence only if it is material to the covered member." },
        { label: "B", text: "Owning any direct financial interest in the client, regardless of amount", isCorrect: true, rationale: "Correct — any direct financial interest impairs independence, no matter how small." },
        { label: "C", text: "Having a cousin employed by the client in a non-key position", isCorrect: false, rationale: "A cousin is not a close relative or immediate family member for independence purposes." },
        { label: "D", text: "Having previously audited the client three years ago", isCorrect: false, rationale: "Prior service alone does not impair independence." },
      ],
      explanation: "The materiality threshold applies only to indirect financial interests. Any direct financial interest in an attest client impairs independence regardless of how immaterial it is — a distinction candidates frequently miss. Immediate family (spouse, spouse equivalent, dependents) are generally treated as the covered member.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["ethics", "independence", "financial interest"],
    },
    {
      question: "A CPA firm performs bookkeeping services for a nonissuer audit client. Independence may be maintained if:",
      options: [
        { label: "A", text: "The firm's fees for bookkeeping are less than its audit fees", isCorrect: false, rationale: "The relative size of fees does not determine whether independence is preserved." },
        { label: "B", text: "Client management accepts responsibility, designates a competent individual to oversee the service, and the firm makes no management decisions", isCorrect: true, rationale: "Correct — these general requirements must be met before any nonattest service can be provided to an attest client." },
        { label: "C", text: "The engagement letter states that independence is not impaired", isCorrect: false, rationale: "Asserting independence in a letter does not create it." },
        { label: "D", text: "The bookkeeping is performed by staff not assigned to the audit", isCorrect: false, rationale: "Segregating personnel does not by itself satisfy the requirements." },
      ],
      explanation: "Nonattest services may be provided to a nonissuer attest client if management assumes all management responsibilities, designates an individual with suitable skill and knowledge to oversee the service, evaluates the adequacy and results of the service, and accepts responsibility for it. Note that under SEC and PCAOB rules, bookkeeping for an issuer audit client is prohibited outright.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["ethics", "nonattest services"],
    },
    {
      question: "The AICPA Code's conceptual framework approach should be applied when:",
      options: [
        { label: "A", text: "A specific rule in the Code prohibits the relationship", isCorrect: false, rationale: "When an explicit prohibition applies, the rule governs and no threats analysis is needed." },
        { label: "B", text: "A relationship or circumstance is not specifically addressed by the Code", isCorrect: true, rationale: "Correct — the threats and safeguards framework is applied to situations the rules do not explicitly cover." },
        { label: "C", text: "The client requests a waiver of an independence requirement", isCorrect: false, rationale: "Clients cannot waive independence requirements." },
        { label: "D", text: "The engagement is a compilation", isCorrect: false, rationale: "The type of engagement does not determine when the framework applies." },
      ],
      explanation: "The Code first applies specific rules and interpretations. Where a situation is not explicitly addressed, the member applies the conceptual framework: identify threats (self-review, advocacy, adverse interest, familiarity, undue influence, self-interest, management participation), evaluate their significance, and apply safeguards to reduce them to an acceptable level.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["ethics", "conceptual framework"],
    },
    {
      question: "A contingent fee arrangement is PROHIBITED when a CPA:",
      options: [
        { label: "A", text: "Represents a client in an IRS examination of a filed return", isCorrect: false, rationale: "Contingent fees are permitted for representation before a revenue agent examining a filed return." },
        { label: "B", text: "Prepares an original tax return for an audit client", isCorrect: true, rationale: "Correct — contingent fees are prohibited for preparing original returns and for any client for whom the member performs an audit." },
        { label: "C", text: "Performs a consulting engagement for a client the firm does not audit", isCorrect: false, rationale: "Contingent fees are permitted for nonattest clients." },
        { label: "D", text: "Represents a client in a court proceeding", isCorrect: false, rationale: "Judicial proceedings are among the permitted exceptions." },
      ],
      explanation: "Contingent fees and commissions are prohibited for clients where the member performs an audit, review, or examination of prospective financial information, and are prohibited for preparing original or amended returns or claims for refund. Exceptions exist for fees fixed by courts and for representation in examinations and judicial proceedings.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["ethics", "contingent fees"],
    },
  ],

  "engagement-acceptance-and-quality-management": [
    {
      question: "Which precondition must be present before an auditor accepts an audit engagement?",
      options: [
        { label: "A", text: "The auditor has already assessed control risk as low", isCorrect: false, rationale: "Control risk is assessed during the audit, well after acceptance." },
        { label: "B", text: "The financial reporting framework is acceptable and management acknowledges its responsibilities for the statements, internal control, and providing access to evidence", isCorrect: true, rationale: "Correct — an unacceptable framework or management's refusal to acknowledge these responsibilities means the engagement should not be accepted." },
        { label: "C", text: "The client has agreed to correct all misstatements the auditor may identify", isCorrect: false, rationale: "Such an advance commitment is neither required nor obtainable; the auditor evaluates uncorrected misstatements at the end of the audit." },
        { label: "D", text: "The prior year financial statements received an unmodified opinion", isCorrect: false, rationale: "A prior modified opinion does not preclude accepting the engagement." },
      ],
      explanation: "Before accepting an engagement the auditor must establish that the financial reporting framework to be applied is acceptable, and obtain management's agreement that it acknowledges responsibility for the financial statements, for internal control, and for providing the auditor with access to all information and personnel needed. Without these preconditions the audit cannot be conducted, and the auditor should decline.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["engagement acceptance", "preconditions"],
    },
    {
      question: "Under SQMS No. 1, a firm's system of quality management is built around:",
      options: [
        { label: "A", text: "A standardized checklist applied uniformly to all firms", isCorrect: false, rationale: "The standard rejects a one-size-fits-all approach in favor of tailoring to the firm." },
        { label: "B", text: "A risk-based approach in which the firm sets quality objectives, identifies quality risks, and designs responses", isCorrect: true, rationale: "Correct — SQMS No. 1 requires a risk assessment process tailored to the firm's nature and circumstances." },
        { label: "C", text: "Annual peer review as the sole monitoring mechanism", isCorrect: false, rationale: "Peer review is external; the standard requires the firm's own ongoing monitoring and remediation process." },
        { label: "D", text: "Engagement partner sign-off on every working paper", isCorrect: false, rationale: "This is not the structure of a quality management system." },
      ],
      explanation: "SQMS No. 1 replaced the older quality control standards with a risk-based system of quality management. The firm establishes quality objectives, identifies and assesses quality risks that could impede them, designs and implements responses, and monitors and remediates deficiencies — with an annual evaluation of the system by the individual assigned ultimate responsibility.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["quality management", "SQMS"],
    },
    {
      question: "Which matter should be documented in the engagement letter for an audit?",
      options: [
        { label: "A", text: "The auditor's assessed level of control risk", isCorrect: false, rationale: "Control risk is assessed during the audit, not agreed in advance with the client." },
        { label: "B", text: "The objective and scope of the audit, and the responsibilities of the auditor and management", isCorrect: true, rationale: "Correct — the engagement letter documents the agreed terms, including scope, objectives, and respective responsibilities." },
        { label: "C", text: "The specific audit procedures to be performed on each account", isCorrect: false, rationale: "Detailed procedures are in the audit program, not the engagement letter, and are not negotiated with the client." },
        { label: "D", text: "The expected amount of the audit adjustment", isCorrect: false, rationale: "Misstatements are unknown before the audit is performed." },
      ],
      explanation: "The engagement letter records the agreed terms: the objective and scope of the audit, the responsibilities of the auditor and of management, the inherent limitations of an audit, the applicable financial reporting framework, and the expected form of the report. Establishing management's responsibilities in writing is essential to a clear understanding.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["engagement acceptance", "engagement letter"],
    },
    {
      question: "An engagement quality review for an audit must be performed by:",
      options: [
        { label: "A", text: "The engagement partner, before releasing the report", isCorrect: false, rationale: "The reviewer must be someone other than the engagement partner to provide objective evaluation." },
        { label: "B", text: "A qualified individual who is not a member of the engagement team", isCorrect: true, rationale: "Correct — the reviewer must have sufficient competence, authority, and objectivity, and must not be part of the engagement team." },
        { label: "C", text: "An external peer reviewer selected by the state board", isCorrect: false, rationale: "That describes peer review, a separate external process." },
        { label: "D", text: "Any staff member with at least two years of experience", isCorrect: false, rationale: "The reviewer must have sufficient and appropriate experience and authority, which two years generally does not confer." },
      ],
      explanation: "An engagement quality review is an objective evaluation of the significant judgments made by the engagement team and the conclusions reached. It must be performed by a qualified reviewer who is not on the engagement team, and the report cannot be released until the review is complete.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["quality management", "engagement quality review"],
    },
    {
      question: "A prospective client refuses to allow the successor auditor to communicate with the predecessor auditor. The successor should:",
      options: [
        { label: "A", text: "Accept the engagement but expand substantive testing", isCorrect: false, rationale: "Expanded testing does not address what the refusal signals about management integrity." },
        { label: "B", text: "Consider the refusal a significant matter that ordinarily precludes accepting the engagement", isCorrect: true, rationale: "Correct — an unexplained refusal raises serious questions about management's integrity and the reasons for the change." },
        { label: "C", text: "Accept the engagement and communicate with the predecessor anyway", isCorrect: false, rationale: "The predecessor cannot respond without client consent due to confidentiality obligations." },
        { label: "D", text: "Accept the engagement and document the refusal in the working papers", isCorrect: false, rationale: "Documentation alone does not resolve the underlying concern." },
      ],
      explanation: "The predecessor auditor is bound by confidentiality and can respond only with client consent. A refusal to permit that communication, without a reasonable explanation, is a serious indicator about management's integrity and ordinarily leads the successor to decline the engagement.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["engagement acceptance", "predecessor auditor"],
    },
  ],

  "audit-planning-and-materiality": [
    {
      question: "Performance materiality is set at an amount:",
      options: [
        { label: "A", text: "Equal to overall materiality for the financial statements as a whole", isCorrect: false, rationale: "Setting them equal would leave no allowance for undetected misstatements aggregating." },
        { label: "B", text: "Less than overall materiality, to reduce the risk that uncorrected and undetected misstatements aggregate above materiality", isCorrect: true, rationale: "Correct — performance materiality provides a margin for the aggregation of misstatements." },
        { label: "C", text: "Greater than overall materiality, to allow for immaterial errors", isCorrect: false, rationale: "A higher threshold would reduce, not increase, the rigor of testing." },
        { label: "D", text: "Determined by management based on user expectations", isCorrect: false, rationale: "Materiality is an auditor judgment, not a management determination." },
      ],
      explanation: "Overall materiality is the threshold at which misstatements could influence users' decisions. Performance materiality is set lower — commonly a percentage of overall materiality — so that the aggregate of undetected and uncorrected misstatements is unlikely to exceed overall materiality. Lower performance materiality means more extensive testing.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["planning", "materiality"],
    },
    {
      question: "Audit risk is set at 5%, inherent risk is assessed at 60%, and control risk at 50%. What is the maximum acceptable detection risk?",
      options: [
        { label: "A", text: "Approximately 17%", isCorrect: true, rationale: "Correct — RMM = 0.60 × 0.50 = 0.30, so DR = 0.05 ÷ 0.30 ≈ 0.167, or about 17%." },
        { label: "B", text: "30%", isCorrect: false, rationale: "30% is the risk of material misstatement, not detection risk." },
        { label: "C", text: "5%", isCorrect: false, rationale: "5% is the overall audit risk, not the detection risk component." },
        { label: "D", text: "1.5%", isCorrect: false, rationale: "This multiplies the components rather than dividing audit risk by RMM." },
      ],
      explanation: "The audit risk model is AR = IR × CR × DR, so DR = AR ÷ (IR × CR). Here 0.05 ÷ (0.60 × 0.50) = 0.05 ÷ 0.30 ≈ 16.7%. Detection risk is the only component the auditor controls: when RMM is high, acceptable detection risk falls and more substantive testing is required.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["planning", "audit risk model"],
    },
    {
      question: "If the auditor assesses the risk of material misstatement as higher than originally planned, the auditor should:",
      options: [
        { label: "A", text: "Increase acceptable detection risk and perform less substantive testing", isCorrect: false, rationale: "This reverses the relationship and would leave audit risk unacceptably high." },
        { label: "B", text: "Decrease acceptable detection risk and perform more persuasive substantive testing", isCorrect: true, rationale: "Correct — detection risk varies inversely with RMM if overall audit risk is to stay acceptable." },
        { label: "C", text: "Increase the materiality threshold", isCorrect: false, rationale: "Raising materiality would reduce work precisely when more is needed." },
        { label: "D", text: "Withdraw from the engagement", isCorrect: false, rationale: "Higher risk calls for a stronger audit response, not automatic withdrawal." },
      ],
      explanation: "Detection risk has an inverse relationship with the risk of material misstatement. When RMM rises, acceptable detection risk must fall, which the auditor achieves through more effective procedures, testing closer to year-end, larger sample sizes, and more experienced staff assignment.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["planning", "detection risk"],
    },
    {
      question: "Which procedure is required during audit planning?",
      options: [
        { label: "A", text: "Performing tests of controls over the revenue cycle", isCorrect: false, rationale: "Tests of controls are performed in response to assessed risks, not as a planning requirement." },
        { label: "B", text: "Performing preliminary analytical procedures", isCorrect: true, rationale: "Correct — analytical procedures are required in planning to help identify unusual transactions and areas of higher risk." },
        { label: "C", text: "Confirming accounts receivable balances", isCorrect: false, rationale: "Confirmation is a substantive procedure performed during fieldwork." },
        { label: "D", text: "Obtaining the management representation letter", isCorrect: false, rationale: "The representation letter is obtained near the end of the audit." },
      ],
      explanation: "Analytical procedures are required at two points: during planning as a risk assessment procedure, and near the end of the audit to form an overall conclusion. Their use as a substantive procedure during fieldwork is optional. In planning, they help the auditor understand the entity and identify unexpected relationships suggesting higher risk.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["planning", "analytical procedures"],
    },
    {
      question: "Which responsibility may the auditor NOT delegate or share when planning an audit?",
      options: [
        { label: "A", text: "Determining the overall audit strategy and audit plan", isCorrect: true, rationale: "Correct — the auditor is solely responsible for the audit strategy and plan, which cannot be determined by management." },
        { label: "B", text: "Obtaining an understanding of the entity's internal control", isCorrect: false, rationale: "The auditor may use the work of others, such as internal audit, in obtaining this understanding." },
        { label: "C", text: "Performing tests of details on inventory", isCorrect: false, rationale: "Internal auditors may provide direct assistance under the external auditor's supervision." },
        { label: "D", text: "Preparing schedules and analyses of account balances", isCorrect: false, rationale: "Client personnel routinely prepare schedules for the auditor to test." },
      ],
      explanation: "The auditor retains sole responsibility for the audit strategy, the audit plan, and the audit opinion. Client staff may prepare schedules and internal auditors may provide direct assistance under supervision, but planning judgments and the opinion itself can never be delegated.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["planning", "auditor responsibility"],
    },
  ],

  "understanding-the-entity-and-internal-control": [
    {
      question: "Which is NOT one of the five components of internal control under the COSO framework?",
      options: [
        { label: "A", text: "Control environment", isCorrect: false, rationale: "This is a COSO component — the foundation of the framework." },
        { label: "B", text: "Risk assessment", isCorrect: false, rationale: "This is a COSO component." },
        { label: "C", text: "Detection risk", isCorrect: true, rationale: "Correct — detection risk is a component of the audit risk model, not of internal control." },
        { label: "D", text: "Monitoring activities", isCorrect: false, rationale: "This is a COSO component." },
      ],
      explanation: "The five COSO components are the control environment, risk assessment, information and communication, monitoring activities, and existing control activities — often remembered as CRIME. Detection risk belongs to the audit risk model and describes the risk that the auditor's own procedures fail to detect a material misstatement.",
      difficulty: "EASY",
      questionType: "EXCEPTION",
      tags: ["internal control", "COSO"],
    },
    {
      question: "The auditor is required to obtain an understanding of internal control in order to:",
      options: [
        { label: "A", text: "Express an opinion on the effectiveness of internal control in every audit", isCorrect: false, rationale: "An opinion on internal control is required only in an integrated audit of an issuer or when separately engaged." },
        { label: "B", text: "Identify and assess risks of material misstatement and design further audit procedures", isCorrect: true, rationale: "Correct — understanding internal control is a risk assessment procedure required in every audit." },
        { label: "C", text: "Detect all instances of fraud committed by management", isCorrect: false, rationale: "No audit provides absolute assurance that all fraud is detected." },
        { label: "D", text: "Provide management with recommendations for improving operations", isCorrect: false, rationale: "Recommendations may result from the audit but are not its purpose." },
      ],
      explanation: "In every audit the auditor must obtain a sufficient understanding of the entity and its internal control to identify and assess the risks of material misstatement and to design appropriate further audit procedures. Obtaining that understanding is distinct from testing operating effectiveness, which is done only when the auditor plans to rely on controls or when substantive procedures alone are insufficient.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["internal control", "risk assessment"],
    },
    {
      question: "A deficiency in internal control that is less severe than a material weakness but important enough to merit attention by those charged with governance is a:",
      options: [
        { label: "A", text: "Material weakness", isCorrect: false, rationale: "A material weakness is more severe — a reasonable possibility that a material misstatement would not be prevented or detected timely." },
        { label: "B", text: "Significant deficiency", isCorrect: true, rationale: "Correct — this is the definition of a significant deficiency." },
        { label: "C", text: "Control activity", isCorrect: false, rationale: "A control activity is a control, not a deficiency." },
        { label: "D", text: "Reportable condition", isCorrect: false, rationale: "This term was superseded by the current significant deficiency terminology." },
      ],
      explanation: "A deficiency exists when a control does not allow management or employees to prevent or detect misstatements on a timely basis. A significant deficiency is less severe than a material weakness but important enough to merit attention by those charged with governance. Both must be communicated in writing to those charged with governance.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["internal control", "deficiencies"],
    },
    {
      question: "The control environment is best described as:",
      options: [
        { label: "A", text: "The specific procedures management uses to authorize transactions", isCorrect: false, rationale: "These are control activities, a separate component." },
        { label: "B", text: "The set of standards, processes, and structures that provide the foundation for internal control, including the tone at the top", isCorrect: true, rationale: "Correct — the control environment underpins all other components." },
        { label: "C", text: "The process of assessing whether controls continue to operate effectively", isCorrect: false, rationale: "This describes monitoring activities." },
        { label: "D", text: "The IT systems used to process transactions", isCorrect: false, rationale: "Technology falls within information and communication and within control activities." },
      ],
      explanation: "The control environment sets the tone of the organization and influences the control consciousness of its people. It encompasses integrity and ethical values, the board's oversight, organizational structure and authority, commitment to competence, and accountability. A weak control environment undermines even well-designed control activities.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["internal control", "control environment"],
    },
    {
      question: "Which limitation is inherent in any system of internal control?",
      options: [
        { label: "A", text: "Controls can be circumvented by collusion or overridden by management", isCorrect: true, rationale: "Correct — collusion and management override are inherent limitations no control system can eliminate." },
        { label: "B", text: "Controls cannot be documented in writing", isCorrect: false, rationale: "Controls are routinely documented." },
        { label: "C", text: "Controls must be tested by an external auditor to be effective", isCorrect: false, rationale: "Controls operate effectively whether or not an auditor tests them." },
        { label: "D", text: "Controls apply only to financial reporting", isCorrect: false, rationale: "Internal control also addresses operations and compliance objectives." },
      ],
      explanation: "Internal control provides reasonable, not absolute, assurance. Inherent limitations include human error, collusion between two or more people, management override, cost-benefit constraints, and the fact that controls are typically designed for routine rather than unusual transactions. This is why the auditor cannot rely on controls alone.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["internal control", "limitations"],
    },
  ],

  "assessing-risk-of-material-misstatement": [
    {
      question: "The risk of material misstatement at the assertion level consists of:",
      options: [
        { label: "A", text: "Inherent risk and detection risk", isCorrect: false, rationale: "Detection risk relates to the auditor's procedures, not to the entity's risk of misstatement." },
        { label: "B", text: "Inherent risk and control risk", isCorrect: true, rationale: "Correct — RMM is the combination of inherent risk and control risk, both of which exist independently of the audit." },
        { label: "C", text: "Control risk and detection risk", isCorrect: false, rationale: "This combination omits inherent risk and improperly includes an auditor-controlled component." },
        { label: "D", text: "Business risk and audit risk", isCorrect: false, rationale: "These are broader concepts, not the components of RMM." },
      ],
      explanation: "The risk of material misstatement is the entity's own risk, comprising inherent risk (susceptibility of an assertion to misstatement before considering controls) and control risk (the risk that controls fail to prevent or detect it). Detection risk is separate: it is the auditor's risk and the only component the auditor can directly control.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["risk assessment", "RMM"],
    },
    {
      question: "A significant risk requiring special audit consideration would most likely arise from:",
      options: [
        { label: "A", text: "Routine, high-volume cash sales processed by an established system", isCorrect: false, rationale: "Routine, systematically processed transactions generally present lower risk." },
        { label: "B", text: "A complex, non-routine related party transaction near year-end", isCorrect: true, rationale: "Correct — complexity, non-routine nature, related parties, and timing near year-end are classic significant risk indicators." },
        { label: "C", text: "Recurring monthly depreciation entries", isCorrect: false, rationale: "Systematic recurring calculations are low risk." },
        { label: "D", text: "Payment of routine utility invoices", isCorrect: false, rationale: "Routine operating disbursements are not significant risks." },
      ],
      explanation: "Significant risks typically involve non-routine or judgmental matters: complexity, related parties, significant management judgment or estimation uncertainty, recent economic or accounting developments, and possible fraud. For each significant risk the auditor must evaluate the design and implementation of related controls and perform substantive procedures specifically responsive to it.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["risk assessment", "significant risks"],
    },
    {
      question: "Which is a required risk assessment procedure in every audit?",
      options: [
        { label: "A", text: "Confirming bank balances", isCorrect: false, rationale: "This is a substantive procedure, not a risk assessment procedure." },
        { label: "B", text: "Inquiries of management, analytical procedures, and observation and inspection", isCorrect: true, rationale: "Correct — these three categories constitute the required risk assessment procedures." },
        { label: "C", text: "Reperformance of control activities", isCorrect: false, rationale: "Reperformance is a test of controls, performed only when the auditor plans to rely on controls." },
        { label: "D", text: "Recalculation of depreciation expense", isCorrect: false, rationale: "This is a substantive test of details." },
      ],
      explanation: "Risk assessment procedures comprise inquiries of management and others within the entity, analytical procedures, and observation and inspection. They provide the basis for assessing risk but never by themselves provide sufficient appropriate evidence for an opinion — further audit procedures are always required.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["risk assessment", "procedures"],
    },
    {
      question: "The auditor is required to presume that a risk of fraud exists in which area?",
      options: [
        { label: "A", text: "Depreciation of fixed assets", isCorrect: false, rationale: "No presumption of fraud risk attaches specifically to depreciation." },
        { label: "B", text: "Revenue recognition", isCorrect: true, rationale: "Correct — the auditor must presume a fraud risk in revenue recognition, and must document any rebuttal of that presumption." },
        { label: "C", text: "Payroll processing", isCorrect: false, rationale: "Payroll may carry fraud risk but there is no required presumption." },
        { label: "D", text: "Prepaid insurance", isCorrect: false, rationale: "No required presumption applies here." },
      ],
      explanation: "Auditing standards require the auditor to presume a fraud risk in revenue recognition and to treat management override of controls as a risk in every audit. The revenue presumption may be rebutted, but the auditor must document the reasons for concluding that no such risk exists.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["risk assessment", "fraud risk"],
    },
    {
      question: "When the auditor assesses control risk at the maximum, this means the auditor:",
      options: [
        { label: "A", text: "Has concluded the client has no internal controls at all", isCorrect: false, rationale: "Controls may exist; the auditor simply does not plan to rely on them." },
        { label: "B", text: "Does not plan to rely on controls and will perform primarily substantive procedures", isCorrect: true, rationale: "Correct — assessing control risk at maximum means relying on substantive procedures for audit evidence." },
        { label: "C", text: "Must issue a qualified opinion", isCorrect: false, rationale: "Control risk assessment does not determine the opinion." },
        { label: "D", text: "Must report a material weakness to those charged with governance", isCorrect: false, rationale: "Choosing not to rely on controls is not the same as identifying a material weakness." },
      ],
      explanation: "Assessing control risk at the maximum is a strategy decision, not a judgment that controls are absent. The auditor may decide testing controls would be inefficient, or that controls are unlikely to be effective, and instead obtain assurance substantively. The exception is where substantive procedures alone cannot provide sufficient evidence, such as highly automated environments.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["risk assessment", "control risk"],
    },
  ],

  "fraud-risk": [
    {
      question: "The three conditions of the fraud triangle are:",
      options: [
        { label: "A", text: "Incentive or pressure, opportunity, and rationalization", isCorrect: true, rationale: "Correct — these three conditions are generally present when fraud occurs." },
        { label: "B", text: "Materiality, risk, and evidence", isCorrect: false, rationale: "These are general audit concepts, not the fraud triangle." },
        { label: "C", text: "Collusion, concealment, and conversion", isCorrect: false, rationale: "These describe how frauds are executed, not the fraud triangle conditions." },
        { label: "D", text: "Inherent risk, control risk, and detection risk", isCorrect: false, rationale: "These are the components of the audit risk model." },
      ],
      explanation: "The fraud triangle identifies three conditions generally present when fraud occurs: an incentive or pressure to commit fraud, an opportunity created by weak controls or the ability to override them, and an attitude or rationalization allowing the person to justify the act. Auditors use this framework to identify fraud risk factors.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["fraud", "fraud triangle"],
    },
    {
      question: "What distinguishes fraud from error in an audit context?",
      options: [
        { label: "A", text: "The dollar magnitude of the misstatement", isCorrect: false, rationale: "Both fraud and error can be large or small; size is not the distinguishing factor." },
        { label: "B", text: "Whether the underlying action was intentional", isCorrect: true, rationale: "Correct — intent is the distinguishing characteristic between fraud and error." },
        { label: "C", text: "Whether the misstatement affects the balance sheet or the income statement", isCorrect: false, rationale: "The affected statement is irrelevant to the distinction." },
        { label: "D", text: "Whether the misstatement was detected by internal or external audit", isCorrect: false, rationale: "Who detects a misstatement does not determine its nature." },
      ],
      explanation: "Fraud is an intentional act involving deception that results in a misstatement; an error is unintentional. The auditor's responsibility is the same for both — to obtain reasonable assurance the statements are free of material misstatement whether caused by fraud or error — but fraud is harder to detect because it involves concealment and possibly collusion.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["fraud", "definitions"],
    },
    {
      question: "Which procedure is required in every audit to address the risk of management override of controls?",
      options: [
        { label: "A", text: "Confirming all related party balances with third parties", isCorrect: false, rationale: "This is not a required override procedure." },
        { label: "B", text: "Testing the appropriateness of journal entries and other adjustments", isCorrect: true, rationale: "Correct — testing journal entries is a required response to the always-present risk of management override." },
        { label: "C", text: "Performing a complete physical inventory count", isCorrect: false, rationale: "Inventory observation addresses inventory assertions, not override generally." },
        { label: "D", text: "Interviewing every employee in the accounting department", isCorrect: false, rationale: "Inquiries are made of appropriate individuals, not universally." },
      ],
      explanation: "Because management is uniquely able to override controls, the auditor must in every audit test the appropriateness of journal entries and other adjustments, review accounting estimates for bias, and evaluate the business rationale for significant unusual transactions. This risk cannot be assessed away.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["fraud", "management override"],
    },
    {
      question: "The auditor discovers evidence suggesting a material fraud involving senior management. The auditor should communicate this to:",
      options: [
        { label: "A", text: "Senior management only", isCorrect: false, rationale: "Reporting suspected fraud only to those possibly involved would be ineffective." },
        { label: "B", text: "Those charged with governance", isCorrect: true, rationale: "Correct — fraud involving senior management is communicated directly to those charged with governance, regardless of magnitude." },
        { label: "C", text: "The SEC, in all cases", isCorrect: false, rationale: "Direct reporting to outside parties is limited and generally arises only in specific legal or regulatory circumstances." },
        { label: "D", text: "The company's external legal counsel", isCorrect: false, rationale: "Counsel is not the required recipient of this communication." },
      ],
      explanation: "Fraud involving senior management, or any fraud causing a material misstatement, must be communicated to those charged with governance on a timely basis. Fraud involving lower-level employees may be reported to an appropriate level of management. Disclosure to parties outside the entity is generally precluded by confidentiality except in specific circumstances such as legal or regulatory requirements.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["fraud", "communication"],
    },
    {
      question: "The required brainstorming session among the engagement team regarding fraud must occur:",
      options: [
        { label: "A", text: "After substantive testing is complete", isCorrect: false, rationale: "The discussion must inform the audit approach, so it cannot wait until testing is finished." },
        { label: "B", text: "During planning, with ongoing communication throughout the audit", isCorrect: true, rationale: "Correct — the discussion occurs during planning and continues as the engagement progresses." },
        { label: "C", text: "Only when fraud risk factors have already been identified", isCorrect: false, rationale: "The discussion is required in every audit, not just where risks are already known." },
        { label: "D", text: "Only on audits of public companies", isCorrect: false, rationale: "The requirement applies to all audits." },
      ],
      explanation: "A discussion among key engagement team members about the susceptibility of the financial statements to material misstatement due to fraud is required in every audit, during planning. It emphasizes professional skepticism and sets aside any belief that management is honest, and communication about fraud risks continues throughout the engagement.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["fraud", "brainstorming"],
    },
  ],

  "responding-to-assessed-risks": [
    {
      question: "In response to a higher assessed risk of material misstatement, the auditor would most likely:",
      options: [
        { label: "A", text: "Perform more testing at an interim date rather than at year-end", isCorrect: false, rationale: "Higher risk pushes testing toward year-end, not away from it." },
        { label: "B", text: "Assign more experienced staff and perform procedures closer to period end", isCorrect: true, rationale: "Correct — higher risk calls for changes in the nature, timing, and extent of procedures, including staffing and timing." },
        { label: "C", text: "Reduce sample sizes to focus on quality over quantity", isCorrect: false, rationale: "Higher risk generally requires larger, not smaller, samples." },
        { label: "D", text: "Rely more heavily on inquiry of management", isCorrect: false, rationale: "Inquiry alone is weak evidence and is least appropriate where risk is high." },
      ],
      explanation: "The auditor responds to higher assessed risk by changing the nature (more reliable procedures such as external confirmation or inspection rather than inquiry), timing (closer to or at period end), and extent (larger samples) of procedures, and by assigning more experienced personnel with increased supervision.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["responding to risk", "further procedures"],
    },
    {
      question: "Tests of controls are performed to:",
      options: [
        { label: "A", text: "Detect material misstatements in account balances directly", isCorrect: false, rationale: "That is the purpose of substantive procedures." },
        { label: "B", text: "Evaluate the operating effectiveness of controls in preventing or detecting material misstatements", isCorrect: true, rationale: "Correct — tests of controls assess whether controls operated effectively during the period." },
        { label: "C", text: "Determine whether the financial statements are fairly presented", isCorrect: false, rationale: "That overall conclusion comes from the totality of audit evidence." },
        { label: "D", text: "Satisfy management's request for operational recommendations", isCorrect: false, rationale: "Tests of controls serve the audit, not management consulting." },
      ],
      explanation: "Tests of controls evaluate operating effectiveness and are performed when the auditor intends to rely on controls to reduce substantive testing, or when substantive procedures alone cannot provide sufficient appropriate evidence. Regardless of assessed control risk, some substantive procedures are always required for material classes of transactions and balances.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["responding to risk", "tests of controls"],
    },
    {
      question: "Which statement about substantive procedures is correct?",
      options: [
        { label: "A", text: "They may be omitted entirely if controls are found to be highly effective", isCorrect: false, rationale: "Substantive procedures can never be eliminated for material items." },
        { label: "B", text: "Some substantive procedures are required for each material class of transactions, balance, and disclosure", isCorrect: true, rationale: "Correct — effective controls reduce but never eliminate the need for substantive testing of material items." },
        { label: "C", text: "They are performed only when control risk is assessed at maximum", isCorrect: false, rationale: "They are performed in every audit regardless of the control risk assessment." },
        { label: "D", text: "They consist solely of analytical procedures", isCorrect: false, rationale: "Substantive procedures include both tests of details and substantive analytical procedures." },
      ],
      explanation: "Because of the inherent limitations of internal control — including management override — the auditor must perform substantive procedures for each material class of transactions, account balance, and disclosure, no matter how effective controls appear. Strong controls reduce the extent of substantive work but never remove the requirement.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["responding to risk", "substantive procedures"],
    },
    {
      question: "If the auditor performs tests of controls at an interim date, what is required regarding the remaining period?",
      options: [
        { label: "A", text: "Nothing further; interim testing covers the full year", isCorrect: false, rationale: "Interim testing does not automatically extend to the remaining period." },
        { label: "B", text: "Obtain evidence about the remaining period, such as testing whether significant changes occurred", isCorrect: true, rationale: "Correct — the auditor must determine what additional evidence is needed for the period between interim testing and year-end." },
        { label: "C", text: "Re-perform all interim tests at year-end", isCorrect: false, rationale: "Complete re-performance is not required; the extent depends on the assessed risk and remaining period length." },
        { label: "D", text: "Assess control risk at the maximum for the remaining period", isCorrect: false, rationale: "The auditor obtains evidence about the remaining period rather than defaulting to maximum control risk." },
      ],
      explanation: "When controls are tested at an interim date, the auditor must obtain evidence covering the remaining period — typically by inquiring about significant changes in the controls, testing a limited number of additional items, or considering the length of the remaining period and the assessed risk. Higher risk requires more evidence for the roll-forward period.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["responding to risk", "interim testing"],
    },
    {
      question: "Dual-purpose testing refers to a procedure that:",
      options: [
        { label: "A", text: "Is performed by two different auditors for corroboration", isCorrect: false, rationale: "Dual purpose refers to the objectives of the test, not the number of auditors." },
        { label: "B", text: "Simultaneously tests the operating effectiveness of a control and the monetary correctness of the transaction", isCorrect: true, rationale: "Correct — a single sample can serve both a test of controls and a substantive test of details." },
        { label: "C", text: "Tests both the current and prior year balances", isCorrect: false, rationale: "Testing two periods is not what dual purpose means." },
        { label: "D", text: "Addresses both financial and operational audit objectives", isCorrect: false, rationale: "The term is specific to combining control and substantive testing." },
      ],
      explanation: "A dual-purpose test uses one sample of transactions to evaluate both whether a control operated effectively and whether the transaction was recorded correctly in dollar terms. It improves efficiency, though the auditor must consider whether the sample size is adequate for both objectives.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["responding to risk", "dual-purpose tests"],
    },
  ],

  "audit-sampling": [
    {
      question: "Which sampling risk affects audit EFFECTIVENESS and is therefore of greater concern to the auditor?",
      options: [
        { label: "A", text: "The risk of assessing control risk too high", isCorrect: false, rationale: "This causes unnecessary additional testing — an efficiency problem, not an effectiveness one." },
        { label: "B", text: "The risk of incorrect acceptance", isCorrect: true, rationale: "Correct — accepting a materially misstated balance means an incorrect audit opinion, which is an effectiveness failure." },
        { label: "C", text: "The risk of incorrect rejection", isCorrect: false, rationale: "This leads to extra work to resolve an apparent misstatement that does not exist — an efficiency issue." },
        { label: "D", text: "Nonsampling risk", isCorrect: false, rationale: "Nonsampling risk is real but is not one of the sampling risks being compared here." },
      ],
      explanation: "Sampling risks come in pairs. Effectiveness risks — the risk of assessing control risk too low (overreliance) and the risk of incorrect acceptance — lead to an inappropriate audit opinion. Efficiency risks — assessing control risk too high and incorrect rejection — cause wasted effort but not a wrong opinion. Effectiveness risks are always the greater concern.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["sampling", "sampling risk"],
    },
    {
      question: "Attribute sampling is used primarily to:",
      options: [
        { label: "A", text: "Estimate the dollar amount of misstatement in an account balance", isCorrect: false, rationale: "That is the objective of variables sampling." },
        { label: "B", text: "Estimate the rate of deviation from a prescribed control", isCorrect: true, rationale: "Correct — attribute sampling measures how often a control fails, expressed as a rate." },
        { label: "C", text: "Select which accounts to confirm", isCorrect: false, rationale: "This describes a selection decision, not the purpose of attribute sampling." },
        { label: "D", text: "Determine overall materiality", isCorrect: false, rationale: "Materiality is a planning judgment, not a sampling result." },
      ],
      explanation: "Attribute sampling answers a yes-or-no question — did the control operate or not — and produces a deviation rate, making it the method for tests of controls. Variables sampling estimates a dollar amount and is used for substantive tests of details. A deviation in a control does not necessarily produce a dollar misstatement.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["sampling", "attribute sampling"],
    },
    {
      question: "Which change would cause the required sample size for a test of details to INCREASE?",
      options: [
        { label: "A", text: "An increase in tolerable misstatement", isCorrect: false, rationale: "A larger tolerable misstatement permits a smaller sample." },
        { label: "B", text: "A decrease in the assessed risk of material misstatement", isCorrect: false, rationale: "Lower assessed risk permits a smaller sample." },
        { label: "C", text: "An increase in the expected amount of misstatement in the population", isCorrect: true, rationale: "Correct — expecting more misstatement requires a larger sample to reach a reliable conclusion." },
        { label: "D", text: "An increase in the acceptable risk of incorrect acceptance", isCorrect: false, rationale: "Accepting more risk permits a smaller sample." },
      ],
      explanation: "Sample size rises as tolerable misstatement falls, as expected misstatement rises, as assessed risk rises, and as the acceptable risk of incorrect acceptance falls. Population size has surprisingly little effect on sample size for large populations — a frequently tested point.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["sampling", "sample size"],
    },
    {
      question: "In a test of controls, the auditor finds a deviation rate of 6% while the tolerable deviation rate is 5%. The auditor should:",
      options: [
        { label: "A", text: "Conclude the control is effective because the difference is small", isCorrect: false, rationale: "The sample results do not support the planned reliance when the rate exceeds tolerance." },
        { label: "B", text: "Increase the assessed level of control risk and modify planned substantive procedures", isCorrect: true, rationale: "Correct — the control cannot be relied upon as planned, so control risk rises and substantive testing expands." },
        { label: "C", text: "Issue a qualified opinion on the financial statements", isCorrect: false, rationale: "A control deviation rate does not by itself require opinion modification." },
        { label: "D", text: "Report a material weakness to the SEC", isCorrect: false, rationale: "Auditors do not report deficiencies directly to the SEC; communication goes to those charged with governance." },
      ],
      explanation: "When the sample deviation rate — adjusted for sampling risk — exceeds the tolerable rate, the auditor cannot rely on the control at the planned level. The response is to increase assessed control risk and perform more extensive substantive procedures, and to consider whether the deficiency should be communicated to those charged with governance.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["sampling", "tests of controls"],
    },
    {
      question: "Probability-proportional-to-size (PPS) sampling is most effective when the auditor:",
      options: [
        { label: "A", text: "Expects a large number of understatements", isCorrect: false, rationale: "PPS is poorly suited to detecting understatements, since zero and negative balances have little or no chance of selection." },
        { label: "B", text: "Expects few misstatements and is primarily concerned with overstatement", isCorrect: true, rationale: "Correct — PPS is efficient when few misstatements are expected and the concern is overstatement." },
        { label: "C", text: "Is testing a population of uniform, equal-value items", isCorrect: false, rationale: "PPS offers little advantage when all items are the same size." },
        { label: "D", text: "Is testing the completeness of accounts payable", isCorrect: false, rationale: "Completeness testing targets understatement and unrecorded items, where PPS is weak." },
      ],
      explanation: "PPS sampling gives each dollar an equal chance of selection, so larger balances are more likely to be selected — efficient for detecting overstatement in accounts like receivables and inventory. Its weaknesses are understatement testing, zero or negative balances, and populations with many expected misstatements.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["sampling", "PPS"],
    },
  ],

  "evidence-types-and-procedures": [
    {
      question: "Which source of audit evidence is generally considered most reliable?",
      options: [
        { label: "A", text: "Inquiry of client management", isCorrect: false, rationale: "Inquiry alone is the weakest form of evidence and generally requires corroboration." },
        { label: "B", text: "A confirmation received directly by the auditor from an independent third party", isCorrect: true, rationale: "Correct — externally generated evidence received directly by the auditor is the most reliable." },
        { label: "C", text: "Copies of invoices provided by the client", isCorrect: false, rationale: "Internally generated documents are less reliable, and copies more so than originals." },
        { label: "D", text: "The client's internally prepared account reconciliations", isCorrect: false, rationale: "Internally generated evidence is less reliable than external evidence." },
      ],
      explanation: "Evidence reliability increases with independence of source, effectiveness of internal control, and directness of the auditor's knowledge. The hierarchy runs roughly: the auditor's own direct observation and recalculation, external evidence received directly, external evidence held by the client, internal evidence with strong controls, and finally inquiry — the weakest.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["evidence", "reliability"],
    },
    {
      question: "The auditor decides not to confirm accounts receivable. This is acceptable only if:",
      options: [
        { label: "A", text: "The client requests that customers not be contacted", isCorrect: false, rationale: "A client request is a scope limitation that must be evaluated, not an automatic justification." },
        { label: "B", text: "Receivables are immaterial, confirmations would be ineffective, or the assessed risk is low and other substantive procedures address the risk", isCorrect: true, rationale: "Correct — these are the three recognized conditions permitting omission of confirmation." },
        { label: "C", text: "The auditor has confirmed receivables in each of the prior three years", isCorrect: false, rationale: "Prior year confirmation does not substitute for current year evidence." },
        { label: "D", text: "Internal controls over receivables are effective", isCorrect: false, rationale: "Effective controls reduce testing but do not alone justify omitting confirmation." },
      ],
      explanation: "External confirmation of accounts receivable is presumptively required. It may be omitted only if receivables are immaterial, confirmations would be ineffective, or the auditor's assessed risk of material misstatement is low and other substantive procedures address the assessed risk. The reasons must be documented.",
      difficulty: "HARD",
      questionType: "EXCEPTION",
      tags: ["evidence", "confirmations"],
    },
    {
      question: "A negative confirmation request asks the recipient to respond:",
      options: [
        { label: "A", text: "Whether they agree or disagree with the stated balance", isCorrect: false, rationale: "That describes a positive confirmation." },
        { label: "B", text: "Only if they disagree with the information stated", isCorrect: true, rationale: "Correct — silence is treated as agreement, which makes negative confirmations weaker evidence." },
        { label: "C", text: "With a complete listing of all transactions in the period", isCorrect: false, rationale: "This describes a blank or open confirmation form." },
        { label: "D", text: "Directly to client management rather than the auditor", isCorrect: false, rationale: "Confirmations must be returned directly to the auditor to remain reliable." },
      ],
      explanation: "Negative confirmations request a reply only if the recipient disagrees, so no response is ambiguous — it could mean agreement or that the request was ignored. They provide less persuasive evidence and are appropriate only when risk is low, controls are effective, a large number of small homogeneous balances exist, and a low exception rate is expected.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["evidence", "confirmations"],
    },
    {
      question: "Which audit procedure best addresses the COMPLETENESS assertion for accounts payable?",
      options: [
        { label: "A", text: "Selecting recorded payables and tracing them to supporting invoices", isCorrect: false, rationale: "Starting from the recorded balance tests existence, not completeness." },
        { label: "B", text: "Examining cash disbursements made after year-end for unrecorded liabilities", isCorrect: true, rationale: "Correct — the search for unrecorded liabilities works from outside the accounting records inward, testing completeness." },
        { label: "C", text: "Confirming recorded payable balances with vendors", isCorrect: false, rationale: "Confirming recorded balances primarily addresses existence and valuation of what is already recorded." },
        { label: "D", text: "Recalculating the accounts payable aging schedule", isCorrect: false, rationale: "This tests mathematical accuracy of recorded amounts." },
      ],
      explanation: "Direction of testing determines the assertion addressed. Tracing from source documents into the records tests completeness; vouching from records back to documents tests existence. Because payables are understated when fraud or error occurs, the search for unrecorded liabilities — reviewing post-year-end disbursements and unmatched invoices — is the key completeness procedure.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["evidence", "assertions", "completeness"],
    },
    {
      question: "The auditor's observation of the client's physical inventory count primarily provides evidence about:",
      options: [
        { label: "A", text: "The valuation of inventory at lower of cost and net realizable value", isCorrect: false, rationale: "Observation addresses quantities and condition, not the pricing decision." },
        { label: "B", text: "The existence and condition of inventory", isCorrect: true, rationale: "Correct — attending the count lets the auditor observe that inventory exists and note damaged or obsolete items." },
        { label: "C", text: "The client's legal title to the inventory", isCorrect: false, rationale: "Rights and obligations are tested through purchase documents, consignment agreements, and inquiry." },
        { label: "D", text: "The adequacy of inventory disclosures", isCorrect: false, rationale: "Disclosure adequacy is evaluated by reviewing the financial statements and notes." },
      ],
      explanation: "Observing the physical count provides evidence primarily about existence and, through the auditor's own observation of damaged or slow-moving goods, about condition. The auditor observes the client's procedures, makes test counts in both directions, and evaluates whether the count is properly controlled — but valuation, rights, and disclosure require separate procedures.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["evidence", "inventory observation"],
    },
  ],
};
