import type { McqBank } from "./types";

/** BAR question bank — all 13 topics. */
export const barBank: McqBank = {
  "financial-statement-analysis": [
    {
      question: "A company has current assets of $500,000, including inventory of $200,000 and prepaid expenses of $20,000, and current liabilities of $200,000. What is the quick ratio?",
      options: [
        { label: "A", text: "2.5", isCorrect: false, rationale: "2.5 is the current ratio, which includes inventory and prepaids." },
        { label: "B", text: "1.4", isCorrect: true, rationale: "Correct — ($500,000 − $200,000 − $20,000) ÷ $200,000 = $280,000 ÷ $200,000 = 1.4." },
        { label: "C", text: "1.5", isCorrect: false, rationale: "This excludes inventory but leaves prepaid expenses in the numerator." },
        { label: "D", text: "0.4", isCorrect: false, rationale: "This does not follow from the amounts given." },
      ],
      explanation: "The quick or acid-test ratio measures the ability to meet current obligations from the most liquid assets, excluding inventory and prepaid expenses because they cannot be converted to cash quickly. Quick assets of $280,000 divided by $200,000 of current liabilities gives 1.4.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["ratio analysis", "liquidity"],
    },
    {
      question: "Under the DuPont framework, return on equity is decomposed into:",
      options: [
        { label: "A", text: "Gross margin, operating margin, and net margin", isCorrect: false, rationale: "These are all profitability measures and do not decompose ROE." },
        { label: "B", text: "Net profit margin, asset turnover, and the equity multiplier", isCorrect: true, rationale: "Correct — these three components capture profitability, efficiency, and leverage." },
        { label: "C", text: "Current ratio, quick ratio, and cash ratio", isCorrect: false, rationale: "These are liquidity measures unrelated to ROE decomposition." },
        { label: "D", text: "Revenue growth, expense growth, and dividend payout", isCorrect: false, rationale: "These do not multiply to produce ROE." },
      ],
      explanation: "DuPont analysis separates ROE into net profit margin (profitability), asset turnover (efficiency), and the equity multiplier (leverage). It reveals why ROE changed — an improvement driven by leverage carries very different risk implications than one driven by margins or asset productivity.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["ratio analysis", "DuPont"],
    },
    {
      question: "Cost of goods sold was $1,200,000, beginning inventory was $180,000, and ending inventory was $220,000. What is inventory turnover?",
      options: [
        { label: "A", text: "6.0 times", isCorrect: true, rationale: "Correct — average inventory is ($180,000 + $220,000) ÷ 2 = $200,000, so $1,200,000 ÷ $200,000 = 6.0." },
        { label: "B", text: "5.5 times", isCorrect: false, rationale: "This uses ending inventory rather than the average." },
        { label: "C", text: "6.7 times", isCorrect: false, rationale: "This uses beginning inventory rather than the average." },
        { label: "D", text: "3.0 times", isCorrect: false, rationale: "This divides by total rather than average inventory." },
      ],
      explanation: "Inventory turnover is cost of goods sold divided by average inventory, measuring how many times inventory is sold and replaced during the period. Average inventory of $200,000 into $1,200,000 of COGS gives 6.0 turns, or roughly 61 days of inventory on hand.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["ratio analysis", "activity ratios"],
    },
    {
      question: "A company's times interest earned ratio declines sharply while its debt-to-equity ratio rises. This most likely indicates:",
      options: [
        { label: "A", text: "Improving financial flexibility", isCorrect: false, rationale: "Both movements point to weakening, not improving, flexibility." },
        { label: "B", text: "Increasing solvency risk, as earnings cover interest less comfortably while leverage grows", isCorrect: true, rationale: "Correct — the combination signals deteriorating ability to service growing debt." },
        { label: "C", text: "A shift from debt to equity financing", isCorrect: false, rationale: "A rising debt-to-equity ratio indicates the opposite shift." },
        { label: "D", text: "Improved short-term liquidity", isCorrect: false, rationale: "Neither ratio measures short-term liquidity." },
      ],
      explanation: "Times interest earned (EBIT divided by interest expense) measures the cushion between operating earnings and fixed financing costs. A falling ratio alongside rising leverage means the company is taking on more debt while its ability to service that debt weakens — a classic solvency warning pattern.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["ratio analysis", "solvency"],
    },
  ],

  "business-combinations-advanced": [
    {
      question: "In a step acquisition, an investor holding a 15% equity interest acquires an additional 60%, obtaining control. The previously held interest should be:",
      options: [
        { label: "A", text: "Carried forward at its existing book value", isCorrect: false, rationale: "Obtaining control is a significant economic event requiring remeasurement." },
        { label: "B", text: "Remeasured to fair value at the acquisition date, with any gain or loss in earnings", isCorrect: true, rationale: "Correct — the previously held interest is remeasured and the resulting gain or loss is recognized in income." },
        { label: "C", text: "Remeasured to fair value with the adjustment recorded in other comprehensive income", isCorrect: false, rationale: "The remeasurement gain or loss goes to earnings, not OCI." },
        { label: "D", text: "Eliminated against goodwill", isCorrect: false, rationale: "The prior interest is not written off against goodwill." },
      ],
      explanation: "When control is obtained in stages, the acquirer remeasures its previously held equity interest to acquisition-date fair value and recognizes the resulting gain or loss in earnings. That fair value then forms part of the consideration used to compute goodwill, alongside the newly transferred consideration and any noncontrolling interest.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["business combinations", "step acquisition"],
    },
    {
      question: "An entity must consolidate a variable interest entity when it is the primary beneficiary, meaning it has:",
      options: [
        { label: "A", text: "A majority of the voting equity interest", isCorrect: false, rationale: "The VIE model applies precisely where voting interests do not determine control." },
        { label: "B", text: "The power to direct the activities most significantly affecting economic performance and the obligation to absorb losses or right to receive benefits that could be significant", isCorrect: true, rationale: "Correct — both the power criterion and the economics criterion must be met." },
        { label: "C", text: "Any variable interest in the entity", isCorrect: false, rationale: "Holding a variable interest alone does not require consolidation." },
        { label: "D", text: "A contractual right to purchase the entity in the future", isCorrect: false, rationale: "A purchase option alone does not establish primary beneficiary status." },
      ],
      explanation: "The variable interest entity model applies where control is not achieved through voting rights. The primary beneficiary — the party with both power over the significant activities and exposure to potentially significant losses or benefits — consolidates the VIE. Only one party can be the primary beneficiary.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["consolidation", "VIE"],
    },
    {
      question: "A parent sells inventory to its 80%-owned subsidiary at a profit, and the subsidiary still holds the goods at year-end. In consolidation, the unrealized profit is:",
      options: [
        { label: "A", text: "Eliminated only to the extent of the parent's 80% ownership", isCorrect: false, rationale: "Intercompany profit is eliminated in full, regardless of ownership percentage." },
        { label: "B", text: "Eliminated in full, with the elimination allocated between controlling and noncontrolling interests for a subsidiary-to-parent sale", isCorrect: true, rationale: "Correct — full elimination is required; only the allocation of the effect depends on the direction of the sale." },
        { label: "C", text: "Not eliminated because the sale was to a separate legal entity", isCorrect: false, rationale: "Consolidation treats the group as one economic entity." },
        { label: "D", text: "Deferred and recognized over the subsidiary's operating cycle", isCorrect: false, rationale: "The profit is eliminated until the goods are sold outside the group." },
      ],
      explanation: "Intercompany profit remaining in ending inventory is eliminated in full, because from the consolidated entity's perspective nothing has been sold to an outside party. For a downstream sale from parent to subsidiary, the full elimination is charged to the controlling interest; for an upstream sale it is allocated between controlling and noncontrolling interests.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["consolidation", "intercompany profit"],
    },
    {
      question: "Push-down accounting, when applied, results in:",
      options: [
        { label: "A", text: "The subsidiary's separate financial statements reflecting the acquirer's new basis in the acquired assets and liabilities", isCorrect: true, rationale: "Correct — the acquirer's stepped-up basis is pushed down into the acquiree's own books." },
        { label: "B", text: "The parent restating its prior year consolidated statements", isCorrect: false, rationale: "Push-down affects the acquiree's separate statements, not prior period consolidations." },
        { label: "C", text: "Elimination of all goodwill from the transaction", isCorrect: false, rationale: "Goodwill may be recognized in the subsidiary's own statements under push-down." },
        { label: "D", text: "The subsidiary adopting the parent's fiscal year end", isCorrect: false, rationale: "Fiscal year alignment is a separate matter." },
      ],
      explanation: "Push-down accounting reflects the acquirer's new basis of accounting in the acquired entity's own separate financial statements. It is optional for the acquiree in a change-of-control event, and the election is made separately for each such event; once elected it is irrevocable.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["business combinations", "push-down accounting"],
    },
  ],

  "derivatives-and-hedge-accounting": [
    {
      question: "For a cash flow hedge, the effective portion of the change in the derivative's fair value is:",
      options: [
        { label: "A", text: "Recognized immediately in earnings", isCorrect: false, rationale: "That is the treatment for a fair value hedge." },
        { label: "B", text: "Recognized in other comprehensive income and reclassified to earnings when the hedged transaction affects earnings", isCorrect: true, rationale: "Correct — deferring the effective portion in OCI achieves the matching that hedge accounting exists to provide." },
        { label: "C", text: "Recorded directly in retained earnings", isCorrect: false, rationale: "Derivative gains and losses do not bypass the income statement or OCI." },
        { label: "D", text: "Not recognized until the derivative is settled", isCorrect: false, rationale: "Derivatives are remeasured to fair value each period regardless of settlement." },
      ],
      explanation: "A cash flow hedge protects against variability in future cash flows, such as a forecasted purchase or floating-rate interest. The effective portion of the derivative's gain or loss is deferred in OCI and reclassified into earnings in the period the hedged transaction affects earnings — matching the two.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["derivatives", "cash flow hedge"],
    },
    {
      question: "In a qualifying fair value hedge, the gain or loss on both the derivative and the hedged item attributable to the hedged risk are:",
      options: [
        { label: "A", text: "Both deferred in other comprehensive income", isCorrect: false, rationale: "OCI deferral characterizes cash flow hedges." },
        { label: "B", text: "Both recognized currently in earnings, offsetting each other", isCorrect: true, rationale: "Correct — recognizing both in earnings in the same period produces the offset that is the point of the hedge." },
        { label: "C", text: "Recognized in earnings and OCI respectively", isCorrect: false, rationale: "Splitting them would defeat the offset." },
        { label: "D", text: "Deferred until the hedged item is sold", isCorrect: false, rationale: "Fair value hedge accounting recognizes both currently." },
      ],
      explanation: "A fair value hedge offsets exposure to changes in the fair value of a recognized asset or liability or a firm commitment. Both the derivative's fair value change and the hedged item's change attributable to the hedged risk go through earnings in the same period, so any net effect represents only hedge ineffectiveness.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["derivatives", "fair value hedge"],
    },
    {
      question: "Which characteristic is NOT required for a financial instrument to be a derivative?",
      options: [
        { label: "A", text: "One or more underlyings and one or more notional amounts", isCorrect: false, rationale: "This is a required characteristic." },
        { label: "B", text: "Little or no initial net investment relative to other contracts with similar responses to market factors", isCorrect: false, rationale: "This is a required characteristic." },
        { label: "C", text: "Net settlement, by contract terms or through market mechanisms", isCorrect: false, rationale: "This is a required characteristic." },
        { label: "D", text: "Being traded on a registered securities exchange", isCorrect: true, rationale: "Correct — exchange trading is not required; many derivatives are privately negotiated over-the-counter contracts." },
      ],
      explanation: "A derivative has three defining characteristics: one or more underlyings and notional amounts, little or no initial net investment, and net settlement. Whether the contract trades on an exchange is irrelevant — forward contracts and swaps negotiated bilaterally are derivatives just as futures and listed options are.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["derivatives", "definition"],
    },
    {
      question: "To qualify for hedge accounting, an entity must, at inception:",
      options: [
        { label: "A", text: "Obtain approval from its external auditor", isCorrect: false, rationale: "Auditor approval is not a criterion for hedge accounting." },
        { label: "B", text: "Formally document the hedging relationship, the risk management objective, and how effectiveness will be assessed", isCorrect: true, rationale: "Correct — contemporaneous formal documentation at inception is mandatory." },
        { label: "C", text: "Demonstrate that the hedge will be perfectly effective", isCorrect: false, rationale: "Perfect effectiveness is not required; the hedge must be highly effective." },
        { label: "D", text: "Settle the derivative within one year", isCorrect: false, rationale: "No maximum term applies." },
      ],
      explanation: "Hedge accounting is elective and requires formal documentation at inception identifying the hedging instrument, the hedged item, the nature of the risk, the risk management objective and strategy, and the method for assessing effectiveness. Without contemporaneous documentation, hedge accounting is unavailable and the derivative is simply marked to market through earnings.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["derivatives", "hedge documentation"],
    },
  ],

  "foreign-currency-translation": [
    {
      question: "When a foreign subsidiary's functional currency is its local currency, the financial statements are converted using:",
      options: [
        { label: "A", text: "The temporal method, with remeasurement gains and losses in earnings", isCorrect: false, rationale: "The temporal method applies when the functional currency is the reporting currency." },
        { label: "B", text: "The current rate method, with the translation adjustment reported in other comprehensive income", isCorrect: true, rationale: "Correct — translation under the current rate method produces a cumulative translation adjustment in OCI." },
        { label: "C", text: "Historical rates for all accounts", isCorrect: false, rationale: "Only certain equity accounts use historical rates under the current rate method." },
        { label: "D", text: "The average rate for all balance sheet accounts", isCorrect: false, rationale: "Assets and liabilities use the current rate; the average rate applies to income statement items." },
      ],
      explanation: "Where the local currency is functional, translation uses the current rate method: assets and liabilities at the current rate, income statement items at the average rate, and equity at historical rates, with the balancing figure recorded as a cumulative translation adjustment in OCI. It stays in OCI until the foreign operation is sold or substantially liquidated.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["foreign currency", "translation"],
    },
    {
      question: "Under the temporal method of remeasurement, monetary assets and liabilities are converted at:",
      options: [
        { label: "A", text: "Historical exchange rates", isCorrect: false, rationale: "Historical rates apply to nonmonetary items under the temporal method." },
        { label: "B", text: "The current exchange rate, with the resulting gain or loss in earnings", isCorrect: true, rationale: "Correct — monetary items use the current rate and the remeasurement effect flows through income." },
        { label: "C", text: "The average rate for the period", isCorrect: false, rationale: "The average rate applies to most income statement items." },
        { label: "D", text: "The rate in effect at the beginning of the year", isCorrect: false, rationale: "The balance sheet date rate is used for monetary items." },
      ],
      explanation: "Under the temporal method, monetary items — cash, receivables, and payables — are remeasured at the current rate, while nonmonetary items such as inventory, fixed assets, and their related expenses stay at historical rates. The remeasurement gain or loss goes to earnings, not OCI, which is the central contrast with translation.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["foreign currency", "remeasurement"],
    },
    {
      question: "A foreign subsidiary operates in a highly inflationary economy. The entity must:",
      options: [
        { label: "A", text: "Continue using the local currency as the functional currency", isCorrect: false, rationale: "Highly inflationary status specifically overrides local currency treatment." },
        { label: "B", text: "Use the reporting currency as the functional currency and remeasure using the temporal method", isCorrect: true, rationale: "Correct — the reporting currency becomes functional, so remeasurement gains and losses run through earnings." },
        { label: "C", text: "Restate the statements for inflation before translating", isCorrect: false, rationale: "Inflation restatement is the IFRS approach; US GAAP requires remeasurement instead." },
        { label: "D", text: "Cease consolidating the subsidiary", isCorrect: false, rationale: "Inflation does not affect the consolidation decision." },
      ],
      explanation: "Where cumulative inflation approximates 100% or more over three years, the economy is highly inflationary and the local currency is not sufficiently stable to serve as functional. US GAAP requires the reporting currency to be treated as the functional currency, so the temporal method applies and gains and losses hit earnings.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["foreign currency", "highly inflationary"],
    },
    {
      question: "A foreign currency transaction gain arising from settling a receivable denominated in a foreign currency is:",
      options: [
        { label: "A", text: "Deferred in other comprehensive income", isCorrect: false, rationale: "OCI treatment applies to translation adjustments, not transaction gains and losses." },
        { label: "B", text: "Recognized in earnings in the period the exchange rate changes", isCorrect: true, rationale: "Correct — transaction gains and losses are recognized currently in income." },
        { label: "C", text: "Recorded as an adjustment to the original sales revenue", isCorrect: false, rationale: "Revenue is fixed at the transaction date rate; subsequent changes are separate gains or losses." },
        { label: "D", text: "Ignored until the receivable is written off", isCorrect: false, rationale: "Rate changes are recognized as they occur, including at each balance sheet date." },
      ],
      explanation: "A foreign currency transaction is one denominated in a currency other than the entity's functional currency. The receivable is recorded at the spot rate on the transaction date, remeasured at each balance sheet date, and settled at the settlement date rate, with the resulting gains and losses recognized in earnings each period.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["foreign currency", "transactions"],
    },
  ],

  "employee-benefit-plan-accounting": [
    {
      question: "The fair value of plan assets is $900,000 and the projected benefit obligation is $1,100,000. What is reported on the balance sheet?",
      options: [
        { label: "A", text: "A net pension asset of $200,000", isCorrect: false, rationale: "The plan is underfunded, producing a liability rather than an asset." },
        { label: "B", text: "A net pension liability of $200,000", isCorrect: true, rationale: "Correct — the funded status is a $200,000 deficit, reported as a liability." },
        { label: "C", text: "A pension liability of $1,100,000 and a separate asset of $900,000", isCorrect: false, rationale: "The funded status is reported net, not gross." },
        { label: "D", text: "No amount, with disclosure only in the notes", isCorrect: false, rationale: "The funded status must be recognized on the balance sheet." },
      ],
      explanation: "An employer recognizes the funded status — plan assets at fair value less the projected benefit obligation — as a net asset or net liability on the balance sheet. Here the $200,000 shortfall is a net pension liability. Unrecognized prior service costs and actuarial gains and losses sit in accumulated OCI and amortize into pension expense over time.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["pensions", "funded status"],
    },
    {
      question: "Which component REDUCES net periodic pension cost?",
      options: [
        { label: "A", text: "Service cost", isCorrect: false, rationale: "Service cost increases pension expense." },
        { label: "B", text: "Interest cost on the projected benefit obligation", isCorrect: false, rationale: "Interest cost increases pension expense." },
        { label: "C", text: "Expected return on plan assets", isCorrect: true, rationale: "Correct — the expected return is subtracted in computing net periodic pension cost." },
        { label: "D", text: "Amortization of prior service cost", isCorrect: false, rationale: "Amortization of prior service cost generally increases pension expense." },
      ],
      explanation: "Net periodic pension cost combines service cost, interest cost, expected return on plan assets (a reduction), amortization of prior service cost, and amortization of net gains or losses. Only service cost is reported in operating expense; the other components are presented outside operating income.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["pensions", "pension expense"],
    },
    {
      question: "The projected benefit obligation differs from the accumulated benefit obligation in that the PBO:",
      options: [
        { label: "A", text: "Excludes the effect of future salary increases", isCorrect: false, rationale: "This describes the ABO, which uses current salary levels." },
        { label: "B", text: "Incorporates assumptions about future compensation levels", isCorrect: true, rationale: "Correct — the PBO reflects projected future salaries, making it larger for pay-related plans." },
        { label: "C", text: "Includes only vested benefits", isCorrect: false, rationale: "That describes the vested benefit obligation." },
        { label: "D", text: "Is measured at the plan's inception only", isCorrect: false, rationale: "The PBO is remeasured at each reporting date." },
      ],
      explanation: "The accumulated benefit obligation measures benefits earned using current salary levels. The projected benefit obligation incorporates estimated future salary increases, and is therefore larger for plans whose benefits depend on final pay. The PBO is the measure used for the balance sheet funded status.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["pensions", "PBO"],
    },
  ],

  "stock-compensation": [
    {
      question: "A company grants 10,000 stock options with a grant-date fair value of $6 each, vesting over three years. What compensation expense is recognized in year one, assuming no forfeitures?",
      options: [
        { label: "A", text: "$60,000", isCorrect: false, rationale: "This recognizes the entire cost immediately rather than over the service period." },
        { label: "B", text: "$20,000", isCorrect: true, rationale: "Correct — total cost of $60,000 spread over the three-year requisite service period gives $20,000 per year." },
        { label: "C", text: "$6,000", isCorrect: false, rationale: "This does not correspond to the grant-date fair value and vesting period given." },
        { label: "D", text: "$0, because no options have been exercised", isCorrect: false, rationale: "Expense is recognized as the service is rendered, not on exercise." },
      ],
      explanation: "Share-based compensation is measured at grant-date fair value and recognized over the requisite service period — typically the vesting period. Total cost is 10,000 × $6 = $60,000, spread evenly over three years at $20,000 per year. Subsequent changes in the share price do not change the expense for equity-classified awards.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["stock compensation", "expense recognition"],
    },
    {
      question: "For an equity-classified share-based payment award, the fair value is:",
      options: [
        { label: "A", text: "Remeasured at each reporting date until settlement", isCorrect: false, rationale: "Remeasurement is required for liability-classified awards, not equity-classified ones." },
        { label: "B", text: "Measured once at the grant date and not subsequently remeasured", isCorrect: true, rationale: "Correct — grant-date measurement is fixed for equity-classified awards." },
        { label: "C", text: "Measured at the exercise date", isCorrect: false, rationale: "Exercise-date measurement is not used under current guidance." },
        { label: "D", text: "Equal to the intrinsic value at each balance sheet date", isCorrect: false, rationale: "Intrinsic value measurement is not the general model." },
      ],
      explanation: "Equity-classified awards are measured at grant-date fair value and that measurement is locked in, so later share price movements do not affect expense. Liability-classified awards — such as cash-settled share appreciation rights — are remeasured to fair value each reporting date until settlement, creating earnings volatility.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["stock compensation", "classification"],
    },
    {
      question: "How does a company account for share-based awards with a performance condition that is not probable of being achieved?",
      options: [
        { label: "A", text: "Recognize the full compensation cost immediately", isCorrect: false, rationale: "Cost is not recognized while achievement is improbable." },
        { label: "B", text: "Recognize no compensation cost, reassessing probability each period", isCorrect: true, rationale: "Correct — cost is recognized only when achievement of the performance condition becomes probable." },
        { label: "C", text: "Recognize cost based on the estimated probability percentage", isCorrect: false, rationale: "A probability-weighted amount is not recognized for performance conditions." },
        { label: "D", text: "Reverse all previously recognized cost permanently", isCorrect: false, rationale: "Assessment continues each period and cost may be recognized later if probability changes." },
      ],
      explanation: "For awards with a performance condition, compensation cost is recognized only if achievement is probable, and the assessment is revisited each reporting period with a cumulative catch-up when the estimate changes. Market conditions are treated differently: their effect is built into the grant-date fair value and cost is recognized regardless of whether the market condition is met.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["stock compensation", "performance conditions"],
    },
  ],

  "revenue-for-specific-industries": [
    {
      question: "Under the input method for a long-term construction contract, revenue is recognized based on:",
      options: [
        { label: "A", text: "Cash collected from the customer to date", isCorrect: false, rationale: "Cash collection does not measure progress toward satisfying the obligation." },
        { label: "B", text: "Costs incurred to date relative to total expected costs", isCorrect: true, rationale: "Correct — the cost-to-cost approach is the most common input method for measuring progress." },
        { label: "C", text: "The number of contracts signed during the period", isCorrect: false, rationale: "Contract volume does not measure progress on any individual contract." },
        { label: "D", text: "Milestone billings issued to the customer", isCorrect: false, rationale: "Billing schedules are negotiated and may not reflect actual progress." },
      ],
      explanation: "When a performance obligation is satisfied over time, progress is measured by an input method (costs incurred, labor hours, or resources consumed) or an output method (units delivered, milestones achieved). The cost-to-cost input method is most common in construction, though costs of uninstalled materials may require adjustment so progress is not overstated.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["revenue recognition", "construction"],
    },
    {
      question: "A contract is expected to result in an overall loss. Under ASC 606, the entity should:",
      options: [
        { label: "A", text: "Recognize the loss proportionately as the contract progresses", isCorrect: false, rationale: "Anticipated losses are recognized immediately in full." },
        { label: "B", text: "Recognize the entire expected loss immediately in the period it becomes evident", isCorrect: true, rationale: "Correct — expected contract losses are recognized in full as soon as they become known." },
        { label: "C", text: "Defer the loss until the contract is complete", isCorrect: false, rationale: "Deferral would misrepresent the entity's position." },
        { label: "D", text: "Record the loss as an adjustment to opening retained earnings", isCorrect: false, rationale: "It is a current period charge, not a prior period adjustment." },
      ],
      explanation: "Conservatism requires immediate recognition of an expected loss on a contract as soon as it becomes evident, regardless of the stage of completion. Profits are recognized only as performance occurs, but anticipated losses are never spread — an asymmetry that appears throughout US GAAP.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["revenue recognition", "contract losses"],
    },
    {
      question: "A franchisor receives an initial franchise fee and will provide ongoing support plus the right to use its brand. The initial fee should generally be:",
      options: [
        { label: "A", text: "Recognized entirely when the franchise agreement is signed", isCorrect: false, rationale: "Signing does not by itself satisfy the performance obligations." },
        { label: "B", text: "Allocated among the identified performance obligations and recognized as each is satisfied", isCorrect: true, rationale: "Correct — the general ASC 606 model applies, with the license to symbolic IP typically recognized over the franchise term." },
        { label: "C", text: "Deferred until the franchise ceases operations", isCorrect: false, rationale: "There is no basis for deferring recognition that long." },
        { label: "D", text: "Recognized on a cash basis as fees are collected", isCorrect: false, rationale: "Cash receipt does not drive recognition under ASC 606." },
      ],
      explanation: "A franchise arrangement typically grants a license to symbolic intellectual property — a brand whose value depends on the franchisor's continuing activities — which is a right to access, satisfied over time. Any distinct pre-opening goods or services are separate obligations recognized when satisfied, with the transaction price allocated by relative standalone selling price.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["revenue recognition", "franchises"],
    },
  ],

  "lease-accounting-lessor": [
    {
      question: "A lessor classifies a lease as a direct financing lease rather than a sales-type lease when:",
      options: [
        { label: "A", text: "The lease transfers control of the underlying asset to the lessee", isCorrect: false, rationale: "Transfer of control indicates a sales-type lease." },
        { label: "B", text: "None of the sales-type criteria are met, but the present value of payments plus a residual value guarantee from a third party equals or exceeds substantially all of fair value, and collection is probable", isCorrect: true, rationale: "Correct — a third-party residual guarantee is the distinguishing feature of a direct financing lease." },
        { label: "C", text: "The lease term exceeds ten years", isCorrect: false, rationale: "Lease term alone does not drive this distinction." },
        { label: "D", text: "The lessor is a manufacturer of the leased asset", isCorrect: false, rationale: "Manufacturer status suggests a sales-type lease with selling profit." },
      ],
      explanation: "A lessor first tests the sales-type criteria, which mirror the lessee's finance lease tests. If none are met, the lease is a direct financing lease when the present value of lease payments plus any residual value guaranteed by a party other than the lessee amounts to substantially all of the asset's fair value and collection is probable. Otherwise it is an operating lease.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["leases", "lessor classification"],
    },
    {
      question: "In a lessor's operating lease, the underlying asset is:",
      options: [
        { label: "A", text: "Derecognized, with a net investment in the lease recorded", isCorrect: false, rationale: "Derecognition occurs in sales-type and direct financing leases." },
        { label: "B", text: "Retained on the lessor's books and depreciated, with lease income recognized on a straight-line basis", isCorrect: true, rationale: "Correct — an operating lease leaves the asset with the lessor, who continues to depreciate it." },
        { label: "C", text: "Written down to fair value at commencement", isCorrect: false, rationale: "No write-down is triggered by entering an operating lease." },
        { label: "D", text: "Transferred to the lessee's balance sheet only", isCorrect: false, rationale: "The lessee records a right-of-use asset, but the lessor keeps the underlying asset." },
      ],
      explanation: "In a lessor operating lease, no sale has occurred: the asset stays on the lessor's balance sheet and continues to be depreciated over its useful life, while lease income is recognized on a straight-line basis over the lease term. Note that both lessor and lessee report assets relating to the same item, which is a deliberate feature of ASC 842.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["leases", "lessor operating lease"],
    },
    {
      question: "Selling profit recognized by a lessor in a sales-type lease is measured as:",
      options: [
        { label: "A", text: "Total lease payments less the carrying amount of the asset", isCorrect: false, rationale: "Undiscounted payments overstate the profit by including interest." },
        { label: "B", text: "The fair value of the underlying asset (or present value of lease payments if lower) less its carrying amount", isCorrect: true, rationale: "Correct — selling profit is the normal margin on the sale, excluding the interest element." },
        { label: "C", text: "The residual value of the asset at the end of the lease", isCorrect: false, rationale: "Residual value is a component of the net investment, not the selling profit." },
        { label: "D", text: "Zero, because lessors never recognize profit at commencement", isCorrect: false, rationale: "Sales-type leases recognize selling profit at commencement." },
      ],
      explanation: "Selling profit in a sales-type lease is the difference between the fair value of the underlying asset — or the present value of lease payments if lower — and the asset's carrying amount, less any deferred initial direct costs. Interest income is recognized separately over the lease term as the net investment unwinds.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["leases", "sales-type lease"],
    },
  ],

  "financial-forecasting-and-projections": [
    {
      question: "The essential difference between a financial forecast and a financial projection is that a projection:",
      options: [
        { label: "A", text: "Covers a longer time horizon", isCorrect: false, rationale: "Time horizon is not the distinguishing feature." },
        { label: "B", text: "Is based on one or more hypothetical assumptions answering a 'what if' question", isCorrect: true, rationale: "Correct — a projection incorporates hypothetical assumptions, while a forecast reflects expected conditions." },
        { label: "C", text: "Is prepared only for internal management use", isCorrect: false, rationale: "Intended use affects distribution restrictions, not the definition." },
        { label: "D", text: "Must be audited before distribution", isCorrect: false, rationale: "Neither type is subject to an audit requirement." },
      ],
      explanation: "A financial forecast presents expected results based on conditions management expects to exist and the course of action it expects to take. A projection presents results given one or more hypothetical assumptions — 'what if we opened twenty new locations' — and its use is restricted to parties negotiating directly with the responsible party.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["prospective information", "forecasts"],
    },
    {
      question: "In a sensitivity analysis of a financial model, the analyst:",
      options: [
        { label: "A", text: "Changes all assumptions simultaneously to a worst-case scenario", isCorrect: false, rationale: "That describes scenario analysis rather than sensitivity analysis." },
        { label: "B", text: "Varies one key assumption at a time to observe the effect on the outcome", isCorrect: true, rationale: "Correct — isolating one variable reveals which assumptions drive the result." },
        { label: "C", text: "Eliminates uncertainty from the forecast", isCorrect: false, rationale: "Sensitivity analysis measures the effect of uncertainty; it cannot remove it." },
        { label: "D", text: "Replaces estimates with historical actual results", isCorrect: false, rationale: "That would convert the forecast into historical reporting." },
      ],
      explanation: "Sensitivity analysis isolates the effect of individual assumptions by varying one at a time, identifying which inputs most influence the outcome and therefore deserve the most attention. Scenario analysis instead changes a coherent set of assumptions together to model a whole state of the world.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["forecasting", "sensitivity analysis"],
    },
    {
      question: "The percentage-of-sales method of forecasting assumes that:",
      options: [
        { label: "A", text: "All expenses are fixed regardless of sales volume", isCorrect: false, rationale: "The method assumes certain items vary with sales, not that all are fixed." },
        { label: "B", text: "Certain balance sheet and income statement items maintain a stable relationship to sales", isCorrect: true, rationale: "Correct — the method projects items that historically move proportionally with sales." },
        { label: "C", text: "Sales will grow at a constant rate indefinitely", isCorrect: false, rationale: "The method forecasts items given a sales level; it does not assume a growth rate." },
        { label: "D", text: "Net income equals a fixed percentage of assets", isCorrect: false, rationale: "This is not the assumption underlying the method." },
      ],
      explanation: "The percentage-of-sales method projects items that historically vary proportionally with sales — cost of goods sold, receivables, inventory, and payables — as a constant percentage, then identifies external financing needed to balance the projected statements. Its weakness is that fixed costs and step-function capacity additions do not scale proportionally.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["forecasting", "percentage of sales"],
    },
  ],

  "data-analytics-for-accounting": [
    {
      question: "An analysis that answers the question 'what is likely to happen next' is best described as:",
      options: [
        { label: "A", text: "Descriptive analytics", isCorrect: false, rationale: "Descriptive analytics summarizes what has already happened." },
        { label: "B", text: "Predictive analytics", isCorrect: true, rationale: "Correct — predictive analytics uses historical patterns to forecast future outcomes." },
        { label: "C", text: "Diagnostic analytics", isCorrect: false, rationale: "Diagnostic analytics explains why something happened." },
        { label: "D", text: "Prescriptive analytics", isCorrect: false, rationale: "Prescriptive analytics recommends what action to take." },
      ],
      explanation: "The four types form a progression of sophistication: descriptive (what happened), diagnostic (why it happened), predictive (what will happen), and prescriptive (what should be done). Predictive techniques such as regression and classification models estimate future outcomes from historical relationships.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["data analytics", "analytics types"],
    },
    {
      question: "In the ETL process used to prepare data for analysis, the transformation stage involves:",
      options: [
        { label: "A", text: "Retrieving data from source systems", isCorrect: false, rationale: "That is the extraction stage." },
        { label: "B", text: "Cleaning, standardizing, and restructuring data into a consistent, analysis-ready form", isCorrect: true, rationale: "Correct — transformation resolves inconsistencies, formats, duplicates, and missing values." },
        { label: "C", text: "Writing the data into the target repository", isCorrect: false, rationale: "That is the loading stage." },
        { label: "D", text: "Building visualizations from the finished dataset", isCorrect: false, rationale: "Visualization occurs after the data is loaded." },
      ],
      explanation: "Extract, transform, load describes moving data from source systems into an analysis environment. Transformation is usually the most demanding stage: resolving inconsistent formats, standardizing units and date conventions, removing duplicates, and handling missing values. Poor transformation silently corrupts every analysis built on the data.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["data analytics", "ETL"],
    },
    {
      question: "Which visualization is most appropriate for showing the composition of total expenses across several categories at a single point in time?",
      options: [
        { label: "A", text: "A line chart", isCorrect: false, rationale: "Line charts are best for showing trends over time." },
        { label: "B", text: "A stacked bar or pie chart", isCorrect: true, rationale: "Correct — these display parts of a whole effectively for a single period." },
        { label: "C", text: "A scatter plot", isCorrect: false, rationale: "Scatter plots display the relationship between two continuous variables." },
        { label: "D", text: "A histogram", isCorrect: false, rationale: "Histograms show the frequency distribution of a single variable." },
      ],
      explanation: "Matching the chart to the analytical question is fundamental: composition at a point in time suits stacked bars or pie charts, trends over time suit line charts, relationships between variables suit scatter plots, and distributions suit histograms or box plots. A mismatch obscures rather than reveals the finding.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["data analytics", "visualization"],
    },
    {
      question: "Testing 100% of a population of transactions rather than a sample is increasingly feasible because:",
      options: [
        { label: "A", text: "Auditing standards now prohibit sampling", isCorrect: false, rationale: "Sampling remains a permitted and widely used approach." },
        { label: "B", text: "Analytics tools can process complete datasets, though the auditor must still evaluate the exceptions identified", isCorrect: true, rationale: "Correct — full-population testing eliminates sampling risk but generates exceptions requiring professional judgment." },
        { label: "C", text: "Full-population testing eliminates the need for professional judgment", isCorrect: false, rationale: "Judgment is still required to evaluate what the analysis surfaces." },
        { label: "D", text: "Complete datasets are always free from error", isCorrect: false, rationale: "Data quality issues remain a significant concern." },
      ],
      explanation: "Analyzing entire populations removes sampling risk, but it does not remove the need for judgment — and it can surface large volumes of exceptions that are not actual misstatements. The auditor must still assess the reliability and completeness of the data and evaluate whether identified items represent real misstatements.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["data analytics", "audit applications"],
    },
  ],

  "governmental-fund-accounting": [
    {
      question: "Which fund balance classification represents amounts constrained by a formal action of the government's highest level of decision-making authority?",
      options: [
        { label: "A", text: "Restricted", isCorrect: false, rationale: "Restricted amounts are constrained externally, by creditors, grantors, or enabling legislation." },
        { label: "B", text: "Committed", isCorrect: true, rationale: "Correct — committed fund balance results from formal action by the government's highest decision-making authority." },
        { label: "C", text: "Assigned", isCorrect: false, rationale: "Assigned amounts reflect intent expressed at a lower level of authority." },
        { label: "D", text: "Unassigned", isCorrect: false, rationale: "Unassigned is the residual classification in the General Fund." },
      ],
      explanation: "Fund balance is reported in five classifications reflecting the strength of the constraint: nonspendable, restricted (external constraints), committed (formal action of the highest authority, reversible only by the same type of action), assigned (intent), and unassigned (residual, generally only in the General Fund).",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["governmental", "fund balance"],
    },
    {
      question: "In a governmental fund, the acquisition of a police vehicle is recorded as:",
      options: [
        { label: "A", text: "A capital asset, depreciated over its useful life", isCorrect: false, rationale: "Governmental funds do not report capital assets or record depreciation." },
        { label: "B", text: "An expenditure in the period of acquisition", isCorrect: true, rationale: "Correct — under the current financial resources focus, the full cost is an expenditure when acquired." },
        { label: "C", text: "A prepaid asset amortized over the useful life", isCorrect: false, rationale: "This is not the treatment under modified accrual." },
        { label: "D", text: "An other financing use", isCorrect: false, rationale: "Other financing sources and uses cover items such as debt proceeds and transfers." },
      ],
      explanation: "Because governmental funds measure current financial resources, purchasing a capital asset consumes spendable resources and is recorded entirely as an expenditure. The asset is then reported and depreciated only in the government-wide statements, and the difference is one of the key reconciling items between the two presentations.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["governmental", "expenditures"],
    },
    {
      question: "A Capital Projects Fund is used to account for:",
      options: [
        { label: "A", text: "The repayment of general long-term debt principal and interest", isCorrect: false, rationale: "That is the purpose of a Debt Service Fund." },
        { label: "B", text: "Financial resources restricted or committed to the acquisition or construction of major capital facilities", isCorrect: true, rationale: "Correct — the fund tracks resources dedicated to major capital projects." },
        { label: "C", text: "Resources held in trust for individuals or other governments", isCorrect: false, rationale: "That describes fiduciary funds." },
        { label: "D", text: "Ongoing general operations of the government", isCorrect: false, rationale: "General operations are accounted for in the General Fund." },
      ],
      explanation: "A Capital Projects Fund accounts for financial resources restricted, committed, or assigned to the acquisition or construction of major capital facilities other than those financed by proprietary or trust funds. Note that the completed asset itself is not reported in the fund — it appears only in the government-wide statements.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["governmental", "capital projects fund"],
    },
  ],

  "government-wide-financial-statements": [
    {
      question: "Government-wide financial statements report using:",
      options: [
        { label: "A", text: "The current financial resources focus and modified accrual basis", isCorrect: false, rationale: "That combination applies to governmental fund statements." },
        { label: "B", text: "The economic resources measurement focus and full accrual basis", isCorrect: true, rationale: "Correct — government-wide statements use full accrual, reporting all assets and liabilities." },
        { label: "C", text: "The cash basis", isCorrect: false, rationale: "The cash basis is not used for government-wide reporting." },
        { label: "D", text: "The budgetary basis of accounting", isCorrect: false, rationale: "Budgetary comparisons are presented separately as supplementary information." },
      ],
      explanation: "Government-wide statements — the statement of net position and the statement of activities — use the economic resources measurement focus and full accrual basis, reporting capital assets, long-term debt, and depreciation. Fiduciary funds are excluded because those resources are not available to support the government's own programs.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["governmental", "government-wide"],
    },
    {
      question: "Which is reported as a program revenue in the government-wide statement of activities?",
      options: [
        { label: "A", text: "General property taxes", isCorrect: false, rationale: "General taxes are general revenues, not attributable to a specific program." },
        { label: "B", text: "Charges for services provided by a specific function", isCorrect: true, rationale: "Correct — charges for services are program revenues offsetting the cost of that function." },
        { label: "C", text: "Unrestricted investment earnings", isCorrect: false, rationale: "Unrestricted investment earnings are general revenues." },
        { label: "D", text: "Unrestricted grants received from the state", isCorrect: false, rationale: "Unrestricted grants are general revenues." },
      ],
      explanation: "The statement of activities presents expenses by function, offset by program revenues — charges for services, operating grants and contributions, and capital grants and contributions — to display the net cost of each function. General revenues such as taxes and unrestricted grants are reported below, showing how the net cost is financed.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["governmental", "statement of activities"],
    },
    {
      question: "Which item requires an adjustment when reconciling governmental fund balance to government-wide net position?",
      options: [
        { label: "A", text: "Cash held in the General Fund", isCorrect: false, rationale: "Cash is reported identically under both presentations." },
        { label: "B", text: "Capital assets and long-term liabilities not reported in governmental funds", isCorrect: true, rationale: "Correct — these are reported only at the government-wide level and are the largest reconciling items." },
        { label: "C", text: "Current year property tax collections", isCorrect: false, rationale: "Timing differences may arise, but this is not the principal structural reconciling item." },
        { label: "D", text: "Salaries paid during the year", isCorrect: false, rationale: "Routine salary payments are recognized in both presentations." },
      ],
      explanation: "Reconciliation from governmental funds to government-wide statements adds capital assets net of accumulated depreciation, subtracts long-term liabilities such as bonds and compensated absences, and adjusts for internal service fund balances and revenues earned but unavailable under modified accrual. GASB requires the reconciliation on the face of the statements or in an accompanying schedule.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["governmental", "reconciliation"],
    },
  ],

  "public-company-reporting-topics": [
    {
      question: "Section 302 of the Sarbanes-Oxley Act requires that:",
      options: [
        { label: "A", text: "The external auditor attest to internal control over financial reporting", isCorrect: false, rationale: "The auditor attestation requirement arises under Section 404(b)." },
        { label: "B", text: "The CEO and CFO personally certify the accuracy of periodic reports and the effectiveness of disclosure controls", isCorrect: true, rationale: "Correct — Section 302 imposes personal certification obligations on the principal executive and financial officers." },
        { label: "C", text: "All public companies rotate audit firms every five years", isCorrect: false, rationale: "SOX requires rotation of the lead audit partner, not of the firm." },
        { label: "D", text: "Companies disclose all related party transactions in an 8-K", isCorrect: false, rationale: "This is not a Section 302 requirement." },
      ],
      explanation: "Section 302 requires the CEO and CFO to certify in each periodic report that they reviewed it, that it contains no material misstatements or omissions, that it fairly presents the financial condition and results, and that they are responsible for and have evaluated disclosure controls and procedures.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SOX", "certification"],
    },
    {
      question: "Under Section 404 of the Sarbanes-Oxley Act, management must:",
      options: [
        { label: "A", text: "Guarantee that no fraud will occur in the company", isCorrect: false, rationale: "No internal control system can guarantee the absence of fraud." },
        { label: "B", text: "Assess and report on the effectiveness of the company's internal control over financial reporting", isCorrect: true, rationale: "Correct — Section 404(a) requires management's annual assessment and report." },
        { label: "C", text: "Obtain shareholder approval for all internal control changes", isCorrect: false, rationale: "No shareholder approval requirement exists." },
        { label: "D", text: "Rotate the chief financial officer every five years", isCorrect: false, rationale: "No such rotation requirement exists." },
      ],
      explanation: "Section 404(a) requires management's annual assessment of the effectiveness of internal control over financial reporting, using a recognized framework such as COSO. Section 404(b) requires the external auditor to attest to that effectiveness, though smaller reporting companies and non-accelerated filers are exempt from the auditor attestation.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SOX", "internal control"],
    },
    {
      question: "A non-GAAP financial measure presented in an earnings release must:",
      options: [
        { label: "A", text: "Be presented more prominently than the comparable GAAP measure", isCorrect: false, rationale: "SEC rules prohibit giving the non-GAAP measure greater prominence." },
        { label: "B", text: "Be reconciled to the most directly comparable GAAP measure, which must not be less prominent", isCorrect: true, rationale: "Correct — Regulation G requires reconciliation and prohibits undue prominence for the non-GAAP figure." },
        { label: "C", text: "Be audited before release", isCorrect: false, rationale: "Non-GAAP measures in earnings releases are not audited." },
        { label: "D", text: "Be approved in advance by the SEC", isCorrect: false, rationale: "No advance SEC approval is required." },
      ],
      explanation: "Regulation G requires that any non-GAAP measure disclosed publicly be accompanied by the most directly comparable GAAP measure and a reconciliation between them, and that the measure not be misleading. SEC guidance also prohibits presenting the non-GAAP measure with greater prominence than the GAAP figure.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["SEC reporting", "non-GAAP measures"],
    },
    {
      question: "The audit committee of a listed company must be composed of:",
      options: [
        { label: "A", text: "At least one member of executive management", isCorrect: false, rationale: "Management participation would defeat the committee's oversight independence." },
        { label: "B", text: "Independent directors, with disclosure of whether at least one qualifies as a financial expert", isCorrect: true, rationale: "Correct — independence is required, and the financial expert status must be disclosed." },
        { label: "C", text: "The company's external auditors", isCorrect: false, rationale: "The auditors report to the committee; they are not members of it." },
        { label: "D", text: "A majority of the company's largest shareholders", isCorrect: false, rationale: "Share ownership is not a qualification for committee membership." },
      ],
      explanation: "Sarbanes-Oxley requires that each member of a listed company's audit committee be an independent director, and that the company disclose whether at least one member is an audit committee financial expert — and if not, why not. The committee is directly responsible for appointing, compensating, and overseeing the external auditor.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SOX", "audit committee"],
    },
  ],
};
