import type { McqBank } from "./types";

/** FAR question bank — topics 1 through 10. */
export const farBankA: McqBank = {
  "conceptual-framework-and-financial-statement-presentation": [
    {
      question: "Which of the following is an enhancing qualitative characteristic of useful financial information?",
      options: [
        { label: "A", text: "Relevance", isCorrect: false, rationale: "Relevance is one of the two fundamental characteristics, not an enhancing one." },
        { label: "B", text: "Faithful representation", isCorrect: false, rationale: "Faithful representation is the other fundamental characteristic." },
        { label: "C", text: "Verifiability", isCorrect: true, rationale: "Correct — verifiability is one of the four enhancing characteristics, along with comparability, timeliness, and understandability." },
        { label: "D", text: "Materiality", isCorrect: false, rationale: "Materiality is an entity-specific aspect of relevance, not a separate enhancing characteristic." },
      ],
      explanation: "The two fundamental qualitative characteristics are relevance and faithful representation. The four enhancing characteristics — comparability, verifiability, timeliness, and understandability — improve the usefulness of information that is already relevant and faithfully represented.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["conceptual framework"],
    },
    {
      question: "Which item would be reported in other comprehensive income rather than net income?",
      options: [
        { label: "A", text: "Unrealized gain on a trading debt security", isCorrect: false, rationale: "Unrealized gains and losses on trading securities flow through net income." },
        { label: "B", text: "Unrealized gain on an available-for-sale debt security", isCorrect: true, rationale: "Correct — unrealized holding gains and losses on AFS debt securities are reported in OCI until realized." },
        { label: "C", text: "Gain on the sale of equipment", isCorrect: false, rationale: "A realized gain on disposal of a fixed asset is included in net income." },
        { label: "D", text: "Loss from a discontinued operation", isCorrect: false, rationale: "Discontinued operations are reported within net income, net of tax, below continuing operations." },
      ],
      explanation: "OCI items are commonly remembered as PUFI: Pension adjustments, Unrealized gains/losses on AFS debt securities, Foreign currency translation adjustments, and Instrument-specific credit risk. Trading security gains, realized disposal gains, and discontinued operations all run through net income.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["OCI", "comprehensive income"],
    },
    {
      question: "Relevance is composed of which combination of attributes?",
      options: [
        { label: "A", text: "Completeness, neutrality, and freedom from error", isCorrect: false, rationale: "These three attributes describe faithful representation, not relevance." },
        { label: "B", text: "Predictive value, confirmatory value, and materiality", isCorrect: true, rationale: "Correct — information is relevant if it has predictive value, confirmatory value, or both, and materiality is the entity-specific aspect of relevance." },
        { label: "C", text: "Comparability, verifiability, and timeliness", isCorrect: false, rationale: "These are enhancing characteristics." },
        { label: "D", text: "Consistency, conservatism, and prudence", isCorrect: false, rationale: "Conservatism and prudence are not components of relevance in the current conceptual framework." },
      ],
      explanation: "Relevance consists of predictive value, confirmatory value, and materiality. Faithful representation consists of being complete, neutral, and free from error.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["conceptual framework", "relevance"],
    },
    {
      question: "A full set of general-purpose financial statements under US GAAP includes all of the following EXCEPT:",
      options: [
        { label: "A", text: "Statement of changes in stockholders' equity", isCorrect: false, rationale: "This is one of the required statements." },
        { label: "B", text: "Statement of cash flows", isCorrect: false, rationale: "This is one of the required statements." },
        { label: "C", text: "Statement of comprehensive income", isCorrect: false, rationale: "Required, though it may be combined with the income statement in a single continuous statement." },
        { label: "D", text: "Statement of budgeted operating results", isCorrect: true, rationale: "Correct — budgets are internal management tools and are not part of a general-purpose set of financial statements." },
      ],
      explanation: "A full set of financial statements comprises the balance sheet, income statement, statement of comprehensive income, statement of cash flows, and statement of changes in stockholders' equity, along with the notes. Budget information is not included in general-purpose external reporting.",
      difficulty: "EASY",
      questionType: "EXCEPTION",
      tags: ["financial statements"],
    },
    {
      question: "A retailer sells a delivery van it had used in operations, recognizing $4,000 above carrying value. How should this be presented?",
      options: [
        { label: "A", text: "As revenue, because the amount arose from a sale", isCorrect: false, rationale: "Revenue arises from ongoing major operations; selling used delivery equipment is peripheral for a retailer." },
        { label: "B", text: "As a gain reported separately from revenue", isCorrect: true, rationale: "Correct — a peripheral or incidental transaction produces a gain, which is reported apart from revenue from the entity's central operations." },
        { label: "C", text: "As a direct credit to retained earnings", isCorrect: false, rationale: "Gains flow through the income statement; they do not bypass it." },
        { label: "D", text: "As other comprehensive income", isCorrect: false, rationale: "A realized gain on disposal of a fixed asset is not an OCI item." },
      ],
      explanation: "Revenues arise from an entity's ongoing major or central operations, while gains arise from peripheral or incidental transactions. For a retailer, disposing of a used delivery van is incidental, so the excess over carrying value is a gain.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["conceptual framework", "gains"],
    },
    {
      question: "Under the FASB conceptual framework, faithful representation requires information to be:",
      options: [
        { label: "A", text: "Complete, neutral, and free from error", isCorrect: true, rationale: "Correct — these are the three attributes of faithful representation." },
        { label: "B", text: "Conservative, prudent, and verifiable", isCorrect: false, rationale: "Neutrality, not conservatism, is required; verifiability is an enhancing characteristic." },
        { label: "C", text: "Predictive, confirmatory, and material", isCorrect: false, rationale: "These describe relevance." },
        { label: "D", text: "Timely, understandable, and comparable", isCorrect: false, rationale: "These are enhancing characteristics." },
      ],
      explanation: "Faithful representation means the depiction is complete (includes all necessary information), neutral (free from bias in selection or presentation), and free from error (no errors in the description or the process used). Neutrality specifically excludes deliberate conservatism.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["conceptual framework", "faithful representation"],
    },
  ],

  "balance-sheet-and-income-statement-preparation": [
    {
      question: "A company disposes of a product line that represented 40% of revenue and a distinct major line of business. How should the results be presented?",
      options: [
        { label: "A", text: "As part of continuing operations, with disclosure in the notes", isCorrect: false, rationale: "A disposal representing a strategic shift with a major effect qualifies for discontinued operations presentation." },
        { label: "B", text: "As a discontinued operation, reported net of tax below income from continuing operations", isCorrect: true, rationale: "Correct — disposal of a major line of business is a strategic shift with a major effect, so it is presented separately, net of tax." },
        { label: "C", text: "As an item of other comprehensive income", isCorrect: false, rationale: "Discontinued operations are part of net income, not OCI." },
        { label: "D", text: "As a prior period adjustment to retained earnings", isCorrect: false, rationale: "Prior period adjustments correct errors; a current-year disposal is not an error correction." },
      ],
      explanation: "A component qualifies as a discontinued operation only when its disposal represents a strategic shift having a major effect on operations and financial results — such as disposing of a major line of business or geographic area. It is then reported net of tax, separately from continuing operations.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["discontinued operations"],
    },
    {
      question: "A company reports net sales of $900,000, cost of goods sold of $540,000, selling and administrative expenses of $180,000, interest expense of $30,000, and a gain on sale of equipment of $20,000. What is operating income?",
      options: [
        { label: "A", text: "$180,000", isCorrect: true, rationale: "Correct — gross profit is $900,000 − $540,000 = $360,000; less operating expenses of $180,000 gives operating income of $180,000. Interest and the gain are non-operating." },
        { label: "B", text: "$170,000", isCorrect: false, rationale: "This incorrectly deducts interest expense, which is a non-operating item." },
        { label: "C", text: "$200,000", isCorrect: false, rationale: "This incorrectly adds the gain on sale, which is non-operating." },
        { label: "D", text: "$360,000", isCorrect: false, rationale: "$360,000 is gross profit, before deducting operating expenses." },
      ],
      explanation: "In a multi-step income statement, operating income = net sales − COGS − operating expenses. Net sales $900,000 − COGS $540,000 = gross profit $360,000, less S&A expenses $180,000 = operating income $180,000. Interest expense and the gain on equipment are non-operating items reported below operating income.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["income statement", "multi-step"],
    },
    {
      question: "An asset is classified as current if it is expected to be realized or consumed within:",
      options: [
        { label: "A", text: "One year from the balance sheet date, without exception", isCorrect: false, rationale: "The operating cycle governs when it is longer than one year." },
        { label: "B", text: "One year or the operating cycle, whichever is longer", isCorrect: true, rationale: "Correct — the classification threshold is one year or the entity's operating cycle, whichever is longer." },
        { label: "C", text: "One year or the operating cycle, whichever is shorter", isCorrect: false, rationale: "The rule uses the longer of the two periods, not the shorter." },
        { label: "D", text: "The period specified by management policy", isCorrect: false, rationale: "The threshold is defined by GAAP, not by management election." },
      ],
      explanation: "Current assets are those expected to be converted to cash, sold, or consumed within one year or the operating cycle, whichever is longer. Businesses with long production cycles — distillers or shipbuilders, for example — may therefore classify as current items that will not convert within twelve months.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["balance sheet", "classification"],
    },
    {
      question: "When a company reports discontinued operations, earnings per share must be presented for:",
      options: [
        { label: "A", text: "Net income only", isCorrect: false, rationale: "EPS for continuing operations and discontinued operations must also be presented." },
        { label: "B", text: "Income from continuing operations and net income only", isCorrect: false, rationale: "Discontinued operations EPS is also required." },
        { label: "C", text: "Income from continuing operations, discontinued operations, and net income", isCorrect: true, rationale: "Correct — all three amounts require EPS presentation, either on the face of the income statement or in the notes." },
        { label: "D", text: "Comprehensive income", isCorrect: false, rationale: "EPS is not presented for comprehensive income." },
      ],
      explanation: "When discontinued operations are reported, EPS must be shown for income from continuing operations, for the discontinued operations, and for net income. EPS is never presented for comprehensive income or other comprehensive income.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["EPS", "discontinued operations"],
    },
    {
      question: "Which presentation of comprehensive income is permitted under US GAAP?",
      options: [
        { label: "A", text: "A single continuous statement of comprehensive income, or two consecutive statements", isCorrect: true, rationale: "Correct — an entity may present a single continuous statement or an income statement immediately followed by a separate statement of comprehensive income." },
        { label: "B", text: "Only within the statement of changes in stockholders' equity", isCorrect: false, rationale: "Presenting comprehensive income solely within the equity statement is not permitted." },
        { label: "C", text: "Only as a note disclosure", isCorrect: false, rationale: "Comprehensive income must be presented in a financial statement, not merely disclosed." },
        { label: "D", text: "Only as a single continuous statement", isCorrect: false, rationale: "The two-statement approach is equally acceptable." },
      ],
      explanation: "US GAAP permits two presentation options for comprehensive income: a single continuous statement beginning with revenues and ending with comprehensive income, or two consecutive statements where the statement of comprehensive income immediately follows the income statement. Presentation only within the equity statement is not allowed.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["comprehensive income", "presentation"],
    },
    {
      question: "A company has current assets of $400,000 and current liabilities of $250,000. It then reclassifies $60,000 of long-term debt as currently maturing. What is the effect on working capital?",
      options: [
        { label: "A", text: "Working capital decreases by $60,000 to $90,000", isCorrect: true, rationale: "Correct — working capital was $150,000; adding $60,000 to current liabilities reduces it to $90,000." },
        { label: "B", text: "Working capital is unchanged at $150,000", isCorrect: false, rationale: "Reclassifying debt into current liabilities directly reduces working capital." },
        { label: "C", text: "Working capital increases by $60,000", isCorrect: false, rationale: "An increase in current liabilities reduces, not increases, working capital." },
        { label: "D", text: "Working capital decreases to $150,000", isCorrect: false, rationale: "$150,000 was the amount before the reclassification." },
      ],
      explanation: "Working capital equals current assets minus current liabilities: $400,000 − $250,000 = $150,000. Reclassifying $60,000 of long-term debt as current increases current liabilities to $310,000, reducing working capital to $90,000.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["balance sheet", "working capital"],
    },
  ],

  "statement-of-cash-flows": [
    {
      question: "Under US GAAP, dividends PAID by a corporation are classified in the statement of cash flows as:",
      options: [
        { label: "A", text: "Operating activities", isCorrect: false, rationale: "Dividends received are operating; dividends paid are not." },
        { label: "B", text: "Investing activities", isCorrect: false, rationale: "Investing activities involve acquiring and disposing of long-term assets and investments." },
        { label: "C", text: "Financing activities", isCorrect: true, rationale: "Correct — dividends paid to shareholders are a financing outflow because they represent a return to providers of capital." },
        { label: "D", text: "Noncash activities disclosed separately", isCorrect: false, rationale: "Cash dividends paid involve an actual cash outflow." },
      ],
      explanation: "Under US GAAP, dividends paid are a financing activity, while dividends received and interest received or paid are all operating activities. Candidates frequently confuse dividends received (operating) with dividends paid (financing).",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["cash flows", "classification"],
    },
    {
      question: "Net income is $150,000. Depreciation expense was $30,000, there was a $10,000 gain on sale of equipment, accounts receivable increased $20,000, and accounts payable increased $15,000. What is net cash provided by operating activities under the indirect method?",
      options: [
        { label: "A", text: "$165,000", isCorrect: true, rationale: "Correct — $150,000 + $30,000 depreciation − $10,000 gain − $20,000 AR increase + $15,000 AP increase = $165,000." },
        { label: "B", text: "$185,000", isCorrect: false, rationale: "This adds the gain instead of subtracting it." },
        { label: "C", text: "$145,000", isCorrect: false, rationale: "This treats the accounts payable increase as a deduction rather than an addition." },
        { label: "D", text: "$205,000", isCorrect: false, rationale: "This fails to deduct both the gain and the receivable increase." },
      ],
      explanation: "Start with net income of $150,000. Add back non-cash depreciation ($30,000). Subtract the gain on sale ($10,000) because it belongs in investing. Subtract the increase in receivables ($20,000) since less cash was collected than revenue recorded. Add the increase in payables ($15,000) since less cash was paid than expense recorded. Total: $165,000.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["cash flows", "indirect method"],
    },
    {
      question: "Sales for the year were $500,000. Accounts receivable increased from $60,000 to $80,000. Under the direct method, cash collected from customers was:",
      options: [
        { label: "A", text: "$520,000", isCorrect: false, rationale: "This adds the receivable increase rather than subtracting it." },
        { label: "B", text: "$480,000", isCorrect: true, rationale: "Correct — $500,000 sales less the $20,000 increase in receivables equals $480,000 collected." },
        { label: "C", text: "$500,000", isCorrect: false, rationale: "This ignores the change in receivables entirely." },
        { label: "D", text: "$440,000", isCorrect: false, rationale: "This subtracts the ending receivable balance rather than the change." },
      ],
      explanation: "Cash collected from customers equals sales adjusted for the change in accounts receivable. Receivables rose $20,000 ($80,000 − $60,000), meaning $20,000 of recorded sales were not yet collected: $500,000 − $20,000 = $480,000.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["cash flows", "direct method"],
    },
    {
      question: "A company acquires a building by issuing common stock directly to the seller. How is this reported?",
      options: [
        { label: "A", text: "As an investing outflow and a financing inflow", isCorrect: false, rationale: "No cash changed hands, so neither section is affected." },
        { label: "B", text: "As a noncash investing and financing activity disclosed separately", isCorrect: true, rationale: "Correct — significant noncash transactions are excluded from the body of the statement and disclosed in a separate schedule or note." },
        { label: "C", text: "As an operating activity", isCorrect: false, rationale: "Acquiring a building is not an operating activity, and no cash was involved." },
        { label: "D", text: "It is not reported at all", isCorrect: false, rationale: "Significant noncash transactions must be disclosed so users understand the change in financial position." },
      ],
      explanation: "The statement of cash flows reports only cash transactions in its three activity sections. Significant noncash investing and financing transactions — such as acquiring assets by issuing stock or debt, or converting debt to equity — must be disclosed separately in a schedule or note.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["cash flows", "noncash transactions"],
    },
    {
      question: "Which of the following is classified as an investing activity?",
      options: [
        { label: "A", text: "Cash paid to purchase treasury stock", isCorrect: false, rationale: "Treasury stock transactions are financing activities." },
        { label: "B", text: "Cash received from issuing bonds", isCorrect: false, rationale: "Issuing debt is a financing inflow." },
        { label: "C", text: "Cash paid to acquire equipment", isCorrect: true, rationale: "Correct — purchasing long-lived productive assets is an investing outflow." },
        { label: "D", text: "Cash paid for income taxes", isCorrect: false, rationale: "Income taxes paid are an operating activity." },
      ],
      explanation: "Investing activities involve acquiring and disposing of long-term assets and investments — purchasing equipment, buying or selling securities, and making or collecting loans. Treasury stock and bond issuances are financing; taxes paid are operating.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["cash flows", "investing"],
    },
    {
      question: "Why is a gain on the sale of equipment subtracted from net income under the indirect method?",
      options: [
        { label: "A", text: "Because the gain is a noncash item that never generated cash", isCorrect: false, rationale: "The sale did generate cash — the issue is where that cash is classified, not whether it existed." },
        { label: "B", text: "Because the entire proceeds from the sale are reported in investing activities, so leaving the gain in operating would double-count it", isCorrect: true, rationale: "Correct — the full cash proceeds appear as an investing inflow, so the gain embedded in net income must be removed from the operating section." },
        { label: "C", text: "Because gains are always reported in other comprehensive income", isCorrect: false, rationale: "Realized gains on disposals are included in net income." },
        { label: "D", text: "Because the gain increases taxable income", isCorrect: false, rationale: "Tax effects are not the reason for this reconciling adjustment." },
      ],
      explanation: "The total cash received from selling equipment is reported as an investing inflow. Because net income already includes the gain, leaving it in the operating section would count part of that same cash twice — so the gain is subtracted in the operating reconciliation. Losses are added back for the same reason.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["cash flows", "indirect method"],
    },
    {
      question: "Under US GAAP, interest paid on borrowings is classified as:",
      options: [
        { label: "A", text: "A financing activity, because it relates to debt", isCorrect: false, rationale: "Only the repayment of debt principal is financing; interest is operating under US GAAP." },
        { label: "B", text: "An operating activity", isCorrect: true, rationale: "Correct — under US GAAP, interest paid and interest received are both operating activities." },
        { label: "C", text: "An investing activity", isCorrect: false, rationale: "Investing relates to long-term assets and investments." },
        { label: "D", text: "Either operating or financing, at the entity's election", isCorrect: false, rationale: "That flexibility exists under IFRS, not US GAAP." },
      ],
      explanation: "US GAAP requires interest paid and received, and dividends received, to be classified as operating activities; only dividends paid are financing. IFRS permits more flexibility, which is a common source of confusion on the exam.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["cash flows", "interest"],
    },
  ],

  "notes-subsequent-events-and-going-concern": [
    {
      question: "A customer with a large outstanding receivable declared bankruptcy two weeks after the balance sheet date, having been in severe financial distress for months before year-end. How should this be treated?",
      options: [
        { label: "A", text: "As a non-recognized subsequent event requiring disclosure only", isCorrect: false, rationale: "The underlying condition — the customer's deteriorated financial position — existed at the balance sheet date." },
        { label: "B", text: "As a recognized subsequent event requiring adjustment of the financial statements", isCorrect: true, rationale: "Correct — the bankruptcy provides evidence about a condition (uncollectibility) that already existed at the balance sheet date, so the allowance must be adjusted." },
        { label: "C", text: "As a prior period adjustment", isCorrect: false, rationale: "This is not an error correction; it is new evidence about an existing estimate." },
        { label: "D", text: "No action, because the bankruptcy occurred after year-end", isCorrect: false, rationale: "Recognized subsequent events require adjustment even though they occur after the balance sheet date." },
      ],
      explanation: "A recognized (Type I) subsequent event provides additional evidence about conditions that existed at the balance sheet date and requires adjustment. Because the customer's financial deterioration predated year-end, the bankruptcy confirms that the receivable was impaired as of the balance sheet date.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["subsequent events"],
    },
    {
      question: "A fire destroyed a company's uninsured warehouse three weeks after year-end. The appropriate treatment is to:",
      options: [
        { label: "A", text: "Adjust the financial statements to write off the warehouse", isCorrect: false, rationale: "The condition (the fire) did not exist at the balance sheet date, so no adjustment is made." },
        { label: "B", text: "Disclose the nature of the event and an estimate of its financial effect", isCorrect: true, rationale: "Correct — this is a non-recognized (Type II) subsequent event requiring disclosure, not adjustment." },
        { label: "C", text: "Do nothing, since the event occurred after the reporting period", isCorrect: false, rationale: "Material non-recognized events must be disclosed so the statements are not misleading." },
        { label: "D", text: "Restate the prior year financial statements", isCorrect: false, rationale: "Restatement applies to error corrections, not subsequent events." },
      ],
      explanation: "A non-recognized (Type II) subsequent event arises from conditions that did not exist at the balance sheet date. The financial statements are not adjusted, but the nature of the event and an estimate of its financial effect (or a statement that an estimate cannot be made) must be disclosed.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["subsequent events"],
    },
    {
      question: "Management's going concern evaluation covers a period of:",
      options: [
        { label: "A", text: "One year from the balance sheet date", isCorrect: false, rationale: "The period runs from the issuance date, not the balance sheet date." },
        { label: "B", text: "One year from the date the financial statements are issued or available to be issued", isCorrect: true, rationale: "Correct — the look-forward period begins on the issuance (or available-to-be-issued) date." },
        { label: "C", text: "Two years from the balance sheet date", isCorrect: false, rationale: "The required evaluation period is one year, not two." },
        { label: "D", text: "The period until the next scheduled debt maturity", isCorrect: false, rationale: "The period is defined by time, not by debt maturities, though maturities are relevant evidence." },
      ],
      explanation: "Management must evaluate whether conditions raise substantial doubt about the entity's ability to continue as a going concern within one year after the date the financial statements are issued or available to be issued — a period that extends beyond one year from the balance sheet date.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["going concern"],
    },
    {
      question: "Substantial doubt about going concern exists and is NOT alleviated by management's plans. Under GAAP, management must:",
      options: [
        { label: "A", text: "Prepare the financial statements on the liquidation basis of accounting", isCorrect: false, rationale: "The liquidation basis is required only when liquidation is imminent, not merely when substantial doubt exists." },
        { label: "B", text: "Disclose the conditions, management's evaluation, and state that substantial doubt exists", isCorrect: true, rationale: "Correct — when doubt is not alleviated, the disclosure must include an explicit statement that substantial doubt exists about the entity's ability to continue as a going concern." },
        { label: "C", text: "Write all assets down to net realizable value", isCorrect: false, rationale: "Going concern doubt does not by itself trigger a general asset write-down." },
        { label: "D", text: "Omit the going concern discussion to avoid a self-fulfilling prophecy", isCorrect: false, rationale: "Disclosure is required; omission would render the statements misleading." },
      ],
      explanation: "When substantial doubt is not alleviated by management's plans, the notes must describe the principal conditions, management's evaluation of their significance, management's plans, and must explicitly state that substantial doubt exists. The going concern basis of accounting continues unless liquidation is imminent.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["going concern", "disclosure"],
    },
    {
      question: "Which disclosure is required in the summary of significant accounting policies?",
      options: [
        { label: "A", text: "The composition of accounts receivable by customer", isCorrect: false, rationale: "This is detailed account information, not a policy." },
        { label: "B", text: "The depreciation method used for property, plant, and equipment", isCorrect: true, rationale: "Correct — the choice of depreciation method is an accounting policy and belongs in the summary of significant accounting policies." },
        { label: "C", text: "The names of the company's principal officers", isCorrect: false, rationale: "This is not an accounting policy disclosure." },
        { label: "D", text: "The details of pending litigation", isCorrect: false, rationale: "Litigation is disclosed as a contingency, in a separate note." },
      ],
      explanation: "The summary of significant accounting policies describes the accounting principles and methods of applying them — revenue recognition policy, depreciation methods, inventory cost flow assumptions, and basis of consolidation. Specific account balances, contingencies, and management details appear in other notes.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["notes", "accounting policies"],
    },
  ],

  "revenue-recognition": [
    {
      question: "A contract includes two performance obligations with standalone selling prices of $80,000 and $40,000. The total transaction price is $100,000. How much is allocated to the first obligation?",
      options: [
        { label: "A", text: "$80,000", isCorrect: false, rationale: "This uses the standalone selling price directly rather than allocating the discount proportionally." },
        { label: "B", text: "$66,667", isCorrect: true, rationale: "Correct — $100,000 × ($80,000 ÷ $120,000) = $66,667." },
        { label: "C", text: "$60,000", isCorrect: false, rationale: "This splits the price other than in proportion to standalone selling prices." },
        { label: "D", text: "$50,000", isCorrect: false, rationale: "This allocates evenly, ignoring the different standalone selling prices." },
      ],
      explanation: "The transaction price is allocated to performance obligations in proportion to their standalone selling prices. Total standalone value is $120,000, so the first obligation receives $100,000 × 80/120 = $66,667 and the second receives $100,000 × 40/120 = $33,333.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["revenue recognition", "allocation"],
    },
    {
      question: "An online marketplace arranges sales between independent sellers and buyers. It never takes control of the goods, does not set prices, and bears no inventory risk. How should it report revenue?",
      options: [
        { label: "A", text: "Gross, at the full amount paid by buyers", isCorrect: false, rationale: "Gross reporting is appropriate only for a principal that controls the good or service before transfer." },
        { label: "B", text: "Net, at the amount of commission retained", isCorrect: true, rationale: "Correct — the marketplace is an agent because it does not control the goods, so it reports only its commission as revenue." },
        { label: "C", text: "Gross, with the amounts remitted to sellers shown as cost of sales", isCorrect: false, rationale: "This is gross presentation, which is inappropriate for an agent." },
        { label: "D", text: "It recognizes no revenue until the buyer resells the goods", isCorrect: false, rationale: "The commission is earned when the arranged sale occurs." },
      ],
      explanation: "An entity is a principal — and reports revenue gross — if it controls the specified good or service before it is transferred. Indicators include primary responsibility for fulfillment, inventory risk, and pricing discretion. Lacking all of these, the marketplace is an agent and reports revenue net.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["revenue recognition", "principal vs agent"],
    },
    {
      question: "A company receives $50,000 cash on December 1 for services to be provided evenly over the following ten months. What is reported at December 31?",
      options: [
        { label: "A", text: "Revenue of $50,000", isCorrect: false, rationale: "Only the portion earned through December 31 may be recognized." },
        { label: "B", text: "Revenue of $5,000 and a contract liability of $45,000", isCorrect: true, rationale: "Correct — one of the ten months has elapsed, so $5,000 is earned and the remaining $45,000 is a contract liability." },
        { label: "C", text: "A contract asset of $50,000", isCorrect: false, rationale: "A contract asset arises when the entity performs before payment is due — here the customer paid in advance." },
        { label: "D", text: "A receivable of $45,000", isCorrect: false, rationale: "No receivable exists; the cash has already been collected." },
      ],
      explanation: "Payment received before performance creates a contract liability. With services delivered evenly over ten months, one month of performance ($5,000) is recognized as revenue at December 31, leaving a $45,000 contract liability.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["revenue recognition", "contract liability"],
    },
    {
      question: "What distinguishes a contract asset from a receivable under ASC 606?",
      options: [
        { label: "A", text: "A contract asset arises from services while a receivable arises from goods", isCorrect: false, rationale: "The distinction has nothing to do with goods versus services." },
        { label: "B", text: "A receivable represents an unconditional right to consideration, while a contract asset is conditional on something other than the passage of time", isCorrect: true, rationale: "Correct — once the right to payment becomes unconditional, the contract asset is reclassified as a receivable." },
        { label: "C", text: "A contract asset is always current while a receivable is always noncurrent", isCorrect: false, rationale: "Both may be current or noncurrent depending on timing." },
        { label: "D", text: "A contract asset is measured at fair value while a receivable is measured at cost", isCorrect: false, rationale: "This is not the basis of the distinction." },
      ],
      explanation: "A receivable is recognized when the entity has an unconditional right to consideration — only the passage of time is required before payment is due. A contract asset exists when the entity has performed but the right to payment is conditional on something further, such as completing another performance obligation.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["revenue recognition", "contract asset"],
    },
    {
      question: "A retailer sells 1,000 units at $100 each and expects 4% to be returned based on historical experience. What revenue should be recognized at the point of sale?",
      options: [
        { label: "A", text: "$100,000, with returns recorded when they occur", isCorrect: false, rationale: "Expected returns must be estimated and excluded from revenue at the time of sale." },
        { label: "B", text: "$96,000, with a refund liability of $4,000 recognized", isCorrect: true, rationale: "Correct — revenue is recognized only for the consideration the entity expects to be entitled to: $100,000 × 96% = $96,000, with a $4,000 refund liability." },
        { label: "C", text: "$104,000", isCorrect: false, rationale: "Expected returns reduce rather than increase revenue." },
        { label: "D", text: "No revenue until the return period expires", isCorrect: false, rationale: "Revenue is recognized when control transfers, with returns estimated — not deferred entirely." },
      ],
      explanation: "A right of return creates variable consideration. Revenue is recognized only for the amount the entity expects to retain — here 96% of $100,000, or $96,000. A refund liability of $4,000 is recorded, along with an asset for the right to recover the returned goods.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["revenue recognition", "right of return"],
    },
    {
      question: "A software company grants a customer a perpetual license to functional intellectual property, delivered immediately, plus one year of ongoing technical support. How is revenue recognized?",
      options: [
        { label: "A", text: "Entirely at delivery of the license", isCorrect: false, rationale: "The support obligation is satisfied over time and cannot be recognized upfront." },
        { label: "B", text: "Entirely over the one-year support period", isCorrect: false, rationale: "The license is a right to use functional IP, satisfied at a point in time." },
        { label: "C", text: "The license portion at delivery, and the support portion over the year", isCorrect: true, rationale: "Correct — these are two distinct performance obligations with different satisfaction patterns, so the allocated amounts are recognized separately." },
        { label: "D", text: "Only when the support period expires and all obligations are complete", isCorrect: false, rationale: "ASC 606 recognizes revenue as each performance obligation is satisfied, not at final completion." },
      ],
      explanation: "A license to functional IP that is static at the transfer date is a right to use, recognized at a point in time. Technical support is a separate performance obligation satisfied over time. The transaction price is allocated between them by relative standalone selling price and recognized on each obligation's own pattern.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["revenue recognition", "licensing"],
    },
  ],

  "cash-receivables-and-bad-debts": [
    {
      question: "Which item is properly included in cash and cash equivalents?",
      options: [
        { label: "A", text: "A certificate of deposit with an original maturity of six months", isCorrect: false, rationale: "Cash equivalents require an original maturity of three months or less." },
        { label: "B", text: "A Treasury bill purchased two months before its maturity date", isCorrect: true, rationale: "Correct — an original maturity of three months or less from the date of purchase qualifies as a cash equivalent." },
        { label: "C", text: "A compensating balance legally restricted under a loan agreement", isCorrect: false, rationale: "Legally restricted compensating balances are reported separately, not as unrestricted cash." },
        { label: "D", text: "Postdated checks received from customers", isCorrect: false, rationale: "A postdated check is a receivable until it becomes negotiable." },
      ],
      explanation: "Cash equivalents are short-term, highly liquid investments with an original maturity of three months or less from the date of acquisition. The test is maturity at purchase, not remaining maturity at year-end, and restricted balances are excluded from unrestricted cash.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["cash", "cash equivalents"],
    },
    {
      question: "A company writes off a specific $8,000 account as uncollectible using the allowance method. What is the effect on total assets and net income?",
      options: [
        { label: "A", text: "Assets decrease $8,000; net income decreases $8,000", isCorrect: false, rationale: "The expense was recognized earlier when the allowance was established, not at write-off." },
        { label: "B", text: "No effect on either total assets or net income", isCorrect: true, rationale: "Correct — the write-off debits the allowance and credits accounts receivable, leaving net receivables and income unchanged." },
        { label: "C", text: "Assets decrease $8,000; no effect on net income", isCorrect: false, rationale: "Both gross receivables and the allowance decrease, so net assets are unchanged." },
        { label: "D", text: "No effect on assets; net income decreases $8,000", isCorrect: false, rationale: "No expense is recorded at the time of write-off under the allowance method." },
      ],
      explanation: "Under the allowance method, bad debt expense is recognized when the allowance is established. Writing off a specific account debits the allowance and credits accounts receivable — both contra and gross amounts fall by the same amount, so net receivables, total assets, and net income are unaffected.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["receivables", "allowance method"],
    },
    {
      question: "The allowance for credit losses had a beginning balance of $12,000. During the year $9,000 of accounts were written off, $2,000 previously written off was recovered, and the desired ending balance is $15,000. What is bad debt expense?",
      options: [
        { label: "A", text: "$10,000", isCorrect: true, rationale: "Correct — $12,000 − $9,000 + $2,000 = $5,000 before adjustment; to reach $15,000 requires expense of $10,000." },
        { label: "B", text: "$15,000", isCorrect: false, rationale: "This treats the desired ending balance as the expense, ignoring the existing balance." },
        { label: "C", text: "$12,000", isCorrect: false, rationale: "This is the beginning balance, not the required expense." },
        { label: "D", text: "$3,000", isCorrect: false, rationale: "This ignores the write-offs and recovery activity during the year." },
      ],
      explanation: "Roll the allowance forward: beginning $12,000, less write-offs $9,000, plus the $2,000 recovery = $5,000 before adjustment. To reach the desired $15,000 ending balance, bad debt expense of $10,000 must be recorded.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["receivables", "allowance"],
    },
    {
      question: "Under the CECL model in ASC 326, an entity measures the allowance based on:",
      options: [
        { label: "A", text: "Losses that have already been incurred and are probable", isCorrect: false, rationale: "This describes the superseded incurred loss model." },
        { label: "B", text: "Lifetime expected credit losses, considering historical experience, current conditions, and reasonable forecasts", isCorrect: true, rationale: "Correct — CECL requires estimating expected losses over the life of the asset from the moment of recognition." },
        { label: "C", text: "Only losses expected within the next twelve months", isCorrect: false, rationale: "The twelve-month approach applies under IFRS 9 for certain stages, not under US GAAP's CECL model." },
        { label: "D", text: "The amount of accounts more than 90 days past due", isCorrect: false, rationale: "Aging informs the estimate but does not define the measurement objective." },
      ],
      explanation: "The current expected credit loss model requires recognizing an allowance for lifetime expected credit losses when a financial asset is first recognized, based on historical loss experience, current conditions, and reasonable and supportable forecasts — a forward-looking approach replacing the older incurred loss model.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["CECL", "receivables"],
    },
    {
      question: "A company factors $200,000 of receivables without recourse, receiving $185,000 cash. How is the transaction recorded?",
      options: [
        { label: "A", text: "As a secured borrowing with a $200,000 liability", isCorrect: false, rationale: "Without recourse and with control surrendered, the transfer qualifies as a sale rather than a borrowing." },
        { label: "B", text: "As a sale, removing the receivables and recognizing a $15,000 loss", isCorrect: true, rationale: "Correct — the receivables are derecognized and the $15,000 difference between carrying amount and proceeds is recognized as a loss on sale." },
        { label: "C", text: "As a sale with a $15,000 gain", isCorrect: false, rationale: "Receiving less than the carrying amount produces a loss, not a gain." },
        { label: "D", text: "No entry until the factor collects from customers", isCorrect: false, rationale: "The transfer is accounted for when it occurs, not when the factor ultimately collects." },
      ],
      explanation: "A factoring arrangement without recourse in which control is surrendered is accounted for as a sale. The receivables are removed from the books and the difference between the $200,000 carrying amount and $185,000 of proceeds is recognized as a $15,000 loss.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["receivables", "factoring"],
    },
  ],

  inventory: [
    {
      question: "Beginning inventory was 100 units at $10. Purchases were 200 units at $13 and 100 units at $16. If 250 units were sold, what is cost of goods sold under FIFO?",
      options: [
        { label: "A", text: "$2,950", isCorrect: true, rationale: "Correct — 100 units at $10 ($1,000) plus 150 units at $13 ($1,950) equals $2,950." },
        { label: "B", text: "$3,550", isCorrect: false, rationale: "This is the LIFO periodic result, taking the most recent costs first." },
        { label: "C", text: "$3,250", isCorrect: false, rationale: "This is the weighted-average result of 250 units at $13." },
        { label: "D", text: "$2,250", isCorrect: false, rationale: "$2,250 is FIFO ending inventory, not cost of goods sold." },
      ],
      explanation: "FIFO assigns the oldest costs to cost of goods sold. The 250 units sold consist of the 100 beginning units at $10 ($1,000) and 150 of the $13 units ($1,950), totaling $2,950. Ending inventory of 150 units is $2,250 (50 at $13 plus 100 at $16), and the two sum to the $5,200 of goods available.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["inventory", "FIFO"],
    },
    {
      question: "Using the same facts — beginning inventory 100 units at $10, purchases of 200 at $13 and 100 at $16, with 250 units sold — what is ending inventory under the weighted-average method (periodic)?",
      options: [
        { label: "A", text: "$1,950", isCorrect: true, rationale: "Correct — total cost $5,200 ÷ 400 units = $13 per unit; 150 units remaining × $13 = $1,950." },
        { label: "B", text: "$2,250", isCorrect: false, rationale: "This is the FIFO ending inventory." },
        { label: "C", text: "$1,650", isCorrect: false, rationale: "This is the LIFO periodic ending inventory." },
        { label: "D", text: "$3,250", isCorrect: false, rationale: "$3,250 is weighted-average cost of goods sold, not ending inventory." },
      ],
      explanation: "Goods available total $5,200 (100 × $10 + 200 × $13 + 100 × $16) across 400 units, giving a weighted-average cost of $13. With 250 sold, 150 units remain: 150 × $13 = $1,950, and cost of goods sold is 250 × $13 = $3,250.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["inventory", "weighted average"],
    },
    {
      question: "A company using FIFO holds inventory costing $50,000 with an estimated selling price of $54,000 and disposal costs of $6,000. At what amount should the inventory be reported?",
      options: [
        { label: "A", text: "$50,000", isCorrect: false, rationale: "Net realizable value is below cost, so a write-down is required." },
        { label: "B", text: "$48,000", isCorrect: true, rationale: "Correct — NRV is $54,000 − $6,000 = $48,000, which is lower than the $50,000 cost." },
        { label: "C", text: "$54,000", isCorrect: false, rationale: "Inventory is never written up to selling price." },
        { label: "D", text: "$44,000", isCorrect: false, rationale: "This subtracts disposal costs twice or applies a normal profit margin, which is not part of the LCNRV test." },
      ],
      explanation: "Inventory measured under FIFO or weighted average is reported at the lower of cost and net realizable value. NRV is the estimated selling price less reasonably predictable costs of completion and disposal: $54,000 − $6,000 = $48,000, below the $50,000 cost, so a $2,000 write-down is required.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["inventory", "LCNRV"],
    },
    {
      question: "Goods held on consignment by a consignee should be included in whose inventory?",
      options: [
        { label: "A", text: "The consignee's, because it has physical possession", isCorrect: false, rationale: "Physical possession does not determine ownership for consigned goods." },
        { label: "B", text: "The consignor's, because it retains title and the risks of ownership", isCorrect: true, rationale: "Correct — the consignor retains title until the goods are sold to a third party, so the goods remain in the consignor's inventory." },
        { label: "C", text: "Neither party's, until a final sale occurs", isCorrect: false, rationale: "The goods exist and belong to someone; they remain the consignor's asset." },
        { label: "D", text: "Split evenly between consignor and consignee", isCorrect: false, rationale: "Inventory is not allocated between parties in this way." },
      ],
      explanation: "In a consignment arrangement, the consignor retains legal title and the risks and rewards of ownership until the consignee sells the goods to an end customer. The goods therefore remain in the consignor's inventory despite being physically located at the consignee.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["inventory", "consignment"],
    },
    {
      question: "Which cost should be capitalized as part of inventory?",
      options: [
        { label: "A", text: "Freight-out to deliver goods to customers", isCorrect: false, rationale: "Freight-out is a selling expense, not an inventory cost." },
        { label: "B", text: "Freight-in on purchases of raw materials", isCorrect: true, rationale: "Correct — costs of bringing inventory to its present location and condition, including inbound freight, are capitalized." },
        { label: "C", text: "Abnormal spoilage from a production accident", isCorrect: false, rationale: "Abnormal spoilage is expensed in the period incurred rather than capitalized." },
        { label: "D", text: "Selling commissions on completed sales", isCorrect: false, rationale: "Selling costs are period expenses." },
      ],
      explanation: "Inventory includes all costs of purchase, conversion, and other costs incurred in bringing the inventory to its present location and condition — including freight-in and normal spoilage. Freight-out, selling costs, and abnormal spoilage are expensed as incurred.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["inventory", "capitalization"],
    },
    {
      question: "In a period of rising prices, which statement about a company using LIFO instead of FIFO is correct?",
      options: [
        { label: "A", text: "Reported net income and income taxes will both be higher", isCorrect: false, rationale: "LIFO produces higher cost of goods sold in rising prices, reducing income and taxes." },
        { label: "B", text: "Reported net income will be lower and cash flows will be higher due to reduced taxes", isCorrect: true, rationale: "Correct — higher COGS lowers taxable income and therefore taxes paid, improving cash flow even though reported income is lower." },
        { label: "C", text: "Ending inventory will be reported at a higher amount", isCorrect: false, rationale: "LIFO leaves older, cheaper costs in ending inventory, producing a lower balance." },
        { label: "D", text: "There will be no difference from FIFO", isCorrect: false, rationale: "The methods differ whenever unit costs change." },
      ],
      explanation: "In rising prices LIFO charges the most recent, highest costs to cost of goods sold, producing lower reported income and a lower ending inventory balance. Because taxable income falls, cash taxes paid are lower — the primary practical reason companies elect LIFO.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["inventory", "LIFO"],
    },
  ],

  "property-plant-and-equipment": [
    {
      question: "Equipment costing $60,000 with a $6,000 salvage value and a six-year life is purchased on April 1. Using straight-line depreciation, what is depreciation expense for the first calendar year?",
      options: [
        { label: "A", text: "$9,000", isCorrect: false, rationale: "This is a full year of depreciation, ignoring that the asset was held only nine months." },
        { label: "B", text: "$6,750", isCorrect: true, rationale: "Correct — annual depreciation is ($60,000 − $6,000) ÷ 6 = $9,000; for nine months, $9,000 × 9/12 = $6,750." },
        { label: "C", text: "$7,500", isCorrect: false, rationale: "This omits salvage value from the depreciable base." },
        { label: "D", text: "$10,000", isCorrect: false, rationale: "This ignores both salvage value and the partial year." },
      ],
      explanation: "The depreciable base is cost less salvage: $60,000 − $6,000 = $54,000, giving annual straight-line depreciation of $9,000. Because the asset was placed in service on April 1, only nine months of that year's depreciation is recorded: $9,000 × 9/12 = $6,750.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["PP&E", "depreciation"],
    },
    {
      question: "A machine costing $200,000 with a $20,000 salvage value is expected to produce 300,000 units over its life. It produced 45,000 units this year. What is depreciation expense using the units-of-production method?",
      options: [
        { label: "A", text: "$30,000", isCorrect: false, rationale: "This omits salvage value from the depreciable base." },
        { label: "B", text: "$27,000", isCorrect: true, rationale: "Correct — ($200,000 − $20,000) ÷ 300,000 = $0.60 per unit; $0.60 × 45,000 = $27,000." },
        { label: "C", text: "$36,000", isCorrect: false, rationale: "This does not correspond to the units produced during the year." },
        { label: "D", text: "$45,000", isCorrect: false, rationale: "This confuses the unit count with a dollar amount." },
      ],
      explanation: "Units-of-production depreciation allocates the depreciable base over expected output. The rate is ($200,000 − $20,000) ÷ 300,000 units = $0.60 per unit, so producing 45,000 units generates $27,000 of depreciation.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["PP&E", "units of production"],
    },
    {
      question: "Which expenditure related to existing equipment should be capitalized rather than expensed?",
      options: [
        { label: "A", text: "Routine lubrication and filter replacement", isCorrect: false, rationale: "Routine maintenance that merely sustains normal operating condition is expensed." },
        { label: "B", text: "An overhaul that extends the asset's useful life by three years", isCorrect: true, rationale: "Correct — expenditures that extend useful life, increase capacity, or improve efficiency are capitalized." },
        { label: "C", text: "Repainting the equipment in company colors", isCorrect: false, rationale: "Cosmetic upkeep does not extend life or capacity." },
        { label: "D", text: "Insurance premiums on the equipment", isCorrect: false, rationale: "Insurance is a period cost." },
      ],
      explanation: "Capitalization is appropriate when an expenditure extends useful life, increases productive capacity, or improves efficiency or quality of output. Ordinary repairs and maintenance that simply keep the asset in normal operating condition are expensed as incurred.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["PP&E", "capitalization"],
    },
    {
      question: "An asset with a carrying value of $900,000 has undiscounted expected future cash flows of $840,000 and a fair value of $760,000. What impairment loss should be recognized?",
      options: [
        { label: "A", text: "$60,000", isCorrect: false, rationale: "This is carrying value less undiscounted cash flows, which determines whether impairment exists but does not measure it." },
        { label: "B", text: "$140,000", isCorrect: true, rationale: "Correct — the asset fails the recoverability test ($900,000 > $840,000), so the loss is carrying value less fair value: $900,000 − $760,000 = $140,000." },
        { label: "C", text: "$80,000", isCorrect: false, rationale: "This is the difference between undiscounted cash flows and fair value, which is not the measurement basis." },
        { label: "D", text: "$0", isCorrect: false, rationale: "The asset is impaired because carrying value exceeds undiscounted future cash flows." },
      ],
      explanation: "US GAAP applies a two-step model. Step one compares carrying value to undiscounted future cash flows: $900,000 exceeds $840,000, so the asset is impaired. Step two measures the loss as carrying value minus fair value: $900,000 − $760,000 = $140,000.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["PP&E", "impairment"],
    },
    {
      question: "Which statement about impairment of long-lived assets held for use under US GAAP is correct?",
      options: [
        { label: "A", text: "Impairment losses may be reversed if the asset's value recovers", isCorrect: false, rationale: "Reversal is permitted under IFRS but prohibited under US GAAP for held-for-use assets." },
        { label: "B", text: "Once recognized, the impairment loss may not be reversed in later periods", isCorrect: true, rationale: "Correct — US GAAP prohibits reversing impairment losses on long-lived assets held for use." },
        { label: "C", text: "Impairment is measured using discounted cash flows in step one", isCorrect: false, rationale: "Step one uses undiscounted cash flows; fair value is used to measure the loss in step two." },
        { label: "D", text: "Depreciation stops once an asset is impaired", isCorrect: false, rationale: "Depreciation continues on the new, lower carrying amount over the remaining useful life." },
      ],
      explanation: "A key US GAAP versus IFRS difference: impairment losses on long-lived assets held for use are never reversed under US GAAP, even if circumstances improve. After impairment, the reduced carrying amount becomes the new cost basis and continues to be depreciated over the remaining life.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["PP&E", "impairment"],
    },
    {
      question: "A long-lived asset meets the criteria to be classified as held for sale. How is it measured and depreciated?",
      options: [
        { label: "A", text: "At the lower of carrying value or fair value less costs to sell, with depreciation discontinued", isCorrect: true, rationale: "Correct — held-for-sale classification changes the measurement basis and stops depreciation." },
        { label: "B", text: "At carrying value, with depreciation continuing until sale", isCorrect: false, rationale: "Depreciation ceases once held-for-sale criteria are met." },
        { label: "C", text: "At fair value, with any gain recognized immediately", isCorrect: false, rationale: "The asset is not written up above carrying value." },
        { label: "D", text: "At net realizable value, with depreciation continuing", isCorrect: false, rationale: "Depreciation stops, and the measure is the lower of carrying value or fair value less costs to sell." },
      ],
      explanation: "Once an asset meets the held-for-sale criteria — management commitment, active marketing, sale probable within one year — it is measured at the lower of its carrying amount or fair value less costs to sell, and depreciation ceases because the asset is no longer being consumed in operations.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["PP&E", "held for sale"],
    },
  ],

  "intangible-assets-and-goodwill": [
    {
      question: "Under US GAAP, internally generated research and development costs are:",
      options: [
        { label: "A", text: "Capitalized and amortized over the expected benefit period", isCorrect: false, rationale: "US GAAP does not permit capitalizing internally generated R&D generally." },
        { label: "B", text: "Expensed as incurred", isCorrect: true, rationale: "Correct — US GAAP requires R&D costs to be expensed as incurred, a notable difference from IFRS." },
        { label: "C", text: "Capitalized only if technological feasibility has been established", isCorrect: false, rationale: "That rule applies specifically to software development costs, not R&D generally." },
        { label: "D", text: "Recorded as a contra-equity account", isCorrect: false, rationale: "R&D is an operating expense, not an equity item." },
      ],
      explanation: "US GAAP requires research and development costs to be expensed as incurred because of uncertainty about future benefits. IFRS, by contrast, capitalizes development costs once specified criteria including technical feasibility are met. Software development has its own separate rules under US GAAP.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["intangibles", "R&D"],
    },
    {
      question: "A reporting unit has a carrying value of $12,000,000 including allocated goodwill of $3,000,000, and a fair value of $10,500,000. What goodwill impairment loss is recognized?",
      options: [
        { label: "A", text: "$3,000,000", isCorrect: false, rationale: "The loss is limited to the excess of carrying value over fair value, which is less than the full goodwill balance." },
        { label: "B", text: "$1,500,000", isCorrect: true, rationale: "Correct — the loss equals carrying value minus fair value ($12,000,000 − $10,500,000), which is below the $3,000,000 goodwill allocated." },
        { label: "C", text: "$0", isCorrect: false, rationale: "Carrying value exceeds fair value, so an impairment exists." },
        { label: "D", text: "$10,500,000", isCorrect: false, rationale: "This is the reporting unit's fair value, not an impairment loss." },
      ],
      explanation: "Under the simplified one-step test, goodwill impairment equals the amount by which the reporting unit's carrying value exceeds its fair value, capped at the goodwill allocated to that unit. Here $12,000,000 − $10,500,000 = $1,500,000, which is less than the $3,000,000 of goodwill, so the full $1,500,000 is recognized.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["goodwill", "impairment"],
    },
    {
      question: "How is a patent with a legal life of 20 years but an expected useful life of 8 years amortized?",
      options: [
        { label: "A", text: "Over 20 years, the legal life", isCorrect: false, rationale: "Amortization uses the shorter of legal or useful life." },
        { label: "B", text: "Over 8 years, the useful life", isCorrect: true, rationale: "Correct — a finite-lived intangible is amortized over the shorter of its legal life and its expected useful life." },
        { label: "C", text: "It is not amortized but tested annually for impairment", isCorrect: false, rationale: "Only indefinite-lived intangibles avoid amortization." },
        { label: "D", text: "Over 14 years, the average of the two", isCorrect: false, rationale: "Averaging is not a permitted approach." },
      ],
      explanation: "Finite-lived intangible assets are amortized over their useful lives, which cannot exceed the legal or contractual life. When the expected period of economic benefit is shorter than the legal life — here 8 years versus 20 — the shorter period governs.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["intangibles", "amortization"],
    },
    {
      question: "Which cost may be capitalized as an intangible asset?",
      options: [
        { label: "A", text: "Costs of internally developing and maintaining a brand name", isCorrect: false, rationale: "Internally generated brand value cannot be capitalized." },
        { label: "B", text: "Legal fees to successfully defend a patent the company owns", isCorrect: true, rationale: "Correct — legal costs of a successful defense are capitalized as part of the patent's carrying amount." },
        { label: "C", text: "Legal fees from an unsuccessful patent defense", isCorrect: false, rationale: "An unsuccessful defense indicates the asset has no enforceable value; costs are expensed and impairment considered." },
        { label: "D", text: "Costs of training employees to use new software", isCorrect: false, rationale: "Training costs are expensed as incurred." },
      ],
      explanation: "Legal costs incurred to successfully defend an intangible asset are capitalized because they preserve the asset's future economic benefits. Unsuccessful defense costs are expensed, and internally generated goodwill, brands, and training costs can never be capitalized.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["intangibles", "capitalization"],
    },
    {
      question: "Software development costs incurred AFTER technological feasibility is established but before general release are:",
      options: [
        { label: "A", text: "Expensed as research and development", isCorrect: false, rationale: "Costs before technological feasibility are R&D; costs after it are capitalized." },
        { label: "B", text: "Capitalized and subsequently amortized", isCorrect: true, rationale: "Correct — once technological feasibility is established, production costs through general release are capitalized." },
        { label: "C", text: "Charged directly to retained earnings", isCorrect: false, rationale: "Costs never bypass the income statement in this way." },
        { label: "D", text: "Recorded as a prepaid asset and expensed at release", isCorrect: false, rationale: "The capitalized amount is amortized over the product's revenue-producing life, not expensed all at once." },
      ],
      explanation: "For software to be sold, leased, or marketed, costs incurred before technological feasibility are expensed as R&D. Once technological feasibility is established, subsequent production costs are capitalized until the product is available for general release, then amortized.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["intangibles", "software"],
    },
  ],

  "investments-debt-and-equity-securities": [
    {
      question: "An investor owns 30% of an investee and applies the equity method. The investee reports net income of $200,000 and pays dividends of $50,000. What is the net increase in the investment account?",
      options: [
        { label: "A", text: "$60,000", isCorrect: false, rationale: "This recognizes the share of income but ignores the reduction for dividends received." },
        { label: "B", text: "$45,000", isCorrect: true, rationale: "Correct — the investment increases by 30% × $200,000 = $60,000 and decreases by 30% × $50,000 = $15,000, a net increase of $45,000." },
        { label: "C", text: "$15,000", isCorrect: false, rationale: "This reflects only the dividends, ignoring the share of earnings." },
        { label: "D", text: "$75,000", isCorrect: false, rationale: "This incorrectly adds the dividends instead of subtracting them." },
      ],
      explanation: "Under the equity method, the investment account increases by the investor's share of investee net income ($60,000) and decreases by the investor's share of dividends ($15,000), because dividends represent a return of the investment rather than income. Net increase: $45,000.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["investments", "equity method"],
    },
    {
      question: "Unrealized holding gains on debt securities classified as available-for-sale are reported in:",
      options: [
        { label: "A", text: "Net income", isCorrect: false, rationale: "Trading securities, not AFS, run unrealized gains through net income." },
        { label: "B", text: "Other comprehensive income", isCorrect: true, rationale: "Correct — AFS debt securities are carried at fair value with unrealized gains and losses in OCI until realized." },
        { label: "C", text: "Retained earnings directly", isCorrect: false, rationale: "Unrealized gains do not bypass OCI to go directly to retained earnings." },
        { label: "D", text: "They are not recognized until sale", isCorrect: false, rationale: "AFS securities are remeasured to fair value each period." },
      ],
      explanation: "Available-for-sale debt securities are measured at fair value with unrealized holding gains and losses reported in other comprehensive income. They are reclassified into net income when the security is sold. Trading securities, by contrast, report unrealized changes directly in net income.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["investments", "AFS"],
    },
    {
      question: "Which classification requires both the positive intent and the ability to hold the security to maturity?",
      options: [
        { label: "A", text: "Trading", isCorrect: false, rationale: "Trading securities are held for short-term profit, not to maturity." },
        { label: "B", text: "Available-for-sale", isCorrect: false, rationale: "AFS is the residual classification with no holding requirement." },
        { label: "C", text: "Held-to-maturity", isCorrect: true, rationale: "Correct — HTM classification requires both positive intent and ability to hold until maturity, and is available only for debt securities." },
        { label: "D", text: "Equity method investments", isCorrect: false, rationale: "The equity method applies to significant influence over an investee, not to maturity intent." },
      ],
      explanation: "Held-to-maturity classification is available only for debt securities and requires the investor to have both the positive intent and the ability to hold the security until maturity. HTM securities are carried at amortized cost rather than fair value. Equity securities can never be HTM because they have no maturity date.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["investments", "HTM"],
    },
    {
      question: "Following ASU 2016-01, how are most equity securities without significant influence measured?",
      options: [
        { label: "A", text: "At cost, with no remeasurement", isCorrect: false, rationale: "Cost measurement applies only under the narrow practicability exception for securities without a readily determinable fair value." },
        { label: "B", text: "At fair value, with changes recognized in net income", isCorrect: true, rationale: "Correct — the available-for-sale classification was eliminated for equity securities, so changes flow through net income." },
        { label: "C", text: "At fair value, with changes recognized in other comprehensive income", isCorrect: false, rationale: "That treatment now applies only to AFS debt securities." },
        { label: "D", text: "At the lower of cost or market", isCorrect: false, rationale: "LCM is not used for equity securities." },
      ],
      explanation: "ASU 2016-01 eliminated the available-for-sale category for equity securities. Most equity investments without significant influence are now measured at fair value with changes recognized in net income. A practicability exception permits cost less impairment, adjusted for observable price changes, when fair value is not readily determinable.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["investments", "equity securities"],
    },
    {
      question: "An investor holding 15% of an investee's voting stock also has representation on the board and participates in policy-making decisions. Which method applies?",
      options: [
        { label: "A", text: "Fair value through net income, because ownership is below 20%", isCorrect: false, rationale: "The 20% threshold is a rebuttable presumption, not a rigid rule." },
        { label: "B", text: "The equity method, because significant influence exists in substance", isCorrect: true, rationale: "Correct — board representation and participation in policy-making demonstrate significant influence, overcoming the presumption based on percentage alone." },
        { label: "C", text: "Full consolidation", isCorrect: false, rationale: "Consolidation requires control, which 15% ownership with board representation does not establish." },
        { label: "D", text: "The cost method with no adjustments", isCorrect: false, rationale: "The cost method is not the default for investments with significant influence." },
      ],
      explanation: "Ownership of 20% to 50% creates a rebuttable presumption of significant influence, but the presumption works in both directions. Board representation, participation in policy-making, material intercompany transactions, or technological dependency can establish significant influence below 20%, requiring the equity method.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["investments", "significant influence"],
    },
  ],
};
