import type { McqBank } from "./types";

/** FAR question bank — topics 11 through 20. */
export const farBankB: McqBank = {
  leases: [
    {
      question: "Which of the following, on its own, requires a lessee to classify a lease as a finance lease?",
      options: [
        { label: "A", text: "The lease term is 40% of the asset's remaining economic life", isCorrect: false, rationale: "A lease term covering the major part of the remaining life triggers finance classification; 40% is not a major part." },
        { label: "B", text: "The lease contains a purchase option the lessee is reasonably certain to exercise", isCorrect: true, rationale: "Correct — a purchase option reasonably certain of exercise is one of the five finance lease criteria." },
        { label: "C", text: "The lessee is responsible for insurance and maintenance", isCorrect: false, rationale: "Responsibility for executory costs does not affect lease classification." },
        { label: "D", text: "The leased asset is a building", isCorrect: false, rationale: "The nature of the underlying asset alone does not determine classification." },
      ],
      explanation: "A lessee classifies a lease as finance if any one of five criteria is met: transfer of ownership, a purchase option reasonably certain of exercise, a lease term covering the major part of remaining economic life, present value of payments amounting to substantially all of fair value, or a specialized asset with no alternative use. Meeting none of them results in an operating lease.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["leases", "classification"],
    },
    {
      question: "A lessee signs a five-year lease with annual year-end payments of $20,000 and a discount rate of 6%. The present value factor for an ordinary annuity of five payments at 6% is 4.2124. What is the initial lease liability?",
      options: [
        { label: "A", text: "$100,000", isCorrect: false, rationale: "This is the undiscounted total of the payments, ignoring the time value of money." },
        { label: "B", text: "$84,248", isCorrect: true, rationale: "Correct — $20,000 × 4.2124 = $84,248." },
        { label: "C", text: "$89,303", isCorrect: false, rationale: "This applies an annuity-due factor, but the payments are made at year-end." },
        { label: "D", text: "$20,000", isCorrect: false, rationale: "This is a single annual payment, not the present value of all five." },
      ],
      explanation: "The lease liability is measured at the present value of lease payments not yet paid. With year-end payments, the ordinary annuity factor applies: $20,000 × 4.2124 = $84,248. The right-of-use asset starts at the same amount, adjusted for initial direct costs, prepayments, and lease incentives.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["leases", "lease liability"],
    },
    {
      question: "A three-year operating lease requires payments of $10,000, $12,000, and $14,000 in successive years. What lease expense does the lessee recognize in year one?",
      options: [
        { label: "A", text: "$10,000", isCorrect: false, rationale: "This is the cash paid, not the straight-line cost recognized." },
        { label: "B", text: "$12,000", isCorrect: true, rationale: "Correct — total payments of $36,000 divided by the three-year term gives $12,000 of expense each year." },
        { label: "C", text: "$14,000", isCorrect: false, rationale: "This is the final year's cash payment." },
        { label: "D", text: "$36,000", isCorrect: false, rationale: "This is the total cost over the whole lease term." },
      ],
      explanation: "An operating lease produces a single straight-line lease cost recognized evenly over the lease term, regardless of the cash payment pattern. Total payments of $36,000 over three years give $12,000 per year; the $2,000 difference in year one adjusts the lease liability and right-of-use asset.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["leases", "operating lease"],
    },
    {
      question: "A lessee may elect NOT to recognize a right-of-use asset and lease liability when:",
      options: [
        { label: "A", text: "The lease term is 12 months or less and contains no purchase option reasonably certain of exercise", isCorrect: true, rationale: "Correct — the short-term lease practical expedient permits straight-line expense recognition without balance sheet recognition." },
        { label: "B", text: "The lease is classified as operating rather than finance", isCorrect: false, rationale: "Operating leases are still recognized on the balance sheet under ASC 842." },
        { label: "C", text: "The lease payments are immaterial to the income statement", isCorrect: false, rationale: "Materiality is a general reporting concept, not the specific ASC 842 exemption." },
        { label: "D", text: "The lessor retains title to the underlying asset", isCorrect: false, rationale: "Retained title is normal in leasing and creates no exemption." },
      ],
      explanation: "ASC 842's central change was putting operating leases on the balance sheet. The narrow exception is the short-term lease expedient: leases with a term of 12 months or less and no purchase option reasonably certain of exercise may be expensed straight-line, elected by class of underlying asset.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["leases", "short-term lease"],
    },
    {
      question: "In the income statement, how does a finance lease differ from an operating lease for a lessee?",
      options: [
        { label: "A", text: "Both produce a single straight-line lease expense", isCorrect: false, rationale: "Only the operating lease produces a single straight-line cost." },
        { label: "B", text: "A finance lease produces separate amortization and interest expense, giving a front-loaded total cost", isCorrect: true, rationale: "Correct — amortization is straight-line while interest declines as the liability is repaid, so total expense is highest in early years." },
        { label: "C", text: "A finance lease produces lower total expense over the lease term", isCorrect: false, rationale: "Total expense over the full term is identical under both models; only the pattern differs." },
        { label: "D", text: "An operating lease is reported entirely in other comprehensive income", isCorrect: false, rationale: "Lease costs are operating expenses within net income, not OCI." },
      ],
      explanation: "A finance lease is presented like a purchase financed with debt: straight-line amortization of the right-of-use asset plus interest on the liability, producing higher expense early. An operating lease combines the two into a single straight-line lease cost. Total expense across the lease term is the same either way.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["leases", "expense recognition"],
    },
    {
      question: "A lessor classifies a lease as a sales-type lease. At commencement, the lessor:",
      options: [
        { label: "A", text: "Continues to report the underlying asset and records depreciation", isCorrect: false, rationale: "That is the lessor's treatment for an operating lease." },
        { label: "B", text: "Derecognizes the underlying asset, records a net investment in the lease, and recognizes selling profit or loss", isCorrect: true, rationale: "Correct — a sales-type lease is accounted for as a sale of the underlying asset." },
        { label: "C", text: "Records a receivable equal to the total undiscounted lease payments", isCorrect: false, rationale: "The net investment is measured at present value, not the undiscounted total." },
        { label: "D", text: "Defers all income until the end of the lease term", isCorrect: false, rationale: "Selling profit is recognized at commencement and interest income over the term." },
      ],
      explanation: "In a sales-type lease the lessor has effectively sold the asset, so it removes the asset from its books, recognizes a net investment equal to the present value of lease payments plus any unguaranteed residual, and records selling profit or loss immediately. Interest income is then recognized over the lease term.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["leases", "lessor"],
    },
  ],

  "current-liabilities-contingencies-and-commitments": [
    {
      question: "A loss contingency is probable and estimated within a range of $200,000 to $500,000, with no amount in the range a better estimate than any other. Under US GAAP, what amount is accrued?",
      options: [
        { label: "A", text: "$500,000, the maximum of the range", isCorrect: false, rationale: "US GAAP accrues the minimum when no point in the range is a better estimate." },
        { label: "B", text: "$200,000, the minimum of the range", isCorrect: true, rationale: "Correct — US GAAP accrues the low end and discloses the additional exposure up to $500,000." },
        { label: "C", text: "$350,000, the midpoint of the range", isCorrect: false, rationale: "The midpoint approach is used under IFRS, not US GAAP." },
        { label: "D", text: "Nothing is accrued; the range is disclosed only", isCorrect: false, rationale: "A probable and reasonably estimable loss must be accrued." },
      ],
      explanation: "When a loss is probable and estimable only as a range, US GAAP requires accruing the low end and disclosing the possible additional loss. IFRS instead uses the midpoint when no single amount within the range is more likely — a frequently tested difference between the frameworks.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["contingencies"],
    },
    {
      question: "A company is virtually certain to win a lawsuit and receive $1,000,000, though judgment has not yet been entered. How should this be reported?",
      options: [
        { label: "A", text: "Accrue a $1,000,000 gain and a receivable", isCorrect: false, rationale: "Gain contingencies are not accrued before realization." },
        { label: "B", text: "Disclose the gain contingency without accruing it", isCorrect: true, rationale: "Correct — gain contingencies may be disclosed, but recognition waits until the gain is realized or realizable." },
        { label: "C", text: "Recognize the gain in other comprehensive income", isCorrect: false, rationale: "OCI is not a holding place for unrecognized gain contingencies." },
        { label: "D", text: "Make no disclosure until cash is received", isCorrect: false, rationale: "Disclosure is appropriate, though it must avoid misleading implications about realization." },
      ],
      explanation: "Conservatism treats gain and loss contingencies asymmetrically. Probable, estimable losses must be accrued, but gain contingencies are never accrued before realization — they may only be disclosed, and the disclosure must avoid implying that recovery is assured.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["contingencies", "gain contingency"],
    },
    {
      question: "Sales were $2,000,000 and warranty costs are estimated at 3% of sales. Actual claims paid were $45,000 and the beginning warranty liability was $18,000. What is the ending warranty liability?",
      options: [
        { label: "A", text: "$60,000", isCorrect: false, rationale: "This is the warranty expense for the year, not the ending liability balance." },
        { label: "B", text: "$33,000", isCorrect: true, rationale: "Correct — $18,000 + $60,000 expense − $45,000 paid = $33,000." },
        { label: "C", text: "$78,000", isCorrect: false, rationale: "This omits the deduction for claims actually paid." },
        { label: "D", text: "$15,000", isCorrect: false, rationale: "This ignores the beginning liability balance." },
      ],
      explanation: "Warranty expense of $60,000 ($2,000,000 × 3%) is accrued in the period of sale to match the related revenue. Claims paid reduce the liability rather than creating additional expense. Rolling forward: $18,000 + $60,000 − $45,000 = $33,000.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["warranties", "current liabilities"],
    },
    {
      question: "Short-term debt maturing within one year may be classified as noncurrent if the entity:",
      options: [
        { label: "A", text: "Merely intends to refinance the obligation on a long-term basis", isCorrect: false, rationale: "Intent alone is not sufficient; ability must also be demonstrated." },
        { label: "B", text: "Both intends to refinance long-term and demonstrates the ability to do so before the statements are issued", isCorrect: true, rationale: "Correct — both intent and demonstrated ability, through an actual refinancing or a noncancelable agreement, are required." },
        { label: "C", text: "Has positive working capital", isCorrect: false, rationale: "The working capital position does not drive debt classification." },
        { label: "D", text: "Classified it as noncurrent in the prior year", isCorrect: false, rationale: "Prior year classification does not carry forward automatically." },
      ],
      explanation: "Under US GAAP, refinancing short-term obligations on a long-term basis requires both intent and ability. Ability is demonstrated by actually refinancing after the balance sheet date but before issuance, or by entering into a noncancelable financing agreement that clearly permits the refinancing.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["current liabilities", "refinancing"],
    },
    {
      question: "An employer must accrue a liability for compensated absences when all of the following conditions are met EXCEPT:",
      options: [
        { label: "A", text: "The obligation relates to services already rendered", isCorrect: false, rationale: "This is one of the four required conditions." },
        { label: "B", text: "The obligation vests or accumulates", isCorrect: false, rationale: "This is one of the four required conditions." },
        { label: "C", text: "Payment is probable and the amount can be reasonably estimated", isCorrect: false, rationale: "These are also required conditions." },
        { label: "D", text: "The employee has submitted a formal written leave request", isCorrect: true, rationale: "Correct — no request is required; the accrual is based on the accumulated or vested right, not on a filing." },
      ],
      explanation: "Compensated absences are accrued when the obligation relates to services already rendered, the rights vest or accumulate, payment is probable, and the amount is reasonably estimable. A leave request from the employee is not among the criteria. Sick pay that accumulates but does not vest may optionally not be accrued.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["compensated absences", "current liabilities"],
    },
  ],

  "long-term-debt": [
    {
      question: "Bonds with a face amount of $500,000 and an 8% annual coupon are issued for $470,000 when the market rate is 9%. Using the effective interest method, what is interest expense for the first year?",
      options: [
        { label: "A", text: "$40,000", isCorrect: false, rationale: "This is the cash interest paid, not the effective interest expense." },
        { label: "B", text: "$42,300", isCorrect: true, rationale: "Correct — $470,000 carrying value × 9% market rate = $42,300." },
        { label: "C", text: "$45,000", isCorrect: false, rationale: "This applies the market rate to face value rather than to the carrying value." },
        { label: "D", text: "$37,600", isCorrect: false, rationale: "This applies the coupon rate to the carrying value, which is not the effective interest method." },
      ],
      explanation: "Effective interest expense equals the carrying value times the market rate at issuance: $470,000 × 9% = $42,300. Cash paid is $40,000 ($500,000 × 8%), so $2,300 of discount is amortized, raising the carrying value to $472,300 for the next period.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["bonds", "effective interest"],
    },
    {
      question: "When bonds are issued at a premium, over the life of the bonds the carrying value and interest expense will:",
      options: [
        { label: "A", text: "Both increase", isCorrect: false, rationale: "A premium is amortized downward, so the carrying value decreases." },
        { label: "B", text: "Both decrease, with carrying value declining toward face value", isCorrect: true, rationale: "Correct — premium amortization reduces carrying value, and since expense is carrying value times a fixed effective rate, expense falls as well." },
        { label: "C", text: "Both increase, with carrying value rising toward face value", isCorrect: false, rationale: "This describes a discount, not a premium." },
        { label: "D", text: "Carrying value decreases while interest expense stays constant", isCorrect: false, rationale: "Under the effective interest method expense moves with the carrying value; only straight-line amortization holds expense constant." },
      ],
      explanation: "Bonds issued at a premium are recorded above face because the coupon exceeds the market rate. Premium amortization pulls the carrying value down toward face over the term, and since effective interest expense is carrying value times a constant market rate, expense declines each period. Interest expense always falls below the cash coupon for premium bonds.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["bonds", "premium"],
    },
    {
      question: "Bonds with a face amount of $1,000,000 and a carrying value of $980,000 are retired early at 102. What gain or loss is recognized?",
      options: [
        { label: "A", text: "A $20,000 loss", isCorrect: false, rationale: "This is only the unamortized discount, not the full loss on extinguishment." },
        { label: "B", text: "A $40,000 loss", isCorrect: true, rationale: "Correct — the reacquisition price of $1,020,000 exceeds the $980,000 carrying value by $40,000." },
        { label: "C", text: "A $40,000 gain", isCorrect: false, rationale: "Paying more than carrying value produces a loss, not a gain." },
        { label: "D", text: "No gain or loss until maturity", isCorrect: false, rationale: "Extinguishment gains and losses are recognized immediately in income." },
      ],
      explanation: "Gain or loss on extinguishment equals the carrying value of the debt less the reacquisition price. The bonds are repurchased at 102% of face, or $1,020,000, against a $980,000 carrying value, producing a $40,000 loss reported in income from continuing operations.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["bonds", "extinguishment"],
    },
    {
      question: "Under current US GAAP, debt issuance costs are:",
      options: [
        { label: "A", text: "Reported as a deferred charge asset and amortized", isCorrect: false, rationale: "This was the older treatment, superseded by ASU 2015-03." },
        { label: "B", text: "Presented as a direct deduction from the carrying amount of the debt", isCorrect: true, rationale: "Correct — issuance costs reduce the debt's carrying amount like a discount and are amortized to interest expense." },
        { label: "C", text: "Expensed immediately when incurred", isCorrect: false, rationale: "They are amortized over the term of the debt, not expensed at once." },
        { label: "D", text: "Charged directly to additional paid-in capital", isCorrect: false, rationale: "That treatment applies to stock issuance costs, not debt issuance costs." },
      ],
      explanation: "Debt issuance costs are presented as a direct deduction from the carrying amount of the related debt liability, in the same manner as a discount, and amortized to interest expense using the effective interest method. Stock issuance costs, by contrast, reduce additional paid-in capital.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["bonds", "issuance costs"],
    },
    {
      question: "A note payable is issued for equipment with no stated interest rate, and neither the note nor the equipment has a readily determinable fair value. How is the note recorded?",
      options: [
        { label: "A", text: "At the face amount of the note", isCorrect: false, rationale: "A non-interest-bearing note must be discounted to reflect the time value of money." },
        { label: "B", text: "At the present value of the note using an imputed interest rate", isCorrect: true, rationale: "Correct — when no determinable fair value exists, a rate is imputed and the note is recorded at the resulting present value." },
        { label: "C", text: "At the seller's carrying value for the equipment", isCorrect: false, rationale: "The seller's book value is irrelevant to the buyer's measurement." },
        { label: "D", text: "At zero until the first payment is made", isCorrect: false, rationale: "The obligation exists from inception and must be recorded." },
      ],
      explanation: "A note with no stated rate, or an unreasonably low rate, is recorded at the fair value of the consideration exchanged. When that fair value cannot be determined, an interest rate is imputed based on prevailing rates for similar instruments, and the difference between face and present value is amortized as interest expense.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["notes payable", "imputed interest"],
    },
  ],

  "equity-and-earnings-per-share": [
    {
      question: "Net income was $500,000. Cumulative preferred stock carries an annual dividend requirement of $50,000, which was not declared this year. Weighted-average common shares were 200,000. What is basic EPS?",
      options: [
        { label: "A", text: "$2.50", isCorrect: false, rationale: "This fails to deduct the cumulative preferred dividend requirement." },
        { label: "B", text: "$2.25", isCorrect: true, rationale: "Correct — ($500,000 − $50,000) ÷ 200,000 = $2.25." },
        { label: "C", text: "$2.75", isCorrect: false, rationale: "This adds rather than subtracts the preferred dividend." },
        { label: "D", text: "$2.00", isCorrect: false, rationale: "This does not follow from the amounts given." },
      ],
      explanation: "Basic EPS is income available to common shareholders divided by weighted-average common shares. For cumulative preferred stock the annual dividend requirement is deducted whether or not declared — a key difference from noncumulative preferred, where only declared dividends are deducted. ($500,000 − $50,000) ÷ 200,000 = $2.25.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["EPS", "preferred stock"],
    },
    {
      question: "A company had 100,000 shares outstanding on January 1 and issued 24,000 additional shares on April 1. What is the weighted-average number of shares for the year?",
      options: [
        { label: "A", text: "124,000", isCorrect: false, rationale: "This treats the new shares as outstanding for the entire year." },
        { label: "B", text: "118,000", isCorrect: true, rationale: "Correct — 100,000 + (24,000 × 9/12) = 100,000 + 18,000 = 118,000." },
        { label: "C", text: "112,000", isCorrect: false, rationale: "This weights the new shares for only six months." },
        { label: "D", text: "100,000", isCorrect: false, rationale: "This ignores the April issuance entirely." },
      ],
      explanation: "Shares are weighted by the portion of the year they were outstanding. The 24,000 shares issued April 1 were outstanding nine of twelve months: 24,000 × 9/12 = 18,000. Added to the 100,000 outstanding all year, the weighted average is 118,000.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["EPS", "weighted average shares"],
    },
    {
      question: "A company declares a 2-for-1 stock split in November. How does this affect the weighted-average share calculation for EPS?",
      options: [
        { label: "A", text: "Shares are weighted from the November split date forward", isCorrect: false, rationale: "Splits and stock dividends are applied retroactively, not weighted from the declaration date." },
        { label: "B", text: "The split is applied retroactively to the beginning of the earliest period presented", isCorrect: true, rationale: "Correct — splits and stock dividends are treated as if they occurred at the start of the earliest period, and prior period EPS is restated." },
        { label: "C", text: "The split has no effect on EPS", isCorrect: false, rationale: "The share count doubles, halving EPS for all periods presented." },
        { label: "D", text: "Only the current year EPS is restated", isCorrect: false, rationale: "All periods presented must be restated for comparability." },
      ],
      explanation: "Stock splits and stock dividends change the share count without changing the entity's resources, so they are applied retroactively to the beginning of the earliest period presented, and all comparative EPS figures are restated. Shares issued for cash, by contrast, are weighted from the issuance date.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["EPS", "stock split"],
    },
    {
      question: "A company has 10,000 outstanding options with a $20 exercise price when the average market price is $25. Using the treasury stock method, how many incremental shares are added to diluted EPS?",
      options: [
        { label: "A", text: "10,000", isCorrect: false, rationale: "This ignores the assumed repurchase of shares with the exercise proceeds." },
        { label: "B", text: "2,000", isCorrect: true, rationale: "Correct — $200,000 of proceeds repurchases 8,000 shares at $25, leaving 10,000 − 8,000 = 2,000 incremental shares." },
        { label: "C", text: "8,000", isCorrect: false, rationale: "8,000 is the number of shares assumed repurchased, not the net dilution." },
        { label: "D", text: "0", isCorrect: false, rationale: "The options are in the money, so they are dilutive." },
      ],
      explanation: "The treasury stock method assumes options are exercised at the start of the period and the proceeds are used to repurchase shares at the average market price. Exercise brings in 10,000 × $20 = $200,000, repurchasing $200,000 ÷ $25 = 8,000 shares. Net dilution is 2,000 shares.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["EPS", "diluted EPS", "treasury stock method"],
    },
    {
      question: "Under the cost method, a company reissues treasury stock for more than it paid. The excess is recorded as:",
      options: [
        { label: "A", text: "A gain in net income", isCorrect: false, rationale: "Transactions in a company's own stock never produce income statement gains or losses." },
        { label: "B", text: "A credit to additional paid-in capital from treasury stock", isCorrect: true, rationale: "Correct — the excess is credited to APIC from treasury stock, an equity account." },
        { label: "C", text: "An increase to common stock at par", isCorrect: false, rationale: "The par value account is unaffected by treasury reissuance under the cost method." },
        { label: "D", text: "Other comprehensive income", isCorrect: false, rationale: "Treasury transactions are recorded directly in equity, not through OCI." },
      ],
      explanation: "A corporation cannot recognize gains or losses on transactions in its own stock. Under the cost method, reissuing treasury shares above cost credits additional paid-in capital from treasury stock; reissuing below cost first debits that account and, once it is exhausted, debits retained earnings.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["treasury stock", "equity"],
    },
    {
      question: "A potentially dilutive security is EXCLUDED from the diluted EPS calculation when:",
      options: [
        { label: "A", text: "Its inclusion would increase EPS or decrease loss per share", isCorrect: true, rationale: "Correct — antidilutive securities are excluded so diluted EPS reflects the worst-case dilution." },
        { label: "B", text: "It was issued during the current year", isCorrect: false, rationale: "Timing of issuance affects weighting, not exclusion." },
        { label: "C", text: "The holder has not yet exercised it", isCorrect: false, rationale: "Diluted EPS assumes exercise or conversion of dilutive instruments still outstanding." },
        { label: "D", text: "It is convertible preferred stock rather than an option", isCorrect: false, rationale: "The form of the instrument does not determine exclusion; its dilutive effect does." },
      ],
      explanation: "Diluted EPS presents the maximum potential dilution, so any security whose assumed exercise or conversion would raise EPS is antidilutive and excluded. Out-of-the-money options are automatically antidilutive; convertible securities require comparing the effect on both numerator and denominator.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["EPS", "antidilutive"],
    },
  ],

  "income-taxes": [
    {
      question: "Pretax book income is $800,000, including $50,000 of tax-exempt municipal bond interest. Tax depreciation exceeded book depreciation by $100,000. The tax rate is 21%. What is total income tax expense?",
      options: [
        { label: "A", text: "$168,000", isCorrect: false, rationale: "This applies the rate to book income without removing the permanent difference." },
        { label: "B", text: "$157,500", isCorrect: true, rationale: "Correct — ($800,000 − $50,000) × 21% = $157,500, comprising $136,500 current and $21,000 deferred." },
        { label: "C", text: "$136,500", isCorrect: false, rationale: "$136,500 is the current portion only; the deferred portion must be added." },
        { label: "D", text: "$147,000", isCorrect: false, rationale: "This does not reflect the correct treatment of either difference." },
      ],
      explanation: "Permanent differences never reverse, so municipal interest is excluded from the provision entirely. Temporary differences affect only the split between current and deferred. Taxable income is $650,000 ($800,000 − $50,000 − $100,000), giving current tax of $136,500, plus a $21,000 deferred tax liability — total $157,500, equal to 21% of $750,000.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["income taxes", "deferred taxes"],
    },
    {
      question: "Which item creates a deferred tax ASSET?",
      options: [
        { label: "A", text: "Tax depreciation in excess of book depreciation", isCorrect: false, rationale: "Accelerated tax depreciation defers tax to later years, creating a deferred tax liability." },
        { label: "B", text: "An accrued warranty liability not yet deductible for tax", isCorrect: true, rationale: "Correct — the expense is recognized for books now but deducted for tax later, producing a future tax benefit." },
        { label: "C", text: "Municipal bond interest income", isCorrect: false, rationale: "This is a permanent difference and creates no deferred tax at all." },
        { label: "D", text: "Installment sale income recognized for books but deferred for tax", isCorrect: false, rationale: "Recognizing income earlier for books than for tax creates a deferred tax liability." },
      ],
      explanation: "A deferred tax asset arises when an expense is recognized for books before it is deductible for tax, or when revenue is taxed before it is recognized for books. Warranty accruals, allowances for credit losses, and unearned revenue taxed on receipt all generate deferred tax assets.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["income taxes", "deferred tax asset"],
    },
    {
      question: "A valuation allowance against a deferred tax asset is required when:",
      options: [
        { label: "A", text: "It is probable that some portion will not be realized", isCorrect: false, rationale: "The US GAAP threshold is 'more likely than not,' a lower bar than 'probable.'" },
        { label: "B", text: "It is more likely than not that some portion will not be realized", isCorrect: true, rationale: "Correct — a greater-than-50% likelihood of non-realization triggers the valuation allowance." },
        { label: "C", text: "The company reported a loss in the current year", isCorrect: false, rationale: "A single loss year is negative evidence but does not automatically require an allowance." },
        { label: "D", text: "Deferred tax assets exceed deferred tax liabilities", isCorrect: false, rationale: "The relative size of DTAs and DTLs does not by itself determine the allowance." },
      ],
      explanation: "Deferred tax assets are recognized in full and then reduced by a valuation allowance if, weighing all available positive and negative evidence, it is more likely than not — greater than 50% — that some portion will not be realized. US GAAP has no valuation allowance concept for deferred tax liabilities.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["income taxes", "valuation allowance"],
    },
    {
      question: "How are deferred tax assets and liabilities classified on a classified balance sheet?",
      options: [
        { label: "A", text: "Current or noncurrent based on the classification of the related asset or liability", isCorrect: false, rationale: "This was the previous rule, eliminated by ASU 2015-17." },
        { label: "B", text: "All as noncurrent", isCorrect: true, rationale: "Correct — all deferred tax assets and liabilities are noncurrent, netted by taxing jurisdiction." },
        { label: "C", text: "All as current", isCorrect: false, rationale: "Deferred taxes are never classified as current under current guidance." },
        { label: "D", text: "Based on when the temporary difference is expected to reverse", isCorrect: false, rationale: "The expected reversal period does not drive classification." },
      ],
      explanation: "ASU 2015-17 simplified presentation by requiring all deferred tax assets and liabilities to be classified as noncurrent, regardless of when the underlying temporary differences reverse. Amounts within the same taxing jurisdiction are offset and presented as a single net noncurrent asset or liability.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["income taxes", "classification"],
    },
    {
      question: "A company's statutory tax rate is 21%, but its effective tax rate is 18%. Which item would explain this difference?",
      options: [
        { label: "A", text: "Tax depreciation exceeding book depreciation", isCorrect: false, rationale: "A temporary difference shifts tax between the current and deferred components but leaves the total provision, and therefore the effective rate, unchanged." },
        { label: "B", text: "Tax-exempt municipal bond interest income", isCorrect: true, rationale: "Correct — a favorable permanent difference reduces total tax expense without any offsetting deferred amount, pulling the effective rate below the statutory rate." },
        { label: "C", text: "An accrued warranty liability not yet deductible for tax", isCorrect: false, rationale: "This creates a deferred tax asset; total tax expense is unaffected, so the effective rate does not move." },
        { label: "D", text: "Unearned revenue taxed on receipt but recognized for books when earned", isCorrect: false, rationale: "Another temporary difference — it changes the current-versus-deferred split, not the total provision." },
      ],
      explanation: "Only permanent differences move the effective tax rate away from the statutory rate, because they change total tax expense. Temporary differences shift amounts between the current and deferred portions of the provision while leaving the total — and thus the effective rate — untouched. A favorable permanent difference such as municipal interest lowers the effective rate; an unfavorable one such as non-deductible fines raises it.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["income taxes", "effective tax rate", "permanent differences"],
    },
    {
      question: "A change in the enacted tax rate affects deferred tax balances in which period?",
      options: [
        { label: "A", text: "The period in which the new rate becomes effective", isCorrect: false, rationale: "Remeasurement occurs at enactment, which may precede the effective date." },
        { label: "B", text: "The period in which the rate change is enacted", isCorrect: true, rationale: "Correct — deferred tax balances are remeasured in the enactment period, with the effect in income from continuing operations." },
        { label: "C", text: "Retrospectively, by restating prior periods", isCorrect: false, rationale: "Rate changes are never applied retrospectively." },
        { label: "D", text: "Only when the temporary difference reverses", isCorrect: false, rationale: "Remeasurement is immediate upon enactment." },
      ],
      explanation: "Deferred tax assets and liabilities are measured using enacted rates expected to apply when the temporary differences reverse. When a new rate is enacted, existing balances are remeasured immediately in the period of enactment — not when the rate takes effect — and the adjustment flows through income from continuing operations.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["income taxes", "rate change"],
    },
  ],

  "accounting-changes-and-error-corrections": [
    {
      question: "A company changes from the FIFO inventory method to the weighted-average method. How is this reported?",
      options: [
        { label: "A", text: "Prospectively, affecting only current and future periods", isCorrect: false, rationale: "Prospective treatment applies to changes in estimate, not changes in principle." },
        { label: "B", text: "Retrospectively, restating prior periods presented and adjusting beginning retained earnings", isCorrect: true, rationale: "Correct — a change in accounting principle is applied retrospectively when practicable." },
        { label: "C", text: "As a cumulative-effect adjustment within current year net income", isCorrect: false, rationale: "The cumulative-effect-in-income approach was superseded by SFAS 154." },
        { label: "D", text: "As an item of other comprehensive income", isCorrect: false, rationale: "Accounting changes are not OCI items." },
      ],
      explanation: "A change in accounting principle is reported retrospectively: prior periods presented are restated as if the new principle had always been applied, and the cumulative effect on earlier periods adjusts the opening balance of retained earnings. A change to LIFO is the notable exception, applied prospectively because prior LIFO layers cannot be reconstructed.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["accounting changes", "principle"],
    },
    {
      question: "Equipment costing $100,000 with no salvage value has been depreciated straight-line over an assumed 10-year life. At the start of year 5, total useful life is revised to 8 years. What is depreciation expense in year 5?",
      options: [
        { label: "A", text: "$10,000", isCorrect: false, rationale: "This continues the original schedule and ignores the revision." },
        { label: "B", text: "$15,000", isCorrect: true, rationale: "Correct — the $60,000 carrying value ($100,000 − $40,000 accumulated) spread over the 4 remaining years equals $15,000." },
        { label: "C", text: "$12,500", isCorrect: false, rationale: "This spreads the original cost over 8 years without accounting for depreciation already taken." },
        { label: "D", text: "$20,000", isCorrect: false, rationale: "This uses too short a remaining life." },
      ],
      explanation: "A change in useful life is a change in accounting estimate, applied prospectively with no restatement of prior periods. Four years at $10,000 leaves a $60,000 carrying value entering year 5, and with 4 years remaining of the revised 8-year life, annual depreciation becomes $15,000.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["accounting changes", "estimate"],
    },
    {
      question: "A material error in a prior year's financial statements is discovered in the current year. How is it corrected?",
      options: [
        { label: "A", text: "By including the correction in current year net income", isCorrect: false, rationale: "Error corrections do not run through current period income." },
        { label: "B", text: "As a prior period adjustment restating the prior statements and adjusting beginning retained earnings", isCorrect: true, rationale: "Correct — material errors require restatement of the affected prior periods." },
        { label: "C", text: "Prospectively, from the date of discovery", isCorrect: false, rationale: "Prospective treatment applies only to changes in estimate." },
        { label: "D", text: "By note disclosure without adjusting any amounts", isCorrect: false, rationale: "Disclosure alone is insufficient for a material error." },
      ],
      explanation: "Correcting a material error in previously issued financial statements is a prior period adjustment. Comparative statements are restated, the beginning balance of retained earnings in the earliest period presented is adjusted, and the nature of the error and its effect on each affected line item are disclosed.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["error correction", "restatement"],
    },
    {
      question: "A change in depreciation method from double-declining balance to straight-line is accounted for as:",
      options: [
        { label: "A", text: "A change in accounting principle applied retrospectively", isCorrect: false, rationale: "Although it involves a principle, it is inseparable from the estimate of the asset's consumption pattern." },
        { label: "B", text: "A change in estimate effected by a change in principle, applied prospectively", isCorrect: true, rationale: "Correct — this specific change is treated as a change in estimate and applied prospectively." },
        { label: "C", text: "A correction of an error", isCorrect: false, rationale: "Changing methods is not an error correction." },
        { label: "D", text: "A change in reporting entity", isCorrect: false, rationale: "Reporting entity changes involve the composition of the reporting group." },
      ],
      explanation: "A change in depreciation, amortization, or depletion method is a change in accounting estimate effected by a change in accounting principle. Because the method reflects a judgment about the pattern of asset consumption, it is applied prospectively — a frequently tested exception to the general retrospective rule for principle changes.",
      difficulty: "HARD",
      questionType: "EXAM_TRAP",
      tags: ["accounting changes", "depreciation method"],
    },
    {
      question: "Which situation is a change in reporting entity?",
      options: [
        { label: "A", text: "Changing the estimated useful life of a building", isCorrect: false, rationale: "This is a change in accounting estimate." },
        { label: "B", text: "Presenting consolidated statements in place of individual company statements", isCorrect: true, rationale: "Correct — changing which entities are included in the reporting group is a change in reporting entity." },
        { label: "C", text: "Adopting a newly issued FASB standard", isCorrect: false, rationale: "This is a change in accounting principle, governed by the standard's own transition guidance." },
        { label: "D", text: "Discovering that inventory was overstated last year", isCorrect: false, rationale: "This is an error correction." },
      ],
      explanation: "A change in reporting entity occurs when the entities comprising the reporting group change — presenting consolidated rather than individual statements, or changing which subsidiaries are included. It is reported retrospectively by restating all prior periods presented so comparisons stay meaningful.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["accounting changes", "reporting entity"],
    },
  ],

  "business-combinations-and-consolidations": [
    {
      question: "An acquirer purchases 80% of a target for $800,000. The fair value of the noncontrolling interest is $200,000 and the fair value of identifiable net assets acquired is $850,000. What is goodwill?",
      options: [
        { label: "A", text: "$150,000", isCorrect: true, rationale: "Correct — $800,000 consideration + $200,000 NCI − $850,000 net identifiable assets = $150,000." },
        { label: "B", text: "$120,000", isCorrect: false, rationale: "This computes only the acquirer's 80% share, but US GAAP requires full goodwill." },
        { label: "C", text: "$50,000", isCorrect: false, rationale: "This omits the noncontrolling interest from the calculation." },
        { label: "D", text: "$0", isCorrect: false, rationale: "The total fair value of the acquiree exceeds identifiable net assets, so goodwill exists." },
      ],
      explanation: "Under the acquisition method, goodwill equals consideration transferred plus the fair value of any noncontrolling interest, less the fair value of identifiable net assets acquired: $800,000 + $200,000 − $850,000 = $150,000. US GAAP requires full goodwill, including the portion attributable to the NCI.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["business combinations", "goodwill"],
    },
    {
      question: "How does an acquirer account for legal and advisory fees incurred to complete a business combination?",
      options: [
        { label: "A", text: "Capitalize them as part of consideration transferred", isCorrect: false, rationale: "Acquisition-related costs are not part of consideration under the acquisition method." },
        { label: "B", text: "Expense them as incurred", isCorrect: true, rationale: "Correct — legal, advisory, and due diligence fees are expensed in the period incurred." },
        { label: "C", text: "Add them to goodwill", isCorrect: false, rationale: "Adding transaction costs to goodwill was the pre-ASC 805 treatment." },
        { label: "D", text: "Deduct them from additional paid-in capital", isCorrect: false, rationale: "That treatment applies to costs of issuing equity securities, not to advisory costs." },
      ],
      explanation: "Acquisition-related costs — finder's fees and legal, accounting, valuation, and other professional fees — are expensed as incurred because they are not part of the fair value exchanged for the acquiree. Costs of registering and issuing debt or equity securities follow their own separate guidance.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["business combinations", "acquisition costs"],
    },
    {
      question: "The fair value of identifiable net assets acquired exceeds the total of consideration transferred and noncontrolling interest. After reassessing its measurements, the acquirer should:",
      options: [
        { label: "A", text: "Record negative goodwill as a deferred credit and amortize it", isCorrect: false, rationale: "Deferred credit treatment is no longer permitted." },
        { label: "B", text: "Recognize a bargain purchase gain in current earnings", isCorrect: true, rationale: "Correct — after confirming all assets and liabilities were properly identified and measured, any remaining excess is recognized as a gain." },
        { label: "C", text: "Reduce the recorded value of acquired long-lived assets proportionately", isCorrect: false, rationale: "Proportionate asset reduction was the older approach under APB 16." },
        { label: "D", text: "Credit additional paid-in capital", isCorrect: false, rationale: "The gain is recognized in earnings, not in equity." },
      ],
      explanation: "A bargain purchase occurs when the fair value of identifiable net assets exceeds consideration plus NCI. Because bargain purchases are unusual, the acquirer must first reassess whether all identifiable assets and liabilities were recognized and measured correctly. Any remaining excess is recognized as a gain in earnings on the acquisition date.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["business combinations", "bargain purchase"],
    },
    {
      question: "In preparing consolidated financial statements, which of the following must be eliminated?",
      options: [
        { label: "A", text: "Dividends paid by the parent to its own shareholders", isCorrect: false, rationale: "Dividends to outside shareholders are genuine distributions and are not eliminated." },
        { label: "B", text: "Intercompany sales between parent and subsidiary and the related unrealized profit in ending inventory", isCorrect: true, rationale: "Correct — transactions within the consolidated group are not transactions with outsiders and are eliminated in full." },
        { label: "C", text: "The subsidiary's sales to unrelated third parties", isCorrect: false, rationale: "Sales to outsiders are genuine consolidated revenue." },
        { label: "D", text: "The noncontrolling interest's share of subsidiary net income", isCorrect: false, rationale: "NCI income is presented as an allocation of consolidated net income, not eliminated." },
      ],
      explanation: "Consolidation presents parent and subsidiary as a single economic entity, so all intercompany balances and transactions — sales, receivables, payables, loans, and unrealized profit remaining in inventory or fixed assets — are eliminated in full, even when the subsidiary is less than wholly owned.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["consolidations", "eliminations"],
    },
    {
      question: "Contingent consideration classified as a liability in a business combination is:",
      options: [
        { label: "A", text: "Measured at fair value on the acquisition date and never remeasured", isCorrect: false, rationale: "Liability-classified contingent consideration is remeasured each period." },
        { label: "B", text: "Measured at acquisition-date fair value and remeasured each period with changes in earnings", isCorrect: true, rationale: "Correct — subsequent fair value changes for liability-classified contingent consideration run through earnings." },
        { label: "C", text: "Recognized only when the contingency is resolved", isCorrect: false, rationale: "It is recognized at acquisition-date fair value as part of consideration transferred." },
        { label: "D", text: "Recorded as an adjustment to goodwill in every subsequent period", isCorrect: false, rationale: "Goodwill is adjusted only for measurement period adjustments about acquisition-date facts, not for later fair value changes." },
      ],
      explanation: "Contingent consideration (an earnout) is included in consideration transferred at its acquisition-date fair value. If classified as a liability it is remeasured to fair value each reporting period with changes in earnings; if classified as equity it is not remeasured. Goodwill is not adjusted for post-acquisition fair value changes.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["business combinations", "contingent consideration"],
    },
  ],

  "not-for-profit-accounting": [
    {
      question: "A not-for-profit organization classifies net assets into how many categories?",
      options: [
        { label: "A", text: "Three: unrestricted, temporarily restricted, and permanently restricted", isCorrect: false, rationale: "This three-class model was replaced by ASU 2016-14." },
        { label: "B", text: "Two: net assets without donor restrictions and net assets with donor restrictions", isCorrect: true, rationale: "Correct — the current model uses two classes based on the presence or absence of donor-imposed restrictions." },
        { label: "C", text: "Four, adding a board-designated class", isCorrect: false, rationale: "Board designations are disclosed within net assets without donor restrictions, not as a separate class." },
        { label: "D", text: "One, with all restrictions shown in the notes", isCorrect: false, rationale: "The two-class presentation is required on the face of the statement of financial position." },
      ],
      explanation: "ASU 2016-14 collapsed the three former classes into two: net assets with donor restrictions and net assets without donor restrictions. Board-designated amounts stay within the unrestricted class because the governing board can reverse its own designations, but the amounts and purposes must be disclosed.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["not-for-profit", "net assets"],
    },
    {
      question: "A donor promises $100,000 to a not-for-profit contingent on the organization raising $100,000 from other donors within one year. At the time of the promise, the organization should:",
      options: [
        { label: "A", text: "Recognize $100,000 of contribution revenue with donor restrictions", isCorrect: false, rationale: "The promise is conditional, so no revenue is recognized yet." },
        { label: "B", text: "Recognize nothing until the matching condition is substantially met", isCorrect: true, rationale: "Correct — a conditional promise to give is not recognized until the barrier is overcome and the donor's right of return lapses." },
        { label: "C", text: "Recognize $100,000 of deferred revenue", isCorrect: false, rationale: "No liability arises because no assets have been transferred." },
        { label: "D", text: "Recognize $50,000 immediately and the rest on completion", isCorrect: false, rationale: "Partial recognition of a conditional promise is not permitted." },
      ],
      explanation: "A conditional promise to give contains a barrier the recipient must overcome plus a right of return or release, and is recognized only when the condition is substantially met. An unconditional promise, by contrast, is recognized immediately as contribution revenue, restricted or unrestricted according to the donor's stipulations.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["not-for-profit", "contributions"],
    },
    {
      question: "Donated services are recognized as contribution revenue by a not-for-profit only if they:",
      options: [
        { label: "A", text: "Are provided by any volunteer for more than 40 hours", isCorrect: false, rationale: "There is no hours-based threshold in the guidance." },
        { label: "B", text: "Create or enhance a nonfinancial asset, or require specialized skills that would otherwise be purchased", isCorrect: true, rationale: "Correct — these are the two recognition criteria for donated services." },
        { label: "C", text: "Are provided by a member of the board of directors", isCorrect: false, rationale: "The donor's role is not the criterion; the nature of the services is." },
        { label: "D", text: "Are valued at more than $5,000", isCorrect: false, rationale: "No dollar threshold governs recognition." },
      ],
      explanation: "Donated services are recognized only when they create or enhance a nonfinancial asset, or when they require specialized skills, are provided by someone possessing those skills, and would typically need to be purchased if not donated. A volunteer attorney or accountant qualifies; a volunteer answering phones generally does not.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["not-for-profit", "donated services"],
    },
    {
      question: "Which statement is required for ALL not-for-profit organizations?",
      options: [
        { label: "A", text: "A statement of functional expenses presented as a separate statement", isCorrect: false, rationale: "The functional expense analysis is required, but it may appear in a separate statement, on the face of the statement of activities, or in the notes." },
        { label: "B", text: "A statement of activities", isCorrect: true, rationale: "Correct — all NFPs must present a statement of financial position, a statement of activities, and a statement of cash flows." },
        { label: "C", text: "A statement of changes in fund balances", isCorrect: false, rationale: "Fund balance reporting belongs to governmental accounting." },
        { label: "D", text: "A budgetary comparison statement", isCorrect: false, rationale: "Budgetary comparisons are a governmental reporting requirement." },
      ],
      explanation: "Every not-for-profit must present a statement of financial position, a statement of activities, and a statement of cash flows, along with an analysis of expenses by both natural and functional classification. That analysis may be presented as a separate statement, within the statement of activities, or in the notes.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["not-for-profit", "financial statements"],
    },
    {
      question: "A university receives payment from a student for tuition. How is this classified?",
      options: [
        { label: "A", text: "As a contribution without donor restrictions", isCorrect: false, rationale: "A contribution is a nonreciprocal transfer; tuition is reciprocal." },
        { label: "B", text: "As an exchange transaction accounted for under revenue recognition guidance", isCorrect: true, rationale: "Correct — the student receives commensurate value in return, making the payment an exchange transaction under ASC 606." },
        { label: "C", text: "As a conditional promise to give", isCorrect: false, rationale: "No promise to give exists; the student is purchasing educational services." },
        { label: "D", text: "As an increase in net assets with donor restrictions", isCorrect: false, rationale: "No donor restriction attaches to tuition payments." },
      ],
      explanation: "The critical distinction for not-for-profits is contribution versus exchange. A contribution is a nonreciprocal transfer in which the donor receives nothing of commensurate value. Tuition, membership dues providing substantial benefits, and program service fees are exchange transactions accounted for under ASC 606.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["not-for-profit", "exchange transactions"],
    },
  ],

  "governmental-accounting": [
    {
      question: "Governmental funds use which measurement focus and basis of accounting?",
      options: [
        { label: "A", text: "Economic resources measurement focus and full accrual basis", isCorrect: false, rationale: "This describes government-wide statements and proprietary funds." },
        { label: "B", text: "Current financial resources measurement focus and modified accrual basis", isCorrect: true, rationale: "Correct — governmental funds report near-term inflows and outflows of spendable resources using modified accrual." },
        { label: "C", text: "Cash basis", isCorrect: false, rationale: "Governmental funds are not on a pure cash basis." },
        { label: "D", text: "Budgetary basis for all reporting purposes", isCorrect: false, rationale: "Budgetary comparisons are supplementary and are not the fund's basis of accounting." },
      ],
      explanation: "Governmental funds — General, Special Revenue, Debt Service, Capital Projects, and Permanent — use the current financial resources measurement focus and modified accrual basis, recognizing revenue when measurable and available and expenditures when the fund liability is incurred. Proprietary and fiduciary funds, and all government-wide statements, use full accrual.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["governmental", "measurement focus"],
    },
    {
      question: "A city levies $1,000,000 of property taxes, expecting 2% to be uncollectible. It collects $950,000 during the year and $20,000 within 60 days after year-end. What property tax revenue is recognized in the General Fund?",
      options: [
        { label: "A", text: "$1,000,000", isCorrect: false, rationale: "The full levy is not recognized because not all of it meets the availability criterion." },
        { label: "B", text: "$970,000", isCorrect: true, rationale: "Correct — $950,000 collected during the year plus $20,000 collected within the 60-day availability period." },
        { label: "C", text: "$950,000", isCorrect: false, rationale: "This excludes amounts collected soon enough after year-end to be considered available." },
        { label: "D", text: "$980,000", isCorrect: false, rationale: "This reflects the levy net of estimated uncollectibles rather than what was actually available." },
      ],
      explanation: "Under modified accrual, revenue is recognized when measurable and available. Property taxes are considered available if collected within 60 days after year-end. Here $950,000 collected in-year plus $20,000 collected within the window equals $970,000; the remainder is reported as deferred inflows of resources.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["governmental", "revenue recognition"],
    },
    {
      question: "A city issues a purchase order for $40,000 of equipment. What entry is made in the General Fund at that time?",
      options: [
        { label: "A", text: "Debit Expenditures, credit Vouchers Payable", isCorrect: false, rationale: "The expenditure is recorded when goods are received, not when ordered." },
        { label: "B", text: "Debit Encumbrances, credit Budgetary Fund Balance Reserved for Encumbrances", isCorrect: true, rationale: "Correct — encumbrance accounting reserves appropriation authority when a commitment is made." },
        { label: "C", text: "Debit Equipment, credit Cash", isCorrect: false, rationale: "Governmental funds do not capitalize fixed assets, and no payment has occurred." },
        { label: "D", text: "No entry until the equipment is received", isCorrect: false, rationale: "Encumbrance accounting exists precisely to record the commitment at the order date." },
      ],
      explanation: "Encumbrance accounting tracks commitments against appropriations so a government does not overspend its budget. Issuing the purchase order records an encumbrance; when the goods arrive the encumbrance is reversed and an expenditure is recorded for the actual amount, which may differ from the estimate.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["governmental", "encumbrances"],
    },
    {
      question: "Which fund type would a city use for a municipal water utility that charges customers rates designed to recover its costs?",
      options: [
        { label: "A", text: "Special Revenue Fund", isCorrect: false, rationale: "Special revenue funds account for restricted revenue sources supporting specific purposes, not business-type operations." },
        { label: "B", text: "Enterprise Fund", isCorrect: true, rationale: "Correct — an enterprise fund accounts for business-type activities where goods or services are sold to external users for a fee." },
        { label: "C", text: "General Fund", isCorrect: false, rationale: "The General Fund accounts for general governmental activities not required to be reported in another fund." },
        { label: "D", text: "Custodial Fund", isCorrect: false, rationale: "Custodial funds hold resources for others in a fiduciary capacity." },
      ],
      explanation: "Enterprise funds are proprietary funds used when goods or services are provided to external users for a fee — water, sewer, or transit utilities, for example. Internal service funds serve other departments within the same government. Both proprietary types use full accrual accounting and the economic resources measurement focus.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["governmental", "fund types"],
    },
    {
      question: "How are capital assets and long-term debt reported on the General Fund's balance sheet?",
      options: [
        { label: "A", text: "As assets and liabilities of the fund, the same as in the government-wide statements", isCorrect: false, rationale: "Governmental funds report only current financial resources and claims against them." },
        { label: "B", text: "They are not reported in the fund; they appear only in the government-wide statement of net position", isCorrect: true, rationale: "Correct — under the current financial resources focus, capital assets and long-term debt are excluded from governmental fund balance sheets." },
        { label: "C", text: "Capital assets are reported but long-term debt is not", isCorrect: false, rationale: "Neither is reported in the governmental fund statements." },
        { label: "D", text: "Both are reported at the government's discretion", isCorrect: false, rationale: "GASB does not permit an election here." },
      ],
      explanation: "Because governmental funds measure current financial resources, capital asset acquisitions are recorded as expenditures and debt proceeds as other financing sources — neither balance appears on the fund balance sheet. The government-wide statements convert to full accrual, reporting capital assets and long-term liabilities with a reconciliation to the fund statements.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["governmental", "government-wide"],
    },
    {
      question: "Which component is Required Supplementary Information rather than part of the basic financial statements?",
      options: [
        { label: "A", text: "The government-wide statement of activities", isCorrect: false, rationale: "This is one of the basic financial statements." },
        { label: "B", text: "Management's Discussion and Analysis", isCorrect: true, rationale: "Correct — MD&A is Required Supplementary Information, presented before the basic financial statements." },
        { label: "C", text: "The notes to the financial statements", isCorrect: false, rationale: "The notes are an integral part of the basic financial statements." },
        { label: "D", text: "The governmental funds balance sheet", isCorrect: false, rationale: "Fund financial statements are part of the basic financial statements." },
      ],
      explanation: "A government's Annual Comprehensive Financial Report includes MD&A as Required Supplementary Information preceding the basic financial statements, which comprise the government-wide statements, the fund statements, and the notes. Budgetary comparison schedules and pension schedules are also typically RSI.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["governmental", "reporting"],
    },
  ],

  "sec-reporting-segments-and-interim-reporting": [
    {
      question: "An operating segment must be separately reported if it meets a quantitative threshold based on:",
      options: [
        { label: "A", text: "5% of revenue, assets, or profit", isCorrect: false, rationale: "The threshold is 10%, not 5%." },
        { label: "B", text: "10% of combined revenue, 10% of combined assets, or 10% of the greater absolute amount of combined profit or combined loss", isCorrect: true, rationale: "Correct — meeting any one of these three 10% tests requires separate reporting." },
        { label: "C", text: "25% of revenue only", isCorrect: false, rationale: "Revenue is only one of three tests, and the threshold is 10%." },
        { label: "D", text: "A majority of consolidated net income", isCorrect: false, rationale: "No majority test exists in segment reporting." },
      ],
      explanation: "An operating segment is reportable if its revenue (including intersegment) is 10% or more of combined revenue, its assets are 10% or more of combined assets, or its absolute profit or loss is 10% or more of the greater of combined reported profit or combined reported loss. Segments are added until reportable segments reach 75% of consolidated external revenue.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["segments", "reporting thresholds"],
    },
    {
      question: "Under US GAAP, an interim period is viewed primarily as:",
      options: [
        { label: "A", text: "A discrete, standalone reporting period", isCorrect: false, rationale: "The discrete view is generally the IFRS approach." },
        { label: "B", text: "An integral part of the annual period", isCorrect: true, rationale: "Correct — US GAAP uses the integral view, so certain costs are allocated across interim periods within the year." },
        { label: "C", text: "A period requiring audited financial statements", isCorrect: false, rationale: "Interim statements are typically reviewed, not audited." },
        { label: "D", text: "Exempt from the accounting principles used annually", isCorrect: false, rationale: "The same principles apply, with modifications for allocation." },
      ],
      explanation: "US GAAP treats an interim period as an integral part of the annual period, so income tax expense is computed using the estimated annual effective tax rate applied to year-to-date income and certain costs benefiting the full year are allocated. IFRS generally applies the discrete view, treating each interim period on its own.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["interim reporting"],
    },
    {
      question: "A large accelerated filer must file its Form 10-K within how many days after fiscal year-end?",
      options: [
        { label: "A", text: "60 days", isCorrect: true, rationale: "Correct — large accelerated filers have a 60-day deadline for the annual report." },
        { label: "B", text: "75 days", isCorrect: false, rationale: "75 days is the deadline for accelerated filers." },
        { label: "C", text: "90 days", isCorrect: false, rationale: "90 days is the deadline for non-accelerated filers." },
        { label: "D", text: "45 days", isCorrect: false, rationale: "45 days is a 10-Q deadline for non-accelerated filers, not a 10-K deadline." },
      ],
      explanation: "Form 10-K deadlines depend on filer status: large accelerated filers (public float of $700 million or more) have 60 days, accelerated filers 75 days, and non-accelerated filers 90 days. Form 10-Q deadlines are 40 days for large accelerated and accelerated filers and 45 days for non-accelerated filers.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SEC reporting", "filing deadlines"],
    },
    {
      question: "A registrant completes a material acquisition. Which form reports this event, and within what time frame?",
      options: [
        { label: "A", text: "Form 10-Q, at the end of the quarter", isCorrect: false, rationale: "Material events requiring prompt disclosure go on Form 8-K rather than waiting for the quarterly report." },
        { label: "B", text: "Form 8-K, within four business days", isCorrect: true, rationale: "Correct — Form 8-K reports material events on a current basis, generally within four business days." },
        { label: "C", text: "Form S-1, within 30 days", isCorrect: false, rationale: "Form S-1 is a registration statement for securities offerings." },
        { label: "D", text: "Form 20-F, within 90 days", isCorrect: false, rationale: "Form 20-F is the annual report for foreign private issuers." },
      ],
      explanation: "Form 8-K is the current report used to disclose material events between periodic filings — acquisitions and dispositions, auditor changes, departures of directors or officers, bankruptcy, and non-reliance on previously issued statements. It is generally due within four business days of the triggering event.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["SEC reporting", "Form 8-K"],
    },
    {
      question: "How is income tax expense determined for an interim period under US GAAP?",
      options: [
        { label: "A", text: "By applying the statutory rate to interim pretax income", isCorrect: false, rationale: "The statutory rate ignores credits, permanent differences, and the year's expected income mix." },
        { label: "B", text: "By applying the estimated annual effective tax rate to year-to-date pretax income and subtracting tax already provided", isCorrect: true, rationale: "Correct — this integral-view approach smooths the effective rate across interim periods." },
        { label: "C", text: "By deferring all tax expense until the fourth quarter", isCorrect: false, rationale: "Tax expense is recognized in every interim period." },
        { label: "D", text: "By using the prior year's actual effective rate", isCorrect: false, rationale: "The current year's estimated annual rate is used, updated each period." },
      ],
      explanation: "Consistent with the integral view, interim tax expense is computed by applying the estimated annual effective tax rate — reflecting expected credits, permanent differences, and the full-year income mix — to year-to-date ordinary income, then subtracting amounts already provided in earlier interim periods. The estimate is revised each quarter.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["interim reporting", "income taxes"],
    },
    {
      question: "Which disclosure is required for each reportable operating segment?",
      options: [
        { label: "A", text: "The number of employees assigned to the segment", isCorrect: false, rationale: "Headcount is not a required segment disclosure." },
        { label: "B", text: "A measure of profit or loss and total assets, as reviewed by the chief operating decision maker", isCorrect: true, rationale: "Correct — segment disclosures follow the management approach, reporting the measures actually used internally." },
        { label: "C", text: "A complete balance sheet and income statement for the segment", isCorrect: false, rationale: "Full financial statements are not required for each segment." },
        { label: "D", text: "The segment's earnings per share", isCorrect: false, rationale: "EPS is presented only at the consolidated level." },
      ],
      explanation: "Segment reporting follows the management approach: the entity discloses a measure of profit or loss and total assets for each reportable segment using the same measures the chief operating decision maker reviews, even where those differ from GAAP amounts, with a reconciliation to consolidated totals. Segment-level EPS and full statements are not required.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["segments", "disclosure"],
    },
  ],
};
