import type { McqBank } from "./types";

/** FAR question bank — third batch, bringing every FAR topic to at least 10 questions. */
export const farBankC: McqBank = {
  "conceptual-framework-and-financial-statement-presentation": [
    {
      question: "Under the FASB conceptual framework, what is the pervasive constraint on the information provided by financial reporting?",
      options: [
        { label: "A", text: "Cost", isCorrect: true, rationale: "Correct — reporting information imposes costs, and those costs should be justified by the benefits of reporting it." },
        { label: "B", text: "Materiality", isCorrect: false, rationale: "Materiality is an entity-specific aspect of relevance, not the pervasive constraint." },
        { label: "C", text: "Conservatism", isCorrect: false, rationale: "Conservatism is not part of the current conceptual framework; it conflicts with neutrality." },
        { label: "D", text: "Timeliness", isCorrect: false, rationale: "Timeliness is an enhancing qualitative characteristic." },
      ],
      explanation: "The cost constraint applies across all financial reporting decisions: standard setters and preparers weigh whether the benefits of providing information justify the costs of producing and using it. Materiality, by contrast, sits within relevance.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["conceptual framework", "cost constraint"],
    },
    {
      question: "Which element of financial statements is defined as the residual interest in the assets of an entity that remains after deducting its liabilities?",
      options: [
        { label: "A", text: "Comprehensive income", isCorrect: false, rationale: "Comprehensive income is the change in equity from nonowner sources during a period, not the residual interest itself." },
        { label: "B", text: "Equity (net assets)", isCorrect: true, rationale: "Correct — equity is the residual interest: assets minus liabilities." },
        { label: "C", text: "Revenue", isCorrect: false, rationale: "Revenue is an inflow from delivering goods or services in ongoing major operations." },
        { label: "D", text: "Investments by owners", isCorrect: false, rationale: "Investments by owners increase equity but are only one source of it." },
      ],
      explanation: "In the conceptual framework, equity (net assets for not-for-profits) is the residual interest in assets after deducting liabilities. The other elements — revenues, expenses, gains, losses, investments by and distributions to owners, and comprehensive income — describe changes in that residual interest.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["elements of financial statements", "equity"],
    },
  ],

  "balance-sheet-and-income-statement-preparation": [
    {
      question: "Cash set aside under a board resolution to fund a plant expansion scheduled to begin in three years should be reported as:",
      options: [
        { label: "A", text: "Cash and cash equivalents", isCorrect: false, rationale: "Cash earmarked for a long-term purpose is not available for current operations." },
        { label: "B", text: "A current asset, separately captioned", isCorrect: false, rationale: "It will not be used within one year or the operating cycle, so it is not current." },
        { label: "C", text: "A noncurrent asset", isCorrect: true, rationale: "Correct — cash designated for the acquisition or construction of noncurrent assets is classified as noncurrent." },
        { label: "D", text: "A reduction of stockholders' equity", isCorrect: false, rationale: "Earmarking cash does not change equity; at most, retained earnings could be appropriated separately." },
      ],
      explanation: "Current assets are those expected to be realized, sold, or consumed within one year or the operating cycle, whichever is longer. Cash restricted or designated for the acquisition of long-term assets does not meet that test and is reported as a noncurrent asset (often within investments and funds).",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["balance sheet", "classification"],
    },
    {
      question: "Following ASU 2015-01, a material event that is both unusual in nature and infrequent in occurrence is reported:",
      options: [
        { label: "A", text: "As an extraordinary item, net of tax, below discontinued operations", isCorrect: false, rationale: "The extraordinary item classification was eliminated by ASU 2015-01." },
        { label: "B", text: "As a separate component of income from continuing operations, before tax", isCorrect: true, rationale: "Correct — it is shown separately (or disclosed) within continuing operations, pretax, and is not presented net of tax." },
        { label: "C", text: "Directly in retained earnings", isCorrect: false, rationale: "Only items such as prior period adjustments bypass the income statement." },
        { label: "D", text: "In other comprehensive income", isCorrect: false, rationale: "Unusual or infrequent items are not OCI items." },
      ],
      explanation: "Extraordinary items no longer exist under US GAAP. Items that are unusual, infrequent, or both are reported as a separate line within income from continuing operations (or disclosed in the notes), on a pretax basis. They may not be shown net of tax, and no per-share amount is presented for them on the face of the statement.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["income statement", "unusual or infrequent items"],
    },
    {
      question: "During the year a company disposed of a component that qualifies as a discontinued operation. The component had an operating loss of $200,000 before disposal and the company recognized a $100,000 pretax loss on the disposal. The tax rate is 25%. What amount is reported as the loss from discontinued operations?",
      options: [
        { label: "A", text: "$75,000", isCorrect: false, rationale: "This tax-effects only the disposal loss and ignores the operating loss." },
        { label: "B", text: "$150,000", isCorrect: false, rationale: "This tax-effects only the operating loss and ignores the disposal loss." },
        { label: "C", text: "$225,000", isCorrect: true, rationale: "Correct — ($200,000 + $100,000) × (1 − 25%) = $225,000." },
        { label: "D", text: "$300,000", isCorrect: false, rationale: "Discontinued operations are presented net of tax, not pretax." },
      ],
      explanation: "The results of a discontinued operation include both its operating results for the period and any gain or loss on disposal. The combined pretax loss of $300,000 is reported net of the related tax benefit of $75,000, giving a $225,000 loss from discontinued operations.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["discontinued operations", "intraperiod tax allocation"],
    },
    {
      question: "Several customers have overpaid their accounts, leaving credit balances in accounts receivable. How should these be reported?",
      options: [
        { label: "A", text: "Netted against accounts receivable with debit balances", isCorrect: false, rationale: "Netting would understate both assets and liabilities." },
        { label: "B", text: "As a current liability", isCorrect: true, rationale: "Correct — the company owes these customers, so the credit balances are a liability." },
        { label: "C", text: "As deferred revenue within equity", isCorrect: false, rationale: "Customer overpayments are not equity." },
        { label: "D", text: "Only in the notes to the financial statements", isCorrect: false, rationale: "Material amounts owed to customers must be recognized, not just disclosed." },
      ],
      explanation: "Offsetting assets and liabilities is generally prohibited unless a right of setoff exists. Credit balances in customer accounts represent amounts owed to those customers, so they are reclassified to current liabilities rather than netted against other receivables.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["balance sheet", "offsetting"],
    },
  ],

  "statement-of-cash-flows": [
    {
      question: "Cash receipts and payments from buying and selling trading securities that were acquired specifically for resale are classified as:",
      options: [
        { label: "A", text: "Operating activities", isCorrect: true, rationale: "Correct — securities acquired specifically for resale are treated like inventory, so their cash flows are operating." },
        { label: "B", text: "Investing activities", isCorrect: false, rationale: "Most investment purchases are investing, but securities bought specifically for resale are an exception." },
        { label: "C", text: "Financing activities", isCorrect: false, rationale: "Financing covers transactions with owners and creditors, not purchases of securities." },
        { label: "D", text: "Noncash investing activities disclosed separately", isCorrect: false, rationale: "These are cash transactions, so they appear in the statement itself." },
      ],
      explanation: "ASC 230 classifies cash flows based on the nature and purpose of the security. Securities acquired specifically for resale and carried at fair value in a trading account are akin to inventory, so their purchases and sales are operating cash flows. Other debt and equity investments are generally investing activities.",
      difficulty: "HARD",
      questionType: "EXAM_TRAP",
      tags: ["cash flow classification", "trading securities"],
    },
    {
      question: "Cost of goods sold was $300,000. Inventory increased by $20,000 and accounts payable to suppliers increased by $15,000. Under the direct method, what is cash paid to suppliers?",
      options: [
        { label: "A", text: "$265,000", isCorrect: false, rationale: "This subtracts the inventory increase instead of adding it." },
        { label: "B", text: "$295,000", isCorrect: false, rationale: "This treats both changes in the wrong direction." },
        { label: "C", text: "$305,000", isCorrect: true, rationale: "Correct — purchases = $300,000 + $20,000 = $320,000; cash paid = $320,000 − $15,000 = $305,000." },
        { label: "D", text: "$335,000", isCorrect: false, rationale: "This adds the payable increase; a larger payable means less cash was paid." },
      ],
      explanation: "First convert COGS to purchases: an inventory increase means more was bought than sold, so add it. Then convert purchases to cash paid: an increase in accounts payable means some purchases were not yet paid, so subtract it.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["direct method", "cash paid to suppliers"],
    },
    {
      question: "During the year a company issued bonds for $500,000, repaid notes payable of $200,000, paid dividends of $50,000, purchased treasury stock for $30,000, and received interest of $10,000. What is net cash provided by financing activities?",
      options: [
        { label: "A", text: "$220,000", isCorrect: true, rationale: "Correct — $500,000 − $200,000 − $50,000 − $30,000 = $220,000." },
        { label: "B", text: "$230,000", isCorrect: false, rationale: "This includes interest received, which is an operating inflow." },
        { label: "C", text: "$250,000", isCorrect: false, rationale: "This omits the treasury stock purchase, which is a financing outflow." },
        { label: "D", text: "$270,000", isCorrect: false, rationale: "This omits dividends paid, which are a financing outflow under US GAAP." },
      ],
      explanation: "Financing activities are transactions with owners and creditors: issuing and repaying debt, issuing and reacquiring stock, and paying dividends. Interest received (and paid) is an operating cash flow under US GAAP.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["financing activities"],
    },
  ],

  "notes-subsequent-events-and-going-concern": [
    {
      question: "A lawsuit arising from a product defect that occurred before year-end is settled after the balance sheet date, but before the statements are issued, for more than the amount accrued. How should the settlement be treated?",
      options: [
        { label: "A", text: "Adjust the accrued liability at year-end to the settlement amount", isCorrect: true, rationale: "Correct — the condition (the defect and the claim) existed at the balance sheet date, so this is a recognized subsequent event." },
        { label: "B", text: "Disclose the settlement only, without adjusting", isCorrect: false, rationale: "Disclosure only applies to conditions that arose after the balance sheet date." },
        { label: "C", text: "Record the additional loss in the following year", isCorrect: false, rationale: "The settlement provides evidence about a condition that existed at year-end, so it belongs in the current statements." },
        { label: "D", text: "Record it as a prior period adjustment", isCorrect: false, rationale: "Prior period adjustments are for errors in previously issued statements, not subsequent events." },
      ],
      explanation: "Recognized (Type I) subsequent events provide additional evidence about conditions that existed at the balance sheet date. Because the underlying event occurred before year-end, the settlement refines the estimate and the accrual is adjusted.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["subsequent events", "recognized"],
    },
    {
      question: "One month after year-end, and before the financial statements are issued, a company issues $5 million of bonds. How is this reported in the year-end statements?",
      options: [
        { label: "A", text: "Recognized as a liability at year-end", isCorrect: false, rationale: "The bonds did not exist at the balance sheet date." },
        { label: "B", text: "Disclosed in the notes as a nonrecognized subsequent event", isCorrect: true, rationale: "Correct — the condition arose after year-end, so it is disclosed if material but not recognized." },
        { label: "C", text: "Not reported at all", isCorrect: false, rationale: "A material financing transaction after year-end should be disclosed to keep the statements from being misleading." },
        { label: "D", text: "Reported as a reclassification of existing debt", isCorrect: false, rationale: "Nothing about existing debt has changed." },
      ],
      explanation: "Nonrecognized (Type II) subsequent events relate to conditions that did not exist at the balance sheet date — for example, issuing debt or equity, business combinations, or casualty losses after year-end. They are disclosed when material, with the nature of the event and an estimate of its financial effect.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["subsequent events", "nonrecognized"],
    },
    {
      question: "An entity that is NOT an SEC filer evaluates subsequent events through:",
      options: [
        { label: "A", text: "The balance sheet date", isCorrect: false, rationale: "Subsequent events by definition occur after the balance sheet date." },
        { label: "B", text: "The date the financial statements are available to be issued, and it must disclose that date", isCorrect: true, rationale: "Correct — non-SEC filers evaluate through the available-to-be-issued date and disclose it." },
        { label: "C", text: "The date the financial statements are issued, with no disclosure of the date", isCorrect: false, rationale: "Evaluating through the issuance date without disclosure applies to SEC filers." },
        { label: "D", text: "90 days after year-end", isCorrect: false, rationale: "There is no fixed day count." },
      ],
      explanation: "SEC filers evaluate subsequent events through the date the statements are issued and are not required to disclose that date. All other entities evaluate through the date the statements are available to be issued and must disclose the date through which subsequent events were evaluated.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["subsequent events", "evaluation date"],
    },
    {
      question: "For material related party transactions, which disclosure is NOT required and should not be made unless it can be substantiated?",
      options: [
        { label: "A", text: "The nature of the relationship", isCorrect: false, rationale: "This is required." },
        { label: "B", text: "A description of the transactions", isCorrect: false, rationale: "This is required." },
        { label: "C", text: "The dollar amounts of the transactions for each period presented", isCorrect: false, rationale: "This is required." },
        { label: "D", text: "A statement that the transactions were on terms equivalent to arm's-length transactions", isCorrect: true, rationale: "Correct — this representation is not required and may only be made if it can be substantiated." },
      ],
      explanation: "ASC 850 requires disclosure of the nature of the relationship, a description of the transactions, the dollar amounts, and amounts due to or from related parties. Because related party transactions are not presumed to be at arm's length, an assertion that they were should not be made unless it can be substantiated.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["related parties", "disclosure"],
    },
    {
      question: "Under ASC 205-40, substantial doubt about an entity's ability to continue as a going concern exists when it is ______ that the entity will be unable to meet its obligations as they become due within one year after the financial statements are issued (or available to be issued).",
      options: [
        { label: "A", text: "Reasonably possible", isCorrect: false, rationale: "Reasonably possible is a lower threshold than the standard uses." },
        { label: "B", text: "Probable", isCorrect: true, rationale: "Correct — the threshold is 'probable', consistent with its meaning in ASC 450." },
        { label: "C", text: "More likely than not", isCorrect: false, rationale: "More likely than not is the income tax recognition threshold, not the going concern one." },
        { label: "D", text: "Virtually certain", isCorrect: false, rationale: "This is higher than the standard requires." },
      ],
      explanation: "Management evaluates whether conditions and events, considered in the aggregate, indicate that it is probable the entity will be unable to meet its obligations within one year after the issuance date. If so, substantial doubt exists, and management then considers whether its plans alleviate it.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["going concern"],
    },
  ],

  "revenue-recognition": [
    {
      question: "Under ASC 606, variable consideration is included in the transaction price only to the extent that:",
      options: [
        { label: "A", text: "The amount has been received in cash", isCorrect: false, rationale: "Revenue recognition does not depend on cash collection." },
        { label: "B", text: "It is probable that a significant reversal of cumulative revenue recognized will not occur when the uncertainty is resolved", isCorrect: true, rationale: "Correct — this is the variable consideration constraint." },
        { label: "C", text: "It is more likely than not that the amount will be earned", isCorrect: false, rationale: "The constraint uses 'probable' and focuses on avoiding a significant reversal." },
        { label: "D", text: "The customer has agreed to the final amount in writing", isCorrect: false, rationale: "Variable consideration is estimated before the final amount is known." },
      ],
      explanation: "Variable consideration is estimated using the expected value or most likely amount method, then constrained: only the portion for which a significant revenue reversal is not probable is included. Factors such as susceptibility to external factors and limited experience increase the likelihood of reversal.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["ASC 606", "variable consideration"],
    },
  ],

  "cash-receivables-and-bad-debts": [
    {
      question: "At year-end the bank statement shows a balance of $50,000. Deposits in transit total $8,000, outstanding checks total $12,000, and a $100 bank service charge has not been recorded by the company. What is the correct cash balance?",
      options: [
        { label: "A", text: "$45,900", isCorrect: false, rationale: "The service charge adjusts the book balance, not the bank balance — the correct balance already reflects it." },
        { label: "B", text: "$46,000", isCorrect: true, rationale: "Correct — $50,000 + $8,000 − $12,000 = $46,000." },
        { label: "C", text: "$54,000", isCorrect: false, rationale: "This adds outstanding checks and subtracts deposits in transit — the reverse of the correct treatment." },
        { label: "D", text: "$70,000", isCorrect: false, rationale: "Outstanding checks must be subtracted from the bank balance." },
      ],
      explanation: "Starting from the bank balance, add deposits in transit (recorded by the company, not yet by the bank) and subtract outstanding checks (recorded by the company, not yet cleared). Bank service charges are already reflected in the bank balance; they are an adjustment to the company's book balance.",
      difficulty: "EASY",
      questionType: "CALCULATION",
      tags: ["bank reconciliation"],
    },
    {
      question: "A legally restricted compensating balance maintained in connection with a long-term borrowing arrangement should be reported as:",
      options: [
        { label: "A", text: "Cash and cash equivalents", isCorrect: false, rationale: "Legally restricted cash is not freely available." },
        { label: "B", text: "A noncurrent asset, separately disclosed", isCorrect: true, rationale: "Correct — a restriction tied to long-term debt makes the balance noncurrent." },
        { label: "C", text: "A reduction of the related long-term debt", isCorrect: false, rationale: "Assets and liabilities are not offset without a right of setoff." },
        { label: "D", text: "A current asset, because it is held in cash", isCorrect: false, rationale: "The balance cannot be used within the year, so it is not current." },
      ],
      explanation: "Compensating balances that are legally restricted are separated from cash. When they relate to short-term borrowings they are current; when they relate to long-term borrowings they are classified as noncurrent assets. The arrangement is also disclosed.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["cash", "restricted cash"],
    },
    {
      question: "Accounts receivable total $400,000 at year-end and the company estimates that 5% will be uncollectible. Before adjustment, the allowance for credit losses has a $3,000 debit balance. What is credit loss expense for the year?",
      options: [
        { label: "A", text: "$17,000", isCorrect: false, rationale: "This treats the debit balance as if it were a credit balance." },
        { label: "B", text: "$20,000", isCorrect: false, rationale: "This ignores the existing debit balance in the allowance." },
        { label: "C", text: "$23,000", isCorrect: true, rationale: "Correct — the required credit balance is $20,000, so $20,000 + $3,000 debit = $23,000." },
        { label: "D", text: "$3,000", isCorrect: false, rationale: "This is just the pre-adjustment balance." },
      ],
      explanation: "Under a balance-sheet approach, the allowance must end at the estimated uncollectible amount ($400,000 × 5% = $20,000 credit). Because the account starts with a $3,000 debit, the adjusting entry must be $23,000.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["allowance for credit losses"],
    },
    {
      question: "A company pledges its accounts receivable as collateral for a bank loan. How are the receivables reported?",
      options: [
        { label: "A", text: "They are removed from the balance sheet and a gain or loss is recognized", isCorrect: false, rationale: "Pledging is not a transfer, so no derecognition occurs." },
        { label: "B", text: "They remain on the balance sheet, and the pledge is disclosed", isCorrect: true, rationale: "Correct — the company keeps the receivables and discloses that they secure the loan." },
        { label: "C", text: "They are reclassified as a noncurrent investment", isCorrect: false, rationale: "Pledging does not change the nature of the receivables." },
        { label: "D", text: "They are netted against the loan payable", isCorrect: false, rationale: "Offsetting is not permitted here." },
      ],
      explanation: "Pledging (a general assignment of receivables as collateral) does not transfer the receivables. The borrower records the loan as a liability, keeps the receivables as assets, and discloses the pledge.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["pledging", "receivables"],
    },
    {
      question: "A company transfers receivables with recourse, and the transfer meets the conditions for sale accounting. How does the transferor account for the recourse obligation?",
      options: [
        { label: "A", text: "Discloses it only", isCorrect: false, rationale: "A recourse obligation arising in a sale is a liability that must be recognized." },
        { label: "B", text: "Records a liability for the recourse obligation at fair value, which increases the loss on sale", isCorrect: true, rationale: "Correct — the obligation is measured at fair value and included in the gain or loss calculation." },
        { label: "C", text: "Keeps the receivables on the books and records a loan", isCorrect: false, rationale: "That is the accounting when the sale conditions are NOT met." },
        { label: "D", text: "Records the recourse as a reduction of equity", isCorrect: false, rationale: "Recourse relates to creditors, not owners." },
      ],
      explanation: "When a transfer qualifies as a sale, the receivables are derecognized and any new assets obtained or liabilities incurred — including a recourse obligation — are recognized at fair value. The recourse liability reduces net proceeds and therefore increases the loss on the sale.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["factoring", "transfers of financial assets"],
    },
  ],

  inventory: [
    {
      question: "A company adopted dollar-value LIFO when its inventory was $100,000 at base-year prices (index 1.00). At the end of year 1, inventory at current-year cost is $132,000 and the price index is 1.10. What is ending inventory under dollar-value LIFO?",
      options: [
        { label: "A", text: "$120,000", isCorrect: false, rationale: "This is ending inventory at base-year prices, before valuing the new layer at current prices." },
        { label: "B", text: "$122,000", isCorrect: true, rationale: "Correct — base layer $100,000 + new layer $20,000 × 1.10 = $122,000." },
        { label: "C", text: "$132,000", isCorrect: false, rationale: "This is current-year cost, which LIFO does not use for the base layer." },
        { label: "D", text: "$110,000", isCorrect: false, rationale: "This applies the index to the base layer instead of the new layer." },
      ],
      explanation: "Deflate ending inventory to base-year prices: $132,000 / 1.10 = $120,000. The real increase is $20,000 at base-year prices, which forms a new layer priced at the current index: $20,000 × 1.10 = $22,000. Add the base layer of $100,000 for $122,000.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["dollar-value LIFO"],
    },
    {
      question: "Beginning inventory was $60,000 and purchases were $240,000. Sales were $250,000, and the historical gross margin is 30% of sales. Using the gross profit method, what is estimated ending inventory?",
      options: [
        { label: "A", text: "$50,000", isCorrect: false, rationale: "This subtracts sales at retail rather than at cost." },
        { label: "B", text: "$75,000", isCorrect: false, rationale: "This is the gross profit, not ending inventory." },
        { label: "C", text: "$125,000", isCorrect: true, rationale: "Correct — goods available $300,000 − COGS ($250,000 × 70%) $175,000 = $125,000." },
        { label: "D", text: "$225,000", isCorrect: false, rationale: "This subtracts gross profit instead of cost of goods sold." },
      ],
      explanation: "Goods available for sale are $60,000 + $240,000 = $300,000. Estimated COGS is sales × (1 − gross margin) = $250,000 × 70% = $175,000. Estimated ending inventory is $300,000 − $175,000 = $125,000. The method is used for interim estimates and casualty losses, not year-end GAAP reporting.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["gross profit method", "inventory estimation"],
    },
  ],

  "property-plant-and-equipment": [
    {
      question: "During construction of a qualifying asset, the amount of interest capitalized is the:",
      options: [
        { label: "A", text: "Total interest incurred by the company during the period", isCorrect: false, rationale: "Only avoidable interest on the expenditures can be capitalized." },
        { label: "B", text: "Lesser of avoidable interest and actual interest incurred", isCorrect: true, rationale: "Correct — avoidable interest is computed on weighted-average accumulated expenditures, capped at actual interest incurred." },
        { label: "C", text: "Greater of avoidable interest and actual interest incurred", isCorrect: false, rationale: "Capitalized interest can never exceed actual interest incurred." },
        { label: "D", text: "Interest on specific construction borrowings only", isCorrect: false, rationale: "Interest on general borrowings is also used when expenditures exceed specific borrowings." },
      ],
      explanation: "Capitalized interest equals avoidable interest — the interest that could have been avoided had the expenditures not been made — computed on weighted-average accumulated expenditures using the specific borrowing rate first, then the weighted-average rate on other debt. The amount capitalized cannot exceed total interest actually incurred during the period.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["capitalized interest"],
    },
    {
      question: "A company exchanges equipment (cost $50,000, accumulated depreciation $30,000, fair value $25,000) plus $5,000 cash for new equipment. The exchange has commercial substance. At what amount is the new equipment recorded, and what gain is recognized?",
      options: [
        { label: "A", text: "$25,000; no gain", isCorrect: false, rationale: "This ignores the cash paid and the gain on the old asset." },
        { label: "B", text: "$25,000; $5,000 gain", isCorrect: false, rationale: "The new asset's cost includes the $5,000 cash paid." },
        { label: "C", text: "$30,000; $5,000 gain", isCorrect: true, rationale: "Correct — cost = $25,000 fair value given + $5,000 cash; gain = $25,000 − $20,000 carrying value." },
        { label: "D", text: "$25,000; $10,000 gain", isCorrect: false, rationale: "The gain is fair value less carrying value ($20,000), not less the cash paid." },
      ],
      explanation: "When an exchange has commercial substance, gains and losses are recognized in full. The old asset's carrying value is $20,000 and its fair value is $25,000, so a $5,000 gain is recognized. The new asset is recorded at the fair value of what was given up: $25,000 + $5,000 cash = $30,000.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["nonmonetary exchanges"],
    },
  ],

  "intangible-assets-and-goodwill": [
    {
      question: "A private company elects the private company alternative for goodwill. Goodwill is then amortized on a straight-line basis over:",
      options: [
        { label: "A", text: "40 years", isCorrect: false, rationale: "The 40-year maximum is from superseded pre-2001 guidance." },
        { label: "B", text: "10 years, or less if a shorter life is more appropriate", isCorrect: true, rationale: "Correct — the alternative permits amortization over 10 years or a shorter demonstrated life." },
        { label: "C", text: "15 years", isCorrect: false, rationale: "15 years is the tax amortization period for §197 intangibles, not the GAAP alternative." },
        { label: "D", text: "It is not amortized; it is tested annually for impairment", isCorrect: false, rationale: "That is the treatment for public companies and private companies that don't elect the alternative." },
      ],
      explanation: "Under the private company alternative (ASU 2014-02), goodwill is amortized straight-line over 10 years or less and tested for impairment only when a triggering event occurs. Public business entities do not amortize goodwill and test it at least annually.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["goodwill", "private company alternative"],
    },
    {
      question: "A company acquires a trademark that it can renew indefinitely at minimal cost and intends to use indefinitely. How is it accounted for after acquisition?",
      options: [
        { label: "A", text: "Amortized over 15 years", isCorrect: false, rationale: "15 years is the tax life, not the GAAP treatment for indefinite-lived intangibles." },
        { label: "B", text: "Amortized over its legal life", isCorrect: false, rationale: "When renewal is expected at minimal cost, the useful life is indefinite." },
        { label: "C", text: "Not amortized, and tested for impairment at least annually", isCorrect: true, rationale: "Correct — indefinite-lived intangibles are not amortized but are tested for impairment at least annually." },
        { label: "D", text: "Expensed immediately", isCorrect: false, rationale: "A purchased trademark is an asset." },
      ],
      explanation: "Intangibles with indefinite useful lives are not amortized. They are tested for impairment at least annually (and more often if events indicate impairment) by comparing fair value to carrying amount, with an optional qualitative assessment first. If the life later becomes finite, amortization begins.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["indefinite-lived intangibles", "impairment"],
    },
    {
      question: "How should a company account for legal fees incurred in successfully defending its patent against infringement?",
      options: [
        { label: "A", text: "Capitalize them as part of the cost of the patent", isCorrect: true, rationale: "Correct — a successful defense establishes the patent's value, so the costs are capitalized and amortized over its remaining life." },
        { label: "B", text: "Expense them as incurred", isCorrect: false, rationale: "Costs of an unsuccessful defense are expensed, along with writing off the patent; successful defense costs are capitalized." },
        { label: "C", text: "Record them as research and development expense", isCorrect: false, rationale: "Legal defense is not research and development." },
        { label: "D", text: "Record them as a reduction of equity", isCorrect: false, rationale: "Legal fees are not transactions with owners." },
      ],
      explanation: "Legal fees for a successful patent defense are capitalized because they protect the patent's future benefits. If the defense is unsuccessful, the fees are expensed and the patent is written off.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["patents"],
    },
    {
      question: "Costs of start-up activities, including organization costs incurred to form a corporation, are:",
      options: [
        { label: "A", text: "Capitalized and amortized over 5 years", isCorrect: false, rationale: "Five-year amortization is a tax option, not GAAP." },
        { label: "B", text: "Capitalized as an indefinite-lived intangible", isCorrect: false, rationale: "Start-up costs do not create an identifiable intangible asset." },
        { label: "C", text: "Expensed as incurred", isCorrect: true, rationale: "Correct — ASC 720-15 requires start-up and organization costs to be expensed." },
        { label: "D", text: "Included in goodwill", isCorrect: false, rationale: "Goodwill arises only in a business combination." },
      ],
      explanation: "Under GAAP, start-up and organization costs are expensed as incurred. Tax law differs: a limited amount may be deducted immediately and the remainder amortized over 180 months — a common book-tax difference.",
      difficulty: "EASY",
      questionType: "EXAM_TRAP",
      tags: ["start-up costs"],
    },
    {
      question: "A patent was purchased on January 1, Year 1, for $90,000 and amortized straight-line over 10 years. On January 1, Year 4, the company determines the patent's remaining useful life is only 4 years. What is amortization expense for Year 4?",
      options: [
        { label: "A", text: "$9,000", isCorrect: false, rationale: "This continues the original life, ignoring the change in estimate." },
        { label: "B", text: "$15,750", isCorrect: true, rationale: "Correct — carrying value $90,000 − $27,000 = $63,000, spread over the remaining 4 years." },
        { label: "C", text: "$22,500", isCorrect: false, rationale: "This divides the original cost by 4 years instead of the carrying value." },
        { label: "D", text: "$12,857", isCorrect: false, rationale: "This spreads the carrying value over 7 years, the original remaining life." },
      ],
      explanation: "A change in useful life is a change in estimate, accounted for prospectively. After three years, accumulated amortization is 3 × $9,000 = $27,000, leaving $63,000. That carrying value is amortized over the new remaining life: $63,000 / 4 = $15,750.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["amortization", "change in estimate"],
    },
  ],

  "investments-debt-and-equity-securities": [
    {
      question: "An investor pays $500,000 for 25% of an investee whose net assets have a book value of $1,600,000. The excess is attributable to equipment with a 10-year remaining life. The investee reports net income of $200,000. What equity-method income does the investor recognize?",
      options: [
        { label: "A", text: "$50,000", isCorrect: false, rationale: "This ignores the amortization of the excess cost attributed to equipment." },
        { label: "B", text: "$40,000", isCorrect: true, rationale: "Correct — $200,000 × 25% = $50,000, less $100,000 / 10 = $10,000 depreciation of the excess." },
        { label: "C", text: "$60,000", isCorrect: false, rationale: "The excess depreciation reduces, not increases, equity income." },
        { label: "D", text: "$37,500", isCorrect: false, rationale: "The excess is amortized over the equipment's 10-year life, not 8 years." },
      ],
      explanation: "The investor's share of book value is $1,600,000 × 25% = $400,000, so it paid $100,000 more. Because that excess relates to depreciable equipment, it is depreciated over 10 years ($10,000 per year), reducing equity income from $50,000 to $40,000.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["equity method", "excess cost"],
    },
    {
      question: "Debt securities classified as held-to-maturity are reported on the balance sheet at:",
      options: [
        { label: "A", text: "Fair value, with changes in net income", isCorrect: false, rationale: "That is the treatment for trading securities." },
        { label: "B", text: "Fair value, with changes in other comprehensive income", isCorrect: false, rationale: "That is the treatment for available-for-sale securities." },
        { label: "C", text: "Amortized cost, net of any allowance for credit losses", isCorrect: true, rationale: "Correct — HTM securities are carried at amortized cost, with expected credit losses recognized through an allowance under CECL." },
        { label: "D", text: "Lower of cost or market", isCorrect: false, rationale: "LCM is not used for debt securities." },
      ],
      explanation: "Held-to-maturity debt securities are measured at amortized cost — cost adjusted for premium or discount amortization using the effective interest method. Under ASC 326, an allowance for expected credit losses is deducted.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["held-to-maturity"],
    },
    {
      question: "Unrealized holding gains and losses on debt securities classified as trading are reported in:",
      options: [
        { label: "A", text: "Net income", isCorrect: true, rationale: "Correct — trading securities are measured at fair value through net income." },
        { label: "B", text: "Other comprehensive income", isCorrect: false, rationale: "OCI is used for available-for-sale debt securities." },
        { label: "C", text: "Directly in retained earnings", isCorrect: false, rationale: "Holding gains are not recorded directly in retained earnings." },
        { label: "D", text: "The notes only, until the securities are sold", isCorrect: false, rationale: "Trading securities are remeasured to fair value every period." },
      ],
      explanation: "Trading debt securities are carried at fair value with unrealized gains and losses in net income. Available-for-sale debt securities are also carried at fair value, but their unrealized gains and losses (other than credit losses) go to OCI.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["trading securities"],
    },
    {
      question: "An entity holds an equity security that does not have a readily determinable fair value and does not qualify for the equity method. If it elects the measurement alternative, the investment is measured at:",
      options: [
        { label: "A", text: "Original cost, never adjusted", isCorrect: false, rationale: "The alternative requires adjustment for impairment and observable price changes." },
        { label: "B", text: "Cost minus impairment, plus or minus changes from observable price changes in orderly transactions for identical or similar investments", isCorrect: true, rationale: "Correct — this is the ASC 321 measurement alternative." },
        { label: "C", text: "Fair value, with changes in other comprehensive income", isCorrect: false, rationale: "OCI treatment for equity securities was eliminated by ASU 2016-01." },
        { label: "D", text: "Lower of cost or net realizable value", isCorrect: false, rationale: "That is an inventory measurement basis." },
      ],
      explanation: "Equity securities are generally measured at fair value through net income. For those without a readily determinable fair value, ASC 321 permits a measurement alternative: cost less impairment, adjusted up or down when an observable price change occurs in an orderly transaction for the identical or a similar investment of the same issuer.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["equity securities", "measurement alternative"],
    },
    {
      question: "Under ASC 326, how is a credit loss on an available-for-sale debt security recognized?",
      options: [
        { label: "A", text: "As a direct write-down of amortized cost that can never be reversed", isCorrect: false, rationale: "The current model uses an allowance, which can be reversed if credit improves." },
        { label: "B", text: "Through an allowance for credit losses, limited to the amount by which fair value is below amortized cost", isCorrect: true, rationale: "Correct — the allowance is capped at the difference between fair value and amortized cost." },
        { label: "C", text: "In other comprehensive income with the rest of the unrealized loss", isCorrect: false, rationale: "Only the non-credit portion of the decline goes to OCI." },
        { label: "D", text: "Only when the security is sold", isCorrect: false, rationale: "Credit losses are recognized as they are expected, not when realized." },
      ],
      explanation: "For AFS debt securities, the credit-related portion of a decline is recorded through an allowance (and credit loss expense in net income), limited to the amount by which fair value is below amortized cost. The non-credit portion stays in OCI. If credit improves, the allowance can be reduced.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["available-for-sale", "credit losses"],
    },
  ],

  leases: [
    {
      question: "At lease commencement, a lessee's lease liability is $84,000. The lessee paid $2,000 of initial direct costs and received a $3,000 lease incentive from the lessor. At what amount is the right-of-use asset initially measured?",
      options: [
        { label: "A", text: "$84,000", isCorrect: false, rationale: "This ignores the initial direct costs and the incentive." },
        { label: "B", text: "$83,000", isCorrect: true, rationale: "Correct — $84,000 + $2,000 − $3,000 = $83,000." },
        { label: "C", text: "$89,000", isCorrect: false, rationale: "Lease incentives received reduce, not increase, the ROU asset." },
        { label: "D", text: "$85,000", isCorrect: false, rationale: "This subtracts the initial direct costs and adds the incentive." },
      ],
      explanation: "The ROU asset starts with the lease liability, then adds any lease payments made at or before commencement and initial direct costs, and subtracts lease incentives received.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["ASC 842", "right-of-use asset"],
    },
    {
      question: "In a sale-and-leaseback, the transfer of the asset does not qualify as a sale under ASC 606. How does the seller-lessee account for the transaction?",
      options: [
        { label: "A", text: "It derecognizes the asset and recognizes a gain", isCorrect: false, rationale: "Derecognition requires that the transfer qualify as a sale." },
        { label: "B", text: "It keeps the asset on its books and accounts for the proceeds as a financial liability", isCorrect: true, rationale: "Correct — a failed sale is accounted for as a financing arrangement." },
        { label: "C", text: "It records a right-of-use asset and a lease liability only", isCorrect: false, rationale: "Lease accounting applies only after a successful sale." },
        { label: "D", text: "It recognizes the proceeds as revenue over the lease term", isCorrect: false, rationale: "Proceeds from a failed sale are borrowings, not revenue." },
      ],
      explanation: "If control of the asset does not transfer — for example, because the seller-lessee has a repurchase option that is not at fair value — the transaction is a failed sale. The seller-lessee continues to recognize the asset and records the cash received as a financial liability; the buyer-lessor records a receivable.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["sale-leaseback"],
    },
  ],

  "current-liabilities-contingencies-and-commitments": [
    {
      question: "An unasserted claim exists — no lawsuit has been filed yet. The company must disclose it when:",
      options: [
        { label: "A", text: "Any claim is conceivable", isCorrect: false, rationale: "Speculative claims do not require disclosure." },
        { label: "B", text: "It is probable a claim will be asserted and an unfavorable outcome is at least reasonably possible", isCorrect: true, rationale: "Correct — both conditions must be met for an unasserted claim to require disclosure." },
        { label: "C", text: "Legal counsel has been consulted", isCorrect: false, rationale: "Consulting counsel does not trigger disclosure." },
        { label: "D", text: "The claim is remote but material", isCorrect: false, rationale: "Remote claims generally require no disclosure." },
      ],
      explanation: "For unasserted claims, ASC 450 requires disclosure only when it is probable the claim will be asserted and there is a reasonable possibility the outcome will be unfavorable. If both assertion and loss are probable and the loss can be estimated, an accrual is required.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["loss contingencies", "unasserted claims"],
    },
    {
      question: "A loss contingency is reasonably possible and its amount can be estimated. How is it reported?",
      options: [
        { label: "A", text: "Accrued and disclosed", isCorrect: false, rationale: "Accrual requires that the loss be probable." },
        { label: "B", text: "Disclosed only", isCorrect: true, rationale: "Correct — reasonably possible losses are disclosed but not accrued." },
        { label: "C", text: "Neither accrued nor disclosed", isCorrect: false, rationale: "That is the treatment for most remote losses." },
        { label: "D", text: "Accrued only", isCorrect: false, rationale: "Accrual without disclosure is never the rule, and here accrual isn't allowed." },
      ],
      explanation: "Probable and estimable losses are accrued. Reasonably possible losses are disclosed (nature of the contingency and an estimate or range, or a statement that no estimate can be made). Remote losses generally require nothing, apart from certain guarantees.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["loss contingencies"],
    },
    {
      question: "Which contingency generally must be disclosed even though the likelihood of loss is remote?",
      options: [
        { label: "A", text: "A lawsuit that counsel expects to win", isCorrect: false, rationale: "A remote lawsuit loss requires no disclosure." },
        { label: "B", text: "A guarantee of another entity's debt", isCorrect: true, rationale: "Correct — guarantees are disclosed even when the chance of loss is remote." },
        { label: "C", text: "General business risks such as a possible recession", isCorrect: false, rationale: "General business risks are not accrued or disclosed as contingencies." },
        { label: "D", text: "A possible future uninsured fire", isCorrect: false, rationale: "Risk of future uninsured losses is not a loss contingency requiring disclosure." },
      ],
      explanation: "Guarantees of indebtedness of others and similar arrangements are disclosed regardless of the likelihood of loss. Under ASC 460, a guarantor also generally recognizes a liability at inception for the fair value of the obligation it has taken on.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["guarantees", "remote contingencies"],
    },
    {
      question: "A company installs an offshore platform that it is legally required to dismantle at the end of its life. How is the asset retirement obligation (ARO) initially recognized?",
      options: [
        { label: "A", text: "Expensed at the undiscounted cost of dismantling", isCorrect: false, rationale: "The ARO is capitalized, not expensed, and measured at fair value." },
        { label: "B", text: "Recognized as a liability at fair value, with the same amount capitalized into the asset", isCorrect: true, rationale: "Correct — the liability (usually a present value) is added to the asset's carrying amount and depreciated." },
        { label: "C", text: "Disclosed only until dismantling begins", isCorrect: false, rationale: "A legal obligation that can be reasonably estimated must be recognized." },
        { label: "D", text: "Recorded as a reduction of equity", isCorrect: false, rationale: "AROs are liabilities, not equity transactions." },
      ],
      explanation: "An ARO is recognized when incurred at fair value, typically the present value of expected dismantling costs. The same amount is capitalized as part of the asset and depreciated. The liability grows over time through accretion expense, which is an operating expense, not interest expense.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["asset retirement obligations"],
    },
    {
      question: "A retailer sells $100,000 of gift cards. Based on reliable history, it expects 10% to never be redeemed. During the year, $45,000 of cards are redeemed. How much revenue should be recognized for the year, including breakage?",
      options: [
        { label: "A", text: "$45,000", isCorrect: false, rationale: "This ignores breakage, which is recognized in proportion to redemptions." },
        { label: "B", text: "$50,000", isCorrect: true, rationale: "Correct — redemptions are 50% of the $90,000 expected, so $5,000 of breakage is recognized with the $45,000 redeemed." },
        { label: "C", text: "$55,000", isCorrect: false, rationale: "This recognizes all $10,000 of expected breakage upfront." },
        { label: "D", text: "$100,000", isCorrect: false, rationale: "Unredeemed cards are a contract liability until redeemed or until breakage is recognized." },
      ],
      explanation: "Gift card sales create a contract liability. When breakage is expected, it is recognized in proportion to the pattern of rights exercised by customers. Expected redemptions are $90,000; $45,000 is 50% of that, so 50% of expected breakage ($5,000) is recognized.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["gift cards", "breakage"],
    },
  ],

  "long-term-debt": [
    {
      question: "A company issues $100,000 of 5-year bonds with a 6% annual coupon when the market rate is 8%. The PV of $1 at 8% for 5 periods is 0.681 and the PV of an ordinary annuity of $1 at 8% for 5 periods is 3.993. What is the issue price?",
      options: [
        { label: "A", text: "$92,058", isCorrect: true, rationale: "Correct — ($100,000 × 0.681) + ($6,000 × 3.993) = $68,100 + $23,958." },
        { label: "B", text: "$100,000", isCorrect: false, rationale: "Bonds sell at face only when the coupon rate equals the market rate." },
        { label: "C", text: "$68,100", isCorrect: false, rationale: "This is only the present value of the principal." },
        { label: "D", text: "$107,986", isCorrect: false, rationale: "A coupon rate below the market rate produces a discount, not a premium." },
      ],
      explanation: "A bond's price is the present value of its principal plus the present value of its interest payments, both discounted at the market rate. Because the 6% coupon is below the 8% market rate, the bonds sell at a discount.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["bond pricing", "present value"],
    },
    {
      question: "In a troubled debt restructuring, a debtor transfers land with a carrying amount of $300,000 and fair value of $350,000 to fully settle debt with a carrying amount of $500,000. What gain on restructuring of debt does the debtor recognize?",
      options: [
        { label: "A", text: "$50,000", isCorrect: false, rationale: "This is the gain on transferring the land, a separate gain." },
        { label: "B", text: "$150,000", isCorrect: true, rationale: "Correct — debt carrying amount $500,000 − fair value of land $350,000." },
        { label: "C", text: "$200,000", isCorrect: false, rationale: "This is the total gain; the question asks only for the restructuring gain." },
        { label: "D", text: "$0", isCorrect: false, rationale: "Settling debt for less than its carrying amount produces a gain." },
      ],
      explanation: "When a debtor settles debt by transferring a noncash asset, it first remeasures the asset to fair value, recognizing a $50,000 gain on disposal ($350,000 − $300,000). The difference between the debt's carrying amount and the asset's fair value is the gain on restructuring: $500,000 − $350,000 = $150,000.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["troubled debt restructuring"],
    },
    {
      question: "Convertible bonds with no separately accounted-for conversion feature are converted into common stock. Using the book value method, how is the conversion recorded?",
      options: [
        { label: "A", text: "Stock is recorded at the market value of the shares, with a gain or loss", isCorrect: false, rationale: "The book value method records no gain or loss." },
        { label: "B", text: "Stock is recorded at the carrying amount of the bonds, with no gain or loss", isCorrect: true, rationale: "Correct — the bonds' carrying amount is transferred to equity." },
        { label: "C", text: "The bonds are treated as extinguished at face value", isCorrect: false, rationale: "The carrying amount, including any unamortized discount or premium, is what is transferred." },
        { label: "D", text: "The conversion is disclosed but not recorded", isCorrect: false, rationale: "Conversion changes both debt and equity and must be recorded." },
      ],
      explanation: "Under the book value method, the carrying amount of the converted bonds (face value adjusted for any unamortized premium or discount and issuance costs) becomes the recorded amount of the stock issued. Common stock is credited at par and the remainder goes to additional paid-in capital.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["convertible bonds"],
    },
    {
      question: "Bonds with detachable warrants are issued for $1,050,000. Without the warrants, the bonds would have a fair value of $900,000, and the warrants have a fair value of $100,000. How much of the proceeds is allocated to the warrants?",
      options: [
        { label: "A", text: "$100,000", isCorrect: false, rationale: "Proceeds are allocated using relative fair values, not the warrants' stand-alone fair value." },
        { label: "B", text: "$105,000", isCorrect: true, rationale: "Correct — $1,050,000 × $100,000 / $1,000,000." },
        { label: "C", text: "$150,000", isCorrect: false, rationale: "This is the incremental method, which applies only when one fair value is unknown." },
        { label: "D", text: "$0", isCorrect: false, rationale: "Detachable warrants must be accounted for separately." },
      ],
      explanation: "When both fair values are known, proceeds are allocated using their relative fair values. The warrants represent 10% of the combined $1,000,000 fair value, so they receive 10% of the $1,050,000 proceeds, recorded in additional paid-in capital.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["detachable warrants"],
    },
    {
      question: "The straight-line method of amortizing bond discount or premium is acceptable under US GAAP:",
      options: [
        { label: "A", text: "Always, as an accounting policy election", isCorrect: false, rationale: "The effective interest method is required unless straight-line isn't materially different." },
        { label: "B", text: "Only if its results are not materially different from the effective interest method", isCorrect: true, rationale: "Correct — straight-line is allowed only when the difference is immaterial." },
        { label: "C", text: "Only for bonds issued at a premium", isCorrect: false, rationale: "The rule applies equally to premiums and discounts." },
        { label: "D", text: "Never", isCorrect: false, rationale: "It is allowed when results are not materially different." },
      ],
      explanation: "The effective interest method is required because it produces a constant rate of interest on the carrying amount. Straight-line amortization may be used only if its results are not materially different.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["effective interest method"],
    },
  ],

  "equity-and-earnings-per-share": [
    {
      question: "A company with 100,000 shares of $1 par common stock outstanding declares a 10% stock dividend when the market price is $30 per share. By how much does retained earnings decrease?",
      options: [
        { label: "A", text: "$10,000", isCorrect: false, rationale: "Par value is used only for large stock dividends (typically over 20–25%)." },
        { label: "B", text: "$300,000", isCorrect: true, rationale: "Correct — a small stock dividend is capitalized at market value: 10,000 shares × $30." },
        { label: "C", text: "$0", isCorrect: false, rationale: "A stock dividend transfers retained earnings to paid-in capital." },
        { label: "D", text: "$3,000,000", isCorrect: false, rationale: "This multiplies all outstanding shares by the market price." },
      ],
      explanation: "Small stock dividends (generally below 20–25% of outstanding shares) are recorded at fair value: retained earnings is debited $300,000, common stock is credited $10,000 at par, and additional paid-in capital $290,000. Total equity is unchanged.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["stock dividends"],
    },
    {
      question: "A company grants 10,000 stock options with a grant-date fair value of $12 each. The options cliff-vest after 4 years of service. Assuming no forfeitures, what compensation expense is recognized in Year 1?",
      options: [
        { label: "A", text: "$120,000", isCorrect: false, rationale: "Expense is recognized over the service period, not at grant." },
        { label: "B", text: "$30,000", isCorrect: true, rationale: "Correct — $120,000 total fair value / 4-year service period." },
        { label: "C", text: "$0", isCorrect: false, rationale: "Expense begins in the first year of service." },
        { label: "D", text: "It depends on the stock price at year-end", isCorrect: false, rationale: "Equity-classified awards are measured at grant-date fair value and not remeasured." },
      ],
      explanation: "Equity-classified share-based awards are measured at grant-date fair value and recognized as expense over the requisite service period — here, $120,000 over 4 years. The fair value is not remeasured for later changes in the stock price.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["share-based compensation"],
    },
  ],

  "income-taxes": [
    {
      question: "Under ASC 740, a tax benefit from an uncertain tax position is recognized only if:",
      options: [
        { label: "A", text: "It is probable of being sustained on examination", isCorrect: false, rationale: "The threshold is more-likely-than-not, which is lower than probable." },
        { label: "B", text: "It is more likely than not to be sustained on examination based on its technical merits", isCorrect: true, rationale: "Correct — then the benefit is measured as the largest amount that is more than 50% likely to be realized." },
        { label: "C", text: "The taxing authority has not yet examined the return", isCorrect: false, rationale: "Recognition assumes the position will be examined by an authority with full knowledge." },
        { label: "D", text: "It has been disclosed in the tax return", isCorrect: false, rationale: "Disclosure on the return does not determine recognition." },
      ],
      explanation: "ASC 740 uses a two-step approach: (1) recognition — the position must be more likely than not (greater than 50%) to be sustained on its technical merits, assuming examination; (2) measurement — the benefit recognized is the largest amount with a greater than 50% likelihood of being realized on settlement.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["uncertain tax positions"],
    },
  ],

  "accounting-changes-and-error-corrections": [
    {
      question: "A small company switches from the cash basis of accounting to accrual-basis GAAP. How is this change reported?",
      options: [
        { label: "A", text: "As a change in accounting principle, applied retrospectively", isCorrect: false, rationale: "Moving from a non-GAAP method to GAAP is an error correction, not a change in principle." },
        { label: "B", text: "As a correction of an error, through a prior period adjustment", isCorrect: true, rationale: "Correct — a change from a method that is not GAAP to GAAP is treated as an error correction." },
        { label: "C", text: "As a change in estimate, applied prospectively", isCorrect: false, rationale: "Nothing about an estimate has changed." },
        { label: "D", text: "As a change in reporting entity", isCorrect: false, rationale: "The entity reporting has not changed." },
      ],
      explanation: "A change in accounting principle is a change from one GAAP method to another. Moving from a non-GAAP method (such as the cash basis for a GAAP reporter) to GAAP corrects an error and is reported through restatement and a prior period adjustment.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["error correction"],
    },
    {
      question: "Ending inventory for Year 1 was understated by $10,000, and the error was never corrected. Ignoring taxes, what is the effect on Year 2?",
      options: [
        { label: "A", text: "Year 2 net income is understated by $10,000", isCorrect: false, rationale: "Year 2's beginning inventory is understated, which understates COGS and overstates net income." },
        { label: "B", text: "Year 2 net income is overstated by $10,000, and retained earnings at the end of Year 2 is correct", isCorrect: true, rationale: "Correct — the error reverses in Year 2, so cumulative retained earnings is right by the end of Year 2." },
        { label: "C", text: "Retained earnings at the end of Year 2 is understated by $10,000", isCorrect: false, rationale: "Inventory errors counterbalance over two years." },
        { label: "D", text: "Year 2 is unaffected", isCorrect: false, rationale: "Year 1's ending inventory becomes Year 2's beginning inventory." },
      ],
      explanation: "Understating Year 1 ending inventory overstates Year 1 COGS and understates Year 1 net income. That same understated amount becomes Year 2's beginning inventory, understating Year 2 COGS and overstating Year 2 net income by the same amount. The errors counterbalance, so retained earnings is correct at the end of Year 2.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["counterbalancing errors", "inventory errors"],
    },
    {
      question: "When a change in accounting principle is applied retrospectively, the cumulative effect of the change on periods before those presented is reported as:",
      options: [
        { label: "A", text: "A separate line in current-year net income", isCorrect: false, rationale: "Reporting a cumulative effect in current net income was eliminated with SFAS 154." },
        { label: "B", text: "An adjustment to the opening balance of retained earnings of the earliest period presented", isCorrect: true, rationale: "Correct — prior periods presented are restated, and earlier effects go to opening retained earnings." },
        { label: "C", text: "An item of other comprehensive income", isCorrect: false, rationale: "Changes in principle do not flow through OCI." },
        { label: "D", text: "A note disclosure only", isCorrect: false, rationale: "Retrospective application changes the reported amounts, not just the disclosures." },
      ],
      explanation: "Under retrospective application, all periods presented are recast as if the new principle had always been used, and the cumulative effect on periods before the earliest one presented is recorded as an adjustment to that period's opening retained earnings (or other appropriate equity component).",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["change in accounting principle", "retrospective application"],
    },
    {
      question: "A company changes from FIFO to LIFO. Why is this change usually applied prospectively rather than retrospectively?",
      options: [
        { label: "A", text: "Changes to LIFO are changes in estimate", isCorrect: false, rationale: "A change in inventory method is a change in principle." },
        { label: "B", text: "Determining prior-period LIFO layers is usually impracticable, so the beginning inventory of the year of change becomes the base-year layer", isCorrect: true, rationale: "Correct — the impracticability exception applies, with disclosure of why retrospective application wasn't done." },
        { label: "C", text: "GAAP prohibits retrospective application for inventory changes", isCorrect: false, rationale: "Other inventory changes, such as LIFO to FIFO, are applied retrospectively." },
        { label: "D", text: "The IRS requires prospective application", isCorrect: false, rationale: "Tax rules do not determine the GAAP reporting method for the change." },
      ],
      explanation: "Changes in accounting principle are normally applied retrospectively. For a change to LIFO, reconstructing historical LIFO layers is generally impracticable, so the company uses the carrying amount of inventory at the beginning of the year of change as its base layer and discloses why retrospective application was not done.",
      difficulty: "HARD",
      questionType: "EXAM_TRAP",
      tags: ["change in accounting principle", "LIFO"],
    },
    {
      question: "In Year 2, a company discovers that $20,000 of depreciation was omitted from its Year 1 financial statements, which have already been issued. The tax rate is 25%. What adjustment is made to the beginning Year 2 retained earnings?",
      options: [
        { label: "A", text: "A $20,000 decrease", isCorrect: false, rationale: "Prior period adjustments are reported net of tax." },
        { label: "B", text: "A $15,000 decrease", isCorrect: true, rationale: "Correct — $20,000 × (1 − 25%) = $15,000 net-of-tax decrease." },
        { label: "C", text: "A $15,000 increase", isCorrect: false, rationale: "Omitted depreciation overstated income, so retained earnings must decrease." },
        { label: "D", text: "No adjustment; record $20,000 extra depreciation in Year 2", isCorrect: false, rationale: "Material errors in issued statements are corrected through a prior period adjustment, not current income." },
      ],
      explanation: "Omitting depreciation overstated Year 1 net income. The correction is a prior period adjustment to beginning retained earnings, net of the related tax effect: $20,000 − $5,000 = $15,000. Comparative Year 1 statements are restated.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["prior period adjustment"],
    },
  ],

  "business-combinations-and-consolidations": [
    {
      question: "A parent sells inventory costing $60,000 to its subsidiary for $80,000. At year-end, 25% of the goods remain in the subsidiary's inventory. What unrealized profit is eliminated in consolidation?",
      options: [
        { label: "A", text: "$20,000", isCorrect: false, rationale: "Profit on goods sold to outside customers has been realized." },
        { label: "B", text: "$15,000", isCorrect: false, rationale: "This is the profit on the goods already sold to outsiders." },
        { label: "C", text: "$5,000", isCorrect: true, rationale: "Correct — $20,000 intercompany profit × 25% still held." },
        { label: "D", text: "$0", isCorrect: false, rationale: "Profit on goods still held within the group is unrealized and must be eliminated." },
      ],
      explanation: "Intercompany profit is realized only when the goods are sold outside the consolidated group. The total profit is $20,000, and 25% of the goods remain in the group, so $5,000 is eliminated from ending inventory and consolidated income.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["intercompany transactions", "unrealized profit"],
    },
    {
      question: "An acquirer records provisional amounts for a business combination. Six months later, it obtains new information about facts that existed at the acquisition date. How are the provisional amounts adjusted?",
      options: [
        { label: "A", text: "Retrospectively, restating prior periods", isCorrect: false, rationale: "Measurement period adjustments are no longer applied retrospectively." },
        { label: "B", text: "In the period the adjustment is identified, generally with an offsetting change to goodwill", isCorrect: true, rationale: "Correct — adjustments within the one-year measurement period are recognized when identified, usually against goodwill." },
        { label: "C", text: "They cannot be adjusted once recorded", isCorrect: false, rationale: "Provisional amounts can be adjusted during the measurement period." },
        { label: "D", text: "As a gain or loss in net income only", isCorrect: false, rationale: "The offsetting entry is generally to goodwill, not income." },
      ],
      explanation: "The measurement period lasts up to one year from the acquisition date. New information about conditions that existed at the acquisition date adjusts the provisional amounts, generally with an offset to goodwill, in the period the adjustment is determined. The effect on earnings of the change, calculated as if it had been recorded at acquisition, is recognized in the current period and disclosed.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["measurement period"],
    },
    {
      question: "In a consolidated balance sheet, the noncontrolling interest in a subsidiary is presented:",
      options: [
        { label: "A", text: "As a liability", isCorrect: false, rationale: "NCI is an ownership interest, not an obligation." },
        { label: "B", text: "In the mezzanine between liabilities and equity", isCorrect: false, rationale: "Mezzanine presentation applies only to certain redeemable instruments." },
        { label: "C", text: "Within equity, separately from the parent's equity", isCorrect: true, rationale: "Correct — ASC 810 requires NCI to be shown in equity, separate from the parent's equity." },
        { label: "D", text: "Only in the notes", isCorrect: false, rationale: "NCI appears on the face of the consolidated balance sheet." },
      ],
      explanation: "Noncontrolling interest is the equity in a subsidiary not attributable to the parent. It is reported within consolidated equity, clearly separated from the parent's equity. Consolidated net income and comprehensive income are likewise attributed between the parent and the NCI.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["noncontrolling interest"],
    },
  ],

  "not-for-profit-accounting": [
    {
      question: "A donor gives a museum $1,000,000 with the stipulation that the principal be maintained in perpetuity and only the investment income be spent. How is the gift classified?",
      options: [
        { label: "A", text: "Net assets without donor restrictions, designated by the board", isCorrect: false, rationale: "Board designations are internal decisions; this restriction comes from the donor." },
        { label: "B", text: "Net assets with donor restrictions", isCorrect: true, rationale: "Correct — a perpetual (endowment) restriction imposed by the donor is reported with donor restrictions." },
        { label: "C", text: "A liability until the income is spent", isCorrect: false, rationale: "An unconditional gift is contribution revenue, not a liability." },
        { label: "D", text: "Deferred revenue", isCorrect: false, rationale: "Contributions are not deferred; the restriction affects the net asset class." },
      ],
      explanation: "Under ASU 2016-14, NFPs report two classes: net assets with donor restrictions and without donor restrictions. Donor-imposed perpetual restrictions, such as endowment principal, fall in the 'with donor restrictions' class, and the nature of the restriction is disclosed. Board-designated endowments remain without donor restrictions.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["endowments", "net asset classification"],
    },
    {
      question: "Under ASU 2016-14, which not-for-profit organizations must present an analysis of expenses by both nature and function?",
      options: [
        { label: "A", text: "Only voluntary health and welfare organizations", isCorrect: false, rationale: "Before ASU 2016-14 only VHWOs had this requirement; it now applies to all NFPs." },
        { label: "B", text: "All not-for-profit organizations", isCorrect: true, rationale: "Correct — all NFPs present this analysis in one location: the face of a statement, a separate statement, or the notes." },
        { label: "C", text: "Only NFPs with revenue above $1 million", isCorrect: false, rationale: "There is no revenue threshold." },
        { label: "D", text: "No NFP; only a functional classification is required", isCorrect: false, rationale: "The analysis of nature and function is required." },
      ],
      explanation: "ASU 2016-14 requires every not-for-profit to present expenses by both their nature (e.g., salaries, rent) and their function (program services, management and general, fundraising), in one location — the statement of activities, a separate statement, or the notes.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["NFP reporting", "functional expenses"],
    },
    {
      question: "A not-for-profit spends donor-restricted funds on the purpose the donor specified. How is this reported in the statement of activities?",
      options: [
        { label: "A", text: "As new contribution revenue without donor restrictions", isCorrect: false, rationale: "The contribution was already recognized when received." },
        { label: "B", text: "As a reclassification — net assets released from restrictions — increasing net assets without donor restrictions and decreasing net assets with donor restrictions", isCorrect: true, rationale: "Correct — the release is reported as a reclassification between the two classes." },
        { label: "C", text: "As an expense of net assets with donor restrictions", isCorrect: false, rationale: "All expenses are reported in net assets without donor restrictions." },
        { label: "D", text: "Only in the notes", isCorrect: false, rationale: "Releases appear on the face of the statement of activities." },
      ],
      explanation: "When a donor's restriction is satisfied, the amount is reclassified from net assets with donor restrictions to net assets without donor restrictions, shown as 'net assets released from restrictions'. The related expense is then reported in net assets without donor restrictions, where all expenses are reported.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["release from restrictions"],
    },
    {
      question: "A museum receives a donated painting that it adds to its collection. Under what condition may the museum choose not to recognize the contribution?",
      options: [
        { label: "A", text: "If the painting's fair value cannot be estimated precisely", isCorrect: false, rationale: "Measurement difficulty alone is not the collection criterion." },
        { label: "B", text: "If the painting is held for public exhibition, protected and preserved, and proceeds from any sale of collection items must be used for acquisitions or direct care of collections", isCorrect: true, rationale: "Correct — collection items meeting these conditions need not be capitalized." },
        { label: "C", text: "If the donor asks the museum not to record it", isCorrect: false, rationale: "Donor preferences do not determine recognition." },
        { label: "D", text: "Never — all donated assets must be recognized", isCorrect: false, rationale: "GAAP provides a specific exception for collection items." },
      ],
      explanation: "Contributed works of art and historical treasures need not be recognized if they are added to a collection held for public exhibition, education, or research; are protected, kept unencumbered, cared for, and preserved; and are subject to a policy requiring sale proceeds to be used for acquisitions or direct care of collections. Unrecognized collections must still be disclosed.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["collections", "contributions"],
    },
    {
      question: "A not-for-profit receives an unconditional pledge of $100,000 to be collected in two years. The present value of the pledge is $90,000. What contribution revenue is recognized when the pledge is received?",
      options: [
        { label: "A", text: "$100,000", isCorrect: false, rationale: "Pledges due in more than one year are measured at present value." },
        { label: "B", text: "$90,000, with donor restrictions", isCorrect: true, rationale: "Correct — measured at present value, with an implied time restriction." },
        { label: "C", text: "$90,000, without donor restrictions", isCorrect: false, rationale: "A multi-year pledge carries an implied time restriction." },
        { label: "D", text: "$0 until collected", isCorrect: false, rationale: "Unconditional pledges are recognized when received." },
      ],
      explanation: "Unconditional promises to give that are collectible in more than one year are measured at the present value of expected cash flows. The discount is later accreted as contribution revenue, not interest. Because payment is in a future period, the contribution is reported with donor restrictions.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["pledges", "present value"],
    },
  ],

  "governmental-accounting": [
    {
      question: "Government-wide financial statements are prepared using which measurement focus and basis of accounting?",
      options: [
        { label: "A", text: "Current financial resources, modified accrual", isCorrect: false, rationale: "That is the basis for governmental fund statements." },
        { label: "B", text: "Economic resources, accrual", isCorrect: true, rationale: "Correct — government-wide statements report all assets and liabilities, including capital assets and long-term debt." },
        { label: "C", text: "Economic resources, modified accrual", isCorrect: false, rationale: "This combination is not used." },
        { label: "D", text: "Cash basis", isCorrect: false, rationale: "GAAP-basis governmental statements are not prepared on the cash basis." },
      ],
      explanation: "Government-wide statements (the statement of net position and statement of activities) use the economic resources measurement focus and full accrual basis, like proprietary funds. Governmental funds use the current financial resources focus and modified accrual basis, which is why a reconciliation is required.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["government-wide statements"],
    },
    {
      question: "A city holds resources in trust to pay pension benefits to its employees. In which fund are these resources reported?",
      options: [
        { label: "A", text: "General Fund", isCorrect: false, rationale: "The General Fund is for resources not required to be accounted for elsewhere." },
        { label: "B", text: "Special revenue fund", isCorrect: false, rationale: "Special revenue funds account for restricted or committed revenue used for specific purposes of the government itself." },
        { label: "C", text: "Pension (and other employee benefit) trust fund", isCorrect: true, rationale: "Correct — pension trust funds are fiduciary funds." },
        { label: "D", text: "Internal service fund", isCorrect: false, rationale: "Internal service funds provide goods or services to other departments on a cost-reimbursement basis." },
      ],
      explanation: "Resources the government holds in trust for others, such as employee pension plan assets, are reported in fiduciary funds — here, a pension trust fund. Fiduciary funds are excluded from the government-wide statements because the resources cannot be used to support the government's own programs.",
      difficulty: "EASY",
      questionType: "APPLICATION",
      tags: ["fiduciary funds"],
    },
    {
      question: "Which governmental fund is used to account for resources accumulated to pay principal and interest on general long-term debt?",
      options: [
        { label: "A", text: "Capital projects fund", isCorrect: false, rationale: "Capital projects funds account for resources used to acquire or build capital facilities." },
        { label: "B", text: "Debt service fund", isCorrect: true, rationale: "Correct — debt service funds accumulate resources for general long-term debt principal and interest." },
        { label: "C", text: "Permanent fund", isCorrect: false, rationale: "Permanent funds hold resources where only earnings may be used for government programs." },
        { label: "D", text: "Enterprise fund", isCorrect: false, rationale: "Enterprise fund debt is paid and reported within the enterprise fund itself." },
      ],
      explanation: "Debt service funds account for financial resources restricted, committed, or assigned to pay principal and interest on general long-term debt. Under modified accrual, general long-term debt principal and interest are generally recognized as expenditures when due.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["governmental funds", "debt service"],
    },
    {
      question: "A city issues general obligation bonds at par to finance construction of a new library. How are the proceeds reported in the capital projects fund?",
      options: [
        { label: "A", text: "As revenue", isCorrect: false, rationale: "Bond proceeds are not revenue." },
        { label: "B", text: "As a long-term liability", isCorrect: false, rationale: "Governmental funds do not report long-term liabilities." },
        { label: "C", text: "As an other financing source", isCorrect: true, rationale: "Correct — bond proceeds are an other financing source in governmental funds." },
        { label: "D", text: "As a reduction of expenditures", isCorrect: false, rationale: "Proceeds are a separate financing source, not an offset to spending." },
      ],
      explanation: "Governmental funds focus on current financial resources, so they report bond proceeds as 'other financing sources' rather than recording a liability. The debt itself appears in the government-wide statement of net position.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["capital projects fund", "other financing sources"],
    },
  ],

  "sec-reporting-segments-and-interim-reporting": [
    {
      question: "A large accelerated filer must file each quarterly report on Form 10-Q within how many days after the end of the quarter?",
      options: [
        { label: "A", text: "30 days", isCorrect: false, rationale: "No filer category has a 30-day 10-Q deadline." },
        { label: "B", text: "40 days", isCorrect: true, rationale: "Correct — large accelerated and accelerated filers have 40 days." },
        { label: "C", text: "45 days", isCorrect: false, rationale: "45 days applies to non-accelerated filers." },
        { label: "D", text: "60 days", isCorrect: false, rationale: "60 days is the 10-K deadline for large accelerated filers." },
      ],
      explanation: "Form 10-Q is filed for the first three fiscal quarters (the fourth is covered by the 10-K). Large accelerated and accelerated filers must file within 40 days of quarter-end; non-accelerated filers within 45 days.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["Form 10-Q", "SEC deadlines"],
    },
    {
      question: "After identifying reportable segments using the 10% tests, a company must add more segments if the external revenue of its reportable segments is less than what percentage of total consolidated revenue?",
      options: [
        { label: "A", text: "50%", isCorrect: false, rationale: "The threshold is higher." },
        { label: "B", text: "75%", isCorrect: true, rationale: "Correct — reportable segments must account for at least 75% of consolidated external revenue." },
        { label: "C", text: "90%", isCorrect: false, rationale: "The threshold is 75%." },
        { label: "D", text: "10%", isCorrect: false, rationale: "10% is the threshold for identifying individual reportable segments." },
      ],
      explanation: "The 75% test ensures segment reporting covers most of the business. If reportable segments' total external revenue is below 75% of consolidated revenue, more operating segments are reported until the threshold is met, even if they don't pass the 10% tests.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["segment reporting", "75% test"],
    },
    {
      question: "The combined revenue of all operating segments, including intersegment sales, is $5,000,000. Considering only the revenue test, which segment is a reportable segment?",
      options: [
        { label: "A", text: "Segment with $300,000 of revenue", isCorrect: false, rationale: "$300,000 is only 6% of combined revenue." },
        { label: "B", text: "Segment with $450,000 of revenue", isCorrect: false, rationale: "$450,000 is 9%, below the 10% threshold." },
        { label: "C", text: "Segment with $499,000 of revenue", isCorrect: false, rationale: "Just under $500,000, so it fails the revenue test." },
        { label: "D", text: "Segment with $520,000 of revenue, of which $80,000 is intersegment", isCorrect: true, rationale: "Correct — the test uses total revenue including intersegment sales, and $520,000 is more than 10% of $5,000,000." },
      ],
      explanation: "An operating segment is reportable if its revenue (external plus intersegment) is 10% or more of the combined revenue of all operating segments. Here the threshold is $500,000. Including intersegment sales is the common trap: the $520,000 segment passes even though its external revenue is only $440,000.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["segment reporting", "10% test"],
    },
    {
      question: "At an interim date, the market value of inventory temporarily declines below cost, and the decline is reasonably expected to be recovered by year-end. How is this handled in the interim financial statements?",
      options: [
        { label: "A", text: "The loss is recognized in the interim period", isCorrect: false, rationale: "Temporary declines expected to recover within the year need not be recognized." },
        { label: "B", text: "The loss is not recognized in the interim period", isCorrect: true, rationale: "Correct — temporary declines expected to reverse by year-end are not recognized." },
        { label: "C", text: "The loss is deferred to the fourth quarter automatically", isCorrect: false, rationale: "It is not recognized at all if it reverses by year-end." },
        { label: "D", text: "The loss is recorded in other comprehensive income", isCorrect: false, rationale: "Inventory write-downs are not OCI items." },
      ],
      explanation: "Interim periods are viewed as integral parts of the annual period. Inventory losses from market declines are recognized in the interim period unless the decline is temporary and reasonably expected to be restored by year-end. Permanent declines are recognized when they occur.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["interim reporting", "inventory"],
    },
  ],
};
