import type { McqBank } from "./types";

/** ISC question bank — all 12 topics. */
export const iscBank: McqBank = {
  "it-general-controls": [
    {
      question: "Which of the following is a change management control?",
      options: [
        { label: "A", text: "Requiring a unique user ID and password to access the accounting system", isCorrect: false, rationale: "This is an access control, a different ITGC domain." },
        { label: "B", text: "Requiring that program changes be tested and approved before migration to production", isCorrect: true, rationale: "Correct — testing and approval before promotion to production is the core change management control." },
        { label: "C", text: "Scheduling nightly backup jobs", isCorrect: false, rationale: "Backup scheduling falls under computer operations." },
        { label: "D", text: "Installing antivirus software on workstations", isCorrect: false, rationale: "This is a security control, not change management." },
      ],
      explanation: "Change management controls ensure that only authorized, tested changes reach production. Key elements are documented requests, appropriate approvals, testing in a separate environment, segregation between the person developing and the person promoting the change, and the ability to roll back.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["ITGC", "change management"],
    },
    {
      question: "Why do weak IT general controls undermine reliance on automated application controls?",
      options: [
        { label: "A", text: "Application controls cannot operate without general controls being tested first", isCorrect: false, rationale: "Application controls can operate; the issue is whether their continued reliable operation can be relied upon." },
        { label: "B", text: "Without effective ITGCs, there is no assurance that the application control operated consistently and was not altered during the period", isCorrect: true, rationale: "Correct — ITGCs provide the assurance that a tested application control stayed unchanged and operated throughout the period." },
        { label: "C", text: "General controls replace the need for application controls entirely", isCorrect: false, rationale: "The two are complementary, not substitutes." },
        { label: "D", text: "Application controls apply only to manual processes", isCorrect: false, rationale: "Application controls are by definition automated." },
      ],
      explanation: "An automated control operates consistently — but only if the program and the data it relies on remain unaltered. IT general controls over access, program changes, and operations provide that assurance. Where ITGCs are deficient, an auditor who tested an application control once cannot conclude it operated the same way all year.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["ITGC", "application controls"],
    },
    {
      question: "A programmer has the ability to move their own code changes directly into the production environment. This represents a deficiency in:",
      options: [
        { label: "A", text: "Physical security controls", isCorrect: false, rationale: "Physical security addresses access to facilities and hardware." },
        { label: "B", text: "Segregation of duties within change management", isCorrect: true, rationale: "Correct — the person writing a change should not be the person promoting it to production." },
        { label: "C", text: "Data backup procedures", isCorrect: false, rationale: "Backup procedures are unrelated to this deficiency." },
        { label: "D", text: "Network perimeter defense", isCorrect: false, rationale: "The issue is internal authorization, not perimeter security." },
      ],
      explanation: "Allowing a developer to migrate their own changes to production removes the independent check that the change was authorized and tested, and creates the opportunity to introduce unauthorized code. Compensating controls — independent review of production change logs, for instance — may partially mitigate the risk where full segregation is impractical in a small IT function.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["ITGC", "segregation of duties"],
    },
    {
      question: "A user retains system access after transferring to a different department. This indicates a weakness in:",
      options: [
        { label: "A", text: "The user provisioning and periodic access review process", isCorrect: true, rationale: "Correct — access rights must be modified on role change and confirmed by periodic recertification." },
        { label: "B", text: "The password complexity policy", isCorrect: false, rationale: "Password strength is unrelated to whether access should exist at all." },
        { label: "C", text: "The data encryption standard", isCorrect: false, rationale: "Encryption protects data confidentiality, not authorization appropriateness." },
        { label: "D", text: "The disaster recovery plan", isCorrect: false, rationale: "Recovery planning addresses availability after disruption." },
      ],
      explanation: "Access accumulation — where employees gather permissions as they move roles without losing old ones — is a common and serious deficiency, because it erodes segregation of duties over time. Controls include timely provisioning and de-provisioning tied to HR events and periodic access recertification by business owners.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["ITGC", "access management"],
    },
  ],

  "information-systems-fundamentals": [
    {
      question: "In a relational database, a foreign key:",
      options: [
        { label: "A", text: "Uniquely identifies each row within its own table", isCorrect: false, rationale: "That is the function of a primary key." },
        { label: "B", text: "References the primary key of another table, enforcing referential integrity", isCorrect: true, rationale: "Correct — foreign keys create and enforce relationships between tables." },
        { label: "C", text: "Encrypts sensitive columns in the table", isCorrect: false, rationale: "Keys define structure and relationships, not encryption." },
        { label: "D", text: "Stores the database backup location", isCorrect: false, rationale: "This is unrelated to key structures." },
      ],
      explanation: "A primary key uniquely identifies each row in a table; a foreign key is a column referencing another table's primary key. Referential integrity prevents orphaned records — an order line cannot reference a customer that does not exist — which is a fundamental data integrity control.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["databases", "relational model"],
    },
    {
      question: "An ERP system's primary benefit to an organization is that it:",
      options: [
        { label: "A", text: "Eliminates the need for internal controls", isCorrect: false, rationale: "Integration changes the control environment but never eliminates the need for controls." },
        { label: "B", text: "Integrates business functions around a common database, reducing redundant data entry and reconciliation", isCorrect: true, rationale: "Correct — a single shared data source is the defining characteristic and main benefit of an ERP." },
        { label: "C", text: "Guarantees the accuracy of all recorded transactions", isCorrect: false, rationale: "An ERP faithfully processes whatever is entered, including errors." },
        { label: "D", text: "Removes the need for user access restrictions", isCorrect: false, rationale: "Integration makes access controls more critical, not less." },
      ],
      explanation: "An ERP integrates functions such as finance, procurement, manufacturing, and HR around a shared database, so a transaction entered once updates all affected modules. The corresponding risk is concentration: a single point of failure, and a control weakness in one module can affect the whole organization.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["systems", "ERP"],
    },
    {
      question: "Which processing method updates master files immediately as each transaction occurs?",
      options: [
        { label: "A", text: "Batch processing", isCorrect: false, rationale: "Batch processing accumulates transactions and processes them together on a schedule." },
        { label: "B", text: "Real-time (online) processing", isCorrect: true, rationale: "Correct — real-time processing updates the master file at the moment the transaction is entered." },
        { label: "C", text: "Sequential file processing", isCorrect: false, rationale: "This describes a file organization method, typically used with batch processing." },
        { label: "D", text: "Offline processing", isCorrect: false, rationale: "Offline processing implies no immediate connection to the master file." },
      ],
      explanation: "Real-time processing updates records immediately, giving current information but requiring continuous system availability and strong input controls, since there is no batch review before posting. Batch processing groups transactions for periodic processing, permitting batch totals and control counts but leaving data temporarily out of date.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["systems", "processing methods"],
    },
    {
      question: "In the cloud shared responsibility model for Infrastructure as a Service (IaaS), the customer is responsible for:",
      options: [
        { label: "A", text: "Physical security of the data center", isCorrect: false, rationale: "Physical infrastructure is always the provider's responsibility." },
        { label: "B", text: "The operating system, applications, and data, including their configuration and patching", isCorrect: true, rationale: "Correct — under IaaS the provider supplies infrastructure and the customer manages everything above it." },
        { label: "C", text: "Nothing, since the provider manages the entire stack", isCorrect: false, rationale: "That would describe a fully managed SaaS arrangement, and even there the customer retains data responsibilities." },
        { label: "D", text: "Hypervisor maintenance and virtualization software", isCorrect: false, rationale: "The virtualization layer is managed by the provider." },
      ],
      explanation: "Responsibility shifts with the service model. Under IaaS the provider secures physical facilities, hardware, and virtualization while the customer manages the OS, applications, and data. PaaS moves the OS and runtime to the provider; SaaS moves nearly everything, though the customer always retains responsibility for its data and access configuration.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["cloud", "shared responsibility"],
    },
  ],

  "data-management-and-governance": [
    {
      question: "Data governance is best described as:",
      options: [
        { label: "A", text: "The technical process of backing up databases", isCorrect: false, rationale: "Backup is one operational activity, not the governance framework." },
        { label: "B", text: "The framework of policies, roles, and accountability for managing data as an organizational asset", isCorrect: true, rationale: "Correct — governance establishes who decides what about data and under what rules." },
        { label: "C", text: "The encryption of all data in transit", isCorrect: false, rationale: "Encryption is a security control, not a governance framework." },
        { label: "D", text: "The purchase of data analytics software", isCorrect: false, rationale: "Tool selection is not governance." },
      ],
      explanation: "Data governance defines decision rights and accountability for data — establishing data owners and stewards, quality standards, definitions, retention and classification policies, and access rules. Without it, organizations accumulate inconsistent definitions and duplicate sources that undermine reporting reliability.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["data governance"],
    },
    {
      question: "Which dimension of data quality is violated when the same customer appears three times in a master file under slightly different names?",
      options: [
        { label: "A", text: "Timeliness", isCorrect: false, rationale: "Timeliness concerns whether data is current." },
        { label: "B", text: "Uniqueness, and consequently consistency", isCorrect: true, rationale: "Correct — duplicate records for one real-world entity violate uniqueness and create inconsistency across systems." },
        { label: "C", text: "Availability", isCorrect: false, rationale: "Availability concerns whether data is accessible when needed." },
        { label: "D", text: "Confidentiality", isCorrect: false, rationale: "Confidentiality concerns protection from unauthorized disclosure." },
      ],
      explanation: "Common data quality dimensions include accuracy, completeness, consistency, timeliness, validity, and uniqueness. Duplicate master records fragment transaction history, distort analytics such as customer profitability, and can defeat credit limit controls that assume one record per customer.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["data quality"],
    },
    {
      question: "A data retention policy primarily addresses the risk that:",
      options: [
        { label: "A", text: "Data will be encrypted with an outdated algorithm", isCorrect: false, rationale: "Cryptographic currency is a separate security concern." },
        { label: "B", text: "Data is kept longer than legally required or business-justified, or destroyed before obligations expire", isCorrect: true, rationale: "Correct — retention policy manages both over-retention and premature destruction." },
        { label: "C", text: "Users will forget their passwords", isCorrect: false, rationale: "This is an access management matter." },
        { label: "D", text: "The network will be breached from outside", isCorrect: false, rationale: "Perimeter security is a distinct control area." },
      ],
      explanation: "Retention policy cuts both ways: keeping data beyond its useful life increases breach exposure and storage cost and may violate privacy principles requiring deletion, while destroying data too early can breach legal, regulatory, or litigation hold obligations. A defensible schedule with documented, consistent disposal is the goal.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["data governance", "retention"],
    },
    {
      question: "A data dictionary in an organization's data management framework serves to:",
      options: [
        { label: "A", text: "Store the actual transaction records", isCorrect: false, rationale: "Transaction data resides in the database tables, not the dictionary." },
        { label: "B", text: "Document the meaning, format, source, and ownership of each data element", isCorrect: true, rationale: "Correct — the dictionary is metadata describing the data itself." },
        { label: "C", text: "Encrypt sensitive fields automatically", isCorrect: false, rationale: "Encryption is applied by security controls, not by documentation." },
        { label: "D", text: "Replace the need for database backups", isCorrect: false, rationale: "Documentation does not substitute for backup." },
      ],
      explanation: "A data dictionary is metadata: it records what each field means, its format and valid values, where it originates, and who owns it. It is essential for consistent reporting — when 'revenue' or 'active customer' means different things in different systems, reconciliation becomes impossible without an agreed definition.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["data governance", "metadata"],
    },
  ],

  "security-fundamentals": [
    {
      question: "The CIA triad in information security refers to:",
      options: [
        { label: "A", text: "Control, Inspection, and Authorization", isCorrect: false, rationale: "These are not the components of the triad." },
        { label: "B", text: "Confidentiality, Integrity, and Availability", isCorrect: true, rationale: "Correct — these three objectives define information security." },
        { label: "C", text: "Compliance, Investigation, and Assurance", isCorrect: false, rationale: "These are not the triad components." },
        { label: "D", text: "Cryptography, Identification, and Authentication", isCorrect: false, rationale: "These are mechanisms used to achieve the triad, not the triad itself." },
      ],
      explanation: "Confidentiality protects information from unauthorized disclosure, integrity ensures it is not improperly modified, and availability ensures authorized users can access it when needed. The three often trade off — locking data down tightly can impair availability — so security design balances them against business needs.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["security", "CIA triad"],
    },
    {
      question: "Multi-factor authentication requires the user to present:",
      options: [
        { label: "A", text: "Two different passwords", isCorrect: false, rationale: "Two passwords are both the same factor type — something you know." },
        { label: "B", text: "Credentials from two or more different categories: something you know, have, or are", isCorrect: true, rationale: "Correct — the factors must come from distinct categories to provide genuine additional assurance." },
        { label: "C", text: "A password entered twice for confirmation", isCorrect: false, rationale: "Re-entry confirms typing accuracy, not identity." },
        { label: "D", text: "Approval from two different managers", isCorrect: false, rationale: "This describes dual authorization of a transaction, not authentication." },
      ],
      explanation: "Authentication factors fall into three categories: knowledge (password, PIN), possession (token, phone), and inherence (fingerprint, facial recognition). Multi-factor authentication draws from two or more different categories, so compromising a password alone is insufficient — which is why MFA is among the most effective controls against credential theft.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["security", "authentication"],
    },
    {
      question: "The principle of least privilege requires that:",
      options: [
        { label: "A", text: "All users receive identical access rights for simplicity", isCorrect: false, rationale: "Uniform access grants most users far more than they need." },
        { label: "B", text: "Users are granted only the minimum access necessary to perform their job duties", isCorrect: true, rationale: "Correct — limiting access to what the role requires contains the damage from compromise or misuse." },
        { label: "C", text: "Only executives have access to sensitive systems", isCorrect: false, rationale: "Seniority does not determine business need for access." },
        { label: "D", text: "Access is granted permanently once approved", isCorrect: false, rationale: "Least privilege requires access to be removed when no longer needed." },
      ],
      explanation: "Least privilege limits each account to the minimum permissions its role requires, which contains the blast radius when an account is compromised or misused. It pairs with segregation of duties and with periodic access reviews to prevent the gradual accumulation of unnecessary rights.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["security", "least privilege"],
    },
    {
      question: "Asymmetric encryption differs from symmetric encryption in that asymmetric encryption:",
      options: [
        { label: "A", text: "Uses the same key to encrypt and decrypt", isCorrect: false, rationale: "That describes symmetric encryption." },
        { label: "B", text: "Uses a mathematically related public and private key pair, solving the problem of securely distributing keys", isCorrect: true, rationale: "Correct — the public key can be shared openly while the private key stays secret." },
        { label: "C", text: "Cannot be used over public networks", isCorrect: false, rationale: "Asymmetric encryption was designed precisely for use over untrusted networks." },
        { label: "D", text: "Is always faster than symmetric encryption", isCorrect: false, rationale: "Asymmetric encryption is considerably slower, which is why hybrid approaches are common." },
      ],
      explanation: "Symmetric encryption uses one shared key — fast, but requiring a secure channel to distribute the key. Asymmetric encryption uses a public key to encrypt and a corresponding private key to decrypt, removing the distribution problem. In practice systems combine both: asymmetric to exchange a symmetric session key, then symmetric for bulk data.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["security", "encryption"],
    },
    {
      question: "A phishing attack primarily exploits:",
      options: [
        { label: "A", text: "A flaw in the encryption algorithm", isCorrect: false, rationale: "Phishing bypasses technical controls rather than breaking them." },
        { label: "B", text: "Human behavior, by deceiving users into revealing credentials or taking harmful actions", isCorrect: true, rationale: "Correct — phishing is social engineering, targeting people rather than technology." },
        { label: "C", text: "An unpatched operating system vulnerability", isCorrect: false, rationale: "That describes exploitation of a technical vulnerability." },
        { label: "D", text: "Physical access to the data center", isCorrect: false, rationale: "Phishing is conducted remotely." },
      ],
      explanation: "Phishing is social engineering: attackers impersonate a trusted party to induce users to disclose credentials, transfer funds, or open malicious attachments. Because it targets people rather than systems, the countermeasures are largely awareness training, email filtering, verification procedures for payment changes, and multi-factor authentication limiting the value of stolen credentials.",
      difficulty: "EASY",
      questionType: "CONCEPTUAL",
      tags: ["security", "social engineering"],
    },
  ],

  "privacy-frameworks": [
    {
      question: "The privacy principle of data minimization requires an organization to:",
      options: [
        { label: "A", text: "Collect as much data as possible for future analysis", isCorrect: false, rationale: "This is the opposite of minimization." },
        { label: "B", text: "Collect only personal information that is necessary for the identified purpose", isCorrect: true, rationale: "Correct — minimization limits collection to what the stated purpose actually requires." },
        { label: "C", text: "Minimize the number of employees who work with data", isCorrect: false, rationale: "That relates to access control, not data minimization." },
        { label: "D", text: "Store all data in a single location", isCorrect: false, rationale: "Centralization is an architecture decision, not a privacy principle." },
      ],
      explanation: "Data minimization holds that organizations should collect only the personal information necessary for a specified purpose, retain it only as long as needed, and use it only for the purposes disclosed. It reduces both breach exposure and compliance burden — data never collected cannot be stolen.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["privacy", "data minimization"],
    },
    {
      question: "Personally identifiable information (PII) is best defined as:",
      options: [
        { label: "A", text: "Any data stored in a company database", isCorrect: false, rationale: "Most business data is not personal information." },
        { label: "B", text: "Information that can identify a specific individual, alone or when combined with other available data", isCorrect: true, rationale: "Correct — the definition includes indirect identification through combination with other data." },
        { label: "C", text: "Only Social Security and government identification numbers", isCorrect: false, rationale: "These are examples, but PII is far broader." },
        { label: "D", text: "Financial statements of a private individual", isCorrect: false, rationale: "This is one possible category, not the definition." },
      ],
      explanation: "PII includes direct identifiers such as name, government ID numbers, and email address, and also indirect identifiers that identify someone in combination — postal code, birth date, and gender together frequently identify an individual uniquely. This is why de-identification is harder than simply removing names.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["privacy", "PII"],
    },
    {
      question: "Under a consent-based privacy model, an organization that wishes to use personal data for a new purpose not disclosed at collection should:",
      options: [
        { label: "A", text: "Proceed, since the data is already in its possession", isCorrect: false, rationale: "Possession does not confer unlimited use rights." },
        { label: "B", text: "Obtain new consent or otherwise establish a valid basis for the new purpose", isCorrect: true, rationale: "Correct — purpose limitation requires a fresh basis for materially new uses." },
        { label: "C", text: "Anonymize the data and then use it without restriction, without assessing re-identification risk", isCorrect: false, rationale: "Genuine anonymization can permit use, but only where re-identification risk has actually been assessed and addressed." },
        { label: "D", text: "Notify regulators but not data subjects", isCorrect: false, rationale: "Notifying a regulator does not substitute for a lawful basis regarding the individuals." },
      ],
      explanation: "Purpose limitation confines the use of personal data to the purposes disclosed when it was collected. Materially new purposes require a new lawful basis — typically fresh consent. Effective anonymization can take data outside privacy rules entirely, but only where re-identification risk has been genuinely assessed rather than assumed away.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["privacy", "purpose limitation"],
    },
    {
      question: "The privacy category of the AICPA Trust Services Criteria differs from the confidentiality category in that privacy:",
      options: [
        { label: "A", text: "Applies to all business information regardless of type", isCorrect: false, rationale: "That broader scope describes confidentiality." },
        { label: "B", text: "Applies specifically to personal information and covers its collection, use, retention, disclosure, and disposal", isCorrect: true, rationale: "Correct — privacy is scoped to personal information across its full lifecycle." },
        { label: "C", text: "Addresses only system uptime", isCorrect: false, rationale: "Uptime is the availability criterion." },
        { label: "D", text: "Is identical to confidentiality in scope", isCorrect: false, rationale: "The two categories differ in the type of information they protect." },
      ],
      explanation: "The Trust Services Criteria comprise security, availability, processing integrity, confidentiality, and privacy. Confidentiality protects any information designated as confidential — trade secrets, contract terms — while privacy applies specifically to personal information and addresses notice, choice, collection, use, retention, disclosure, and disposal.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["privacy", "trust services criteria"],
    },
  ],

  "incident-response": [
    {
      question: "In the NIST incident response lifecycle, which phase includes limiting the damage of an active incident and removing the attacker's foothold?",
      options: [
        { label: "A", text: "Preparation", isCorrect: false, rationale: "Preparation occurs before an incident, building capability and plans." },
        { label: "B", text: "Detection and analysis", isCorrect: false, rationale: "This phase identifies and characterizes the incident." },
        { label: "C", text: "Containment, eradication, and recovery", isCorrect: true, rationale: "Correct — this phase limits the damage, removes the threat, and restores normal operations." },
        { label: "D", text: "Post-incident activity", isCorrect: false, rationale: "This phase captures lessons learned after resolution." },
      ],
      explanation: "The NIST lifecycle has four phases: preparation, detection and analysis, containment/eradication/recovery, and post-incident activity. Containment decisions involve real tradeoffs — isolating a system stops the spread but may destroy volatile forensic evidence needed to understand the attack.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["incident response", "NIST"],
    },
    {
      question: "Recovery point objective (RPO) specifies:",
      options: [
        { label: "A", text: "How quickly a system must be restored after a disruption", isCorrect: false, rationale: "That is the recovery time objective." },
        { label: "B", text: "The maximum acceptable amount of data loss, measured as a period of time", isCorrect: true, rationale: "Correct — RPO defines how far back the recovery point may be, and therefore drives backup frequency." },
        { label: "C", text: "The physical location of the backup facility", isCorrect: false, rationale: "Location is a separate planning decision." },
        { label: "D", text: "The number of staff required for recovery", isCorrect: false, rationale: "Staffing is not part of the RPO definition." },
      ],
      explanation: "RPO answers 'how much data can we afford to lose' and dictates backup frequency — a one-hour RPO requires backups or replication at least hourly. RTO answers 'how long can we be down' and dictates recovery infrastructure. A tight RTO justifies a hot site; a loose one may permit a cold site.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["business continuity", "RPO"],
    },
    {
      question: "A hot site differs from a cold site in that a hot site:",
      options: [
        { label: "A", text: "Is a physical location with power and space but no equipment", isCorrect: false, rationale: "That describes a cold site." },
        { label: "B", text: "Is fully equipped and configured with current data, enabling near-immediate resumption of operations", isCorrect: true, rationale: "Correct — a hot site supports the fastest recovery, at the highest cost." },
        { label: "C", text: "Is less expensive to maintain than a cold site", isCorrect: false, rationale: "Hot sites are considerably more expensive." },
        { label: "D", text: "Can only be used for non-critical systems", isCorrect: false, rationale: "Hot sites exist precisely to support the most critical systems." },
      ],
      explanation: "Recovery sites trade cost against speed. A cold site provides space and utilities only, taking days or weeks to bring online. A warm site has hardware and connectivity but not current data. A hot site is fully configured with replicated data and can take over almost immediately, at the highest ongoing cost.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["business continuity", "recovery sites"],
    },
    {
      question: "Why is post-incident review an essential phase of incident response rather than an optional one?",
      options: [
        { label: "A", text: "It is required to close the incident ticket in the system", isCorrect: false, rationale: "Administrative closure is not the substantive reason." },
        { label: "B", text: "It identifies control weaknesses that permitted the incident and drives improvements preventing recurrence", isCorrect: true, rationale: "Correct — without it, the organization remains exposed to the same attack path." },
        { label: "C", text: "It assigns individual blame for the incident", isCorrect: false, rationale: "Blame-focused reviews discourage reporting and reduce effectiveness." },
        { label: "D", text: "It eliminates the possibility of future incidents", isCorrect: false, rationale: "No process can eliminate incidents entirely." },
      ],
      explanation: "Post-incident review examines what happened, how detection and response performed, which controls failed, and what should change. Skipping it means the underlying weakness persists and the same attack path stays open. Effective reviews focus on systemic causes rather than individual fault, so people report problems early.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["incident response", "lessons learned"],
    },
  ],

  "business-process-automation": [
    {
      question: "Robotic process automation (RPA) is best suited to processes that are:",
      options: [
        { label: "A", text: "Highly judgmental and require professional interpretation", isCorrect: false, rationale: "Judgment-intensive work is poorly suited to rule-based automation." },
        { label: "B", text: "High-volume, rule-based, repetitive, and involve structured data", isCorrect: true, rationale: "Correct — RPA excels where the steps are deterministic and inputs are structured." },
        { label: "C", text: "Performed once per year with varying requirements", isCorrect: false, rationale: "Low-frequency, variable processes rarely justify automation investment." },
        { label: "D", text: "Dependent on unstructured verbal communication", isCorrect: false, rationale: "Traditional RPA cannot process unstructured verbal inputs." },
      ],
      explanation: "RPA uses software bots to perform structured, rule-based tasks across applications — reconciliations, data transfers between systems, invoice matching. It works at the user interface layer without changing underlying systems. Automating a poorly designed process, however, simply produces errors faster, so processes should be improved before automation.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["automation", "RPA"],
    },
    {
      question: "A significant control risk introduced by RPA is that:",
      options: [
        { label: "A", text: "Bots require more manual review than the process they replace", isCorrect: false, rationale: "Automation reduces manual handling; the risk lies elsewhere." },
        { label: "B", text: "Bot credentials may accumulate excessive privileges and operate outside normal user access governance", isCorrect: true, rationale: "Correct — bot identities are frequently over-privileged and excluded from standard access reviews." },
        { label: "C", text: "Bots cannot process transactions accurately", isCorrect: false, rationale: "Bots execute their programmed steps consistently." },
        { label: "D", text: "RPA eliminates the audit trail entirely", isCorrect: false, rationale: "Well-implemented RPA produces detailed logs." },
      ],
      explanation: "Bots need system credentials, and those non-human identities are often granted broad access to span multiple applications and then omitted from periodic access reviews. Additional risks include a bot faithfully propagating an error at scale, and inadequate change control over bot logic. Bot accounts should be governed like privileged user accounts.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["automation", "RPA risks"],
    },
    {
      question: "In a straight-through processing environment for accounts payable, the most important compensating control is:",
      options: [
        { label: "A", text: "Manual review of every transaction before payment", isCorrect: false, rationale: "Reviewing every item would defeat the purpose of straight-through processing." },
        { label: "B", text: "Strong preventive configuration controls plus exception reporting and monitoring of overrides", isCorrect: true, rationale: "Correct — automated environments rely on configuration integrity and rigorous exception handling." },
        { label: "C", text: "Increasing the number of approval levels for all payments", isCorrect: false, rationale: "Adding approvals to all items removes the efficiency benefit without targeting risk." },
        { label: "D", text: "Eliminating vendor master file changes entirely", isCorrect: false, rationale: "Vendor data must be maintained; the control is over how changes are authorized." },
      ],
      explanation: "Where transactions flow through without human intervention, assurance shifts to the design and configuration of the automated controls — three-way match tolerances, duplicate invoice detection, vendor master change authorization — supported by monitoring of exceptions and manual overrides. Those overrides are where fraud typically appears.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["automation", "straight-through processing"],
    },
  ],

  "systems-development-life-cycle": [
    {
      question: "Which system implementation approach carries the highest risk?",
      options: [
        { label: "A", text: "Parallel conversion, running old and new systems simultaneously", isCorrect: false, rationale: "Parallel running is the safest approach, though the most costly." },
        { label: "B", text: "Direct cutover, switching entirely to the new system at once", isCorrect: true, rationale: "Correct — direct cutover leaves no fallback if the new system fails." },
        { label: "C", text: "Pilot conversion in one location first", isCorrect: false, rationale: "Piloting limits exposure to a single site." },
        { label: "D", text: "Phased conversion by module", isCorrect: false, rationale: "Phasing spreads risk across smaller increments." },
      ],
      explanation: "Direct cutover, sometimes called big bang, is fastest and cheapest but offers no fallback if the new system fails. Parallel conversion is safest since the old system continues as a check, but it doubles processing effort. Pilot and phased approaches sit between, containing failures to one location or module.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SDLC", "implementation"],
    },
    {
      question: "User acceptance testing is performed primarily to confirm that:",
      options: [
        { label: "A", text: "The code contains no syntax errors", isCorrect: false, rationale: "Syntax errors are caught in development and unit testing." },
        { label: "B", text: "The system meets business requirements and works as users need it to in practice", isCorrect: true, rationale: "Correct — UAT validates fitness for business purpose from the user's perspective." },
        { label: "C", text: "The hardware capacity is sufficient", isCorrect: false, rationale: "That is verified by performance and load testing." },
        { label: "D", text: "The vendor contract terms have been met", isCorrect: false, rationale: "Contract compliance is a procurement matter, though UAT may inform it." },
      ],
      explanation: "UAT is conducted by business users rather than IT, confirming the system satisfies the documented requirements and supports real workflows. It is the last gate before production and, critically, should be performed in a test environment with representative data — never against live production data.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SDLC", "testing"],
    },
    {
      question: "Maintaining separate development, test, and production environments is important because it:",
      options: [
        { label: "A", text: "Reduces the cost of hardware", isCorrect: false, rationale: "Multiple environments increase infrastructure cost." },
        { label: "B", text: "Prevents untested changes and development activity from affecting live data and operations", isCorrect: true, rationale: "Correct — environment separation protects production integrity and supports segregation of duties." },
        { label: "C", text: "Eliminates the need for change approvals", isCorrect: false, rationale: "Approvals remain essential." },
        { label: "D", text: "Allows developers unrestricted access to production", isCorrect: false, rationale: "Separation exists precisely to restrict such access." },
      ],
      explanation: "Separate environments ensure that development and testing cannot corrupt live data or disrupt operations, and they enforce segregation of duties by making promotion between environments a controlled, approved step. Where production data is copied to test, sensitive fields should be masked to protect confidentiality.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SDLC", "environments"],
    },
  ],

  "third-party-and-vendor-risk": [
    {
      question: "When an organization outsources a significant process to a service provider, responsibility for the effectiveness of related internal controls:",
      options: [
        { label: "A", text: "Transfers entirely to the service provider", isCorrect: false, rationale: "Outsourcing the activity does not outsource accountability." },
        { label: "B", text: "Remains with the user entity's management, which must monitor the outsourced controls", isCorrect: true, rationale: "Correct — management retains accountability for controls over its own financial reporting." },
        { label: "C", text: "Transfers to the external auditor", isCorrect: false, rationale: "Auditors provide assurance; they never assume control responsibility." },
        { label: "D", text: "Is eliminated for the outsourced process", isCorrect: false, rationale: "The control objectives still apply to the user entity." },
      ],
      explanation: "An organization may outsource an activity but never its accountability. Management remains responsible for internal control over its financial reporting, and must monitor the provider — typically through SOC reports, contractual right-to-audit clauses, service level monitoring, and implementing any complementary user entity controls the provider assumes are in place.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["vendor risk", "outsourcing"],
    },
    {
      question: "Complementary user entity controls described in a SOC report are:",
      options: [
        { label: "A", text: "Controls the service organization performs on behalf of all its customers", isCorrect: false, rationale: "Those are the service organization's own controls." },
        { label: "B", text: "Controls the user entity must implement for the service organization's controls to achieve their objectives", isCorrect: true, rationale: "Correct — the service organization assumes these are in place at the customer." },
        { label: "C", text: "Optional enhancements the user entity may choose to adopt", isCorrect: false, rationale: "They are assumed to be operating, not optional." },
        { label: "D", text: "Controls performed by the service auditor during the engagement", isCorrect: false, rationale: "The service auditor tests controls but does not perform them operationally." },
      ],
      explanation: "A service organization's controls are frequently designed on the assumption that customers perform certain controls themselves — reviewing output reports, authorizing user access, or verifying data submitted. If the user entity does not actually perform these complementary controls, the overall control objectives are not met despite a clean SOC report.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["vendor risk", "CUECs"],
    },
    {
      question: "In a SOC report, the carve-out method for a subservice organization means that the subservice organization's controls are:",
      options: [
        { label: "A", text: "Included within the scope of the description and tested by the service auditor", isCorrect: false, rationale: "That describes the inclusive method." },
        { label: "B", text: "Excluded from the description and testing, with the user entity needing separate assurance over them", isCorrect: true, rationale: "Correct — carved-out controls create a gap the user entity must address separately." },
        { label: "C", text: "Replaced by the service organization's own controls", isCorrect: false, rationale: "The subservice organization continues to perform its own controls." },
        { label: "D", text: "Tested by the user auditor during the financial statement audit", isCorrect: false, rationale: "The user auditor typically cannot access the subservice organization directly." },
      ],
      explanation: "When a service organization uses a subservice organization — a cloud hosting provider, for example — it may carve out those controls, excluding them from its description and the auditor's testing, or use the inclusive method covering them. Under the carve-out method the user entity must obtain separate assurance, usually a SOC report from the subservice organization itself.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["vendor risk", "subservice organizations"],
    },
  ],

  "soc-engagements": [
    {
      question: "A SOC 2 report is generally:",
      options: [
        { label: "A", text: "Distributed freely to the general public without restriction", isCorrect: false, rationale: "General distribution is the feature of a SOC 3 report." },
        { label: "B", text: "Restricted in use to management, user entities, and other specified knowledgeable parties", isCorrect: true, rationale: "Correct — SOC 2 reports contain detailed control and testing information and are restricted-use." },
        { label: "C", text: "Filed with the SEC as part of periodic reporting", isCorrect: false, rationale: "SOC reports are not SEC filings." },
        { label: "D", text: "Provided only to the service organization's external auditor", isCorrect: false, rationale: "The report is provided to user entities and other specified parties." },
      ],
      explanation: "SOC 2 reports include detailed descriptions of the system, the controls, the auditor's tests, and the results, making them restricted-use documents for knowledgeable parties who can interpret them. SOC 3 covers the same trust services criteria but omits the detail, so it may be distributed generally, often as a marketing document.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SOC engagements", "SOC 2"],
    },
    {
      question: "Which trust services category must be included in every SOC 2 engagement?",
      options: [
        { label: "A", text: "Privacy", isCorrect: false, rationale: "Privacy is optional and included only when relevant to the engagement scope." },
        { label: "B", text: "Security, referred to as the common criteria", isCorrect: true, rationale: "Correct — security is the mandatory baseline category in every SOC 2." },
        { label: "C", text: "Availability", isCorrect: false, rationale: "Availability is optional." },
        { label: "D", text: "Processing integrity", isCorrect: false, rationale: "Processing integrity is optional." },
      ],
      explanation: "Security — the common criteria — is required in every SOC 2 engagement. Availability, processing integrity, confidentiality, and privacy are optional and selected based on the commitments the service organization makes to its customers. A cloud infrastructure provider might add availability; a payroll processor might add confidentiality and privacy.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["SOC engagements", "trust services criteria"],
    },
    {
      question: "A service organization's management is responsible for which element of a SOC engagement?",
      options: [
        { label: "A", text: "Testing the operating effectiveness of the controls", isCorrect: false, rationale: "Testing is the service auditor's responsibility." },
        { label: "B", text: "Preparing the description of the system and providing a written assertion about it", isCorrect: true, rationale: "Correct — management prepares the description and asserts to its fairness and the suitability of control design." },
        { label: "C", text: "Issuing the opinion on the controls", isCorrect: false, rationale: "The opinion is the service auditor's." },
        { label: "D", text: "Selecting which user entities may rely on the report", isCorrect: false, rationale: "Distribution is governed by the report's use restrictions, not a management selection process." },
      ],
      explanation: "In a SOC engagement, management prepares the description of the service organization's system and provides a written assertion that the description is fairly presented, the controls are suitably designed, and — for a Type 2 report — that they operated effectively. The service auditor independently tests and reports an opinion on those assertions.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["SOC engagements", "responsibilities"],
    },
  ],

  "it-audit-and-advisory": [
    {
      question: "Generalized audit software allows an auditor to:",
      options: [
        { label: "A", text: "Modify the client's production programs to add audit routines", isCorrect: false, rationale: "Auditors do not alter client production systems." },
        { label: "B", text: "Independently extract, sort, summarize, and analyze client data files", isCorrect: true, rationale: "Correct — GAS lets the auditor interrogate client data directly and independently." },
        { label: "C", text: "Replace the need for an understanding of internal control", isCorrect: false, rationale: "Understanding internal control remains a required risk assessment procedure." },
        { label: "D", text: "Guarantee detection of all fraud", isCorrect: false, rationale: "No tool provides such a guarantee." },
      ],
      explanation: "Generalized audit software enables the auditor to read client files directly and perform tasks such as recalculating balances, identifying duplicates and gaps in sequences, aging receivables, stratifying populations, and selecting samples. Its power depends entirely on obtaining complete and accurate data, which the auditor must verify.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["IT audit", "CAATs"],
    },
    {
      question: "An integrated test facility (ITF) involves:",
      options: [
        { label: "A", text: "Processing auditor test data through a dummy entity within the live production system", isCorrect: true, rationale: "Correct — an ITF establishes a fictitious entity so test transactions process alongside real ones." },
        { label: "B", text: "Running a separate copy of the client's system offline", isCorrect: false, rationale: "That describes a test environment rather than an ITF." },
        { label: "C", text: "Reviewing printed output reports manually", isCorrect: false, rationale: "This is a manual procedure, not an ITF." },
        { label: "D", text: "Interviewing IT personnel about system functionality", isCorrect: false, rationale: "Inquiry is not an ITF technique." },
      ],
      explanation: "An integrated test facility creates a fictitious entity — a dummy department or customer — within the live system, so auditor test transactions process under genuine production conditions. The critical requirement is careful reversal of the test entries so client financial data is not distorted.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["IT audit", "ITF"],
    },
    {
      question: "When evaluating IT risks, the auditor should recognize that automated controls:",
      options: [
        { label: "A", text: "Are inherently less reliable than manual controls", isCorrect: false, rationale: "Automated controls are generally more consistent than manual ones." },
        { label: "B", text: "Operate consistently but will systematically repeat any error in their programmed logic", isCorrect: true, rationale: "Correct — consistency is a strength for correct logic and a serious risk for flawed logic." },
        { label: "C", text: "Do not require testing if the vendor is reputable", isCorrect: false, rationale: "Vendor reputation is not a substitute for testing." },
        { label: "D", text: "Cannot be overridden by management", isCorrect: false, rationale: "Management with sufficient access can override or reconfigure automated controls." },
      ],
      explanation: "Automation removes human inconsistency, so a correctly configured control operates the same way every time — which also means a logic error propagates uniformly to every transaction rather than appearing sporadically. This consistency is why testing a small sample can support a conclusion, provided IT general controls confirm the program did not change.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["IT audit", "automated controls"],
    },
  ],

  "emerging-technology-considerations": [
    {
      question: "A blockchain's immutability means that recorded transactions:",
      options: [
        { label: "A", text: "Are guaranteed to be accurate and economically valid", isCorrect: false, rationale: "Immutability protects the record from alteration; it says nothing about whether the entry was correct." },
        { label: "B", text: "Cannot practically be altered once confirmed, though an erroneous entry requires a correcting transaction", isCorrect: true, rationale: "Correct — the record resists alteration, so errors are fixed by new offsetting entries rather than edits." },
        { label: "C", text: "Can be edited by the network administrator when errors are found", isCorrect: false, rationale: "No single administrator can rewrite a properly functioning distributed ledger." },
        { label: "D", text: "Are automatically audited by the network", isCorrect: false, rationale: "Consensus validates protocol rules, not business substance." },
      ],
      explanation: "Blockchain provides a tamper-resistant record, but immutability is not accuracy. A transaction recorded incorrectly, or one recording a fictitious underlying event, remains permanently on the chain and must be corrected by a subsequent offsetting transaction. Auditors must still verify that on-chain records correspond to real-world events and that the entity controls the relevant private keys.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["emerging technology", "blockchain"],
    },
    {
      question: "A significant risk when an organization deploys artificial intelligence in financial processes is that:",
      options: [
        { label: "A", text: "AI models never require ongoing monitoring once validated", isCorrect: false, rationale: "Models degrade as conditions change and require continuous monitoring." },
        { label: "B", text: "Model logic may be difficult to explain, and bias in training data can produce systematically skewed outputs", isCorrect: true, rationale: "Correct — explainability and training data bias are the central governance concerns." },
        { label: "C", text: "AI eliminates the need for management review of outputs", isCorrect: false, rationale: "Human oversight becomes more important, not less." },
        { label: "D", text: "AI systems cannot process structured financial data", isCorrect: false, rationale: "Structured data is precisely what such systems handle well." },
      ],
      explanation: "AI introduces explainability challenges — a model may produce a recommendation without a traceable rationale, complicating audit evidence — and bias risk, where unrepresentative training data yields systematically skewed results. Model drift as conditions change means validation must be ongoing, and human review of consequential outputs remains essential.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["emerging technology", "artificial intelligence"],
    },
    {
      question: "When an organization migrates financial systems to a public cloud, a key control consideration is:",
      options: [
        { label: "A", text: "Cloud providers assume full responsibility for the customer's data security", isCorrect: false, rationale: "Responsibility is shared, and the customer always retains obligations over its data and access." },
        { label: "B", text: "Access configuration, data location, and the provider's own control environment must be evaluated and monitored", isCorrect: true, rationale: "Correct — misconfiguration by the customer is among the most common causes of cloud data exposure." },
        { label: "C", text: "Migrating to the cloud removes the need for a disaster recovery plan", isCorrect: false, rationale: "Cloud resilience must still be configured, tested, and understood." },
        { label: "D", text: "Cloud environments cannot be audited", isCorrect: false, rationale: "SOC reports and configuration reviews make cloud environments auditable." },
      ],
      explanation: "Cloud adoption shifts rather than removes control responsibilities. Customers must configure access correctly — publicly exposed storage caused by misconfiguration is a leading breach cause — understand where data physically resides for regulatory purposes, evaluate the provider's controls via SOC reports, and plan for portability and continuity if the relationship ends.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["emerging technology", "cloud"],
    },
  ],
};
