import type { McqBank } from "./types";

/** REG question bank — topics 10 through 18. See reg-a.ts for the note on indexed amounts. */
export const regBankB: McqBank = {
  "individual-taxation-adjustments-and-deductions": [
    {
      question: "Which expense is deductible as an adjustment to arrive at adjusted gross income rather than as an itemized deduction?",
      options: [
        { label: "A", text: "Mortgage interest on a personal residence", isCorrect: false, rationale: "Qualified residence interest is an itemized deduction." },
        { label: "B", text: "One half of self-employment tax", isCorrect: true, rationale: "Correct — the employer-equivalent portion of self-employment tax is an above-the-line deduction." },
        { label: "C", text: "Charitable contributions to a public charity", isCorrect: false, rationale: "Charitable contributions are itemized deductions." },
        { label: "D", text: "Unreimbursed medical expenses", isCorrect: false, rationale: "Medical expenses are itemized, subject to an AGI floor." },
      ],
      explanation: "Above-the-line deductions reduce AGI and are available whether or not the taxpayer itemizes. Common examples include one half of self-employment tax, deductible IRA and self-employed retirement plan contributions, self-employed health insurance, health savings account contributions, and student loan interest. Reducing AGI is valuable because many other provisions are keyed to it.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["deductions", "adjustments to income"],
    },
    {
      question: "Unreimbursed medical expenses are deductible as an itemized deduction only to the extent they exceed what percentage of adjusted gross income?",
      options: [
        { label: "A", text: "2%", isCorrect: false, rationale: "The 2% floor applied to miscellaneous itemized deductions, which are currently suspended." },
        { label: "B", text: "7.5%", isCorrect: true, rationale: "Correct — medical expenses are deductible only above a 7.5% of AGI floor." },
        { label: "C", text: "10%", isCorrect: false, rationale: "The floor was 10% for some earlier years but is currently 7.5%." },
        { label: "D", text: "There is no floor", isCorrect: false, rationale: "A floor applies, which is why most taxpayers deduct nothing for medical costs." },
      ],
      explanation: "Only unreimbursed medical expenses exceeding 7.5% of AGI are deductible, and only for taxpayers who itemize. Qualifying costs include payments for diagnosis, treatment, prescription medication, and qualifying long-term care, but not cosmetic surgery or general health items such as vitamins.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["deductions", "medical expenses"],
    },
    {
      question: "Investment interest expense is deductible by an individual only to the extent of:",
      options: [
        { label: "A", text: "Total investment income including tax-exempt interest", isCorrect: false, rationale: "Tax-exempt income does not support an interest deduction." },
        { label: "B", text: "Net investment income, with the excess carried forward indefinitely", isCorrect: true, rationale: "Correct — the deduction is limited to net investment income, and any disallowed amount carries forward." },
        { label: "C", text: "50% of adjusted gross income", isCorrect: false, rationale: "No AGI percentage limitation governs investment interest." },
        { label: "D", text: "The full amount paid, without limitation", isCorrect: false, rationale: "A limitation applies." },
      ],
      explanation: "Investment interest expense is deductible only up to net investment income, defined as investment income less related expenses. Excess interest carries forward indefinitely. Net capital gains and qualified dividends are excluded from investment income unless the taxpayer elects to forgo preferential rates on them.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["deductions", "investment interest"],
    },
    {
      question: "A taxpayer's business meal expenses incurred while entertaining a client at a restaurant are generally:",
      options: [
        { label: "A", text: "Fully deductible", isCorrect: false, rationale: "Full deductibility applied only during specific temporary relief periods." },
        { label: "B", text: "Deductible at 50% of the amount incurred, if not lavish and the taxpayer is present", isCorrect: true, rationale: "Correct — business meals are subject to the 50% limitation when the ordinary requirements are met." },
        { label: "C", text: "Not deductible at all", isCorrect: false, rationale: "Entertainment is nondeductible, but qualifying business meals remain 50% deductible." },
        { label: "D", text: "Deductible at 25%", isCorrect: false, rationale: "The statutory limitation is 50%, not 25%." },
      ],
      explanation: "Business meals are 50% deductible when the expense is ordinary and necessary, not lavish or extravagant, and the taxpayer or an employee is present with a business contact. Entertainment expenses — sporting events, theater tickets, club dues — are entirely nondeductible following the Tax Cuts and Jobs Act, so meals must be separately stated.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["deductions", "meals and entertainment"],
    },
  ],

  "filing-status-credits-and-amt": [
    {
      question: "To qualify for head of household filing status, a taxpayer must generally:",
      options: [
        { label: "A", text: "Be married and file separately from a spouse", isCorrect: false, rationale: "Head of household requires the taxpayer to be unmarried or considered unmarried." },
        { label: "B", text: "Be unmarried and pay more than half the cost of maintaining a home for a qualifying person for more than half the year", isCorrect: true, rationale: "Correct — these are the core requirements for head of household status." },
        { label: "C", text: "Have a dependent child under age 6", isCorrect: false, rationale: "No such age requirement applies to the qualifying person generally." },
        { label: "D", text: "Have been widowed within the past two years", isCorrect: false, rationale: "That describes qualifying surviving spouse status." },
      ],
      explanation: "Head of household requires the taxpayer to be unmarried or considered unmarried at year-end, to pay more than half the cost of keeping up a home, and for a qualifying person to live there more than half the year. A dependent parent is an exception — the parent need not live with the taxpayer, provided the taxpayer pays more than half the cost of the parent's home.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["filing status", "head of household"],
    },
    {
      question: "The primary difference between a refundable and a nonrefundable tax credit is that a refundable credit:",
      options: [
        { label: "A", text: "May be carried forward to future years", isCorrect: false, rationale: "Carryforward is a feature of certain nonrefundable credits, not the definition of refundability." },
        { label: "B", text: "Can reduce tax liability below zero, generating a refund", isCorrect: true, rationale: "Correct — a refundable credit can produce a payment to the taxpayer beyond taxes owed." },
        { label: "C", text: "Reduces adjusted gross income rather than tax", isCorrect: false, rationale: "Credits reduce tax directly; deductions reduce income." },
        { label: "D", text: "Is available only to taxpayers who itemize", isCorrect: false, rationale: "Credits are not tied to itemizing." },
      ],
      explanation: "A nonrefundable credit can reduce tax liability only to zero, with any excess wasted or, for some credits, carried forward. A refundable credit — such as the earned income credit — can generate a payment to the taxpayer exceeding the tax owed. Credits are more valuable than deductions of the same amount because they reduce tax dollar for dollar.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["credits", "refundable"],
    },
    {
      question: "In computing alternative minimum taxable income, which item is an adjustment or preference that increases AMTI?",
      options: [
        { label: "A", text: "Charitable contributions to public charities", isCorrect: false, rationale: "Charitable contributions are allowed for AMT purposes." },
        { label: "B", text: "The bargain element on exercise of an incentive stock option", isCorrect: true, rationale: "Correct — the spread on ISO exercise is not income for regular tax but is an AMT adjustment in the year of exercise." },
        { label: "C", text: "Qualified residence interest on acquisition debt", isCorrect: false, rationale: "Interest on debt used to acquire or improve a residence is generally allowed for AMT." },
        { label: "D", text: "Wages from employment", isCorrect: false, rationale: "Wages are already in regular taxable income and are not an adjustment." },
      ],
      explanation: "The AMT recomputes taxable income by adding back certain benefits. Common adjustments and preferences include the ISO bargain element, private activity bond interest, and depreciation differences. This is why exercising incentive stock options and holding the shares can trigger AMT even though no cash was received.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["AMT", "adjustments and preferences"],
    },
    {
      question: "A qualifying surviving spouse may use the married filing jointly tax rates for how long after the year of the spouse's death?",
      options: [
        { label: "A", text: "One year", isCorrect: false, rationale: "The status extends beyond a single year." },
        { label: "B", text: "Two years following the year of death, if a dependent child is maintained in the home", isCorrect: true, rationale: "Correct — the status is available for the two taxable years after the year of death, subject to the dependent child requirement." },
        { label: "C", text: "Five years", isCorrect: false, rationale: "The period is limited to two years." },
        { label: "D", text: "Indefinitely, until remarriage", isCorrect: false, rationale: "The status expires after two years regardless of remarriage." },
      ],
      explanation: "In the year of death, a surviving spouse generally files a joint return. For the two following years, qualifying surviving spouse status permits use of joint return rates provided the taxpayer has not remarried and maintains a household that is the principal home of a dependent child. After that, head of household may be available.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["filing status", "qualifying surviving spouse"],
    },
  ],

  "retirement-plans-and-tax-planning-basics": [
    {
      question: "The key tax difference between a traditional IRA and a Roth IRA is that:",
      options: [
        { label: "A", text: "Traditional IRA contributions may be deductible and qualified distributions are taxable; Roth contributions are never deductible and qualified distributions are tax-free", isCorrect: true, rationale: "Correct — the two accounts differ in when the tax benefit is realized." },
        { label: "B", text: "Both are funded with after-tax dollars and both are taxed on distribution", isCorrect: false, rationale: "This would produce double taxation and describes neither account." },
        { label: "C", text: "Roth contributions are deductible and distributions are taxable", isCorrect: false, rationale: "This reverses the Roth treatment." },
        { label: "D", text: "Neither account permits investment earnings to grow tax-deferred", isCorrect: false, rationale: "Both provide tax-advantaged growth." },
      ],
      explanation: "A traditional IRA may give a current deduction, with earnings tax-deferred and qualified distributions taxed as ordinary income. A Roth IRA gives no deduction, but qualified distributions — generally after age 59½ and a five-year holding period — are entirely tax-free, including earnings.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["retirement", "IRA"],
    },
    {
      question: "A distribution from a traditional IRA before age 59½ is generally subject to:",
      options: [
        { label: "A", text: "No additional tax, only ordinary income tax", isCorrect: false, rationale: "An additional penalty tax applies absent an exception." },
        { label: "B", text: "A 10% additional tax, in addition to ordinary income tax, unless an exception applies", isCorrect: true, rationale: "Correct — the 10% early distribution penalty applies unless a statutory exception is met." },
        { label: "C", text: "A 50% additional tax", isCorrect: false, rationale: "The higher penalty relates to failing to take required minimum distributions." },
        { label: "D", text: "Capital gains tax rates", isCorrect: false, rationale: "IRA distributions are taxed as ordinary income, not at capital gains rates." },
      ],
      explanation: "Early distributions from a traditional IRA are subject to a 10% additional tax on top of ordinary income tax. Statutory exceptions include death, total and permanent disability, qualified higher education expenses, first-time home purchase up to a statutory limit, certain medical expenses, and a series of substantially equal periodic payments.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["retirement", "early distributions"],
    },
    {
      question: "Which retirement plan characteristic describes a defined benefit plan?",
      options: [
        { label: "A", text: "The employee bears the investment risk and the account balance determines the benefit", isCorrect: false, rationale: "This describes a defined contribution plan." },
        { label: "B", text: "The employer promises a specified benefit at retirement and bears the investment risk", isCorrect: true, rationale: "Correct — the benefit is defined by formula and the employer must fund it." },
        { label: "C", text: "Contributions are always made solely by the employee", isCorrect: false, rationale: "Defined benefit plans are employer-funded." },
        { label: "D", text: "Benefits depend entirely on the performance of employee-selected investments", isCorrect: false, rationale: "This describes a defined contribution arrangement such as a 401(k)." },
      ],
      explanation: "A defined benefit plan promises a specific retirement benefit, typically based on salary and years of service, with the employer bearing the funding and investment risk. A defined contribution plan such as a 401(k) defines only the contribution, leaving the eventual benefit dependent on investment performance and the employee bearing that risk.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["retirement", "plan types"],
    },
  ],

  "c-corporation-taxation": [
    {
      question: "A domestic corporation owns 30% of another domestic corporation and receives $100,000 in dividends. What is the dividends received deduction?",
      options: [
        { label: "A", text: "$50,000", isCorrect: false, rationale: "The 50% tier applies to ownership below 20%." },
        { label: "B", text: "$65,000", isCorrect: true, rationale: "Correct — ownership of at least 20% but less than 80% qualifies for the 65% deduction." },
        { label: "C", text: "$100,000", isCorrect: false, rationale: "The 100% deduction requires ownership of 80% or more." },
        { label: "D", text: "$0", isCorrect: false, rationale: "A dividends received deduction is available at every ownership tier for qualifying domestic dividends." },
      ],
      explanation: "The dividends received deduction has three tiers based on ownership: less than 20% gives a 50% deduction, at least 20% but less than 80% gives 65%, and 80% or more gives 100%. At 30% ownership, the deduction is 65% of $100,000, or $65,000. The DRD relieves multiple layers of corporate tax on the same earnings.",
      difficulty: "MEDIUM",
      questionType: "CALCULATION",
      tags: ["C corporation", "dividends received deduction"],
    },
    {
      question: "A C corporation's charitable contribution deduction is limited to what percentage of taxable income?",
      options: [
        { label: "A", text: "5%", isCorrect: false, rationale: "The corporate limit is higher than 5%." },
        { label: "B", text: "10%, computed before the charitable deduction, the DRD, and certain other items", isCorrect: true, rationale: "Correct — the 10% corporate limit is computed on a modified taxable income figure." },
        { label: "C", text: "50%", isCorrect: false, rationale: "Percentage limits at that level apply to individuals, not corporations." },
        { label: "D", text: "There is no limit for corporations", isCorrect: false, rationale: "A limit applies, with a five-year carryforward for the excess." },
      ],
      explanation: "A corporation may deduct charitable contributions up to 10% of taxable income computed without regard to the charitable deduction itself, the dividends received deduction, any capital loss carryback, and certain other items. Contributions exceeding the limit carry forward five years.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["C corporation", "charitable contributions"],
    },
    {
      question: "How may a C corporation use a net capital loss?",
      options: [
        { label: "A", text: "Deduct up to $3,000 against ordinary income each year", isCorrect: false, rationale: "The $3,000 allowance is available to individuals, not corporations." },
        { label: "B", text: "Only against capital gains, carrying back three years and forward five years", isCorrect: true, rationale: "Correct — corporate capital losses offset capital gains exclusively, with a 3-back, 5-forward carry period." },
        { label: "C", text: "Against ordinary income without limitation", isCorrect: false, rationale: "Corporations cannot offset ordinary income with capital losses at all." },
        { label: "D", text: "Carry forward indefinitely against any income", isCorrect: false, rationale: "The carryforward is limited to five years and to capital gains." },
      ],
      explanation: "Corporations may deduct capital losses only against capital gains — never against ordinary income. Unused net capital losses carry back three years and forward five, and expire if unused. Individuals fare better, deducting $3,000 annually against ordinary income with an indefinite carryforward.",
      difficulty: "MEDIUM",
      questionType: "EXAM_TRAP",
      tags: ["C corporation", "capital losses"],
    },
    {
      question: "Under Section 351, a transfer of property to a corporation in exchange for stock is generally tax-free if the transferors:",
      options: [
        { label: "A", text: "Own at least 50% of the corporation immediately after the exchange", isCorrect: false, rationale: "The control threshold is higher than 50%." },
        { label: "B", text: "Are in control, owning at least 80% of voting power and 80% of all other classes of stock immediately after the exchange", isCorrect: true, rationale: "Correct — the 80% control test must be met immediately after the transfer." },
        { label: "C", text: "Receive only cash in exchange for the property", isCorrect: false, rationale: "Receiving cash boot triggers gain recognition; stock must be received for nonrecognition." },
        { label: "D", text: "Hold the stock for at least one year", isCorrect: false, rationale: "No holding period requirement applies to Section 351 nonrecognition." },
      ],
      explanation: "Section 351 defers gain when property is transferred to a corporation solely in exchange for stock and the transferors, as a group, control the corporation immediately afterward — at least 80% of combined voting power and 80% of the shares of each other class. Services do not count as property, and boot received triggers recognition to the extent of the lesser of boot or realized gain.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["C corporation", "Section 351"],
    },
  ],

  "s-corporation-taxation": [
    {
      question: "Which of the following would disqualify a corporation from making an S election?",
      options: [
        { label: "A", text: "Having 90 individual shareholders", isCorrect: false, rationale: "The limit is 100 shareholders, so 90 is acceptable." },
        { label: "B", text: "Having a nonresident alien as a shareholder", isCorrect: true, rationale: "Correct — a nonresident alien shareholder disqualifies the S election." },
        { label: "C", text: "Having voting and nonvoting common stock outstanding", isCorrect: false, rationale: "Differences in voting rights alone do not create a second class of stock." },
        { label: "D", text: "Being incorporated in Delaware", isCorrect: false, rationale: "Any domestic corporation may elect S status regardless of state of incorporation." },
      ],
      explanation: "S corporation eligibility requires a domestic corporation with no more than 100 shareholders, only one class of stock, and shareholders limited to individuals, estates, and certain trusts. Nonresident aliens, partnerships, and corporations cannot be shareholders. Differences in voting rights are expressly permitted and do not create a second class.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["S corporation", "eligibility"],
    },
    {
      question: "A shareholder's basis in S corporation stock is increased by:",
      options: [
        { label: "A", text: "The shareholder's share of corporate liabilities", isCorrect: false, rationale: "Unlike partnerships, S corporation shareholders do not get basis for entity-level debt to third parties." },
        { label: "B", text: "The shareholder's share of separately and non-separately stated income", isCorrect: true, rationale: "Correct — income allocations increase stock basis, preventing double taxation on distribution." },
        { label: "C", text: "Distributions received from the corporation", isCorrect: false, rationale: "Distributions decrease, not increase, stock basis." },
        { label: "D", text: "The corporation's retained earnings at year-end", isCorrect: false, rationale: "Basis tracks the shareholder's own allocations, not the entity's aggregate retained earnings." },
      ],
      explanation: "S corporation stock basis increases for capital contributions and allocated income items, and decreases for distributions, then for nondeductible expenses and losses. A crucial difference from partnerships is that S corporation shareholders receive no basis for entity-level liabilities — only for direct loans they personally make to the corporation.",
      difficulty: "HARD",
      questionType: "EXAM_TRAP",
      tags: ["S corporation", "basis"],
    },
    {
      question: "A shareholder has $10,000 of stock basis and is allocated a $25,000 loss from the S corporation. The shareholder may currently deduct:",
      options: [
        { label: "A", text: "$25,000", isCorrect: false, rationale: "Losses are limited to basis; the full amount cannot be deducted." },
        { label: "B", text: "$10,000, with $15,000 suspended and carried forward indefinitely", isCorrect: true, rationale: "Correct — the deduction is capped at basis, and the excess is suspended until basis is restored." },
        { label: "C", text: "$0, because losses can never pass through", isCorrect: false, rationale: "S corporation losses do pass through, subject to limitations." },
        { label: "D", text: "$12,500, being half the loss", isCorrect: false, rationale: "No such proration rule exists." },
      ],
      explanation: "Loss deductions pass through only to the extent of the shareholder's stock basis plus basis in direct loans to the corporation. Here $10,000 is deductible and $15,000 is suspended indefinitely until basis is restored by future income or additional contributions. At-risk and passive activity limits then apply as further hurdles.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["S corporation", "loss limitation"],
    },
    {
      question: "The accumulated adjustments account (AAA) of an S corporation is used primarily to:",
      options: [
        { label: "A", text: "Track the corporation's total assets", isCorrect: false, rationale: "AAA is an earnings measure, not an asset account." },
        { label: "B", text: "Determine the taxability of distributions where the corporation has accumulated earnings and profits from prior C corporation years", isCorrect: true, rationale: "Correct — AAA identifies the amount that may be distributed tax-free before reaching C corporation E&P." },
        { label: "C", text: "Compute the corporation's payroll tax liability", isCorrect: false, rationale: "AAA has no bearing on payroll taxes." },
        { label: "D", text: "Establish each shareholder's ownership percentage", isCorrect: false, rationale: "Ownership is determined by shares held." },
      ],
      explanation: "AAA is a corporate-level account tracking undistributed income already taxed to shareholders. It matters chiefly for S corporations with accumulated earnings and profits from former C corporation years: distributions come first from AAA tax-free to the extent of basis, then from accumulated E&P as a taxable dividend.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["S corporation", "AAA"],
    },
  ],

  "partnership-taxation": [
    {
      question: "A partner contributes $50,000 cash and is allocated a $20,000 share of partnership liabilities. During the year the partner is allocated $15,000 of income and receives a $10,000 cash distribution. What is the partner's year-end basis?",
      options: [
        { label: "A", text: "$75,000", isCorrect: true, rationale: "Correct — $50,000 + $20,000 liabilities + $15,000 income − $10,000 distribution = $75,000." },
        { label: "B", text: "$55,000", isCorrect: false, rationale: "This omits the share of partnership liabilities." },
        { label: "C", text: "$85,000", isCorrect: false, rationale: "This fails to reduce basis for the distribution." },
        { label: "D", text: "$50,000", isCorrect: false, rationale: "This ignores all activity after the initial contribution." },
      ],
      explanation: "Partnership basis begins with contributions and is increased by the partner's share of income and of partnership liabilities, then decreased by distributions and the share of losses. A partner's share of entity liabilities creating basis is a defining difference from S corporations, where shareholders get no basis for entity-level debt.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["partnership", "basis"],
    },
    {
      question: "A guaranteed payment to a partner for services is:",
      options: [
        { label: "A", text: "Treated as a distribution reducing the partner's capital account only", isCorrect: false, rationale: "A guaranteed payment is not a distribution; it is deductible by the partnership." },
        { label: "B", text: "Deductible by the partnership and ordinary income to the receiving partner", isCorrect: true, rationale: "Correct — guaranteed payments are determined without regard to income and are treated much like salary." },
        { label: "C", text: "Tax-free to the partner", isCorrect: false, rationale: "Guaranteed payments are fully taxable as ordinary income." },
        { label: "D", text: "Capital gain to the partner", isCorrect: false, rationale: "The character is ordinary, not capital." },
      ],
      explanation: "A guaranteed payment is compensation to a partner determined without regard to partnership income. The partnership deducts it in computing ordinary business income, and the partner reports it as ordinary income subject to self-employment tax. It is reported separately from the partner's distributive share.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["partnership", "guaranteed payments"],
    },
    {
      question: "In a nonliquidating distribution of cash exceeding a partner's outside basis, the partner:",
      options: [
        { label: "A", text: "Recognizes no gain and carries a negative basis forward", isCorrect: false, rationale: "Basis can never fall below zero." },
        { label: "B", text: "Recognizes gain to the extent the cash exceeds basis, generally as capital gain", isCorrect: true, rationale: "Correct — cash distributions exceeding basis trigger gain recognition." },
        { label: "C", text: "Recognizes ordinary income equal to the full distribution", isCorrect: false, rationale: "Only the excess over basis is recognized, and generally as capital gain." },
        { label: "D", text: "Recognizes a loss equal to the excess", isCorrect: false, rationale: "An excess distribution produces gain, not loss." },
      ],
      explanation: "A partner's basis cannot go below zero. In a nonliquidating distribution, cash first reduces basis; any excess is recognized as gain, generally capital. Distributions of property other than cash normally cause no recognition, with the property taking a basis limited to the partner's remaining outside basis.",
      difficulty: "HARD",
      questionType: "APPLICATION",
      tags: ["partnership", "distributions"],
    },
    {
      question: "Which item must be separately stated on a partnership's Schedule K-1 rather than included in ordinary business income?",
      options: [
        { label: "A", text: "Cost of goods sold", isCorrect: false, rationale: "COGS is part of ordinary business income." },
        { label: "B", text: "Charitable contributions", isCorrect: true, rationale: "Correct — charitable contributions are separately stated because limitations apply at the partner level." },
        { label: "C", text: "Employee wages paid to non-partners", isCorrect: false, rationale: "Ordinary wage expense is included in the ordinary income computation." },
        { label: "D", text: "Rent expense on the business premises", isCorrect: false, rationale: "Ordinary operating rent is included in business income." },
      ],
      explanation: "Items whose tax treatment depends on the individual partner's own circumstances must be separately stated so the partner can apply the relevant limits: charitable contributions, capital gains and losses, Section 1231 gains, tax-exempt income, investment interest expense, and foreign taxes. Ordinary operating income and expenses are netted into a single figure.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["partnership", "separately stated items"],
    },
  ],

  "trusts-estates-and-gift-tax-basics": [
    {
      question: "For a gift to qualify for the annual gift tax exclusion, the gift must be:",
      options: [
        { label: "A", text: "Made to a family member", isCorrect: false, rationale: "The exclusion applies to gifts to any donee, related or not." },
        { label: "B", text: "A present interest, giving the donee an immediate right to use and enjoy the property", isCorrect: true, rationale: "Correct — future interests do not qualify for the annual exclusion." },
        { label: "C", text: "Made in cash rather than property", isCorrect: false, rationale: "The form of the gift is irrelevant." },
        { label: "D", text: "Reported on a gift tax return in all cases", isCorrect: false, rationale: "Gifts fully covered by the annual exclusion generally need not be reported." },
      ],
      explanation: "The annual exclusion is available per donee per year, but only for gifts of a present interest — an unrestricted right to the immediate use, possession, or enjoyment of the property. A gift into a trust with distributions deferred is a future interest and does not qualify unless the trust contains Crummey withdrawal rights.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["gift tax", "annual exclusion"],
    },
    {
      question: "Distributable net income (DNI) of a trust serves primarily to:",
      options: [
        { label: "A", text: "Determine the trust's charitable deduction", isCorrect: false, rationale: "That is not the function of DNI." },
        { label: "B", text: "Limit the trust's distribution deduction and the amount taxable to beneficiaries, and to determine the character of distributions", isCorrect: true, rationale: "Correct — DNI acts as a ceiling on both the deduction and the beneficiaries' income, and preserves character." },
        { label: "C", text: "Establish the trust's basis in its assets", isCorrect: false, rationale: "DNI is an income concept, unrelated to asset basis." },
        { label: "D", text: "Compute the estate tax due at the grantor's death", isCorrect: false, rationale: "DNI is an income tax concept, not a transfer tax one." },
      ],
      explanation: "DNI is the central concept in fiduciary income taxation. It caps the trust's or estate's distribution deduction, caps the amount beneficiaries must include in income, and carries the character of the underlying income — tax-exempt interest stays tax-exempt in the beneficiary's hands. The effect is to tax income once, either to the entity or to the beneficiary.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["trusts", "DNI"],
    },
    {
      question: "A transfer of property to a spouse who is a U.S. citizen is:",
      options: [
        { label: "A", text: "Subject to gift tax on the full value", isCorrect: false, rationale: "The unlimited marital deduction shelters qualifying spousal transfers." },
        { label: "B", text: "Eligible for an unlimited marital deduction", isCorrect: true, rationale: "Correct — qualifying transfers to a citizen spouse are fully deductible for gift and estate tax purposes." },
        { label: "C", text: "Limited to the annual exclusion amount", isCorrect: false, rationale: "The marital deduction is not capped at the annual exclusion." },
        { label: "D", text: "Taxable only if the property is real estate", isCorrect: false, rationale: "The type of property does not determine the deduction." },
      ],
      explanation: "The unlimited marital deduction permits transfers of any amount between spouses without gift or estate tax, deferring the tax until the surviving spouse's death or later disposition. Transfers to a non-citizen spouse are limited to an annual amount, since the deferred tax could otherwise leave the U.S. tax system entirely.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["gift tax", "marital deduction"],
    },
    {
      question: "A simple trust is characterized by all of the following EXCEPT:",
      options: [
        { label: "A", text: "It must distribute all income currently", isCorrect: false, rationale: "This is a defining characteristic of a simple trust." },
        { label: "B", text: "It makes no distributions of corpus during the year", isCorrect: false, rationale: "This is a defining characteristic." },
        { label: "C", text: "It makes no charitable contributions during the year", isCorrect: false, rationale: "This is a defining characteristic." },
        { label: "D", text: "It may accumulate income at the trustee's discretion", isCorrect: true, rationale: "Correct — accumulating income makes the trust complex, not simple." },
      ],
      explanation: "A simple trust must distribute all of its income currently, make no distributions of principal, and make no charitable contributions. A trust failing any of these tests in a given year is a complex trust for that year. The classification is tested annually, so a trust can shift between the two.",
      difficulty: "MEDIUM",
      questionType: "EXCEPTION",
      tags: ["trusts", "simple trust"],
    },
  ],

  "employee-benefits-and-payroll-tax": [
    {
      question: "Which statement correctly describes the Social Security and Medicare components of FICA?",
      options: [
        { label: "A", text: "Both apply to unlimited wages", isCorrect: false, rationale: "The Social Security component stops at an annual wage base." },
        { label: "B", text: "Social Security applies up to an annual wage base; Medicare applies to all wages with no ceiling", isCorrect: true, rationale: "Correct — only the Social Security portion is capped." },
        { label: "C", text: "Both are capped at the same annual wage base", isCorrect: false, rationale: "Medicare has no wage ceiling." },
        { label: "D", text: "Neither applies to wages paid to corporate officers", isCorrect: false, rationale: "Corporate officers performing services are employees for FICA purposes." },
      ],
      explanation: "FICA has two components. Social Security tax applies to wages up to an annually indexed wage base and then stops. Medicare tax applies to all wages without limit, and an Additional Medicare Tax applies to wages above a threshold — withheld from the employee only, with no employer match.",
      difficulty: "MEDIUM",
      questionType: "CONCEPTUAL",
      tags: ["payroll tax", "FICA"],
    },
    {
      question: "In computing self-employment tax, net earnings from self-employment are first multiplied by:",
      options: [
        { label: "A", text: "100%", isCorrect: false, rationale: "A reduction factor applies before the tax rate." },
        { label: "B", text: "92.35%", isCorrect: true, rationale: "Correct — the 92.35% factor approximates the employer-share deduction an employee would effectively receive." },
        { label: "C", text: "50%", isCorrect: false, rationale: "50% relates to the deduction for one half of self-employment tax, not the base computation." },
        { label: "D", text: "15.3%", isCorrect: false, rationale: "15.3% is the combined tax rate applied after the reduction, not the reduction factor." },
      ],
      explanation: "Self-employment income is multiplied by 92.35% before applying the 15.3% combined rate, placing the self-employed on comparable footing with employees whose employer-paid share is not part of their wages. The taxpayer then deducts one half of the resulting self-employment tax above the line.",
      difficulty: "HARD",
      questionType: "CALCULATION",
      tags: ["payroll tax", "self-employment"],
    },
    {
      question: "Which employer-provided fringe benefit is generally EXCLUDED from an employee's gross income?",
      options: [
        { label: "A", text: "A year-end cash bonus", isCorrect: false, rationale: "Cash compensation of any kind is taxable wages." },
        { label: "B", text: "Employer-paid premiums on the first $50,000 of group-term life insurance coverage", isCorrect: true, rationale: "Correct — coverage up to $50,000 is excluded; the cost of excess coverage is imputed income." },
        { label: "C", text: "A gift card provided in place of a holiday bonus", isCorrect: false, rationale: "Cash equivalents such as gift cards are taxable regardless of amount." },
        { label: "D", text: "Personal use of a company vehicle", isCorrect: false, rationale: "Personal use is a taxable fringe benefit valued under prescribed rules." },
      ],
      explanation: "Employer-paid group-term life insurance is excluded up to $50,000 of coverage, with the cost of coverage above that included in wages under IRS tables. Other common exclusions include health insurance premiums, de minimis fringe benefits, working condition fringes, and qualified employee discounts. Cash and cash equivalents are always taxable.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["fringe benefits", "exclusions"],
    },
  ],

  "exempt-organizations-basics": [
    {
      question: "Unrelated business taxable income (UBTI) of an exempt organization is income from an activity that is:",
      options: [
        { label: "A", text: "Any activity generating revenue for the organization", isCorrect: false, rationale: "Revenue from activities furthering the exempt purpose is not UBTI." },
        { label: "B", text: "A trade or business, regularly carried on, and not substantially related to the exempt purpose", isCorrect: true, rationale: "Correct — all three elements must be present for income to be UBTI." },
        { label: "C", text: "Conducted entirely by volunteers", isCorrect: false, rationale: "A substantially volunteer-run activity is specifically excepted from UBTI." },
        { label: "D", text: "Related to the organization's exempt purpose", isCorrect: false, rationale: "Related activity income is precisely what is not taxed." },
      ],
      explanation: "UBTI requires a trade or business, regularly carried on, that is not substantially related to the organization's exempt purpose. Taxing it prevents unfair competition with commercial businesses. Statutory exceptions cover activities run substantially by volunteers, those conducted for the convenience of members, and sales of donated merchandise.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["exempt organizations", "UBTI"],
    },
    {
      question: "To qualify as exempt under Section 501(c)(3), an organization must satisfy which requirement?",
      options: [
        { label: "A", text: "It must never generate revenue in excess of expenses", isCorrect: false, rationale: "An exempt organization may run a surplus; what matters is that earnings do not benefit private individuals." },
        { label: "B", text: "No part of its net earnings may inure to the benefit of any private shareholder or individual", isCorrect: true, rationale: "Correct — the private inurement prohibition is fundamental to 501(c)(3) status." },
        { label: "C", text: "It must be organized as a corporation", isCorrect: false, rationale: "Trusts and unincorporated associations may also qualify." },
        { label: "D", text: "It must engage in substantial lobbying to advance its purpose", isCorrect: false, rationale: "Substantial lobbying jeopardizes exempt status rather than supporting it." },
      ],
      explanation: "A 501(c)(3) organization must be organized and operated exclusively for exempt purposes — charitable, religious, educational, scientific, or literary among them — with no private inurement, no substantial lobbying, and no participation in political campaigns. Violating the campaign intervention prohibition can result in revocation.",
      difficulty: "MEDIUM",
      questionType: "APPLICATION",
      tags: ["exempt organizations", "501(c)(3)"],
    },
    {
      question: "The principal distinction between a public charity and a private foundation is that a private foundation:",
      options: [
        { label: "A", text: "Is not exempt from federal income tax", isCorrect: false, rationale: "Private foundations are exempt, though subject to excise taxes and stricter rules." },
        { label: "B", text: "Typically receives support from a narrow group of donors and is subject to stricter operating rules and excise taxes", isCorrect: true, rationale: "Correct — the funding base drives the classification and the additional restrictions that follow." },
        { label: "C", text: "May not make grants to other organizations", isCorrect: false, rationale: "Grantmaking is the core activity of most private foundations." },
        { label: "D", text: "Is required to file Form 990-N only", isCorrect: false, rationale: "Private foundations file Form 990-PF regardless of size." },
      ],
      explanation: "A 501(c)(3) organization is presumed to be a private foundation unless it qualifies as a public charity by meeting a public support test or by its nature, such as churches, schools, and hospitals. Private foundations face excise taxes on net investment income, minimum distribution requirements, and prohibitions on self-dealing and excess business holdings.",
      difficulty: "HARD",
      questionType: "CONCEPTUAL",
      tags: ["exempt organizations", "private foundations"],
    },
  ],
};
